### ISSUE TITLE
[eFEAT] How to properly import training from previous version.

### ISSUE THREAD

**Issue by chauriber** [akasolace/HO#100]
I've just imported old HRF files from 1.434 into 1.436 fresh install, and partial training are not shown (decimal skill level).

**Comment by brokenelevator** [comment]
@chauriber wouldn't it be better if you used 1.434 database in 1.436?
Anyone correct me if I'm wrong but decimal skill levels are not in HRF's so can not be imported.
You could use `subskill recalculation` from `file` menu. I don't know how well it works but since you don't have the values anyway, it won't break anything.
You could also manually add them but the best would be to use old database.

**Comment by akasolace** [comment]
fully agree with @brokenelevator

**Comment by chauriber** [comment]
Hi. I did a subskill recalculation with no luck. I'm very sorry if my request is misplaced, but I don't know how to import old database to 1.436. I believe I should copy old "db" folder to 1.436 root folder, and maybe some other files, but I don'k know. I did not find a wiki or something to follow. Sorry.

**Comment by akasolace** [comment]
@chauriber, 
Hello backup the dB folder and user.xml file.
Install latest version of HO. Make a first download check that all worked and close ho. The first download will create a new dB folder and new user xml file in the installation directory. Replace them with one zip saved when you backed it up. Open HO again and you should get all your old data. Download new team data again and you should be fine.

**Comment by chauriber** [comment]
Thanks! I worked.

By the way, I've manually replaced special skill icons on HO.jar with the new ht icons (under /gui/bilder/spec1.png through spec8.png). I've been using those. It feels more modern ht. Just an opinion.
Cheers.

**Comment by chauriber** [comment]
Should I keep old hrf files? I just want to start new version with accumulative decimal skill levels, and as I can see, it works fine.

**Comment by brokenelevator** [comment]
> I've manually replaced special skill icons on HO.jar with the new ht icons

I don't really pay attention to those but if more people share your opinion something could be done about this,

> Should I keep old hrf files?

Well, that depends. I keep those, but that is personal preference.
I don't believe there is a reason to keep them if you keep your database safe and won't need to apply them somewhere else or what not.
So it is your choice. It is not like they take up much space anyway.

**Comment by akasolace** [comment]
@chauriber where did you get the new ht icons you are referring to ?

**Comment by chauriber** [comment]
I'm sorry I didn't see your reply. I got them by copying directly from ht site. They are colored icons. HT has changed the icons pack to just black. Now I have upgraded to latest stable release and I'm happy to see you updated the icons. Cheers.
