### ISSUE TITLE
[FEATURE] Search bottom 3 divisions of a country for bot teams

### ISSUE THREAD

**Issue by Adito5393** [akasolace/HO#1001]
**Is your feature request related to a problem? Please describe.**
Every season **Series swapping** is available, however, there is no automated way of searching and finding out which series contains bot teams! Before I used to see [here](http://ht.alergromania.ro/data/bot-teams-by-series/) but the owner did not update the DB for a long time already.

**Describe the solution you'd like**
I think we could set up GitHub actions to do the search and store the data (for every country, the bottom 3 divisions are scanned and order the list by the number of bots per serie) every 16 weeks and allow all users to do the query.

Have you tried to do something similar in the past? Or do you think this can't be achieved with the HO code available at the moment?

**Comment by akasolace** [comment]
This could be done but outside of HO!, maybe the developer of Alltid would be interested in developing this feature.. I believe he has already all the data ....
