### ISSUE TITLE
[BUG]HO internal update (help->update) does not work

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1008]
started HO 5.0 r3557
help->update gives 

![image](https://user-images.githubusercontent.com/11821502/116813720-7517dc80-ab55-11eb-9fd4-b30912f8b5e7.png)

clicking "Ja" (Yes) gives: 

![image](https://user-images.githubusercontent.com/11821502/116813707-64fffd00-ab55-11eb-8069-53d6c6376756.png)

output.log:
 [Info]    HO: VERSION: 5.0   versionType:  DEV   RevisionNumber: 3557
 [Info]    HOVerwaltung: language used for interface is: Deutsch
 [Info]    HOMainFrame: This is HO! version 5.0 DEV (r3557), have fun!
 [Info]    HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
 [Info]    HOMainFrame: Using java: 15.0.1 (AdoptOpenJDK)
 [Error]   Updater: installer exited with value: 1

error.log
Mai 02, 2021 12:13:54 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open start
Mai 02, 2021 12:13:54 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open end

**Comment by akasolace** [comment]
You are using a portable version ?

**Comment by wsbrenk** [comment]
this is the link i used: https://github.com/akasolace/HO/releases/download/dev/HOSetup-5.0.3562.0-DEV-JRE.exe

**Comment by wsbrenk** [comment]
@akasolace just tested upgrade 3566 to 3568
* deleted reg-entry Computer\HKEY_CURRENT_USER\SOFTWARE\JavaSoft\Prefs\485
* started help->update
* update OK
* deleted reg-entry is back again

**Comment by akasolace** [comment]
@wsbrenk  ok so I guess we can close this issue... thank you for testing !
