### ISSUE TITLE
Not all players available in lineup-dropdowns

### ISSUE THREAD

**Issue by Paule22** [akasolace/HO#101]
The dropdowns in the lineup-tool do not show all players. 

HO 1.436.2.1064, Mac

**Comment by mistermax80** [comment]
I Will test... But are you sure it is not present filters in box fifth bottom?

**Comment by Paule22** [comment]
Oh my god. I'm so sorry!
I've overlooked the last filter (exclude last line-up).

SORRY!

**Comment by mistermax80** [comment]
Ok no problem!
Close Issue.
