### ISSUE TITLE
[FEATURE] update design of about window

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1016]
Redo about windows:

 - Remove text about icons 
 - Change logo 

@wsbrenk  what do you think ? 

![image](https://user-images.githubusercontent.com/1136496/117853978-4f8f7f00-b289-11eb-841b-be50ce00d486.png)

**Comment by MaSedlacek** [comment]
take

**Comment by MaSedlacek** [comment]
@akasolace @wsbrenk 
Hei guys,
Are there any official CHPP logos other than [the one used](https://wiki.hattrick.org/wiki/File:Chpp_logotype.gif)?
I didn't find any. 

The logo looks fine in my HTO but I use the default skin.
![image](https://user-images.githubusercontent.com/53978029/118545318-b95ecb80-b756-11eb-9b6b-f9d843d2f97d.png)
I guess the white pixels visible in the darker skin are the thing that bothers you.

Thanks.

**Comment by akasolace** [comment]
no, I can't find any.
We can simply replace it with HO! logo.

**Comment by MaSedlacek** [comment]
OK.
Do you mean the logo itself of the splashsreen logo?
The logo could work at the same position if made a bit smaller
![image](https://user-images.githubusercontent.com/53978029/118710978-4c633880-b81f-11eb-811b-a39563e17d57.png)

The splashscreen could work at the bottom of the panel.
![image](https://user-images.githubusercontent.com/53978029/118711059-66048000-b81f-11eb-90e1-d0f4dc44d924.png)

Thanks.

**Comment by akasolace** [comment]
@MaSedlacek or we can also keep the CHPP logo but with a white background as on HT website. 
Also, I would suggest to include a link to HO website: https://akasolace.github.io/HO/

What do you think?

**Comment by MaSedlacek** [comment]
@akasolace 
Background image - great, [this one](https://wiki.hattrick.org/images/3/36/Chpp_logotype.gif) should have white background, it could work fine.
Link to HO website - agree too.
I'll post a screenshot here once ready. Probably only next week, won't have time in the rest of this week.

**Comment by akasolace** [comment]
hello @MaSedlacek I am planning to make the first alpha release of 5.0 this weekend. If you could push your commit for this ticket by then that would be great ...

**Comment by MaSedlacek** [comment]
@akasolace 
Sorry, finally finished this. Credits removed, CHPP logo with white background added, HO link added. 
Looks fine to me, didn't test on different themes.

**Comment by akasolace** [comment]
@MaSedlacek I thematized the color of the link ...
