### ISSUE TITLE
[BUG] deactivated entry in Preferences, release channels

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1019]
**Describe the bug**
either remove or implement this feature

![image](https://user-images.githubusercontent.com/1136496/117864420-1230ee80-b295-11eb-83d9-320b2b65d436.png)

**Comment by MaSedlacek** [comment]
take

**Comment by akasolace** [comment]
should be fixed by #1037

**Comment by akasolace** [comment]
@MaSedlacek in case of manual check of new version the message box "you have the latest version" is fine but in case o background check I would not display that message but only the message in case there is effectivly a new vesion.

**Comment by MaSedlacek** [comment]
@akasolace I agree, good catch. I'll fix and provide update

**Comment by MaSedlacek** [comment]
@akasolace 
Pull request with an update created. There are 2 commits.
The second commit is refactoring only. Looks like a lot of changes but I just broke the code into smaller methods. 
I also commented out an unreachable part - I believe it can be needed somewhere. Feel free to uncomment or delete.
