### ISSUE TITLE
[BUG] NPE when youth player exits without any information about his top 3 skills

### ISSUE THREAD

**Issue by poteus** [akasolace/HO#1021]
**Describe the bug**
When I try to download the data from HT, I receive an Error message stating "File is corrupt".

**To Reproduce**
1. Go to 'File'
2. Click on 'Download'
3. Click again on 'Download'
4. See error: "File is corrupt"

**Screenshots**
Screenshot added of the error.
![Screen Shot 2021-05-11 at 3 06 57 PM](https://user-images.githubusercontent.com/20169360/117878521-7c349e00-b26b-11eb-9cfa-7d87f1efd1e3.png)

**Platform information:**
 - OS: macOS Catalina
 - Version 10.15.7

**Additional context**
I deleted the database to start from fresh, but I still have the same issue. I have another team which has no issues downloading the data from HT. 

The only file I can share is the HRF file. Do you want me to upload that one?

**Comment by wsbrenk** [comment]
@poteus could you check, if there is a log file in %APPDATA%/HP/logs with info about this error?

**Comment by poteus** [comment]
I found the error files...

First file: error.log
[error.log](https://github.com/akasolace/HO/files/6462997/error.log)

2nd file: HO-2021-05-11.log
[HO-2021-05-11.log](https://github.com/akasolace/HO/files/6462998/HO-2021-05-11.log)

**Comment by akasolace** [comment]
@wsbrenk it seems this is an error in youth module

**Comment by wsbrenk** [comment]
@poteus youth module has problem with a youth player without any information about the top 3 skills. One or two of them should be reported by the scout, at scouting date. For the moment i have no idea, why these information is not available. 

I will send a fix that handles the symptom  (no crash, when trying to find other top3 skills). But i'm not sure if there other unexpected situations concerning missing scout informations. 

If you could upload your database folder of your team, i could try to debug your downloads and find the reason of missing scout information.

**Comment by akasolace** [comment]
should be closed by #1022,  @poteus / @wsbrenk can you please check whether or not latest release fix that issue ?

**Comment by poteus** [comment]
![Screen Shot 2021-05-12 at 8 24 11 AM](https://user-images.githubusercontent.com/20169360/117982324-843c1e80-b2fb-11eb-8512-9177a271040f.png)
![Screen Shot 2021-05-12 at 8 24 29 AM](https://user-images.githubusercontent.com/20169360/117982335-8605e200-b2fb-11eb-94b1-2d2f37080f7d.png)

@akasolace Still error.
@wsbrenk Yes, the error began after I started my youth squad. I do not remember import an hrf-file tho.

**Comment by wsbrenk** [comment]
@poteus could you again deliver the logs from latest download?

**Comment by poteus** [comment]
There logs were made from my work computer (IOS). The previous logs were from my home computer (Windows).

[error.log](https://github.com/akasolace/HO/files/6467571/error.log)
[HO-2021-05-12.log](https://github.com/akasolace/HO/files/6467572/HO-2021-05-12.log)

**Comment by wsbrenk** [comment]
@poteus thanks - i never could test youth module with fresh youth team, that has players that were not scouted.
Hopefully the next pull request will fix it - next dev version from @akasolace when he is back from long weekend, i hope.

**Comment by poteus** [comment]
No problem.
Not in a hurry.  I will keep uploading the log files once we have the ew
pull...

Thanks for the hard work.

Alexis Rivera
Math - STEM - Robotics

**Comment by poteus** [comment]
Still same error.
![Screenshot 1](https://user-images.githubusercontent.com/20169360/118344886-80c0b700-b4f6-11eb-9c32-331d36de4473.png)
![Screenshot 2](https://user-images.githubusercontent.com/20169360/118344888-828a7a80-b4f6-11eb-96de-753da629dbd3.png)
![Screenshot 3](https://user-images.githubusercontent.com/20169360/118344890-84543e00-b4f6-11eb-9a76-672525c22eef.png)
![Screenshot 4](https://user-images.githubusercontent.com/20169360/118344891-86b69800-b4f6-11eb-8367-8fe52596b773.png)

Error logs:
[error.log](https://github.com/akasolace/HO/files/6481746/error.log)
[HO-2021-05-14.log](https://github.com/akasolace/HO/files/6481747/HO-2021-05-14.log)

**Comment by wsbrenk** [comment]
the changes of commit 1e107c0bf9d81ecb07b704ce7d5a65bd396535c8 are not part of 3566er version. Please test again with next upcoming dev version.

**Comment by akasolace** [comment]
hi @poteus, I just released new dev artefacts (5.0.3568) that contains the fix. Please test this one and let me know if it fixes your issues.  Cheers

**Comment by poteus** [comment]
@akasolace @wsbrenk 
It seems to be working on my IOS MacBook Pro.
I will check tonight on my Windows computer (I thought I had a connection error).

**Comment by poteus** [comment]
From my Windows box...

![Screenshot 1](https://user-images.githubusercontent.com/20169360/118584133-ea8dca80-b75b-11eb-8946-ee7bea1215bc.png)
![Screenshot 2](https://user-images.githubusercontent.com/20169360/118584135-ebbef780-b75b-11eb-9ba8-1d1c74e04cf2.png)
![Screenshot 3](https://user-images.githubusercontent.com/20169360/118584140-ed88bb00-b75b-11eb-8ddb-8fba1f03047f.png)
[error.log](https://github.com/akasolace/HO/files/6498060/error.log)
[HO-2021-05-17.log](https://github.com/akasolace/HO/files/6498061/HO-2021-05-17.log)

**Comment by akasolace** [comment]
@poteus using version 3568 gives different results whether you are using it on windows (bug above) or macOS (working well) ?

**Comment by akasolace** [comment]
@poteus @wsbrenk I think I can close this ticket, can you please both confirm ?

**Comment by poteus** [comment]
I erased the match in question. Issue solved.
