### ISSUE TITLE
[BUG] experience not displayed

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#1023]
In the squad tab the experience sublevels are not displayed in the player details

1. Go to squad tab
2. Click on 'adjust subskils
3. Change value of experience
4. Experience always show 00 sublevel

 - OS: Windows
 - Version 4.1.3310.2

**Comment by akasolace** [comment]
should be fixed by #1026

**Comment by akasolace** [comment]
@aristodemos2008 could you please check this issue is fixed in latest dev version ?

**Comment by aristodemos2008** [comment]
> 
> 
> @aristodemos2008 could you please check this issue is fixed in latest dev version ?

I've copied my DB to the DEV HO-5.0.3568.0. Updated team from HT. Experience sublevels are displayed correctly. Thank you.
