### ISSUE TITLE
[BUG] Missing training for wednesday match.

### ISSUE THREAD

**Issue by chauriber** [akasolace/HO#1029]
Hi. Today's update of ho data did not recognize past wednesday secondary cup match as training. Checked lineup and training options. Only past sunday match has the +xx to the players skill values. I'm on 4.1 since 2 or 3 weeks.

**Comment by wsbrenk** [comment]
same as #795

this should be fixed in HO 5

**Comment by akasolace** [comment]
@chauriber yes this will be fixed in 5.0, you can give it a test using the DEV version ....
