### ISSUE TITLE
[BUG] can't download new data

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1038]
![Screenshot 1](https://user-images.githubusercontent.com/20169360/118584133-ea8dca80-b75b-11eb-8946-ee7bea1215bc.png)
![Screenshot 2](https://user-images.githubusercontent.com/20169360/118584135-ebbef780-b75b-11eb-9ba8-1d1c74e04cf2.png)
![Screenshot 3](https://user-images.githubusercontent.com/20169360/118584140-ed88bb00-b75b-11eb-8ddb-8fba1f03047f.png)
[error.log](https://github.com/akasolace/HO/files/6498060/error.log)
[HO-2021-05-17.log](https://github.com/akasolace/HO/files/6498061/HO-2021-05-17.log)

_Originally posted by @poteus in https://github.com/akasolace/HO/issues/1021#issuecomment-842790553_

**Comment by akasolace** [comment]
@poteus I created the bug ticket on your behalf, in my view this is a different issue than #1021 (@wsbrenk I think you agree)
Could you please just confirms you also experience that issue from macOS. 
Also could you share your database here, thank you.

**Comment by poteus** [comment]
Confirmed, the bug only appears on my Windows box.

Which database do you need?

![Screen Shot 2021-05-18 at 8 22 58 AM](https://user-images.githubusercontent.com/20169360/118658738-471bd480-b7b2-11eb-9d5f-267b565c75a4.png)

**Comment by tychobrailleur** [comment]
Intriguing, that game ([matchid=20955045]) does not involve Team ID 27090, which would explain the error.

**Comment by poteus** [comment]
I thought the same thing. Then I thought that it could be a game that one of my player played before I purchased it...
I have not check that yet tho.

**Comment by poteus** [comment]
Hum, probably not... The game was in 2004, between 2 bots.

**Comment by tychobrailleur** [comment]
> Hum, probably not... The game was in 2004, between 2 bots.

I guess you could delete the game from the Matches list. :-)

**Comment by poteus** [comment]
I do not know how to do that tho...

**Comment by akasolace** [comment]
I can't check now but I notice this is an hto integrated game not a regular one .... 
what surprises me is that HO behave differently on Windows and on MacOS, you have the same database for both ? 
You can put here the zip file highlighted in your screenshot, I will try to have a look later today ...

**Comment by poteus** [comment]
2 different databases...

Windows database
[db_Starlite-2021-05-18.zip](https://github.com/akasolace/HO/files/6508911/db_Starlite-2021-05-18.zip)

IOS database
[db_Starlite-2021-05-19.zip](https://github.com/akasolace/HO/files/6508908/db_Starlite-2021-05-19.zip)

**Comment by akasolace** [comment]
indeed there is no such game in htointegrated system ...

**Comment by akasolace** [comment]
so there are 2 things:
 1. understand why your HO is trying to download a non-existing match
 2. ensure error 51 does not crash HO!

**Comment by akasolace** [comment]
@poteus I have no idea where those ghost games are coming from.... I can't find trace of them in HT. In that case I think the simpler is to delete them manually as per the screenshot below.
You might have to delete couple of them.

I created #1040 to facilitate such tasks in the future. 
Meanwhile I will close this ticket as it is not really a bug. The real bug was to get those entries in the first place but don't know how to investigate this.
 
![image](https://user-images.githubusercontent.com/1136496/118851757-6578f180-b8d2-11eb-95af-b9d3713571c1.png).

**Comment by wsbrenk** [comment]
@akasolace did you check if sourcesystem of those matches was hattrick? Maybe those matches were from the youth team?!

**Comment by akasolace** [comment]
@wsbrenk I did check it was not a youth match .... I have no idea where those entries came from ...

**Comment by akasolace** [comment]
I just experienced that bug (see #1038)

**Comment by wsbrenk** [comment]
match 20955045 from 2004 is not the correct SourceSystem=htointegrated but hattrick

**Comment by wsbrenk** [comment]
the given url looks like the nt lineup download in NthrfConvertXml2Hrf.java. should not happen in none national teams!
