### ISSUE TITLE
[BUG] Players show different skill increase starting from same level after playing in training position in same game

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#1056]
**Describe the bug**
After first time training defending last week with my key players in a Saphir cup game [matchID=678872142] (https://www.hattrick.org/Club/Matches/Match.aspx?matchID=678872142)
player Henning Schram gained from assumed 4.00 -> 4.29 after 90 min
player Fynn Legendorff gained from assumed 4.00 -> 4.34 after 89 min
player Frank-Ullrich Moll gained from assumed 5.00 -> 5.29 after 89 min

Schram gained not enough, he should have an increase +0,34 like Legendorff
**Screenshots**
![Screenshot 2021-05-30 112238](https://user-images.githubusercontent.com/64270318/120099451-cd81d000-c13b-11eb-9884-3e9cda98e807.JPG)

**Platform information:**
 - OS: Windows 10 Pro 20H2 Build 19042.985
 HO! 5.0 Dev Build 3576

**Add Info**
HO!3.0 stable shows no such difference, Schram and Legendorff gained the same estimated skill level.
![Screenshot 2021-05-30 114729](https://user-images.githubusercontent.com/64270318/120099662-040c1a80-c13d-11eb-9eb6-4fe9458da353.JPG)

**Comment by wsbrenk** [comment]
I guess Legendorff has still been calculated as a 21-year-old

**Comment by datatramp** [comment]
then level 4 base increase would be the same as increasing from level 5 (Schram/Moll) ? that is wrong.

**Comment by wsbrenk** [comment]
i see - have to check that - thanks!

**Comment by wsbrenk** [comment]
@datatramp found a bug concerning minutes counting. please check if that repairs your issue with next dev version - thanks.

**Comment by datatramp** [comment]
ok I will check with upcoming training update when next dev build is available. Thx for your work!

**Comment by wsbrenk** [comment]
you could run recalc subskills (7 weeks) to correct the numbers.

**Comment by datatramp** [comment]
I updated to Build 3600 and did a recalc subskills (7 weeks). It looks fine now, good work!
![Screenshot 2021-06-03 191748](https://user-images.githubusercontent.com/64270318/120685992-cc84d180-c4a0-11eb-9e60-32635accc0b9.JPG)
