### ISSUE TITLE
[eFEAT] upgrade SDK to OpenJDK 14

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#106]
Due to approaching EOL of java 8, it is time to upgrade to JDK 11 (LTS)

https://stackoverflow.com/questions/27861658/how-specify-the-required-java-version-in-a-gradle-build

**Comment by brokenelevator** [comment]
It may be a stupid question but is there anything we need to do?
I'm running OpenJDK.

**Comment by akasolace** [comment]
there are some depraction warnings, so the code will have to be adjusted somehow
However, I am not sure of the required efforts. We'll see in time

**Comment by bmariesan** [comment]
@akasolace I can help you with the migration, however I'm not knowledgeable in Swing at all so I might break some things. Also I've seen that currently on JDK 11 and on JDK 8 on my version of Mac the project won't build due to the theme, only Nimbus is compliant. If I have some time this weekend or next week I'll add a pull request with the minimum changes required to upgrade to JDK 11

**Comment by akasolace** [comment]
hello @bmariesan, I think this transition will not take place shortly. 
If you want to participate in HO, which would be super cool, I would suggest you to pick an open issue with not such a wide scope. Happy to give you some idea :-)

**Comment by tychobrailleur** [comment]
I have been pulling my hair on this one over the weekend.  One of the difficulties I am facing here is that most of the plugins packaging for osx use jpackage, which is available for java 14, but used to be available for 11 from there: https://jdk.java.net/jpackage/ – which is now a broken link.

There are some artefacts lying around that can be found from there: https://mail.openjdk.java.net/pipermail/openjfx-dev/2018-September/022500.html but it would require everyone to download them, install them correctly, and rename as needed (`jpackage` is `jpackager` in those artefacts).

@akasolace Would it make sense to go straight to 14 to use [badass](https://badass-runtime-plugin.beryx.org/releases/latest/)?  it seems to be the strategy adopted by jabref, for example.

**Comment by akasolace** [comment]
> Would it make sense to go straight to 14 to use badass?

yes it sounds good to me. I think we will need to have compiliation option to ensure compatibility with jdk11 as I think it is still the std on a lot of Linux distribution.

**Comment by akasolace** [comment]
I agree lets go straight to java 14, question is do we do it for 4.0 or for next release ?

**Comment by tychobrailleur** [comment]
For the next one.  This requires a lot of changes: gradle version 6, some of the deps including scribe.

Modules also load resources differently, I need that problem in intellij.

**Comment by tychobrailleur** [comment]
You can have a glimpse of the change on my (broken) branch tychobrailleur:java-11

**Comment by akasolace** [comment]
ok so we leave it for 5.0

**Comment by tychobrailleur** [comment]
Right, update on this: I can package the app as a `pkg` and `dmg`, and it runs fine (a few hardcoded changes here and there that will need to be addressed, in particular the path to db, i.e. #372 needs to be fixed – it looks like the behaviour changed on OSX, `/db` now points to the root path `/db`, which makes more sense).

Biggest problem now is IntelliJ: no resource in `src/main/resources` get loaded from classpath when running in the IDE (similar to https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000430279-Can-t-access-resource-with-Java-10), and I haven't figured out a way to solve this.  In the small repro (https://github.com/tychobrailleur/neoho), I am using relative path with `File`, but that's not sustainable...

**Comment by akasolace** [comment]
@tychobrailleur Is there a branch I can pull and test ?  See if the error is specific to macOS or more general?

**Comment by tychobrailleur** [comment]
> @tychobrailleur Is there a branch I can pull and test ? See if the error is specific to macOS or more general?

It is on my [java-14](https://github.com/tychobrailleur/HO/tree/java-14) (which is also my java-11 branch, but that was getting confusing).

**Comment by akasolace** [comment]
closed by f99fa5f0ce0886777a16c1ab03177e3b78d07ddf
