### ISSUE TITLE
[eBUG] NT hrf file invalid

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#107]
**Describe the bug**
As described on the forum, it is possible to activate the ntHRF module.  It is possible to download an NT hrf file.
Then the idea is to be able to load the hrf file into the database.
Statement suggests it's only compatible with v1.432

**To Reproduce**
1. Enable module.  File > Preferences > Modules > Activate NThrf & Restart
2. Create new db for NT team
3. Load file.  File > Import from hrf
4. See error attached

**Screenshots**

[](url)
**Platform information:**
 - Win10
 - HO 1.436

**Additional context**
Currently reviewing hrf files.  fields such as "massor" exist in NT version not in club version and vice versa.  Will submit files shortly.
One line in NT file corrupt with "playingmatch=truecash=0"
Name format is one line in nt format, but multi-lines in club format

Blanked 
![corrupt_nt_file](https://user-images.githubusercontent.com/48737160/54787128-bc1b1000-4c22-11e9-8ba6-6cb62d930d23.jpg)

nt hrf file loaded, but with skills blanked out.

[nt_3042_20190319_1220-blanked.zip](https://github.com/akasolace/HO/files/2994217/nt_3042_20190319_1220-blanked.zip)

**Comment by Synthespian** [comment]
Splitting "playingmatch=truecash=0" line to two lines still does not load and is corrupt.

**Comment by DavidatorusF** [comment]
not sure use use our own HO for NT is nice

own HO is for life, NTHO is just for a moment

**Comment by Synthespian** [comment]
Additional info ... downloaded an hrf from the nt tracker portal and that successfully loaded into HO, with a wierd -1 trainer, but they're in.  So, nothing wrong with getting NT players in, just the format of the hrf downloaded.

**Comment by akasolace** [comment]
@konved  Could you have a look to this one and to #108 and have an assessment of how much work it would be to tackle this? Can we try to squeeze it into 2.0 or would we have to wait for next release ?

**Comment by Synthespian** [comment]
Personally, I'd stick it as a nice to have and do after.  Major upgrades need to be hard-hitting and this only covers a tiny percentage of users.
And if they are making changes to the NT process, maybe the shortlist would be the better thing to import rather than / including the team sheet.

As a side comment, I'm in "thank you cap mode for Q2 players who missed out because we didn't qualify".  I've got no need to add them to the HO squad, because they won't stick around, but I'd like to keep track of the real prospects, hence the thought above about the shortlist.

**Comment by akasolace** [comment]
@Synthespian 
Personally I do not know anything about NTHRF, I am not even aware of current HT support.
Your comment above is cryptic to me.

> Personally, I'd stick it as a nice to have and do after. Major upgrades need to be hard-hitting and this only covers a tiny percentage of users.

This I got, according to you no need to rush anything into 2.0 release. That's good news.

> And if they are making changes to the NT process, maybe the shortlist would be the better thing to import rather than / including the team sheet.

Here I am lost. Who are "they" ?  HT devs ?   What is the shortlist you are talking about ? What is you call the team sheet ?

> As a side comment, I'm in "thank you cap mode for Q2 players who missed out because we didn't qualify". I've got no need to add them to the HO squad, because they won't stick around, but I'd like to keep track of the real prospects, hence the thought above about the shortlist.

Here again I didn't catch a thing.


As you can see you will have to educate us about the NTHRF module (or at least me).  Can you please be very specific about:
   1) current functionality? What it does and how you are using it?
   2) clear description of what changes you would like to see 

Thank you

**Comment by yaute74** [comment]
Bad news, the teamid is not the good way to test if it's national team.
So I do something else for this part

**Comment by akasolace** [comment]
@yaute74 ok, for curiosity what is the correct way to test this?

**Comment by DavidatorusF** [comment]
@akasolace 
I think you need the userid, if the manager is a National coach, you get the players through the  NationalPlayers API

**Comment by Synthespian** [comment]
1) whilst I'm an u20 manager, I'm happy to help with testing.  
2) definitely want both an u20 and a full NT as I bet there's a difference or two somewhere. ;)
3) or just get the NT managers to download and send you the nthrf files.

**Comment by yaute74** [comment]
> @akasolace   ok, for curiosity what is the correct way to test this?

His solution is to create a list with all teamid, but I don't like it.

> @DavidatorusF  I think you need use the userid, if the manager is a National coach, you get the players through the NationalPlayers API

I don't understand your solution

> @Synthespian whilst I'm an u20 manager, I'm happy to help with testing

Realy appreciate your help

> @Synthespian  definitely want both an u20 and a full NT as I bet there's a difference or two somewhere

Why do you say that ? it work for national team. The danish manager do a test

My solution is to add a new field in "BASICS" table to indicate if it's a national team. If we use the download from NtHrf menu the flag will be set to yes, if we use the "standard" download to false.
The only problem if for the old databse, but ony @Synthespian  and Danish manager use it.

**Comment by Synthespian** [comment]
> My solution is to add a new field in "BASICS" table to indicate if it's a national team. If we use the download from NtHrf menu the flag will be set to yes, if we use the "standard" download to false.
> The only problem if for the old databse, but ony @Synthespian and Danish manager use it.

If it's the only way you get the hrf then surely it's a element you can incorporate as you write the hrf fle?  Seems sensible.
Silly question, what functionality are you trying to **_enable_** with the NT team that a standard manager would not want?
My guess is that it would be reduced functionality (don't need training page, etc) so you could even make it a user task to state that this db is an NT one.

**Comment by yaute74** [comment]
>Silly question, what functionality are you trying to enable with the NT team that a standard manager would not want?

Actually I just want that Download HRF and lineup works (no other things)

>My guess is that it would be reduced functionality (don't need training page, etc) so you could even make it a user task to state that this db is an NT one.

I've been thinking about this solution, it more easier to implement and a more secure change

@akasolace @DavidatorusF  what do you think about it ?

**Comment by DavidatorusF** [comment]
@yaute74 
why do you want lineup ?

NT coach need his players for simulate his lineup, he don't care about the old one...

about upload/download lineup, it's something who didn't work before for NT

and remember that non-supporter will never be allowed to upload their lineup

**Comment by akasolace** [comment]
> @akasolace @DavidatorusF what do you think about it ?

@yaute74  I am not familiar with this topic. If I am most information are coming from NTHRF file (from hattrickportal) and not from CHPP, correct ? Is it a mix of datasource you have to deal with ?

@yaute74   is the test to check whether or not it as NT team not reliable ?  In case it is not reliable,  you are suggesting on first import to ask the user whether or not it is a NT team and if it is the case to store that information in the database ?  Is it correct

**Comment by yaute74** [comment]
@akasolace to my knowledge all datas come from CHPP

For the lineup problem I create the issue #196 The Danish national team manager want to use it. I send an HO.jar to  Synthespian with debug info. If it's not an esay modification I will do nothing.

For this issue, download of hrf work but the source code to check if it's a national team is not good. So I suggest two solutions:
- add a flag in the database
- add an option when we create the database (in user.xml)

For me the second is better because it will work with existing databases of national team manager.
We can enable/disable the modules we want. 
We can remove module NtHRF and have one 'download' menu and call the good program depending of the option.

**Comment by DavidatorusF** [comment]
@akasolace 
module NTHRF was a way for only get NT players already in the NT team

with the HRF from Portal, NT Coach and his scouts have the possibility to import a list of players, list they have created on Portal

as I understand, Yaute work for NT team become a "regular" team

**Comment by akasolace** [comment]
@DavidatorusF ah ok thanks for the precision

**Comment by akasolace** [comment]
@Synthespian  can you confirm I can close this bug ?

Thanks

**Comment by Synthespian** [comment]
Sure.
I'll re-test the new "flag" when it's released (unless I've missed it :P).  The rest (inc the hrf download) works.
Not sure if you guys wanted me to close, or for you, so just commenting for now.

Thanks! :)

**Comment by akasolace** [comment]
> I'll re-test the new "flag" when it's released
what do you mean ?

> Not sure if you guys wanted me to close, or for you, so just commenting for now.
if you tell me latest dev version fixes that issue, I will close it .

thanks
