### ISSUE TITLE
[eFEAT] improve NT HRF module 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#108]
linked to bug:  #107
the idea is tp improve NT HRF module to allow user 2 have database and a single HO install.
Get more information from @Synthespian and or from @DavidatorusF

**Comment by akasolace** [comment]
@yaute74 , @DavidatorusF  is this really an open ticket or should it be closed ?

**Comment by yaute74** [comment]
@akasolace I think it could be close
