### ISSUE TITLE
[BUG] training wrong value displayed for new player

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1080]
I just bought a player, 

As expected in HT, I have no information about skills development

![image](https://user-images.githubusercontent.com/1136496/121245175-ffafd200-c89f-11eb-8ddf-5033d8a6fd75.png)

In HO!  it shows:

![image](https://user-images.githubusercontent.com/1136496/121245238-15bd9280-c8a0-11eb-928b-8c75fe8b8dbe.png)

whereas in reality it has PM = 3 and Scoring = 16  (values correctly displayed in Lineup tab)

**Comment by wsbrenk** [comment]
@akasolace do you mean the values given in training development of ...?
these values are expected skill changes in the future.

**Comment by akasolace** [comment]
I thought training development was past training (I think display can really be clarified see #1079 ).  
Still,  I bought the player with skill 16 in scoring and HO! tells me that in 2 days his skill will drop to 16 (which is also incorrect).

**Comment by wsbrenk** [comment]
>  (I think display can really be clarified see #1079 ).
Still, I bought the player with skill 16 in scoring and HO! tells me that in 2 days his skill will drop to 16 (which is also incorrect).

i confirm clarification of the display. currently it is done by different colors. black letters for past skill ups, colored letter for future skill ups. Bad tagging of selected player is a problem of the dark mode.

Could you debug, why your new player shows a skill down from 17 to 16? I can't see, when your download was done and if it could be, that the player had skill 17 then!?

**Comment by akasolace** [comment]
no I purchased my player with skill 16, also HO! forecast a loss o skill from 17 to 16 to happen in 2 days ... (not in the past)

**Comment by akasolace** [comment]
I just updated HO! and still the same issue  (squad tab is good but Training tab predict a fake skill drop )



![image](https://user-images.githubusercontent.com/1136496/121319818-ded19600-c90c-11eb-8b26-7071ad82bc0a.png)

![image](https://user-images.githubusercontent.com/1136496/121319993-09bbea00-c90d-11eb-95cb-681d72c708f4.png)


![image](https://user-images.githubusercontent.com/1136496/121319928-f741b080-c90c-11eb-95d5-09e9972817b1.png)

**Comment by akasolace** [comment]
actually I just noticed plenty of players have that bug ...

**Comment by wsbrenk** [comment]
@akasolace I suspect that we mistakenly do not specify the target skill, but the initial skill on skill drops.

Since HO assumes subskill 0 for new players, it is propable that the skill drops in the near future.

**Comment by akasolace** [comment]
My understanding is that skill drops only occur or player above 27 (not the case here).
Also HO does not really report a skill drop here, my player is at 16 and HO! says skill drop to occur tomorrow to get to level 16 (and tomorrow is not even a Monday when skill drop occurs). 
So here it is really all wrong ....
However I put all this to HO 6.0 because I think this panel deserve a big refresh (not just a quick fix) ...

**Comment by wsbrenk** [comment]
what I suspect is that your player dropped to 15,999, and in the display it was rounded up again to 16

**Comment by akasolace** [comment]
then maybe we should not use the nb of decimal from user preference for rounding but more for truncating ... it might be less confusing across the app. What do you think ?

**Comment by wsbrenk** [comment]
i tried to check my assumption - i can't find any rounding issue up to now.

you should try to debug FuturePlayer.previewPlayer to find the reason for the skill drop and it's wrong display

**Comment by wsbrenk** [comment]
skill losses only begin at the age of 28 years. This is what i found today. As far as i can see, this was changed about  3 years ago.
