### ISSUE TITLE
[BUG]wrong rating values

### ISSUE THREAD

**Issue by eljardinero4** [akasolace/HO#1086]
1. the simulated rating values in the setup page are very much lower than in reality
2. in the past I was able to see whole team in the same page... 

![hattrick bug](https://user-images.githubusercontent.com/84559255/121767786-dec6d580-cb5a-11eb-8fcb-2eee312bcd41.JPG)

 - Windows 10
 - Version 5.0 DEV (r3566)

**Comment by akasolace** [comment]
@eljardinero4  normally difference are always below 1, Are you takling about much more bigger difference ?

**Comment by eljardinero4** [comment]
Yes I'm talking about bigger differences, e.g. MF rating: HO says armselig(min) while in HT it's brillant (tief)...
but the number in HO for the same rating is 9.24...

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/121812843-b7126300-cc69-11eb-8828-629a178bf5a3.png)

text represantation match rating numbers and differences to previous linup setting is displayed again

**Comment by eljardinero4** [comment]
this wasn't fixed...

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/129441868-b589f1a9-ab86-424d-be46-2eb3e2b791dc.png)

this is displayed in my r3672 (HO-Dev release). The skill names are looking correct, or not?

what do i see wrong?

**Comment by wsbrenk** [comment]
if your point is the discrepance to the hattrick values, did you check the values at minute 0?:
![image](https://user-images.githubusercontent.com/11821502/129442094-b905b701-e5b8-4402-bbf0-3d16da40fe80.png)

only these should correspond to hattricks values.

**Comment by eljardinero4** [comment]
I just installed the latest version but I can't open HO any more, I'm getting below error message. What do I need to do?![Unbenannt](https://user-images.githubusercontent.com/84559255/129473264-43f4042b-6f5f-4ca4-bee0-c6dd54922102.JPG)

**Comment by wsbrenk** [comment]
@eljardinero4 could you please check with this version: https://github.com/akasolace/HO/releases/tag/v5.0.3673-dev

PLEASE BE CAREFUL USING DEV_RELEASE - never without backup of your previous installation including db folders.

**Comment by eljardinero4** [comment]
Now it works, thanks a lot!

**Comment by wsbrenk** [comment]
#1118
