### ISSUE TITLE
[eBUG] Missing Income for some tournament type 

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#109]
**Describe the bug**
In the stats tab, doesn't showed the income value, in case of some tournament type

**Screenshots**
![Cattura2](https://user-images.githubusercontent.com/15519907/54916040-db52bf80-4ef8-11e9-95b9-a1a0ed5c2764.PNG)

**Platform information:**
 - OS: all
 - Version 2 r1075

**Comment by akasolace** [comment]
cloed by 4a32b9a
