### ISSUE TITLE
[BUG] wrong specialty in youth academy

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1095]
feedback from wettnetzer:

wettnetzer
Moin. Mir ist grad ein kleiner Fehler im HO (in der neusten dev) im Internat aufgefallen. Aufgrund des SEs hier (119372013) in Minute 32 wurde Achim Rössert im HO als Köpper markiert. Er war jedoch der Flankengeber, der Köpper ist Folko Sautner.

I just noticed a small error in the HO (in the latest dev) in the youth module. Due to the SEs here (119372013) in minute 32, Achim Rössert was marked as header in the HO. However, he was passing, the header is Folko Sautner.

**Comment by akasolace** [comment]
closed by #1096
