### ISSUE TITLE
[BUG] writing arabic

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1101]
As the only team, the wages in HO of the team in kuwait are not normal writing - but writing in arabic. but it's not only the wages

- site statistic / arena the income total are in arabic
- site transfer / the total is in arabic
- site misc /the overview "this week" and "previus Week" is in arabic

see the pictures here

![BUG Zahl_0](https://user-images.githubusercontent.com/88058929/127222979-67bce87f-8284-47ad-8096-bedd91416e4d.jpg)
![BUG Zahl_1](https://user-images.githubusercontent.com/88058929/127222980-0c6c2143-0078-4be1-bac7-d78773763b33.jpg)
![BUG Zahl_2](https://user-images.githubusercontent.com/88058929/127222985-8f3eb20a-9448-4a01-b5b1-0ec7ca9d73ef.jpg)
![BUG Zahl_3](https://user-images.githubusercontent.com/88058929/127222987-a1cb0613-3ddd-4c09-9f2c-f69d3419da4d.jpg)

how can i change this?
thank's pepper

HO Version 4.1

**Comment by wsbrenk** [comment]
CurrencyUtils.getLeagueCurrencyFormater should get an option to override the league settings by a user configuration

**Comment by peppermil** [comment]
In HO version 3.0, the numbers are all written normally - also not in arabic. only the currency symbol is in arabic.

**Comment by wsbrenk** [comment]
curious: 
release notes "wages/prices are formatted as team local currency as opposed to host system currency (bug #93)"
was part of the 1.436 release

**Comment by wsbrenk** [comment]
hattrick displays currency in CHF. So currency will be determined by user's first team's league, not by second or third teams.

**Comment by wsbrenk** [comment]
store countryId of first team together with currencyRate in XTRAData (and Module_configuration), to select CurrencyFormat.

**Comment by wsbrenk** [comment]
@peppermil if you want, you could try to test it with the currently released DEV-version 5.0.3729

But be careful - never use a DEV version without backup of your database and program folders

**Comment by peppermil** [comment]
thank you - it worked good

**Comment by peppermil** [comment]
ups sorry

**Comment by wsbrenk** [comment]
many thanks for your feedback

**Comment by peppermil** [comment]
I open it again - various amounts are again in Arabic script ;)
