### ISSUE TITLE
[eFEAT] verify if/how positive/bad weather events are considered in prediction rating

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#111]
verify if/how positive/bad weather events are considered in prediction rating. They are surely not in line with the latest reform

**Comment by mistermax80** [comment]
@akasolace  I could wrong, but I remember in line up, relation to weater apperar these icons.
![Cattura1](https://user-images.githubusercontent.com/15519907/56189944-771fa900-6029-11e9-93ba-d1b3f2a6001a.PNG)
![Uploading Cattura3.PNG…]()

**Comment by akasolace** [comment]
@mistermax80 you are right
