### ISSUE TITLE
[BUG] An error has occurred during startup

### ISSUE THREAD

**Issue by Asterus48** [akasolace/HO#1114]
**Describe the bug**
I have installed the 5.0 DEV version for MacOS, both the version, with or without Java, after the installation without errors the error appears when HO is launched.

**To Reproduce**
1. Click on the HO icon
2. Error in the title
3. java.lang.ClassNotFoundException: core.HOLauncher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:80)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)

**Screenshots**
<img width="747" alt="Schermata 2021-08-12 alle 17 31 55" src="https://user-images.githubusercontent.com/50919908/129226363-4c639f50-8842-4a4e-a818-5bee30d563bf.png">

**Platform information:**
 - OS: macOS 
 - Version 11.5.2

**Comment by adrimorales1** [comment]
Same error

OS: Windows
Version: Windows 11 Pro  22000.132

**Comment by wsbrenk** [comment]
@tychobrailleur if i compare the artefacts in https://github.com/akasolace/HO/releases/tag/v5.0.3673-dev and the latest in https://github.com/akasolace/HO/releases/tag/dev i see a quite big difference in the size of the artefacts. Could it be, that the latest run did something wrong?

**Comment by Asterus48** [comment]
the two cases are different, after the error with the previous version I uninstalled v5.0.3673-dev and reinstalled 4.1, when a new 5.0.3703-dev. was released, I tried to reinstall it and the new error appeared , now uninstalled again waiting for it to work better

**Comment by wsbrenk** [comment]
Thanks for that information - To confirm: Both new dev-releases did not start on your mac?

@adrimorales1: same on windows? 

my own 3673-installation (HOSetup-5.0.3672.0-DEV-JRE.exe) on windows works fine!

**Comment by Asterus48** [comment]
the two cases are different, after the error with the previous version I uninstalled v5.0.3673-dev and reinstalled 4.1, when a new 5.0.3703-dev. was released, I tried to reinstall it and the new error appeared , now uninstalled again waiting for it to work better

> Thanks for that information - To confirm: Both new dev-releases did not start on your mac?
> 
> @adrimorales1: same on windows?
> 
> my own 3673-installation (HOSetup-5.0.3672.0-DEV-JRE.exe) on windows works fine!

no, the previous 3672 - DEV start fine, the error is on training
    Click on Training
    See error "Cannot invoke "core.training.WeeklyTrainingType.getTrainingSkillPartlyTrainingPositions()" because "tt" is null"

**Comment by wsbrenk** [comment]
> See error "Cannot invoke "core.training.WeeklyTrainingType.getTrainingSkillPartlyTrainingPositions()" because "tt" is null"

this bug is in r3650 (#1097) - should be fixed in HOSetup-5.0.3672.0-DEV-JRE.exe

**Comment by Asterus48** [comment]
> > See error "Cannot invoke "core.training.WeeklyTrainingType.getTrainingSkillPartlyTrainingPositions()" because "tt" is null"
> 
> this bug is in r3650 (#1097) - should be fixed in HOSetup-5.0.3672.0-DEV-JRE.exe

ok, tnx

**Comment by wsbrenk** [comment]
@tychobrailleur:  the HO.jar file is missing in installation folder.

**Comment by wsbrenk** [comment]
#1121 fixed this
