### ISSUE TITLE
[eBUG] change age display in squad tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#113]
**Describe the bug**
currently a player of 17y and 7day is displayed as 17.7
wherea a player of 17y and 100 days is displayed as 17.100

it should either be real decimal or a clear display of years and days

**Comment by brokenelevator** [comment]
I don't believe it to be a bug. I think format years.days is pretty clear and real decimal would be unnecessary obfuscation.
What would be clear display for you?

**Comment by akasolace** [comment]
funny because to me always found this really confusing.
either true decimal or something like in HT: 17y 50d

**Comment by brokenelevator** [comment]
I guess to each their own.

Like I mentioned true decimal would be useless. You wouldn't be able to
find the days without calculator. Unless you can multiply by 112 in your
head, which most people don't.

As for other ways:
17y 50d - Would take more space and is language dependent. On the opposite
side it is clear as a day, for most people.
17(50) - No really clearer then 17.50, other than people will not confuse
it with a decimal.

For me we can do either of these. I don't see a need but I don't really pay
attention to this sort of details (as long as I can understand them). I
wouldn't even know what HT uses, unless I specifically checked, so...

czw., 25 kwi 2019 o 14:08 akasolace <notifications@github.com> napisał(a):

**Comment by imikacic** [comment]
I would prefer 17(50) over 17.50 or 17y 50d

P.S. Hello, just lurking around

**Comment by akasolace** [comment]
Personally I would prefer `17y 50d` but I could live with `17(50)` but thank you for the input @imikacic

**Comment by yaute74** [comment]
I aslo prefer the 17 (50). Hattrick use it player table:
![screenshot](https://user-images.githubusercontent.com/34601782/56963229-c3ee9e00-6b58-11e9-95e8-779817a90f1f.png)

**Comment by akasolace** [comment]
@yaute74  I haven't noticed that it is how HT displays it ... so it clear this is the one we should adopt
