### ISSUE TITLE
[FEATURE] Automated DEV Release next steps

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1135]
my latest changes were
* start the action on push to the master branch
* selection of the release tag/channel is done by the settings in build.gradle and published in version.properties and github tag
* build number is determined by the github run number (no longer by gradle run number)

if other maintainer @akasolace or @tychobrailleur agree with this approach, we should remove release-beta and release-stable action.

before releasing the first stable version, the language file processing needs to be implemented.

**Comment by wsbrenk** [comment]
#1136 enabled the poeditor pull task

**Comment by wsbrenk** [comment]
to check if the translation workflow is OK, we should change/edit some translations and verify that a new build will include them.

@akasolace please enable me to do that. i think i requested an account.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/131250752-29b0ea5a-7a17-41cf-a4fd-5ead9ec6860e.png)

this dialog shows the latest language keys i introduced. I would like to translate them in poeditor and verify if the next dev release will include this translations.

**Comment by wsbrenk** [comment]
@akasolace my translations didn't arrive in latest dev-release;-(

**Comment by wsbrenk** [comment]
changing the gradle build order doesn't help. 

@akasolace is there some kind of commit in poeditor required?

**Comment by akasolace** [comment]
@wsbrenk I think I know what is going on   but I dont know how to fix it ...

**Comment by wsbrenk** [comment]
@akasolace added some logging to build.gradle: 


> Task :preparingBuild
Deleting build and execution files ....
...
Hangul(Korean).properties 104821 1630746402657
Deutsch.properties 97504 1630746402657
Indonesian.properties 24340 1630746402661
...

> Task :processResources
> Task :check
> Task :poeditorPull
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.
> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :assemble
> Task :build

> Task :createLanguageFileList
...
Hangul(Korean).properties 105279 1630746466117
Deutsch.properties 98050 1630746459457
Indonesian.properties 24340 1630746402661
....


looks like the poeditorPull is working. the file size and last modification time stamp is changed for some property files.
but the new translations are still NOT shown in current dev version;-(

**Comment by wsbrenk** [comment]
Heureka - got it:

![image](https://user-images.githubusercontent.com/11821502/132089906-4dea9c69-7151-4416-b427-6875ca9e4eed.png)

processResources.dependsOn poeditorPull
was the solution

**Comment by wsbrenk** [comment]
what's left to do is some cleanups:

* remove unused -beta and -stable action files
* remove logging and other unused parts from the build.gradle
  * task printVersion
  * latest*.html
  * ...

**Comment by wsbrenk** [comment]
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead. Consult the upgrading guide for further information: 
at build_1tr20zv7oux82mxdcl5x0juch$_run_closure2.doCall(C:\Users\wolfgang\Documents\HO\build.gradle:33)

at build_1tr20zv7oux82mxdcl5x0juch$_run_closure11$_closure33.doCall(C:\Users\wolfgang\Documents\HO\build.gradle:165)

**Comment by wsbrenk** [comment]
the log of the action claims

 found 1 releases to delete
👍🏼  all releases deleted successfully!

but there are a lot of releases, which are not deleted

**Comment by akasolace** [comment]
how do you delete release ? 
also is it not too much to build release on each commit ?

**Comment by wsbrenk** [comment]
each commit on master. for the moment i'm quiet happy with that, but

we could use another "standard"-develop branch with is NOT released
or we change the builder to run on a release branch

**Comment by wsbrenk** [comment]
the delete is done by some github action plugin which i do not know

**Comment by wsbrenk** [comment]
> but there are a lot of releases, which are not deleted

last runs successfully deleted previous dev-releases. => Problem solved.

**Comment by wsbrenk** [comment]
@tychobrailleur , @akasolace : How do you see the runner's complaint about gradle 7.0 incompatibility?

The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead. Consult the upgrading guide for further information:
at build_1tr20zv7oux82mxdcl5x0juch$_run_closure2.doCall(C:\Users\wolfgang\Documents\HO\build.gradle:33)
