### ISSUE TITLE
[eBUG] Freeze after click on 'Player Analysis' tab

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#114]
**Describe the bug**
Freeze after click on 'Player Analysis' tab

**To Reproduce**
Click on tab

**Screenshots**

**Platform information:**
 - OS: Linux
 - Version Dev

**Additional context**
In MatchLineupPlayerTable.java don't use byte because IMatchRoleID. could be greater than 127

**Comment by akasolace** [comment]
I introduced that bug with support for extra lineup.
I guess it might be already closed in my local branch if not I will tackle it later on ...
