### ISSUE TITLE
[eBUG]  DB: constraint violation: XTRADATA column: CURRENCYNAME

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#116]
HO still launch but the following is logged:

JDBCAdapter: JDBCAdapter.executeUpdate : java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10855 table: XTRADATA column: CURRENCYNAME
Statement: INSERT INTO XTRADATA ( HRF_ID , CurrencyRate, HasPromoted , LogoURL , SeriesMatchDate ,TrainingDate, EconomyDate, LeagueLevelUnitID ) VALUES(95,10.0,0,'//res.hattrick.org/teamlogo/18/176/1755/1754082/1754082.png', '2019-05-04 21:00:00.0', '2019-05-03 05:15:00.0', '2019-05-04 02:30:00.0', 36840 )
java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10855 table: XTRADATA column: CURRENCYNAME

**Comment by brokenelevator** [comment]
Do you have an updated database?
In 'updateDBv23' CURRENCYNAME is dropped so this problem should not appear.

**Comment by akasolace** [comment]
I had this message when running DEV version, I will double check

**Comment by akasolace** [comment]
closed by ef27789
