### ISSUE TITLE
[BUG]Transfer Tab - wrong season

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1172]
In the transfer overview, the global season is listed. if you select the individual season, the season of the local season is added. There is no possibility to enter the global season

Global season 78
Swiss season 66

I discovered this in version 4.1 as well as in DEF version 5. In the old version HO 3.0 the season is correct.

![BUG_Transfer_all season](https://user-images.githubusercontent.com/88058929/132512101-798b8942-ada5-45d2-802a-b6458491e958.jpg)

![BUG_Transfer_season 66](https://user-images.githubusercontent.com/88058929/132512127-4dc79e1c-d41f-44ba-847a-8f05ded36118.jpg)

**Comment by wsbrenk** [comment]
@peppermil could you check if seasonoffset is correctly stored in your basic table

in dev version you can start sql editor with debug -> sql-editor
copy the command 
select * from  BASICS
to the text field and execute the statement by pushing F5 or the correspondig button
![image](https://user-images.githubusercontent.com/11821502/132584490-f6a7998b-24c7-4f1c-8440-26c8d6efea15.png)

@akasolace in my database i found a hint for our week 16 problems: see the selected line where season offset 1 is calculated (should never happen).

**Comment by peppermil** [comment]
i have 2 entries, but i dont know which one is the right one
- 0
- (null)

![Screenshot 2021-09-09 113230](https://user-images.githubusercontent.com/88058929/132661741-79270f65-9377-4544-9961-7e8ad13bbeeb.jpg)
![Screenshot 2021-09-09 113319](https://user-images.githubusercontent.com/88058929/132661765-1c6d112f-29e4-455c-8690-4c7ccad7ade2.jpg)

from the second team

![Screenshot 2021-09-09 113900](https://user-images.githubusercontent.com/88058929/132663508-4a88a301-ddba-4813-880d-2b40e99079a9.jpg)

**Comment by akasolace** [comment]
@peppermil  could you share your db here ?

**Comment by wsbrenk** [comment]
SeasonOffset is the problem: if switzerland is 12 seasons behind sweden the value 12 is expected in downloads after end of 2019. Prior downloads should show (null).

**Comment by akasolace** [comment]
yes, I checked xml from hattrick and it shows correct value:

```
    <League>
      <LeagueID>46</LeagueID>
      <LeagueName>Switzerland</LeagueName>
      <Season>66</Season>
      <SeasonOffset>-13</SeasonOffset>
```

**Comment by wsbrenk** [comment]
@akasolace colors are not optimal for nimbus theme:

![image](https://user-images.githubusercontent.com/11821502/132759117-ca06d1d7-f6dc-4ac2-bc06-72fd2e9067c7.png)

**Comment by wsbrenk** [comment]
>      <SeasonOffset>-13</SeasonOffset>

@akasolace is this number stored in your basic table. tbh i expected a positive number. i fear, if we are ready to get a non zero offset we could have a sign problem. but i have no chance to debug this with my german teams.

**Comment by wsbrenk** [comment]
Not necessarily - the download on 2021-08-21 23:00 was a download of my team and it shows a season offset of (1), which is wrong for my german league. All other downloads are showing the correct value 0. I had the idea that this might be an error on ht side, which might explain our week 16 problem which arrises from time to time.

The values 0 in @peppermil database are definitely another error - i fear on our side, but without a team in foreign countries or his database i can't reproduce it. 

Did you see the "white" arrows on white background in the new transfer panel?

**Comment by peppermil** [comment]
> 
> 
> @peppermil could you share your db here ?


@akasolac > if you tell me - where the DB is - yes

**Comment by wsbrenk** [comment]
@peppermil on windows systems you find them in %APPDATA%/HO. one of the zip-files would be great.

**Comment by peppermil** [comment]
[https://1drv.ms/u/s!AjKUl1nPppPXjZkoo_aC4WluRFiHJg?e=sIAvgt](url)

**Comment by wsbrenk** [comment]
thank you

**Comment by wsbrenk** [comment]
first download on my side stores correct offset value:

![image](https://user-images.githubusercontent.com/11821502/132922990-337cb146-c5ae-499b-a515-60a57add5a80.png)

**Comment by wsbrenk** [comment]
fixing sign error in HTCalendar.getHTSeason gives this:

![image](https://user-images.githubusercontent.com/11821502/132924173-7176bfa1-bcbf-4544-834c-0832f091342e.png)

after reloading all your transfers. Up to now i have no idea, why your downloads gives season offset of 0 and not the correct -13.

**Comment by wsbrenk** [comment]
@peppermil could you check your hrf-files, if they show the correct season offset:

[basics]
application=HO
appversion=0.0
date=2021-09-11 00:03:11
season=66
seasonOffset=-13
...

**Comment by peppermil** [comment]
yes, it is

[basics]
application=HO
appversion=4.1
date=2021-09-11 09:44:13
season=66
seasonOffset=-13
matchround=3

**Comment by wsbrenk** [comment]
very strange  - i don't find anything that could explain your wrong values stored in your database. I would now check for errors in your runtime environment.  is there anything suspicious in your log files after you downloaded data (%APPDATA%/HO/logs)?

**Comment by peppermil** [comment]
hi
of the first, thank you for your efforts ;)

I also find it also very strange, especially since it worked for you.

Here are my logs
https://1drv.ms/u/s!AjKUl1nPppPXjZknL7tVntSPDsaRxQ?e=ErvYgI

**Comment by wsbrenk** [comment]
got it! Please test again with current 5.0 dev version.

error was repaired in https://github.com/akasolace/HO/commit/e5b46c4743916acfd626d4ca3fb45c726441b7f3#diff-1476fe820e5d82ea5a462531f38a5824c9f5c98f618e37ef2376ad0cba9e40ab
 Basics(Properties) seasonOffset->seasonoffset

**Comment by peppermil** [comment]
when i make a update in the DB from 4.1 - was wrong (whit the version HOSetup-5.0.3773.0-DEV-JRE)

![Screenshot 2021-09-12 094028](https://user-images.githubusercontent.com/88058929/132987731-abf2ecc2-c9d3-4e8e-a782-2703458da210.jpg)

when i startet with a new DB - was 1 player not correct (whit the version HOSetup-5.0.3773.0-DEV-JRE)

![Screenshot 2021-09-12 112955](https://user-images.githubusercontent.com/88058929/132987751-04450c0e-db90-4b09-82ba-24b824d27671.jpg)

when i take the portable version - was perfekt (whit the version HOSetup-5.0.3774.0-DEV-JRE)

![Screenshot 2021-09-12 143935](https://user-images.githubusercontent.com/88058929/132987941-edbdc8c5-fd27-4efe-993f-db3cee11e6db.jpg)

**Comment by wsbrenk** [comment]
transfers with fired players were not updated in database
