### ISSUE TITLE
match module improvements

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1181]
Adding two requests about this or at least a discussion about them.

1. Do you think a third option (mentioned it earlier) for cups would be logic/useful?
Today: 
"Show my cup games" = National + Secondary Cups
"Show my Secondary cup games" = Secondary Cups only

I think it would make sense to also have 
"Show my National cup games" = National Cup games only

How do you feel about that?

And...
2,
On matches module there are 3 Tabs.
a. Matches
b. Stats (W-D-L)
c. Stats (Goals)

On the second one I can now chose venue: "All, Home, Away, Neutral"
Example: Lets say I'm checking my cup games (all of them), I have 288 cup matches in total and on the tab 'Stats (W-D-L)' I now chose venue 'Home'. I can now see W-D-L-stats from my 70 Cup Games on home ground. But if I change tabs to 'matches' all 288 are listed
Also the tab 'Stats (Goals)' still shows stats from all 288 matches,

Is it possible to update all 3 tabs according to how I chose to show "All, Home, Away, Neutral"?

Edit: If the latter is possible maybe drag the venue-options away from the one TAB and put it outside like:
![hepp](https://user-images.githubusercontent.com/12071221/132245484-27e1d75c-21de-485d-a47b-f74818bf0daa.png)

_Originally posted by @murko69 in https://github.com/akasolace/HO/issues/470#issuecomment-913756973_

**Comment by akasolace** [comment]
Hi @wsbrenk not sure I will have a lot of time but if thats ok I would assign this one to me and I would have a look at it whenever possible ...

**Comment by akasolace** [comment]
- [x] moves location selection to main tab
 - [ ] apply location selection to all query
 - [ ] introduce national, secondary and all cup
 - [ ] center and bold table headers

**Comment by akasolace** [comment]
@wsbrenk what I see today is 2 options: 
   - see my national cup matches
   - see my secondary cup matches
I will add an option:
  - see my cup match displaying both
