### ISSUE TITLE
[FEATURE]  Numeric Values in Statistic tab

### ISSUE THREAD

**Issue by manguz** [akasolace/HO#1199]
Hi, first of all, thank you very much for keeping alive this tool. I'd like to thank everyone envolved.
My simple request is if you can add numeric values near the dots in the new statistic tab.
New tab is great, but I really can't understand much like I used to with V4.

Cheers

**Comment by manguz** [comment]
Hi, any news about this? I was using version 4.1 just for this but now it seems broken as it doesn't download data anymore :(

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/200188871-dec6c181-a772-4e99-a030-fbba028b7e53.png)

found a way to enable tool tips - would that be sufficient?
showing all tool tips does not look good:

![image](https://user-images.githubusercontent.com/11821502/200189005-d9886733-87be-424e-baa6-446dff8102dc.png)

**Comment by manguz** [comment]
Need some adjustment from user side, but better than nothing in my opinion. Assuming you can make it toggleble.
Thank you very much for your work

**Comment by wsbrenk** [comment]
check box to control labels:
![image](https://user-images.githubusercontent.com/11821502/200642951-9a319fed-6d32-4db9-87f3-fced115e4878.png)

**Comment by manguz** [comment]
That's great! Great job, seems perfect now 
Thank you very much

**Comment by manguz** [comment]
![Castel De Britti FC (Versione JAVA_ 17 0 3) 10_11_2022 09_16_06](https://user-images.githubusercontent.com/1549220/201037739-7cc258da-36e6-4bab-96ff-d637a3edfa88.png)

Great JOB!!
