### ISSUE TITLE
[eBUG] first row of substitutes on DEV

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#120]
**Describe the bug**

**To Reproduce**
1. Go to 'DEV HO2 r1088'
2. Click on 'lineup'
3. Scroll down to 'first row of substitutes'

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/57039985-72303b80-6c5e-11e9-8396-3ce7966d57ba.png)
substitutes is not translated -> poeditor
first row of substitutes : I can't select the same player for different places

**Platform information:**
 - OS: Ubuntu 16.04

**Comment by DavidatorusF** [comment]
first row of substitutes
I don't think it's needed to see the players already on the field in the list

**Comment by akasolace** [comment]
@DavidatorusF I would like to replicate HT behaviour ...
