### ISSUE TITLE
[BUG] Training Application Tab not working

### ISSUE THREAD

**Issue by HOTester** [akasolace/HO#1214]
**Describe the bug**
1. On the training tab under the training functions tab, no training development is shown
2. On the Prediction tab under the training functions tab, no predictions are shown after updating future training
3. On the Analyzer tab, nothing is shown in the graph or the Training development pane
4. On the Effect tab, nothing is shown here either,

**To Reproduce**
1. Go to 'Functions->Training'
2. Update Future trainings by clicking "Edit All" and click "apply"
3. See error by clicking on all subtabs as mentioned above.

**Platform information:**
 - OS: Windows10
 - 20H2 Build 19042.1237

**Additional context**
Running version HO-5.0.3800.1-portable-win-BETA-JRE

**Screenshots**

![analyzer-tab](https://user-images.githubusercontent.com/92029826/136197439-9710d254-f276-469f-87be-dc1d02f8d0e2.JPG)
![effect-tab](https://user-images.githubusercontent.com/92029826/136197443-a3fc39ce-9e39-4112-bbee-1e8686a24d75.JPG)
![prediction-tab](https://user-images.githubusercontent.com/92029826/136197445-c86fe58f-3ea9-415d-86dd-23ce5658b6d9.JPG)
![training-tab](https://user-images.githubusercontent.com/92029826/136197446-731b07e1-e5af-41d1-a617-71837bd4ef0b.JPG)

**Comment by wsbrenk** [comment]
@HOTester sorry up to now i have no good idea about the reason of that issue.

could it be, you changed the training settings?
![image](https://user-images.githubusercontent.com/11821502/136673660-f1792071-6333-4eee-b4d0-8896135b3835.png)

for me it would be easiest if you could upload your HO database here (zip-file in %APPDATA%/HO/db). Then I could hopefully easily find the cause in the debugger.

**Comment by HOTester** [comment]
Please find attached the DB

[db_user-2021-10-09.zip](https://github.com/akasolace/HO/files/7317026/db_user-2021-10-09.zip)

**Comment by wsbrenk** [comment]
these are the settings from your database:

![image](https://user-images.githubusercontent.com/11821502/136698387-cc0550d3-ba68-4c7d-83c3-c774db1439b6.png)
