### ISSUE TITLE
[BUG] Error in LineUp Editor

### ISSUE THREAD

**Issue by HOTester** [akasolace/HO#1223]
**Describe the bug**
In the right hand side on the Lineup tab, an overview of the teams strength is shown.
There is a bar at the top, where you can select the minute in the game that you want to analyse.
The 80th minute is listed twice.
![image](https://user-images.githubusercontent.com/92029826/136704906-a7707545-ed8b-4687-bd59-de931817d2cc.png)

When pressing the second one, the following java.lang.NullPointerException is thrown
![image](https://user-images.githubusercontent.com/92029826/136705071-927811d6-db80-4c15-a851-90af3b4bebb7.png)

**To Reproduce**
1. Set your team in the LineUp editor
2. Click the second 80th minute  

**Screenshots**
See above

**Platform information:**
 - OS: Win10
 - Version 21H1 (19043.1237)

**Additional context**
Running HO version HO-5.0.3803-portable-win-BETA-JRE

**Comment by steffanots** [comment]
take
