### ISSUE TITLE
[eFEAT] refactor match highlight event type

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#123]
Actually event type is separate in type and sub type but it's no logical.
type is the hundred of the value
sub type is the rest

Example of event type started by 5:

> 500 | Both teams walkover
> 501 | Home team walkover
> 502 | Away team walkover
> 503 | Both teams break game (2 players remaining)
> 504 | Home team breaks game (2 players remaining)
> 505 | Away team breaks game (2 players remaining)
> 510 | Yellow card nasty play
> 511 | Yellow card cheating
> 512 | Red card (2nd warning) nasty play
> 513 | Red card (2nd warning) cheating
> 514 | Red card without warning
> 597 | Second half started
> 598 | Match started
> 599 | Match finished

All this event have the type!
A better way is to define all event in interface and create method for all case we use

**Comment by akasolace** [comment]
I never looked at that part. For the rest of CHPP it is indeed how it is done.

**Comment by yaute74** [comment]
we have this

>             	// Convert the ID to type and subtype.
>            	int eventKey = (Integer.valueOf(XMLManager.getFirstChildNodeValue((Element) root.getElementsByTagName("EventTypeID").item(0)))).intValue();
>            	final int highlighttyp = (int) Math.floor(eventKey/100);
>            	final int highlightsubtyp = eventKey - highlighttyp*100;

**Comment by brokenelevator** [comment]
@yaute74 I'm not sure what you mean. Have you checked IMatchHighlight class?

**Comment by yaute74** [comment]
@brokenelevator Maybe I am wrong. What a analyze:
- we get the highlights events in method XMLMatchdetailsParser:readHighlights
- the events id is separate in type and sube typ.
- events in the same hundred have the same type
- so Match started (598) and Red card (514) have the same type 5
- if we look in class IMatchHighlight type 5 is HIGHLIGHT_KARTEN 
- so for me it's not logical

What I want to do:
- add in IMatchHighlight all highlights events with their full id (no type and sub type)
- if necessary create method, for example:

>public static boolean isRedCard(int evtId) {
     if (evtId == 512 || evtId == 513 || evtId == 514) {
          return true;
     }
     return false;
}

**Comment by brokenelevator** [comment]
So what you want to do is to change all the fields there to full names and full values?
I suppose if the split is not rooted somewhere in code I'm fine with that. It may be somewhat clearer.
You could translate those while you are at it.

I'm not sure if the code example is the best idea...but without context can't think of a better one. Still if one would exchange codes for names it might be nice for readability.

**Comment by yaute74** [comment]
@brokenelevator 
>So what you want to do is to change all the fields there to full names and full values?

yes it's the goal

>I'm not sure if the code example is the best idea

why ? 

This example is to replace this code:
`else if ((hls.get(i).getHighlightTyp() == IMatchHighlight.HIGHLIGHT_KARTEN)
					&& (hls.get(i).getHighlightSubTyp() == IMatchHighlight.HIGHLIGHT_SUB_ROT
					|| hls.get(i).getHighlightSubTyp() == IMatchHighlight.HIGHLIGHT_SUB_GELB_ROT_HARTER_EINSATZ
					|| hls.get(i).getHighlightSubTyp() == IMatchHighlight.HIGHLIGHT_SUB_GELB_ROT_UNFAIR)`

**Comment by akasolace** [comment]
@yaute74 
I think @brokenelevator suggested to have something as follow for better lisibility:

public static boolean isRedCard(int evtId) {
if (evtId == IMatchHighlight.RedCard || evtId == 2YellowCards ) {
return true;
}
return false;
}

**Comment by yaute74** [comment]
@akasolace if you speak about the number, of course it was just for the example

**Comment by akasolace** [comment]
@yaute74 ah ok perfect then :-)

**Comment by brokenelevator** [comment]
> why ?

Like @akasolace said,  better visibility by using the names but I see it was just for example. I was also thinking or making it even better by making less operations but I can't think of how to do that.

**Comment by akasolace** [comment]
@yaute74  I did not really follow this one, should it be closed ?

**Comment by yaute74** [comment]
@akasolace I do nothing about it, so don't close it. I can work on it for the version 3.

**Comment by akasolace** [comment]
>@akasolace I do nothing about it, so don't close it. I can work on it for the version 3.

@yaute74 ok clear thank you 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaute74** [comment]
I close because after study it need to it takes too much effort for what it's worth
