### ISSUE TITLE
[eFEAT] Sort by training preview

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#124]
Could be great to sort table by training preview  (issue #44)

**Comment by akasolace** [comment]
you would do that by adding a column to the table ?

**Comment by yaute74** [comment]
I don't know, new column, popup menu, button in header.

**Comment by yaute74** [comment]
@akasolace  do you think something like this:
![image](https://user-images.githubusercontent.com/34601782/57615463-0910c800-757c-11e9-8769-08fa07491185.png)

With: training (estimate training)
And color depending 50%/100% position: color green/greelight (black/grey)
But I am not satisfied with the rendering, the color is not very visible

Question if we do that:
- column in which position ? last after column ?
- we remove icon and tooltip (I add for training preview) in player name column ?

**Comment by akasolace** [comment]
Hello @yaute74
  I would rather stick with what you did initially.
Hence, I suggest,  we add a very thin column on the left where we have the training indicator (i.e. the green bar, would be in that new column instead of the player name column). We could sort by training in clicking on that new column header. 
I would keep the infobull and we might add a new info bull for the column header.

What do you think ?

**Comment by yaute74** [comment]
@akasolace I will check this solution

**Comment by mistermax80** [comment]
link also: #234

**Comment by yaute74** [comment]
@akasolace I will propose another solution, manage a third click on the name column:
- first click sort by name ascending
- second click sort by name descending
- third click sort by training preview
- fourth click by name ascending
- etc ...

Add a column in first position is an important modification compare to the functionality and it will take more space.

**Comment by akasolace** [comment]
Sounds a good idea, does the job and implementation is simple. Only issue is that users won’t be easily aware of that functionality but this is no big deal ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment]
yes good idea: please reminder also the training tab: #234 😄 
![image](https://user-images.githubusercontent.com/15519907/70064203-68522a80-15e9-11ea-9ff5-d45ef660d4e0.png)

**Comment by yaute74** [comment]
@mistermax80 I do PR but I don't treat the training page because it's sorted from an invisible column and I don't want to broke something, if you want to do it....

**Comment by akasolace** [comment]
closed by afd64be

**Comment by mistermax80** [comment]
> @mistermax80 I do PR but I don't treat the training page because it's sorted from an invisible column and I don't want to broke something, if you want to do it....

Only default sort is on hidden column... Ok... I will do... 😭

**Comment by mistermax80** [comment]
@yaute74 , do you watch in my branc why doesn't works?

Thanks.

**Comment by yaute74** [comment]
@mistermax80  it's because OutputPanel don't use tableSorter (it call setRowSorter)

**Comment by mistermax80** [comment]
Thanks I will try to adjust in order to use tableSorter

**Comment by mistermax80** [comment]
@yaute74 
Do you advise me change in table sort or replicate the third click on the current table in that tab?

**Comment by yaute74** [comment]
@mistermax80 if you can the same behaviour than in squad tab

**Comment by akasolace** [comment]
same here, 

@mistermax80 will you close this one shortly? 
@yaute74 in case mistermax does not close it, do you want to tackle it or shoud I remove it from 2.1 release? 

I wait for your feedback

**Comment by yaute74** [comment]
@akasolace no, I cannot treat it sorry

**Comment by akasolace** [comment]
ok I remove the milestone .. we will advise later on on this one

**Comment by tychobrailleur** [comment]
I can look into this one, if no one is working on it.

**Comment by akasolace** [comment]
@tychobrailleur is there really something to be done here or should we simply close this one ?  your call ... :-)

**Comment by akasolace** [comment]
> I can look into this one, if no one is working on it.

@tychobrailleur is it still something you want to have a look at ? Doesn't sound a big one but @mistermax80 has been struggling on this one and @yaute74 seemed to think it was not a quick fix ... let me know

**Comment by akasolace** [comment]
@tychobrailleur I am really thinking of closing this one ... except if has you stated above it is something you want to look into .... I can also simply remove the 4.0 tag if it something you want to look after at some point .....

**Comment by tychobrailleur** [comment]
@akasolace Yes, I think it can be closed.  As far as I remember, the only outstanding table was the one in Training (cf. https://github.com/akasolace/HO/issues/124#issuecomment-561217067), the others being addressed with the “three-way click.”  

With all the recent changes to Training, and the current issues on master with Training tab, I will left this aside.
