### ISSUE TITLE
[eFEAT] Add stamina training like training preview

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#125]
Add stamina training (futur and done) like training preview (issue #44)

**Comment by akasolace** [comment]
closed by #bda2ab56b333d217810b77912d84db9e004f4ae1

**Comment by mistermax80** [comment]
@yaute74 
The partial stamina training is not detected:
![image](https://user-images.githubusercontent.com/15519907/70065578-a3edf400-15eb-11ea-83ad-f07bbcb5cc6d.png)

HT situation:
![image](https://user-images.githubusercontent.com/15519907/70065404-596c7780-15eb-11ea-8737-53257e8e0e83.png)

**Comment by yaute74** [comment]
@mistermax80 thank for report I will have look when I have a moment

**Comment by yaute74** [comment]
@mistermax80 @akasolace I have look somewhere that players are not train during out of play.
Is right ? it's the same thing for stamina ?

In my match, my player enter at minute 31 and match finish at minute 95 and on train page is written:  Komlan Leke | DC (64') -- | --

**Comment by akasolace** [comment]
@yaute74  what do you mean by "out of play"

95-31 = 64 ... it looks correct ... what surprises you ?

**Comment by yaute74** [comment]
@akasolace 
Before all matchs ended at 90'
When they introduce out-of-play, I read somewhere (don't remember where) that players are not trained during out-of-play (so if match ended at 95', no train from 90' to 95').
Is that true ? I have no substitute in training position this week, so I can't confirm.
And I was wondering if it's the same thing for stamina.

**Comment by akasolace** [comment]
@yaute74 ah ok I understand now. I was not aware of this, I always thought they received normal training during that time but capped at 90' max for a given player.
The best is to ask an official on HT forum, except if @DavidatorusF already knows the rule

**Comment by mistermax80** [comment]
This is my situation after cup match:
![image](https://user-images.githubusercontent.com/15519907/70225289-06abd080-174f-11ea-84ef-34225fcef2a5.png)

**Comment by yaute74** [comment]
@mistermax80 I know the max training is 90'. The question is about out-of-play.
- I have a match ended at 95'
- my player enter at the 80' minute in a training position
=> He is training 10 minutes or 15 minutes ? I am not sure it's 15 minutes...

**Comment by mistermax80** [comment]
I think to have the response:
in relation to my screen in cup match:
daniel letujiu played the first part of the match, after leoncio substitute him.
So, daniel played 76 min, leoncio 16 min --> then 90' - 76' = 14' and not 16', I think leoncio played 14 min and 2 min extratime (match enden in 92 min).

**Comment by yaute74** [comment]
@mistermax80 but leoncio is not in a train position ? his bar is not green

**Comment by akasolace** [comment]
@yaute74 have you asked on HT for official confirmation of how this off-time training work?

**Comment by yaute74** [comment]
@akasolace I will ask on forum

**Comment by mistermax80** [comment]
In fact! He received only stamina training.

**Comment by akasolace** [comment]
closed by #308
