### ISSUE TITLE
Subskill recalculation not showing any training prediction

### ISSUE THREAD

**Issue by kmhil** [akasolace/HO#1257]
**Describe the bug**
When I click the Subskill recalculation button, the Training prediction doesn't show anything at all

**To Reproduce**
1. Go to 'Training' tab
2. Click on 'Subskill recalculation'
3. Go to 'Prediction' sub tab

**Screenshots**
![image](https://user-images.githubusercontent.com/93383413/139432160-3717782a-a470-4908-995d-e0c7148c6333.png)

**Platform information:**
 - OS: Windows
 - Version:  Windows 11 Home 21H2 Build 22000.282 Windows Feature Experience Pack 1000.22000.282.0

**Additional context**
HO 5.0 BETA (r3825)

**Comment by wsbrenk** [comment]
@kmhil could you provide me with your database - otherwise I can't reproduce the problem.  (upload one of your zips in %APPDATA%/HO/db)

**Comment by kmhil** [comment]
@wsbrenk sure! there it is:
[db_user-2021-10-29.zip](https://github.com/akasolace/HO/files/7449289/db_user-2021-10-29.zip)

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/139604135-0d1b294c-f373-4c8e-96f6-3a4cd8b46402.png)

**Comment by wsbrenk** [comment]
setting all factores to 0 gives this:

![image](https://user-images.githubusercontent.com/11821502/139604159-638b47bf-0694-45dd-9fc6-aecc082caa68.png)

**Comment by wsbrenk** [comment]
same as #1214
