### ISSUE TITLE
[BUG] No training progress shown on Squad Tab after download

### ISSUE THREAD

**Issue by HOTester** [akasolace/HO#1258]
**Describe the bug**
When getting the training updates, no training progress are shown. Only skillups.

**To Reproduce**
1. Go to Squad Tab
2. Click F11 to download abd save hrf file
3. No sub-skill progress shown, only skillups.

**Screenshots**
![image](https://user-images.githubusercontent.com/92029826/139598059-0dc3f300-3fad-4c26-9df9-11f03884ac03.png)

**Platform information:**
 - OS: Windows
 - Version 10

**Additional context**
Running r3826 portable win jre version

**Comment by wsbrenk** [comment]
@HOTester sorry - i cannot reproduce this with my teams. Could you provide your database backup zip files (%APPDATA%/HO/db)? maybe the debugger could show, what is going wrong in your case!?

**Comment by HOTester** [comment]
[db.zip](https://github.com/akasolace/HO/files/7461295/db.zip)

**Comment by wsbrenk** [comment]
same as #1255 

@HOTester when you repair (edit) the past training values of your latest training week and recalc your subskills the values will be displayed.

next change of daylight saving time will hopefully download correct training values (next year).

**Comment by HOTester** [comment]
@wsbrenk can you please guide me to understand how to repair (edit) the past training values?
Thanks

**Comment by wsbrenk** [comment]
[HVB-1967 (JAVA version_ 15.0.2) 2021-11-02 23-04-28.zip](https://github.com/akasolace/HO/files/7464246/HVB-1967.JAVA.version_.15.0.2.2021-11-02.23-04-28.zip)
Please look this video

**Comment by HOTester** [comment]
Thank you so much - that was a lot of effort!
