### ISSUE TITLE
[BUG] Cannot invoke "java.sql.Timestamp.after(java.sql.Timestamp)" because the return value of "module.youth.YouthTraining.getMatchDate()" is null

### ISSUE THREAD

**Issue by cipt2001** [akasolace/HO#1263]
**Describe the bug**
When opening the Youth tab I only see one player there, and when I try to select another line in the table I get the following error:
Cannot invoke "java.sql.Timestamp.after(java.sql.Timestamp)" because the return value of "module.youth.YouthTraining.getMatchDate()" is null

**To Reproduce**
1. Go to Youth tab
2. Click on any line in the Players table
3. See error

**Screenshots**
![Screenshot from 2021-11-05 14-21-16](https://user-images.githubusercontent.com/227271/140517859-c7233c1f-5123-419f-8ce0-ad62bcfbd62c.png)

**Platform information:**
 - OS: Ubuntu 20.04
 - Version: 5.0 r3829 (also seen on previous 5.0 releases in the last month)

**Comment by wsbrenk** [comment]
@cipt2001 could you please upload the log of the session?

**Comment by cipt2001** [comment]
[logs.tar.gz](https://github.com/akasolace/HO/files/7496483/logs.tar.gz)
Attached all the logs in logs/. The latest entry is using the new r3831 build.

**Comment by cipt2001** [comment]
I believe this was the first time I was trying to open the Youth tab. Could it be related to the fact that I originally had a HO4 database?
I just tried to start with a clean database, import the latest HRF and everything looks good now in the Youth tab.

Here is the database with problems:
[db_user-2021-11-08.zip](https://github.com/akasolace/HO/files/7500248/db_user-2021-11-08.zip)

**Comment by wsbrenk** [comment]
match details of your match on 06.03.2021 are missing in your database. Don't know how this could happen.
next version can handle this.

**Comment by cipt2001** [comment]
Looks fixed in r3832, thanks!
