### ISSUE TITLE
[FEATURE] Lineup-Simulation workflow

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1267]
Feedback from HT forum:

Match page with always all options available and working instead of being greyed out would be nice

- [x] increase hight of right panel to screen hight
- [x] layout of rating panel
- [x] rating panel change layout of hatstat, loddarstat, tactic and formation
- [x] new copy button in rating panel
- [x] move rating prediction type selection from rating panel to rating settings panel (below rating panel)
- [x] move match selection/banner + up-/download and order settings to new panel above rating panel
- [x] assistant panel and Database Load/Store panels in TabView below rating settings/lineup simulation

**Comment by wsbrenk** [comment]
Another user; "The negative feedback for me is the lineup tab huge and in my opinion with a wrong layout."

**Comment by peppermil** [comment]
It's the same for me, I liked the old lineup tab (HO4) better - more compact layout.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/142763713-c013009d-e516-4659-9af5-be53485ff1a6.png)

**Comment by peppermil** [comment]
yes that would be great ;)

**Comment by wsbrenk** [comment]
progress report: 
![image](https://user-images.githubusercontent.com/11821502/143770949-c71c9ce4-cf2f-45ca-b5c0-245547f7bd4d.png)

**Comment by wsbrenk** [comment]
colored dots instead of borders:
![image](https://user-images.githubusercontent.com/11821502/143788524-9aa5eb2a-c461-4f06-b76a-4e672c7f2251.png)

**Comment by Cotisso** [comment]
Could you please add back the setting where we can save the line ups?
In my opinion it is very important.
Thx, have a great day!

**Comment by wsbrenk** [comment]
Load/Store panels should do that job - i'm working on it.

**Comment by wsbrenk** [comment]
the following database tables have been removed

* AUFSTELLUNG (info will be added to MATCHLINEUPTEAM table)
* POSITIONEN (info will be added to MATCHLINEUPPLAYER table)
* MATCHORDER (info will be added to MATCHLINEUPPLAYER table)

**Comment by wsbrenk** [comment]
MATCHLINEUPTEAM table should store user defined lineups too (template lineups, not assigned to an single match)

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/146759536-0aea147c-ead8-4090-a372-fa0f2199152a.png)

move match and lineup selection not above but below rating and assistant panels
