### ISSUE TITLE
[BUG] CHPP token and preferences not saved on macOS 

### ISSUE THREAD

**Issue by FlorianWerndl** [akasolace/HO#1291]
**Describe the bug**
After setting up a new MBP with M1 Chip I installed HO Version 5 (HO-5.0.3836.2-JRE.dmg). 
Every time HO starts, settings are discarded and I need to add CHPP token again to download team information.

<img width="396" alt="Bildschirmfoto 2021-12-08 um 10 33 10" src="https://user-images.githubusercontent.com/2530954/145184391-c67a8e3a-990c-4fd0-90cb-6467ce0f5e82.png">

**Platform information:**
 OS: macOS Monterey 12.0.1.

**Comment by akasolace** [comment]
@tychobrailleur as this is mac os specific, any chance you can have a look at it ?  can you reproduce or confirm it ?

**Comment by akasolace** [comment]
looks linked to #1296

**Comment by tychobrailleur** [comment]
@FlorianWerndl Would be able to share your log files?  You should be able to find them by going to Finder, click on _Go_ in the menu, select _Go to Folder..._ and enter _~/Library/Application Support/HO/logs_ in the text box.

Couple of questions as well:
- once you have refreshed your token, do records get downloaded ok, and more importantly do they get persisted across sessions (i.e. do your find your data to be saved ok after restarting HO)?
- how do you exit HO?  Do you go _File > Quit_, or another way?

**Comment by FlorianWerndl** [comment]
@tychobrailleur 

// HO-2022-01-25.log
```
15:08:08 [Info]    core.HO: VERSION: 5.1   versionType:  RELEASE   RevisionNumber: 3877
15:08:10 [Info]    core.model.HOVerwaltung: language used for interface is: English
15:08:11 [Error]   core.util.DateTimeUtils: ZoneID could not be identified from hashValue
15:08:11 [Error]   core.util.HTDatetimeBase: ZoneID could not be identified, reverting to System defaults !
15:08:11 [Info]    core.gui.HOMainFrame: This is HO! version 5.1, have fun!
15:08:11 [Info]    core.gui.HOMainFrame: Operating system found: Mac OS X on x86_64 (10.16)
15:08:11 [Info]    core.gui.HOMainFrame: Using java: 15.0.1 (AdoptOpenJDK)
```

// error.log
```
Warning: the fonts "Times" and "Times" are not available for the Java logical font "Serif", which may have unexpected appearance or behavior. Re-enable the "Times" font to remove this warning.
Jan. 25, 2022 3:08:09 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open start
Jan. 25, 2022 3:08:09 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache open end
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: checkpointClose start
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: checkpointClose synched
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: checkpointClose script done
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache commit start
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: dataFileCache commit end
Jan. 25, 2022 3:08:10 PM org.hsqldb.persist.Logger logInfoEvent
INFORMATION: checkpointClose end

```

Questions:
1. Yes, team data seem to be saved correctly. If I restart HO I need to enter token again but team data is up to date. 
2. cmd+q

**Comment by tychobrailleur** [comment]
> cmd+q

Boom, that's it.  Can you confirm that the issue goes away when:

1. Opening HO
2. Refreshing access token
3. Quitting using File > Quit
4. Re-opening HO
5. Downloading data

?

If it is, it should be a straightforward enough fix.

**Comment by FlorianWerndl** [comment]
@tychobrailleur 🙌

Yes, I can confirm that.
