### ISSUE TITLE
[BUG] Is HO! affected by the ongoing log4j issue?

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#1292]
German link
[https://www.bsi.bund.de/SharedDocs/Cybersicherheitswarnungen/DE/2021/2021-549032-10F2.pdf?__blob=publicationFile&v=6](url)

A serious log4j vulnerability has been recently discovered, possibly affecting systems with Java based programs,
making systems potentially open for malware injections, even if the program is not active itself.

I have only german coverage, but sec internet is full of it, if you want to lookup yourself.

I searched my computer and found install4j in executable Jar files from HO! environment, so I am concerned.

Please give advice!

**Comment by wsbrenk** [comment]
as long as I am involved in the development of the HO, log4j is not part of the HO. this applies to versions from HO2.1 to HO5.0.

i searched in git history of older versions and did not find any hint to log4j includes in HO software.

install4j is a module to install the HO. i do not find any log4j jar there either.
