### ISSUE TITLE
[BUG] Problems after HO-Upgrade 4->5

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1295]
Feedback from HT-Forum:

I downloaded HO 5.0 a couple of days ago, upgrading from HO4. I was cautious as I have lost data in previous upgrades, but this time all seemed to go well at first. I have three teams. Two seem fine in new HO5, but one of them has some issues in HO5.

For this one team:
- Each time I open HO, the players' ages are, e.g. "17[up arrow] 193(25)", average 192.9, but when I download data they revert to normal
- The team name does not appear in the header bar
- When I download data I get a dialogue box asking me which of my three teams this is for
- The box bottom right of the squad tab for Compare-HRF isn't updating with the more recent HRFs since the upgrade; the db folder does contain more up-to-date HRFs, but they're not showing on the HO Squad tab

**Comment by wsbrenk** [comment]
to reproduce this, it would be great it the user would provide the database of this team (zip-backup in %APPDATA%/HO/db* ). Last backup of HO4 would be perfect.

**Comment by Chilimonster** [comment]
[db_user-2021-12-13.zip](https://github.com/akasolace/HO/files/7741691/db_user-2021-12-13.zip)

This is is the oldest backup remaining. I think I did the uodate from HO4 to HO5 on 12 Dec (or early morning 3 Dec). I hope this helps?

Thanks, Kevster

**Comment by wsbrenk** [comment]
can reproduce the error - it is the apostrophe in youth team's name.
