### ISSUE TITLE
[BUG] HO 5.0 Start error

### ISSUE THREAD

**Issue by grabhoehle** [akasolace/HO#1300]
When starting HO 5.0 I suddenly get the following error message on a team and HO does not start. With the other 2 teams everything is going normally

See Screenshots

**Platform information:**
 - OS: [Windows 11 Home
 - Version 10.0.22000 Build 22000
 - 
![2021-12-21](https://user-images.githubusercontent.com/96489770/146966355-1b1b8871-31da-49cd-8b1b-da995eed1b3f.png)
![2021-12-21](https://user-images.githubusercontent.com/96489770/146966383-2b5d3d51-9fa1-4026-9da7-a06cd043c751.png)

**Comment by wsbrenk** [comment]
stable release HO5.1
