### ISSUE TITLE
MISC Tab / Fans and Sponsor are not correct

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1301]
- the increase in fans is not added to this figure
- I have chosen the following sponsor type - per league match CHF 82k / this is not added to the fixed amount after the match

Increase in fans Vers. HO4.1:
![grafik](https://user-images.githubusercontent.com/88058929/146987553-63e2645e-1985-4354-8681-718f85ae7612.png)

Increase Fans Vers. HO5.1 (Build 3846): 
![grafik](https://user-images.githubusercontent.com/88058929/146987677-2f48c7f9-7402-4257-b32b-777bb347657e.png)

_Originally posted by @peppermil in https://github.com/akasolace/HO/issues/1282#issuecomment-999043222_

**Comment by peppermil** [comment]
i have see in HT - the listing has been changed - perhaps this can be adapted to HO?
![grafik](https://user-images.githubusercontent.com/88058929/146995734-0ee70785-451b-43ef-9f90-e7c1c6848a6c.png)

**Comment by wsbrenk** [comment]
https://www88.hattrick.org/Forum/Read.aspx?t=17460874&n=1&v=0

chpp inquiry

**Comment by wsbrenk** [comment]
@peppermil for my team it works with latest beta of HO 5.1:

![image](https://user-images.githubusercontent.com/11821502/147071615-552da6b8-f3de-4481-896b-e34872fe95e1.png)

did you download data from hattrick before displaying finances data?

**Comment by peppermil** [comment]
Look in your pic:
in HT "Sponsor" 88k - where is the "Sponsor-Boni" from 41K --> "Sponsor" in HO only 88k
in HT "Transferb." 560 - where is the "Sonstiger" from 30 -- "Sonstiges" in HO inly 560

Gesamteinnahmen HT 703'360
Gesamteinnahmen HO 662'329 - the final result is right (703'359.60), but if you add up the individual positions, it is not right 

OK?

**Comment by wsbrenk** [comment]
AH - sorry, now i see. 30€ were printed too small.

88k are only possible with chpp changes.

**Comment by wsbrenk** [comment]
Last weeks profit/loss fixed

**Comment by akasolace** [comment]
@wsbrenk if that is ok with you I will take this one ....

**Comment by wsbrenk** [comment]
the part that could be done is ready - i think

the missing things are the new sponsor bonuses which are not implemented by chpp

**Comment by akasolace** [comment]
@wsbrenk we can get the bonus, the only thing we cant fix without CHPP change is the board reserve ....
I'll do it next. This weeekend I am going skiing so not sure I will have much time before next week but let see ...

**Comment by wsbrenk** [comment]
@akasolace i see:
![image](https://user-images.githubusercontent.com/11821502/149598369-c5f8b5e1-da42-4a7f-8ec3-a4e6fdfa4cad.png)

the sums (IncomeSum, LastIncomeSum) do include the sponsor bonuses. an extra element is still not available.
