### ISSUE TITLE
[eBUG] Linenup tab: remove broken/useless buttons

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#132]
Remove those buttons and all the related code:

- "show only the lineup" 
- "show only the lineup minimzed"
- "print lineup"

Is there any objection against ? 
@yaute74 @brokenelevator  @mistermax80 @DavidatorusF

**Comment by mistermax80** [comment]
For ok to remove... But I don't know what the other users think... My suggestion is: remove button and wait the users reactions...

**Comment by brokenelevator** [comment]
Like I already mentioned I would fix or leave them as they are from the same reason as @mistermax80. Removing the button to gauge reaction also works I guess.

**Comment by akasolace** [comment]
@mistermax80 with git it is cleaner to remove it all in a single commit
if we regret we uncommit at any time

**Comment by mistermax80** [comment]
Ok good!

**Comment by akasolace** [comment]
closed by 7b999a6
