### ISSUE TITLE
[BUG] Help-> show change log does not work

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1326]
![image](https://user-images.githubusercontent.com/11821502/148616557-cbcb5a5c-f9cb-401d-867c-59a79e2c78ab.png)

**Comment by akasolace** [comment]
Closed by 943bd2ba0edd72dcb6eb3526bff2e907eb57c979, f364cc3d0dc634376598f6ef00fe386fba755a4a, d9344b8937d79dc58febf637516e222f9c423d09, 9135eed292de617a9823e4e680d93070b1f30081, 306b5c698647f919bf5fbe45a53379d7a9c45313, 0b2829bcffb4507939dac1e6631a9f64e16e0646, 097e0e293e14679a77fb35dab02c1ca1f8a4acb3 and b8a00ba7a4972e1d4a9c891f270d7d403faf0c5d
