### ISSUE TITLE
[BUG] misssing release note  (upgrade from portable unix)

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1338]
![image](https://user-images.githubusercontent.com/1136496/148837799-382f8e59-947c-4c54-8b2e-a8c7366c9743.png)

**Comment by wsbrenk** [comment]
you removed the release_notes.html from the assets

**Comment by akasolace** [comment]
include action from buildreferences inside pushmd and then remove it .... currentlw called too late in dependency ...
