### ISSUE TITLE
Get last version from properties files instead of html file

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1348]
latest.html ..... files are only used by portable version for upgrade. 

For simplification, we could get latest version information from properties file instead of html and also simplify a bit the gradle script

**Comment by wsbrenk** [comment]
github workflow re-run does not work anymore.

Sometimes when the workflow created a release with only 2 assets (i don't know why this happens), i repaired it by re-runnung the job. This does not work anymore because the commits of latest.htmls can not be pushed.

**Comment by wsbrenk** [comment]
@akasolace could you show me the place where portable version uses the latest.html files for updates? I don't find it.

i think only the old versions HO3 and HO4 used it. 
it is fine, if these versions find one new HO version, they don't need to find the very newest each time we create a new dev version.

**Comment by wsbrenk** [comment]
nothing todo here - i think
