### ISSUE TITLE
[FEATURE] Add avatar in player details

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#1349]

**Comment by jpeace73** [comment]
Player details:
![image](https://user-images.githubusercontent.com/98697055/152196622-2b5e93cf-396b-4331-9e4e-5df0dc9f8380.png)

**Comment by jpeace73** [comment]
Anyway, if it was from HO5.1:

Squad:
![image](https://user-images.githubusercontent.com/98697055/152196889-67868f80-4358-4c64-8654-0c6600bf6cdd.png)

Player details:
![image](https://user-images.githubusercontent.com/98697055/152197084-18370150-2030-4b5c-b29d-3bdad571d418.png)

**Comment by jpeace73** [comment]
Let me know it this is what you want.

Now we miss the database. I am a little concerned to post it here. Can anybody download it?
And I think it can be used to load into HO and fetch new team data ;-)

**Comment by akasolace** [comment]
@jpeace73 and you are not a supporter right ?  I  am surprised I thought non supporter could not see player avatar .... maybe that was a long time ago

**Comment by jpeace73** [comment]
Yes, I am **not** a supporter. 
I have FoxTrick installed.

Anyway I think there has always been player avatar...

**Comment by jpeace73** [comment]
I have just tested with FoxTrick disabled, and I still get player avatars.

**Comment by akasolace** [comment]
@jpeace73 in that case can you try and test the latest dev version (https://github.com/akasolace/HO/releases/tag/dev), see if player avatars are available ?

**Comment by akasolace** [comment]
@wsbrenk I am almost done with this feature:

![image](https://user-images.githubusercontent.com/1136496/152677916-27daba2d-9690-40cf-9e42-2d2cf1e906c0.png)

**Comment by akasolace** [comment]
versus 5.1

![image](https://user-images.githubusercontent.com/1136496/152677965-f068ea7e-c25b-463d-a277-6b60778bbb20.png)

**Comment by akasolace** [comment]
@jpeace73 would be nice if you can try latest dev, I would like to know if that would work for non supporter, thank you !

**Comment by tychobrailleur** [comment]
> @wsbrenk I am almost done with this feature, what do you think of the new look ?
> 
> ![image](https://user-images.githubusercontent.com/1136496/152677916-27daba2d-9690-40cf-9e42-2d2cf1e906c0.png)

Holy bananas!!!  Is that all with `GridBagLayout`?? That's amazing 😯

**Comment by akasolace** [comment]
Yes all with gridbaglayout ... that was quite a refactoring :-)

**Comment by wsbrenk** [comment]
great - looks really good!

**Comment by jpeace73** [comment]
Yes, looks very good!

![image](https://user-images.githubusercontent.com/98697055/153646146-8b5f4d1b-d179-4807-9f84-e57c5f1eb3d0.png)
