### ISSUE TITLE
[BUG] Not able to download / Upload Lineup in HO 5.1 Version

### ISSUE THREAD

**Issue by Achill-3s** [akasolace/HO#1350]
I have updated to the new stable version 5.1 for HO.
But when i go to lineup, i can no longer upload or download lineups for future matches.

When i scroll over it, there is a popup message saying:
"Please start by downloading new data from Hattrick. Meanwhile only lineup simulator is available"

Even afteri download data, I cannot see the upload/downlod lineup options or even select future match.
Kindly help out how to fix this issue please.

Yours Sincerely,
Achilles
![image](https://user-images.githubusercontent.com/98124706/150416807-3628ba99-34e9-44e9-a988-806127a03880.png)

**Comment by wsbrenk** [comment]
i will try to reproduce this

**Comment by Achill-3s** [comment]
If this helps the HO update went from Version 4.1.3310.2 to Version 5.1.3877.2 when the issue above occurred.
Any questions just let me know to help regarding reproducing the bug.

**Comment by Achill-3s** [comment]
FYI both portable or installer versions of 5.1 and 6.0 have the same issue.
I needed to revert back to Portable 4.1 to get the feature working again for setting match orders.

**Comment by wsbrenk** [comment]
could you upload a backup of your database? latest  zip file in %APPDATA%/HO/db

**Comment by Achill-3s** [comment]
Find attached contents of: C:\Users\Achilles_\AppData\Roaming\HO
Three Teams, all work with 4.1,, but not in 5.1 version LineUp

Attachment At:
https://ufile.io/ws0p6u77

**Comment by wsbrenk** [comment]
my system says, that it is not save to download this. could you please attach it to this issue - simple drag it to these notes.

**Comment by Achill-3s** [comment]
File is too big to attach as a reply - 63MB

**Comment by Achill-3s** [comment]
I uploaded the Roaming Folder as it is at a shared dropbox.
Let me know if the link doesnt work for any reason.

https://www.dropbox.com/sh/4o3sa56if7108p2/AACHU7aAZloqdNjE7WsChn1ea?dl=0

**Comment by wsbrenk** [comment]
Download successful

**Comment by wsbrenk** [comment]
there is no authorization in those databases.  i can not invoke a download to reproduce the error.

**Comment by Achill-3s** [comment]
I have re-added the youth permission which was missing since i reverted to 4.1 for using HO.
Keep in mind that it maybe easier to use the portable 5.1 with the attached db below for re-producing the error.
[HO-5.1.3877.2-portable-win-JRE_db&logs_folder.zip](https://github.com/akasolace/HO/files/7931607/HO-5.1.3877.2-portable-win-JRE_db.logs_folder.zip)

**Comment by wsbrenk** [comment]
downloading lineup (F11) works

**Comment by Achill-3s** [comment]
Want me to share anydesk to connect and see if there is something you
missed? HO 5.1 not working for me, only 4.1

**Comment by Achill-3s** [comment]
Latest file as requested.
[dbfortesting.zip](https://github.com/akasolace/HO/files/7937181/dbfortesting.zip)

**Comment by wsbrenk** [comment]
i fear it is a matter of your time zone. Could you please try to set CET and try again with HO5.1.

there is a method dataTooOld disabling the lineup simulation check box (which is set, and with that disabling the upload).

**Comment by wsbrenk** [comment]
setting my time zone to cairo will reproduce the error

**Comment by Achill-3s** [comment]
Reproduced also as you have asked me.
Setting Timezone as UTC or CET and then download hrf , it allows HO 5.1 to work correctly for lineups.
Setting timezone back to UTC+2 Athens and restarting the HP 5.1 App and the Lineup gets greyed out again.

Seems to be a bug related with HO 5.1 and timezone for some reason as you said.

**Comment by wsbrenk** [comment]
@Achill-3s a new beta is available now https://github.com/akasolace/HO/releases/tag/beta

it would be great if you could test it.

**Comment by Achill-3s** [comment]
Hello there  my programming hero :)
Just tested the HO-5.2.3925.1-portable-win-BETA-JRE version of your pre-release.
The upload/ download lineups seems to be working fine now on UTC+2
But i am also giving you 2 small additions below if you may want to consider, in case you think they are important.

First of all screenshoots of the successful recreation test for download/upload lineup.
HO Version: HO-5.2.3925.1-portable-win-BETA-JRE
Timezone: UTC + 2 Athens
![upload_scussess](https://user-images.githubusercontent.com/98124706/151702917-b8969391-1ffc-40cb-a560-d7180ebe876a.JPG)
![version](https://user-images.githubusercontent.com/98124706/151702921-97ccf5f2-bae8-40c8-beba-796062f551a5.JPG)
![timezone](https://user-images.githubusercontent.com/98124706/151702922-03276a20-bdcf-4fbc-9315-d5f6ac42d82b.JPG)

Now for the 2 additions i mentioned.
1) When you upload a future match that is not the next one in your list of matches.
Eg. I upload a lineup for a match i have in 2 weeks, it successfully uploads, shows me the uploaded lineup, but reverts the selected match at the top as the first in the list.
I know its not a real issue, but it can be abit confusing.

Screenshoot example:
I upload lineup for match with BlackBird which is in 3 weeks.
Upload successful, lineup shows correctly, but in the top it will show that the Match select is against Kaktoi which was the first in the list. This happens just after the lineup upload finishes.

![upload_for_future](https://user-images.githubusercontent.com/98124706/151703040-378edd94-0c66-426b-abe3-4568d45c9cb2.JPG)
![after_upload](https://user-images.githubusercontent.com/98124706/151703042-ae133daa-6ea6-4fab-9092-4e4039c48fcf.JPG)

2) And second suggestion is regarding the release logs you provided above.
You mentioned that you changed the time calculation to consider as old 2 days in advance instead of 1 hour, which basically meant just UTC and UTC+2
The max timezone difference you can get from the UTC timezone of UTC should be 13 hours and not 48 hours.
It is basically 12 hours, plus calculating for any computer that may have a few minutes dis-synchronised from internet time.
Thus if you consider it more appropriate then 13 hours should be your max delay.

Thanks again for your Help,
Achilles

**Comment by wsbrenk** [comment]
@Achill-3s many thank for that great test report.

to your suggestions: 

1. You're right if only time zone aspect counts, then 13 hours should be enough - but i really have no idea why data downloaded 2 days ago should be too old. if we work around with 13 hours there would be some users on the world where too old is limited to one single hour whereas CET users will get the limit of 13 hours - factor 13 is not fair, i think;-)

2. to me, this is no longer an issue in HO6 dev version. If we should fix this in HO 5.2, i have to think of.

again thank you
