### ISSUE TITLE
[BUG] Duplicated progress bar should be removed

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1360]
![image](https://user-images.githubusercontent.com/11821502/151659180-e65758a6-84e6-4f7c-9121-61380395bef4.png)

**Comment by wsbrenk** [comment]
akasolace 4 days ago
I think the message are not visible on HO main frame ....
much easier to see what's happening on dialog window when it has the focus.
Also I introduced much more description of what is going on ....

@akasolace the description were displayed in HOMainframes progress bar with my changes you reverted. in my opinion, no competing progress bars should appear.

**Comment by akasolace** [comment]
> in my opinion, no competing progress bars should appear.

@wsbrenk agree, so fqr no relevqnt messqge were displyed during download only incorrect wait information status.
Now relevant message is displayed in download dialog (much more visible). Next I will si,ply put message in main frame saying dowload is ongoing
