### ISSUE TITLE
[BUG] Avatar of bruised player is shown as injured

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1362]
![image](https://user-images.githubusercontent.com/11821502/151659893-5999a49e-bec9-488e-9a0a-f6ff98115388.png)

**Comment by akasolace** [comment]
It is just layer of player are not refreshed.
Hence sold player and injured player are not refreshed ....
Either we download each avatar every download or we store them. At the moment I decided to store them but not to include temporary layer. I need to remove layer for injury .... but we could also decide to download every time if you prefer ...

**Comment by wsbrenk** [comment]
@akasolace it would be sufficiant if injury and bruised layers would not be displayed at all.

if you want to display them, why not store the player avatars without temporaries and overlay those depending on player's status. you need to store the two overlays beneath the player avatars.

**Comment by wsbrenk** [comment]
i don't know if some kind of housekeeping, that is removing the avatars of sold players is a good idea. maybe we will decide to display those avatars in further panels, let say in lineups, then it would be nice to see even the sold players with there avatars.

**Comment by akasolace** [comment]
The layer of injury is easy to treat. I did it for overlay of sold player I
just did not had the example of injured player in my db but very easy to
fix.
At the moment there is no deletion of sold player exactly for the purpose
you mentioned.

**Comment by wsbrenk** [comment]
@akasolace card status needs to be handled as overlay too

on the right side of the avatar the back number is displayed - don't know how to handle this (leave it away if possible)

**Comment by akasolace** [comment]
I think I fixed that .... I guess this is left from when you tested my branch. 
Delete avatars and try download again ...

**Comment by wsbrenk** [comment]
@akasolace you're right only bruised players are still displayed with overlay after i reloaded all avatars

**Comment by akasolace** [comment]
In which of your team do you have such a player ?

**Comment by akasolace** [comment]
@wsbrenk ok just did a commit that should fix bruised player avatar ...

**Comment by wsbrenk** [comment]
@akasolace OK now
