### ISSUE TITLE
[eBUG] guava-27.1-jre.jar no present in deb and rpm package

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#139]
**Describe the bug**
Exception **java.lang.NoClassDefFoundError: com/google/common/collect/Iterables** when we start the linux version 2.0 with .deb or .rpm package.
Jar guava-27.1-jre.jar is not present in the package

**To Reproduce**
1. Install release version HO_2.0.0.1158.deb or HO-2.0.0.1158.rpm
2. Start HO

**Platform information:**
 - OS: Linux
 - Version 2.0.0.1158

@akasolace can you treat it ? (build.gradle need a  lot of modifications to work on linux)

**Comment by akasolace** [comment]
I will look into this one

**Comment by akasolace** [comment]
@yaute74 @DavidatorusF can you check if latest artefacts solve your issues under Linux.
I will also reinstall a new VM to test it on  my side.

**Comment by DavidatorusF** [comment]
I still use .zip

but I have install the last dev.deb

guava-27.1-jre.jar is in the folder
![image](https://user-images.githubusercontent.com/45043004/59161332-bde9c680-8ae1-11e9-978b-72215fa90627.png)

**Comment by akasolace** [comment]
I also tested it under a new VM and it works (I tested only the .deb not the .rpm thought)

**Comment by akasolace** [comment]
closed by f46137b793ef3944ac78559d06ce50f1de077cf0

**Comment by DavidatorusF** [comment]
@akasolace 

right clic on HO_2.0.0.1207.deb, I have  "ouvrir avec installation de l'application"

then popup from ubuntu software center wher I can install it
![image](https://user-images.githubusercontent.com/45043004/59161645-b4625d80-8ae5-11e9-9d0f-ab38e5296876.png)

I don't see any "maintainer" with which new folder or files will be added
