### ISSUE TITLE
Experience error

### ISSUE THREAD

**Issue by Chilimonster** [akasolace/HO#1392]
As mentioned on the HO 5.0 forum, on training upate day, the experience increase for players who have played in friendlies is the same as for those who have played in league matches: +0.03/+0.04 each. It happens for all three of my teams. Files are attached.

Thanks
db_user-2022-02-21.zip
db_Second team-2022-02-21.zip
db_Fly Suckers-2022-02-21.zip

**Comment by wsbrenk** [comment]
DB downloaded - Thanks

**Comment by wsbrenk** [comment]
@Chilimonster after recalculating skills (7 weeks) the experience increments looks good. is that the same for you?

**Comment by Chilimonster** [comment]
No. If you look at a player like James Bullock in the first of my teams, he has only ever played friendlies. If you look at his experience changes over the the first 25 games he played, it has ticked up very gradually from 2.00 to 2.08, but in the last two weeks it has gone to 2.12 then 2.15.

If you look at the change in experience for the whole squad last Thursday after the training update, all 22 who played in one league and one friendly match (except one whose experience reached 4.99) increased 0.03 or 0.04. This has happened for at least the last three weeks:
![image](https://user-images.githubusercontent.com/67347390/155231310-78e2bfd5-2478-474a-95c8-9e3969e2c0a7.png)

Thanks

**Comment by Chilimonster** [comment]
...and this is the same squad following today's training update. 11 played in the league game, and the others in a friendly, but they have all been awarded the league-match experience:

![image](https://user-images.githubusercontent.com/67347390/155613926-70de18b4-79be-4d2b-a8ce-8a041f1e99c7.png)

**Comment by wsbrenk** [comment]
@Chilimonster to confirm it. this is the case even if you recalculate the skills? File->Subskill recalculation (7 weeks)

if i do this, i get this picture:

![image](https://user-images.githubusercontent.com/11821502/155617688-30e617a2-8164-40c5-b186-0407bc1a2893.png)

i have the idea, that the error happens in special constellations. i it probably, that you start the HO application before the training happens and that you download after the training date?

**Comment by wsbrenk** [comment]
there is a new [dev-release](https://github.com/akasolace/HO/releases/tag/dev). it would be great if you could test it.
Please don't do it without backup of your current installation including your database folders.

**Comment by Chilimonster** [comment]
I see what you mean by the 7-week recalculation now. I've tried it and it doesn't change my results the way it has for you. Not at all that I can see.

Today's update was done by opening HO after the training update, then performing File > Download.

I'll try the dev-release

**Comment by Chilimonster** [comment]
Ok, so with the dev-release dowloaded, the recalculation seems to reverse the overestimation of experience, and the figures return to those on your screenshot following your recalculation.

Thanks
