### ISSUE TITLE
[eFEAT]  error message instead exception when receive bad xml

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#140]
Following the problem encountered by A-P-O-C [post=17237535.243]: he get an exception when he try to download xml data from hattrick. He receive an html page due to network security firewalls.
Instead of return an exception we must return an explicit error

**Comment by akasolace** [comment]
@yaute74  should I assign this one to you ?

**Comment by yaute74** [comment]
I do some tests and I cannot display the html document of A-P-O-C with java swings (it's an html with java script)

So what I do it's to display this message:

>Cannot parse xml data (you will have more informations in log file).
>The problem may come from your security policy.

And in the log I add the data that we receive:

>13:16:49 [Error]   core.file.xml.XMLManager: Cannot parse data:<html>.....</html>

It's a small modification and it will work for all data type.

@akasolace it's ok for you ?

**Comment by akasolace** [comment]
@yaute74 it sounds a good approach to me
@brokenelevator @konved  any second opinions ?

**Comment by brokenelevator** [comment]
no. I'll trust your judgement on this one.

**Comment by akasolace** [comment]
closed by ae121aa
