### ISSUE TITLE
[BUG] error downloading anniversary team 

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1433]
feedback from ht forum: 
I tried the new version 6.0261, but it's the same as in 6.0259: when I try to download the 4th team (anniversary team), it says "Die Datei ist fehlerhaft" [ File is corrupt]

**Comment by RanzEckenklauer** [comment]
Hi! Danke dass Du dich drum kümmerst, die Zip-Datei hänge ich an, hoffe ich mache alles richtig.
(Umgangssprache Deutsch hier okay?)
[db_user-2022-04-11.zip](https://github.com/akasolace/HO/files/8467182/db_user-2022-04-11.zip)

**Comment by wsbrenk** [comment]
@RanzEckenklauer die datenbank ist leider komplett leer. Könntest Du noch mal den Download machen und mir anschließend die log-datei liefern. %APPDATA%/HO/logs

**Comment by wsbrenk** [comment]
~~~
  <ArrivalDate>2022-03-22</ArrivalDate>
~~~  

Time of arrival of PhilliipAlexander Kaske is missing

**Comment by RanzEckenklauer** [comment]
[output.log](https://github.com/akasolace/HO/files/8467803/output.log)
[error.log](https://github.com/akasolace/HO/files/8467804/error.log)
[HO-2022-04-11.log](https://github.com/akasolace/HO/files/8467805/HO-2022-04-11.log)

Ich hoffe ich hab alles richtig gemacht...
