### ISSUE TITLE
[FEATURE] Status and TSI colomn takes too much space / additional field "Playable"

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1448]
**Is your feature request related to a problem? Please describe.**
When trying to adjust column width of fields, some fields are restricted to re-adjust. Status and TSI for example take too much space. These are needed colums however, because TSI is good to show with a player, but now it takes up too much space.

**Describe the solution you'd like**
Adjust columns.
For the **TSI field** 
1) delete trail of white spaces behind the number. At best I would only have 8 charachters (6 numbers and 2 dots, so that in general even a player with TSI 1.000.000 could be possible). If no player with TSI exist, I would limit it to 7 charachters (6 number 1 dot, like 999.999).

For the **Status** field there are two options:
1) seperate the injury from the yellow cards, so you can limit each field and not have white spaces between them.
2) limit the number of white spaces between card and injury, so that the field is becoming less wide. 

Alternative additionel field / "**Playable**" (!): You can add a field if a player is able to play next official match (cup and league), that include some logic (If player has: A) injury +1 or higher OR  B) is suspended (red card or 3x yellow). That field can have the value 1 (Y) or 0 (N), and can be used to see the players that are able to play next match, so that I don't need all status information and I can slide that column more to the right, so that I only have information that I need with limited space.

**Additional context**
![image](https://user-images.githubusercontent.com/102049050/162609647-d9345690-02b4-4bc1-97a9-e9e49aa883c4.png)

**Comment by wsbrenk** [comment]
the white space in tsi column is required to hold the difference values of player values are compared to old hrfs.
![image](https://user-images.githubusercontent.com/11821502/209482721-c1fe58d7-3f62-44bf-a80c-cb416118e5ce.png)

**Comment by wsbrenk** [comment]
column width of the tsi column is not restored when user has changed the width

**Comment by wsbrenk** [comment]
minwidth of status column reduced to 50 points
