### ISSUE TITLE
[eFEAT] List of players listed in subs dropbox:

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#146]
Following a remark made by @DavidatorusF on Slakc:

1) we keep as is
2) we remove player already on the field
3) same as 2) but with combo box for user to choose what he wants
4) we visually indicate player already on the field (different color/background)
5) other ideas ....

**Comment by DavidatorusF** [comment]
I vote for 2) ^^

my mind ...
normal users set the lineup before the subs
have players on the field in subs dropox can introduce a mistake for the lineup as, if the user choose one af those, he remove him from the field... if the user don't take care at this, he can send an uncomplete lineup.
on HT, their dropbox include only the 3 best suggestions...

**Comment by akasolace** [comment]
>I vote for 2) ^^ ...

@DavidatorusF thing is that in HT they don't have team. Personally I start with the field player then label them for example team A. Then I do the subs and personally I like to compare rating value between subs and player on the field as it make me sometime change my mind.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
Hence I vote for 4)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
following slack discussion , let go for option 4.

can be treated same time as #133

**Comment by yaute74** [comment]
@akasolace I think you can close it, no ?

**Comment by akasolace** [comment]
closed by #186

**Comment by akasolace** [comment]
@yaute74   @DavidatorusF 

I have something strange, almost all my players are greyed in the sub box (see screenshot below), ... maybe it is a bug only happening on Friday after the training but before the first game of the next week ?

Have you noticed it ?

![image](https://user-images.githubusercontent.com/1136496/63606883-65e73a00-c5d1-11e9-8467-16f2294cbab4.png)

**Comment by DavidatorusF** [comment]
@akasolace 
-The first grey is for player selected on the lineup
-The second grey is for player selected on the lineup for substition

but you're right... something wrong... when we clear lineup, grey stay in the menu

**Comment by yaute74** [comment]
@DavidatorusF ok I will have a look.
@akasolace it's what you d (clear lineup) ?

**Comment by akasolace** [comment]
@yaute74  possibly, I don't remembre what created it in the first place

**Comment by akasolace** [comment]
closed by #211
