### ISSUE TITLE
[BUG] Database Cleanup - Remove HRFs intelligent (by trainingweek)

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1466]
**Describe the bug**
Following up on the (correctly) implemented comparison by training week function (issue #1452). 
This bug is related to the Database Cleanup. This function should remove HRFs files also by training week, so that only relevant comparison files are left in the database.

**To Reproduce**
1. Go to 'File -> Database -> Database Cleanup'
2. Click on 'Remove HRFs intelligent

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/163708890-ddd16129-fb33-42f4-a165-a6b74e03907c.png)
![image](https://user-images.githubusercontent.com/102049050/163708970-97540d98-eb18-4d63-b90d-d549b92e9c5e.png)

**Platform information:**
 - OS: Windows 10
 - Version 6.0 v277

**Comment by masterpatje** [comment]
Almost fixed. Functionality works perfectly, except for last week. I have a notification that there are two entries.
![image](https://user-images.githubusercontent.com/102049050/165292801-e6a126ec-e7d2-4f4f-b3ff-e93c6530b654.png)
I think that the entree of 24 april 2022 should be removed, so that only the last file (with the most recent information) is included.

**Comment by wsbrenk** [comment]
Latest hrf is never removed - this is intentional

**Comment by masterpatje** [comment]
oke great, then it is clear that it is intentional. This one is fixed (and closed).
