### ISSUE TITLE
[BUG] Adjust windows - several locations

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1468]
**Describe the bug**
Window adjusting on initial build on several location. Provided screenshots (initial build and when teamdata is downloaded). Main idea is that on the initial build you want all windows to be fully visible. They can later be adjusted to the need of an user. Now some windows are not fully shown. Instead of describing it I send screenshots. Just adjust the height of the top window or the width of left window a bit and it should be fixed.

Is a bit the same as issue #1451 that you already fixed, but now for other tabs.

**To Reproduce**
1. See description and screenshots.

**Screenshots**
**Line Up -> Line Up**
![image](https://user-images.githubusercontent.com/102049050/163709442-4c545e5d-1207-4a76-ba8c-abc28025d188.png)
![image](https://user-images.githubusercontent.com/102049050/163710036-5d4fdbc0-264d-4a51-8934-543af98a9e87.png)

**Matches**
![image](https://user-images.githubusercontent.com/102049050/163709567-0d70a236-b33c-4948-b7ba-2bb7aba627d5.png)
![image](https://user-images.githubusercontent.com/102049050/163710084-5214bcf5-dc4b-4e6d-b0e5-6673f48783ec.png)

**Transfers -> History**
![image](https://user-images.githubusercontent.com/102049050/163709615-f180f90a-bc63-41f4-bf82-03c16c83b785.png)
![image](https://user-images.githubusercontent.com/102049050/163710164-7de3e066-85e4-49b0-b2ea-4293253200bc.png)

**Transfers -> Transfer Types (request to add more space for the top window to see more players to select)**
![image](https://user-images.githubusercontent.com/102049050/163710211-0dba906b-f114-4d9e-bd9e-800224ea50f8.png)

**Platform information:**
 - OS: Windows 10
 - Version 6.0 v277

**Additional context**

**Comment by masterpatje** [comment]
One more location **TeamAnalyzer**
![image](https://user-images.githubusercontent.com/102049050/163710506-9a2b9b90-5904-442c-a3b4-9a30fbe0f097.png)

**Comment by masterpatje** [comment]
**Training**
Adjust left top window to add a few more players (5-10?)
Adjust right top window to add a few more rows (5-8?) of past trainings
![image](https://user-images.githubusercontent.com/102049050/163710967-4eab4177-2159-4553-9db8-dfc88a37662b.png)

**Comment by wsbrenk** [comment]
@masterpatje again good ideas!

all suggestions adjusted (I just left the team analyzer as it was)

**Comment by masterpatje** [comment]
Thanks. And it works.

Now that I see the result, I would suggest two (minor) changes.
**Training** (adjust width left side so that all skills are shown, the right part does not need that much space)
![image](https://user-images.githubusercontent.com/102049050/164170159-c12cdd14-8afd-401a-89c8-f2453a966221.png)

**Line up** (I would put the right side on the left side, people tend to look at a page from top-left to right, so I would put the most important information there)
![image](https://user-images.githubusercontent.com/102049050/164170771-f08eb133-821e-4b18-bcdf-350c1f1d1617.png)

**Comment by wsbrenk** [comment]
just adjusted training panel - concerning line up, we should do some kind of poll. for me the more important part of the line up panel is on the left side.

**Comment by masterpatje** [comment]
Don't see the change, left part seems the same to me.
![image](https://user-images.githubusercontent.com/102049050/165284308-b5b34967-e948-49e5-911d-28db63b59e85.png)

Maybe also you can work with a split panel like with the squad to seperate the player, so that it can manually be adjusted:
![image](https://user-images.githubusercontent.com/102049050/165284469-ef558630-da43-4fb0-9925-622c7ff0733b.png)

Lastly w.r.t. line up, I think developer's perspective can be a priority as well. So it can be left like this. It is ok. If you would like a poll that is off course also fine, but you can decide this.

**Comment by masterpatje** [comment]
Oke I see what you did. You showed less past trainings, this is unwanted. I would prefer the old trainings to be visible. This is usefull.

The right part needs less space. I meant the width of that part. So that the left side is fully visible.
But as I commented also an option with seperated panels will work.

And for the **height** of the past training, could you go back to the previous setup? That was working well. My request was the width, but mainly because part of the left window was not longer visible and when sliding the player name is not visible anymore. But I think with this additional information I made it clear.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/165393764-a2517199-04d4-4384-935f-2e5ff1dd1c68.png)

this is how training looks like, if i start HO from scratch.

Resize of the main window gives this:

![image](https://user-images.githubusercontent.com/11821502/165393915-27d1bfbb-83be-4c97-b2f2-ff1233b4de42.png)

**Comment by wsbrenk** [comment]
all parts can easily adjusted as you like:
![image](https://user-images.githubusercontent.com/11821502/165395001-3678a6b1-e447-4cd3-90df-224b02329343.png)

**Comment by masterpatje** [comment]
I would like to see the width not widther than needed. So a cut off at stamina would make sense.

But maybe working with two panels, one with only the name of the player and one with the skills would make more sense, because it then can be adjusted to the need of the user. Because otherwise scrolling with the bar to the right means that you see skills without the player name. Under the condition that someone don't adjust the width of the panel. Hope this makes sense.

I can and will sent a screenshot to give you an idea of what would be me ideal window, so that you can judge it or at least form an oppinion. I can't do that now from a mobile device.

**Comment by masterpatje** [comment]
This is what I exactly mean with an ideal window. It is balanced (calm to the eye) and wide just wide enough for all skills to be shown and with enough space on the right.

_Extra_: make a seperate panel for the player name, so that it is always shown and users have more abilitie to adjust to their own needs.

![image](https://user-images.githubusercontent.com/102049050/165479534-dcb1dc7d-0593-40a3-b1b4-e3c0393fe317.png)

**Comment by wsbrenk** [comment]
in all this, we have to take into account the different screen sizes. mine is 2560x1600. There should also be smaller ones.
in my opinion, everything should be visible on small screens, so that nothing is overlooked there. After the start, everyone can adjust the conditions as they need. This is registered and reset when restarted.

other situation with what to display left or on top.

**Comment by masterpatje** [comment]
I agree, in that case a seperate panel for player name (or fixed column) is a must. Otherwise you are able to see the skills but not the player name when scrolling to the right on the slider under that panel.

**Comment by masterpatje** [comment]
For me it does not matter too much, because my screen is big enough and I can adjust accordingly. And I would be oke if you closed this issue #1468, because windows adjustments have been made accordingly and/or argumented that a poll might be a good idea.

If you want (and feel like it) you could add a feature that seperates the player name so that people with a smaller screen can adjust the window to their needs and always are able to see player name next to the skills. (see also last comment).

**Comment by wsbrenk** [comment]
i will check if i could fix the player columns
