### ISSUE TITLE
[BUG] unable to download lineup

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#1477]
**Describe the bug**
Download lineup button is disabled.

**To Reproduce**
1. Update with F11.
2. Go to 'Lineup' tab

**Screenshots**
[https://i.imgur.com/SfAxY3D.png](https://i.imgur.com/SfAxY3D.png)

**Platform information:**
 - OS: Windows
 - Version 5.2 (build 3945)

**Comment by masterpatje** [comment]
Could you check if that button is disabled in the latest **developer** version 6.0 (v288 or higher)?

That developer version is as I concern stable enough to be used and looks really nice. And maybe it could be usefull to incorporate this bug to be fixed in the newest version.

**Comment by aristodemos2008** [comment]
> Could you check if that button is disabled in the latest **developer** version 6.0 (v288 or higher)?
> 
> That developer version is as I concern stable enough to be used and looks really nice. And maybe it could be usefull to incorporate this bug to be fixed in the newest version.

I copied my DB to HO-6.0.289.0-portable-win-DEV-JRE.

However HO fails to load with the following error.

[screenshot](https://i.imgur.com/glZvwch.png)
