### ISSUE TITLE
[BUG] Subskills substitutes incorrectly calculated (on HRF download)

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1489]
**Describe the bug**

**=Subskills are incorrectly calculated.** 
On today's download (5-5-2022) last weeks training (training week 4) was included. The past training table is correctly set. On training week 4 I trained "Crossing" [aka Winger]  which includes the cup match 27-4-2022 and league match 24-4-2022. _(see screenshot 1)_

Today's file is shown as training week 5 and I do a comparison with the file from 26-4-2022 which is shown as training week 4. _(see screenshot 2)_
(@wsbrenk do you consider the training week correct?
- today's file (5-5-2022) includes data for training week 4 and is accordingly set in the past training table
- last week's file (26-4-2022) includes data for training week 3 and is accordingly set in the past trainings table 
- maybe #1452 still has a bug?). 

**=Findings**
In the results the 24-4-2022 match is not taking into consideration, because non of the winger or wing-back received a considerable change in subskill calculation.

Also players that were substituted in the 27-4-2022 were incorrectly calculated. 

I have as a comparison the HO 3.0 results in comparison to HO 6v288 in which they were correctly calculated. (see screenshot 3 and 4)

**To Reproduce**
Download the newest HRF file
Compare last download 

Suggestion: might be connected to the fact that 5-5-2022 is considered a "week 5 training" While it is clearly last week's training which is accordingly set in the past training table?

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/166915641-e4d6a519-7846-4e1b-a8e1-cec0036a5dc9.png)

![image](https://user-images.githubusercontent.com/102049050/166915557-93ea748c-247d-4c76-a5b6-51c9c2463337.png)

![image](https://user-images.githubusercontent.com/102049050/166914373-7cadd539-ef9f-4165-8764-5ed0857791ec.png)
![image](https://user-images.githubusercontent.com/102049050/166914631-4ae95d69-8483-450a-ad46-ba2e2c445384.png)

**Platform information:**
 - OS: Windows 11
 - Version 6.0 v288

**Additional context**

**Comment by masterpatje** [comment]
Today's download; subskills correctly calculated.
Maybe substitutes plays a role on last download? In that download there were matches were players were trainable positions had substitutions.

@wsbrenk could you explain how subskill is calculated in the case that
1) player A is substituted for player B after 60 minutes on "winger"; does player A receives 60 minutes (factor 60/90 of full training) and player B receives 30 minutes (factor 30/90 of full training ) 
2) player A got 60 minutes of training on winger in match A and 30 minutes of training on winger in match B; does player A receives (30 + 60 = 90; factor 90/90 =100% of training).

In the above examples I excluded for age, training-assistent etc. To understand more about what actually is calculated and if that could be improved.

**Comment by wsbrenk** [comment]
@masterpatje your assumptions are correct. player should receive training for each minute they play on training positions (maximum 90 minutes per week). if they were playing on different training positions (full or partial training), they'll got the optimal minutes.

**Comment by masterpatje** [comment]
@wsbrenk I downloaded v293 today (clean install)

There are still problems with subskill calculations. Three players are incorrectly calculated:
![image](https://user-images.githubusercontent.com/102049050/170111122-9206722c-0cf9-468c-87c4-9be2e43e91fe.png)

**Comment by masterpatje** [comment]
I did another test. I included another HRF file with last weeks training and did a "**subskills recalculation**" both 7 weeks and a full subskill recalculation. It produced the same results which is a good thing, but all trainable players got incorrectly calculated:
![image](https://user-images.githubusercontent.com/102049050/170118015-f6266228-9029-48de-8458-bbb28761bdda.png)

**Comment by wsbrenk** [comment]
![dl](https://user-images.githubusercontent.com/11821502/170207997-4c185c1b-6068-44d4-acf0-bcb008efa6d7.jpg)

@masterpatje: very strange. could you please check, if the "download current matches" is checked? Otherwise i fear only the latest league match will be downloaded.

it would be great if you could upload your database backup file. then i could try to  debug this.

**Comment by masterpatje** [comment]
I will do see within 2 hours. If they are standard checked then I am sure that I didnt uncheck it.

But I will look at it

**Comment by masterpatje** [comment]
@wsbrenk; here you go; the matches are included in the database and the box was checked. 
I included the database, which only includes two HRF files. 24-5-2022 and 17-5-2022 and thus include training week 7 and 6, which corresponds to the matches that I included in my screenshots yesterday.

![image](https://user-images.githubusercontent.com/102049050/170230127-33aea340-f87e-4741-837c-85f6d2f60bae.png)

![image](https://user-images.githubusercontent.com/102049050/170230024-c950e7ff-81e1-48aa-aa92-c9ec30892f27.png)
[db_user-2022-05-25.zip](https://github.com/akasolace/HO/files/8769753/db_user-2022-05-25.zip)

**Comment by wsbrenk** [comment]
@masterpatje thank you - i don't know if it is a bug or a feature, but debugger showed that the very first hrf file is ignored on subskill recalculation.

**Comment by wsbrenk** [comment]
fixed: 

![image](https://user-images.githubusercontent.com/11821502/170249926-56d995c8-7897-4fe4-9cb9-ac7b8b0df17e.png)

Maxence increment of one match was eat up by two skill drops.

**Comment by masterpatje** [comment]
Yes, great improvement! See comments for new test results.

**Test HRF download**: (and a comparison file to see the increase more clearly)
![image](https://user-images.githubusercontent.com/102049050/170432420-1ea9c6f1-e5c0-44a1-90ce-6dc0f88d7ad1.png)

![image](https://user-images.githubusercontent.com/102049050/170432503-cfcfe4ff-7e47-4d5e-9d0c-4228ce10f800.png)

**Three comments:**
- **Wellinga** is now explained; he had an increase in skill last week and that is why I thought that he didn't had training, but if you compare it with last week file, you can see the increase of skill level.
- Could you check **Abdelhak Sabbar** he had an increase in skill and 0,20 subskill increase. That seems quite large but could be correct if he had a high subskill before the skill increase. What do you think?
- Could you check **Donrel-Ioan Dan**?  He does not have a subskill increase although he played 63 minutes Wing-Back but was substituted (out). And his age (27) and skill (6) could not be reason that increment is eaten up by skill drop.


**Test "Subskill Recalculation"**
![image](https://user-images.githubusercontent.com/102049050/170433983-0a982558-819b-41cb-a974-67132c182920.png)
**Two comments:**
- **Abdelhak Sabbar** 0,20 subskill (10,20) is no longer visible. Could you check why the recalculation removes that? (see also test results HRF download)
- **Donrel-Ioan Dan**?  He had a subskill increase but I think that still missing is the (15-5-2022, week 7 training) where he played 63 minutes Wing-Back but was substituted (out). (see also test results HRF download)

**Comment by wsbrenk** [comment]
[Cornel-Ioan Dan](https://www85.hattrick.org/Club/Players/Player.aspx?playerId=444412037)
[Jasper Dieleman](https://www85.hattrick.org/Club/Players/Player.aspx?playerId=426548646)
LAV  ZST
normal  defensiv
3-5-2  2-5-3

**Comment by wsbrenk** [comment]
@masterpatje do you still see this bug? otherwise i would like to close this ticket.
