### ISSUE TITLE
[BUG] statistics calculator does not work correctly. 

### ISSUE THREAD

**Issue by Pylbas** [akasolace/HO#1518]
The match statistics calculator does not work correctly. Defense stats are very underrated

By setting the squad in the "Lineup" tab, the HO incorrectly calculates the defense statistics (the statistics are lower than they should be)

**Comment by wsbrenk** [comment]
@Pylbas I guess you mean the rating prediction. Please note that the HO gives the average rating by default, while the Hattrick forecast mentions the value for the start of the game. to get a comparable value in HO click above the ratingdisplay the game minute 0
