### ISSUE TITLE
[BUG] Single player has wrong skill decimals after subskill recalculation

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#1519]
**Describe the bug**
On 7.0, r304, a single player has wrong training decimals even after subskill recalculation. All the other players look more reasonable.
Horcholle appears as DE 15.99 and PS 10.99. According to HT-Portal, he should be around DE 15.45 and PS 10.22.

Here, we can see random jumps for DE and PS
![image](https://user-images.githubusercontent.com/1204726/172621655-7afc3292-f812-485f-b46e-2d0a995c26bf.png)

[db_Canards-2022-06-08.zip](https://github.com/akasolace/HO/files/8861720/db_Canards-2022-06-08.zip)

**To Reproduce**
Check for Simon Horcholle stats on the home page and in Statistics.

**Platform information:**
 - OS: Windows 10
 - Version (including build number): 7.0, r304

**Comment by dominiquelee** [comment]
@wsbrenk that seems unlikely, I didn't even know it was possible to manually adjust subskills until 3 minutes ago.

**Comment by wsbrenk** [comment]
new beta fixes some exception i found in your subskill recalculation - but it does not changed the passing skill of your player

**Comment by dominiquelee** [comment]
I just tested 6.0 r309, downloaded 2 years worth of matches and I still repro the issue. I also noticed that if I do a 7 weeks subskill recalculation, I have 4 players that have some previously trained skills pushed to .99.

If I'm not mistaken, immediately after a full recalculation, a 7 week recalculation should be a no-op, right? That's definitely not the case here.

**Comment by wsbrenk** [comment]
recalculation only takes into account the last 32 weeks. that is the reason why passing is not corrected. if i increase this to 64 weeks (4 seasons), passing curve becomes OK.

concerning defending i'm still searching.

**Comment by dominiquelee** [comment]
A few more screenshots, based on Balland:
- after subskill recalculation from the Training tab, he's DE 17.25, PM 16.50 (I have had one more PM training since I uploaded my db), PS 9.50. Values are pretty close to what HT-Portal reports. The graph looks reasonable.
![image](https://user-images.githubusercontent.com/1204726/173181471-937a4706-2bda-41d5-81b6-54f5c945fd83.png)
- after subskill recalculation from the File menu, he's DE 17.25, PM 15.56, PS 9.99. The graph has a triple bump in one week. about 32 or 33 weeks ago (it appears when I set it to 33, not when I set it to 32).
![image](https://user-images.githubusercontent.com/1204726/173181279-a0c80dbf-f859-4224-b8fe-84d49c1d69c1.png)
- after 7 weeks subskill recalculation from the File menu, he's DE 17.99, PM 15.99, PS 9.99. The graph has two multiple bumps in one week, at 33 and 8 weeks ago.
![image](https://user-images.githubusercontent.com/1204726/173181352-02c248b1-8dbc-4ba2-ac58-713c8ae57ff4.png)
- if I do subskill recalculation from the Training tab followed by a 7 weeks recalculation from the File menu, he's DE 17.99, PM 15.99, PS 9.99. The graph has a single multiple bumps, 8 weeks ago.
![image](https://user-images.githubusercontent.com/1204726/173181444-7e0a644f-17b6-42ab-81a2-b598c03c922a.png)

**Comment by wsbrenk** [comment]
some things are clear now - and fixed soon (hopefully):

the reason for horchrolles defending step is the wrong training date on 25th march, 2022. i think this is/was a problem of daylight saving time. could you please check if this is still the case with your new downloads?
![image](https://user-images.githubusercontent.com/11821502/173182281-7cb668bc-361b-45f6-a857-1aa11709200a.png)

**Comment by dominiquelee** [comment]
I'm not sure if that's your question, but right now, my 03/25 training indeed appears at 4:15 rather than 5:15.
However, if I change the 03/25 training to something else, I can see the bump to .99 actually happens the week after, so it does not match completely.
![image](https://user-images.githubusercontent.com/1204726/173182643-895ad8b0-b6bc-4c3b-9241-77ae0653715b.png)
If I also change the 04/01 to Set pieces, the Defending bump still happens.

**Comment by wsbrenk** [comment]
i implemented some training date tolerance that fixes the horchrolle statistics:
![image](https://user-images.githubusercontent.com/11821502/173182848-d12b7532-0ffa-441e-91f5-92f82b4bc1ef.png)

i'm not happy with that wrong training date. this is another bug and should be fixed in another ticket;-)

**Comment by dominiquelee** [comment]
Looks great! Take your time for the next release, I'm not in a rush to get the fix :)

**Comment by wsbrenk** [comment]
310 beta is ready - 13 minutes were time enough;-)

**Comment by wsbrenk** [comment]
would be great if you could test again - thanks

**Comment by dominiquelee** [comment]
That was fast :)

Looks good to me, none of the 3 ways to recalculate lead to a .99. You can close this issue. Thanks for the fast fix!
