### ISSUE TITLE
[FEATURE] Display further last match info in squad table view

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1523]
[ ] rating at end of game
[ ] lineup position
[ ] minutes

**Comment by sophiastr** [comment]
Can I take this issue?

**Comment by wsbrenk** [comment]
concerning language string please look at src/main/resources/sprache/English.properties
do not attach user languages, they will be created by poeditor

**Comment by sophiastr** [comment]
Hello @wsbrenk , 
I am facing a strange problem. Squad table view shows only 52 columns. After that, it doesn't display anything. Is there something I don't understand well? Is there another class that indicates how many columns will be printed? Moreover, the information about the last match date is stored at additionalArray at position 10. But we use this command: columns[22] = additionalArray[9]; to display that information. Finally, the information about the rating(not the lastratingendgame) doesn't appear in squad table view.

**Comment by wsbrenk** [comment]
@sophiastr i found and fixed some minor constraint errors when saving user column settings.
