### ISSUE TITLE
[eBUG] sorting table by squad is super slow

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#153]
**Describe the bug**
sorting table by squad is super slow and I don't think it was the case before.
other columns sorting is much more reactice.

same behaviour in both tabs Squad and Lineup

**Platform information:**
 - OS: Windows 
 - Version DEV 2.0 r1213

**Comment by yaute74** [comment]
@akasolace I will check on linux if I have the same behaviour

**Comment by yaute74** [comment]
@akasolace I don't reproduce your problem.

**Comment by akasolace** [comment]
@yaute74 ok just to be sure I was referring to the column which holds squad information (A,  B, ... F )

**Comment by akasolace** [comment]
anyone else can share feedback?

**Comment by brokenelevator** [comment]
same thing happens to me. also I got a huge lag on load. possibly same reason because I have squad information on default sorting.

**Comment by yaute74** [comment]
@akasolace you are right, I reproduce the the problem.
I will have a look on it.

**Comment by yaute74** [comment]
@akasolace After a quick look, it's in RatingPredictionManager.java.
Maybe @akasolace  you'll be more efficient than me, as you work on it.

**Comment by yaute74** [comment]
I think the problem come from here:
To sort we call now getLineup() (before  getAufstellung()) and getLineup() call setRatings() who take a lot of time.

**Comment by akasolace** [comment]
@yaute74 ah ok, thank you for finding this. 
So the getLineup call should be replaced by getLineupWithoutRatingRecalc()
I suspect we will find similar issues somewhere else in the code

**Comment by akasolace** [comment]
I actually fixed some of those issues in my last commit eea9fd3

@yaute74  I will let you do the commit and close that issue as you found the origin of the bug, ok for you ?

**Comment by yaute74** [comment]
@akasolace I don't understand. Your modifications solve the problem ?
If it's the case my commit is not necessary :)

**Comment by akasolace** [comment]
@yaute74 no it solved a smilar problem with unecessary rating calculation. Hence  I had to replace getLineup  by getLineupWithoutRatingRecalc
