### ISSUE TITLE
[FEATURE] Hattrick Organizer DEV (seperate folder use)

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1535]
**Is your feature request related to a problem? Please describe.**
I can't install both HO 6 and HO 7 (developer) on my pc. Becuase they will be installed in the same folder. And installing the developer edition will uninstall the HO 6 version.

**Describe the solution you'd like**
I would like to see that the developer edition gets it's own path. On windows this could be Hattrick Organizer (Developer) so that it has its own unique path and can be installed next to the other version.

**Additional context**
- Might have to check if DEV-JRE is allowed to be installed next to another JRE package? 
- And also check when installing a new version (and de-installing the last version) that the last development version is uninstalled and not that a package will de-install HO 6. 
- And also the roaming-appData folder might have to be looked at.

From time to time I am willing to look at HO 7, but if I have to uninstall HO 6 that would not work for me.

**Comment by wsbrenk** [comment]
@masterpatje using a portable version should solve this

**Comment by masterpatje** [comment]
I have no idea what a portable version might be? Can you elaborate on that? For me any sollution will do. So that I can do some QA from time to time for HO7.

**Comment by masterpatje** [comment]
Oke that will work. And sounds like a logical even maybe a preferrable solution.
