### ISSUE TITLE
[BUG] Misc tab - finances

### ISSUE THREAD

**Issue by geocacher1** [akasolace/HO#1549]
Hi ! 

Something went wrong on misc tab in Finances (screen below)

![HOBug](https://user-images.githubusercontent.com/108490960/176762697-3bf5cf0e-2141-4e8b-9b12-914e6bd9df5e.JPG)

**Describe the bug**
The stadium maintenance cost is above all Expenses (28 400 zł), it also looks like there is a problem with staff Expenses name String. All details could be seen on screen

**Screenshots**

**Platform information:**
 - OS: Windows
 - Version: HO 6.0 BETA (r326)

**Comment by geocacher1** [comment]
I updated HO to r329 version today and bug seems to be fixed (i have same info as on screenshot above

**Comment by wsbrenk** [comment]
thanks for testing
