### ISSUE TITLE
[BUG] Subskill recalculation (7-weeks) - Changing training type in Past Trainings does not change recalculation

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1554]
**Describe the bug**
I had a problem in week 8 that I accidently changed the training type before downloading the HRF file. It should have been WINGER, but was set to DEFENDING.

When I do a subskill (7-weeks) recalculation with the _wrong_ (DEFENDING) skill  and afterwards do a subskill (7-weeks) recalculation with the _right_ (WINGER) skill I get the **same** training results, which is wrong. The results are shown in the first screenshot. Winger and Defending subskills have not changed at all.

**Q1: Why doesn't the change of training type in the "past trainings" table from DEFENDING to WINGER lead to a different subskill calculation?
Q2: Does the subskill calculation takes into consideration the "past trainings" table or does it look at the underlying HRF files in the database?** 

**Screenshots**
![image](https://user-images.githubusercontent.com/102049050/176915761-b32753a8-b236-4a33-91b1-e3407d94f55e.png)

**Platform information:**
 - OS: Windows10
 - Version 6.0.327

**Additional context**
Additional information is provided that only for training week 7 no matches apear to be available in the database, but for week 8 matches are in the database.
**Q3: Do the matches in the database play any role in the subskill recalculation?** 

![image](https://user-images.githubusercontent.com/102049050/176915152-94133106-6e3c-4ce5-bb30-5ad81dd9999a.png)

**Comment by masterpatje** [comment]
I did quite some extensive work to determine the training units of last 7 training weeks. A training unit is defined by me as equivalent of 90 minutes full training. 

I however excluded for training week 8; which was set as "defending" in HO, while it should have been "winger" but since HO didn't take it into consideration for recalculation I just excluded it from my excel, because in my excel I had winger training. This means as a result that I also excluded the "defence" training of that training week 8, thus for some player there are some extra "training units" defence that HO takes into consideration which are not visible in my training unites for defence.

It is more tough for me to decide of amount of training is correct (because I don't have any reference), but in general I don't see very strange results.  Except for the one described in the comment above were changing the training type didn't change recalculation.

![image](https://user-images.githubusercontent.com/102049050/176951020-23a95b70-ee47-4c39-b5d0-6a091aece5ef.png)

**Comment by wsbrenk** [comment]
A1: Because of the missing match details. if you download the correspondig matches the training should be considered.
A2: the training of past training display is considered (and in sync with the database contents)

**Comment by masterpatje** [comment]
Oke today got the time to check it.

When I downloaded the missing matches everything worked as intended. Depending on the players position in the match (from the matches in the database) and the past training table it recalculates the training. 

Perfect.
