### ISSUE TITLE
HO Database

### ISSUE THREAD

**Issue by Tarotistas** [akasolace/HO#1576]
Hello, I have lost my DB folder of HO application. I have MAC OS and the folder and file is not with Library/Application support/HO and neither can re-generate.

Can you please help and improve this point of the APP that is not so simple to handle?

Thanks a lot!
BR
Gaspar (Eberlu)

**Comment by wsbrenk** [comment]
@Tarotistas restarting HO should  create a new database folder, if the old one is lost. if you installed a portable version of HO, the database folder (db) should be a subdirectory of your HO installation directory. 
if you installed with the installer, the directory should be in the path you mentioned.

**Comment by Tarotistas** [comment]
Is not as you can see.

How can I restart wo loosing the info? Somehow the db is someplace I can't find.

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/65875612/178124551-7859a914-079f-4ba9-9850-c24d24337b75.png">

**Comment by wsbrenk** [comment]
i understand, that you can start HO and that there is information, you fear to loose - so the database should be on your system - right?

Portable application
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you are using a portable application all the files and folder will be
created within the application directory. You can move this directory
(e.g. on a USB stick or a network drive) and the app will continue to
work as expected.


or did you install HO with an installer?

**Comment by Tarotistas** [comment]
I installed this version 

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/65875612/178125050-876340a4-aa68-405f-8fbb-850184d1e532.png">

**Comment by wsbrenk** [comment]
could you try to find the file HO.jar on your system - where do you start HO?

**Comment by Tarotistas** [comment]
Nothing ....probably I'm not looking well

HO.jar
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/65875612/178125231-323e7247-8edc-4815-b72f-ffb7f863934f.png">

Start from here
<img width="575" alt="image" src="https://user-images.githubusercontent.com/65875612/178125245-1df8fd90-6ab1-44c4-852e-10ea43194b88.png">

**Comment by wsbrenk** [comment]
![hofolder](https://user-images.githubusercontent.com/11821502/178125570-8b39c05d-c60b-4c7b-9127-677d6304f5c5.jpg)

on windows i can move to the directory connected with the icon by doing right mouse click

**Comment by wsbrenk** [comment]
maybe you could find some properties of the icon with right mouse action?

**Comment by wsbrenk** [comment]
maybe mac search is case sensitive - then you should search again for HO.jar

**Comment by wsbrenk** [comment]
I have to go to bed now, it's half past two in the night with us - tomorrow I have a gig

**Comment by wsbrenk** [comment]
this problem shows that we could use a user manual that describes such things. The support of the community sometimes does not seem to be enough.

**Comment by Tarotistas** [comment]
Do you mind this folder from "Show content"? For me the Backup file is the historical problem while need to upgrade wo loosing the data.

<img width="315" alt="image" src="https://user-images.githubusercontent.com/65875612/178170377-98d40b1a-926a-462c-9418-204151fb5621.png">

**Comment by wsbrenk** [comment]
what is in java/app ?

**Comment by wsbrenk** [comment]
but no db directory?

**Comment by masterpatje** [comment]
https://support.apple.com/en-in/HT201250

If you have enabled time machine, you can go back to the time before the db was deleted.

Otherwise if you saved the HRF files on download you can again import them into HO ans rebuild the database. Please make sure you do a recalculation of subskill after importing all files.

**Comment by Tarotistas** [comment]
Hello @masterpatje I have saved the HRF files but again. Can't be improved the db.dat file in the app? This is weakness of the application specially when we try to update. 

Can be an option to export the db in the selected path in a simple way?

Thanks in advance
BR
Gaspar

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/179420898-3ad53ca2-9adb-454c-8cf3-4e368d70dd3e.png)

Help->About will show the database and log file folders

**Comment by Tarotistas** [comment]
That´s for Windows. not for MAC.
No Solution then.

Thanks anyway!

**Comment by wsbrenk** [comment]
@Tarotistas that's right - the picture shows the about dialog on my system (windows). you could test it with the newest beta release on your system - hopefully  Help->About will show the directories on your mac.
