### ISSUE TITLE
[FEATURE] Replace DBManager's EscapeSequences methods

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1593]
i think the existing insert- and deleteEscapeSequences are error prone.

for example they will deliver wrong results if the original strings contained '#' or '§' characters.

To get rid of escaping, the use of prepared statements should be considered.

**Comment by wsbrenk** [comment]
@tychobrailleur what are your thoughts concerning this?

**Comment by wsbrenk** [comment]
#1592 found this escapes here. maybe they are the reason for that issue!?

**Comment by tychobrailleur** [comment]
Yes, I would agree prepared statements are preferable, safer and clearer. I think it would be a lot of work to convert all SQL statements into prepared statements, though?

**Comment by wsbrenk** [comment]
@tychobrailleur work is in progress. the crucial thing is how to migrate all the strings in database with escaped characters. Up to now i have no good idea concerning this. i fear this will become a very long running migration.

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/181372682-a41f1f1f-1574-4523-9005-2d9b4163d249.png)
