### ISSUE TITLE
Last 16 weeks of past Training visible on Training prediction tabl

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#1601]
**Describe the bug**
In the Training Prediction Tab there is a bug concerning visible weeks.
I can see last 16 training prediction weeks of last season which were not visible until now. (see screenshot)
I would expect to see only future training effects as in the past.

**Screenshots**
![Training_Prediction](https://user-images.githubusercontent.com/67096604/180737499-873184cf-053d-4081-af1e-f0cf630d2124.PNG)

**Platform information:**
 
![Platform_Information](https://user-images.githubusercontent.com/67096604/180738120-2e80ebcd-0273-421a-8d5e-12ed6e0d4f95.PNG)

**Additional context**

**Comment by wsbrenk** [comment]
this is a bug in hattrick: https://www87.hattrick.org/Forum/Read.aspx?t=17497428&n=1&v=0

it only happens on last day of the season (or first of the next). then hattrick will give a wrong season offset value.

@johari75 if you download today, the error should be gone.

**Comment by johari75** [comment]
Thanks, you are right.
Error doesn´t occure anymore.
