### ISSUE TITLE
[eFEAT] Lineup tab improve overall rating information

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#161]
As an extra step of #27, we should have **Loddar and Hatstats** in the top right section just below the sector ratings.  Those values would also be **updated with change on the timeline** or if clock are selected

![image](https://user-images.githubusercontent.com/1136496/60904440-5acf8900-a273-11e9-9765-0b116552c0e5.png)

Then we will remove them from the panel below, it will be a better usage of the space overall

![image](https://user-images.githubusercontent.com/1136496/60904655-abdf7d00-a273-11e9-8d56-61be06a2d482.png)

**Comment by akasolace** [comment]
closed by #172

**Comment by akasolace** [comment]
@brokenelevator 
the labels Hatstats / Loddar are missing ...
Also is it possible to align the boxes CD/MF/CA ?

**Comment by brokenelevator** [comment]
@akasolace I'm not sure what you mean by align the boxes.
as for labels... there are no labels for the sectors. why should there be for hatstats and loddar.
there are tooltips.

**Comment by mistermax80** [comment]
@akasolace what do the situation on this?

**Comment by akasolace** [comment]
@mistermax80 nothing was done here. I think it could have been clearer/cleaner, but maybe it does not worth the effort. It might be tricky to do but if you want to give it a try you are more than welcome :-)

**Comment by mistermax80** [comment]
@akasolace, so, the values loddar / hatstats in relation to time is missing? I saw the layout it is ok. Do I understand well?

**Comment by akasolace** [comment]
> @akasolace, so, the values loddar / hatstats in relation to time is missing? I saw the layout it is ok. Do I understand well?

the values are present, I was only mentionning that we might use labels instead of hover text to make it clearer and also maybe to align the value a bit more. Only some visual tweaks really, nothing more

**Comment by mistermax80** [comment]
Ok!

**Comment by mistermax80** [comment]
Current situation:
![image](https://user-images.githubusercontent.com/15519907/71125544-71491b80-21e7-11ea-9e36-22c7814902a9.png)

@akasolace where do you want I can go ahead?

**Comment by akasolace** [comment]
@mistermax80,  As you can see, it has been partially implemented. Hatstats and LoddarStats have been moved to top screen already. I only left the ticket open because to be complete I thought we should label Hatstats and LoddarStats. At the moment it is not clear what those number represents, there is a hoover message but I thought we could try something clearer. Now to be honest, I am not sure we have the space to put the labels. You can give it a try and maybe there is nothing we can do and we close that issue.
For others information in that screen, I never really thought about it, if you have some ideas, lets discuss them

**Comment by akasolace** [comment]
@wsbrenk @mistermax80 @yaute74  please let me know if there is something we should do here or if I simply close the issue. Thanks !

**Comment by yaute74** [comment]
For me hatstat and loddarstats represent the power of the team. Maybe you can use tool-tip if you have a space problem.

**Comment by akasolace** [comment]
There is already tool-tip but I am not sure presentation is ideal.
There is nothing urgent here, we will look at this one when we have time ...

**Comment by yaute74** [comment]
![image](https://user-images.githubusercontent.com/34601782/71620936-c19f8080-2bcc-11ea-95f3-191bf0eda3db.png)

**Comment by akasolace** [comment]
@yaute74 perfect !

**Comment by yaute74** [comment]
@akasolace I do it with Gimp :/

**Comment by akasolace** [comment]
> @akasolace I do it with Gimp :/  

:-)

**Comment by akasolace** [comment]
closed by ca148d6
