### ISSUE TITLE
[BUG] Java heap Space

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1610]
Hi
When i start HO (4,1.33102-JRE) with team 1 and 3 is all ok. when i start with tem 2 is comming the following error message:

Java heap Space (see the Java Erroro in JPG)

![Error_Java space](https://user-images.githubusercontent.com/88058929/181847393-71a90d06-cc62-4f95-a370-749f1a15055b.jpg)

**Platform information:**
 - OS: [Windows11]
 - Version (HOSetup-4.1.3310.2-JRE)

thanks pepper

**Comment by wsbrenk** [comment]
@peppermil could you test if this error also happens with current beta of HO6 (it is close to stable). Alternativly you could upload your database - then i would check that.

**Comment by wsbrenk** [comment]
same as  #1586?

**Comment by peppermil** [comment]
> @peppermil could you test if this error also happens with current beta of HO6 (it is close to stable). Alternativly you could upload your database - then i would check that.

i can't load the hrf files on vers. 6.0 - all files are "corrupt"

DB -->  https://1drv.ms/u/s!AjKUl1nPppPXj4ZfXJ0P1F5JyCvyag?e=Y5Dotc

**Comment by peppermil** [comment]
> same as #1586?

no, i can't start my second team, the ho stop by "prepar to show"

![Error_Java space_1](https://user-images.githubusercontent.com/88058929/182540608-acafeb3c-6e64-48a1-a388-b06c306d3736.jpg)

**Comment by wsbrenk** [comment]
@peppermil  i restored your latest backup (db_Lucerne Lions 12-2022-07-31.zip) and could load it with HO6 beta:

![image](https://user-images.githubusercontent.com/11821502/182678120-dbcac7c9-0605-4ead-8f34-c01a989d80d8.png)

**Comment by wsbrenk** [comment]
Download worked too:

![image](https://user-images.githubusercontent.com/11821502/182678980-478d44a1-6427-498e-9bf4-65aeea626102.png)

**Comment by peppermil** [comment]
you can closed the ticket - with HO 6.0 stable Version finction verry good - I have deleted HO 4 ;)
