### ISSUE TITLE
[BUG] BETA 361 Training

### ISSUE THREAD

**Issue by filex100** [akasolace/HO#1611]
**Describe the bug**
When I open the software and go to training and click on skill predition, it gives an error.

**Platform information:**
 - OS: [Linux]
 - Version (Linux Mint 20.3)

[HO-2022-07-29.log](https://github.com/akasolace/HO/files/9224097/HO-2022-07-29.log)

**Comment by wsbrenk** [comment]
should be fixed in current beta
