### ISSUE TITLE
[BUG] Just checking - Training Week (difference between HO 7 and HO 6)

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1618]
HO6 (left side) and HO7 (right side) uses different Training Week numbers. Is this done intentional? 
![image](https://user-images.githubusercontent.com/102049050/183128129-5cce4a28-ef48-4ea5-b4da-4776c67da292.png)

HO6 seems to make a bit more sense, since the 30 july 2022 file contains the friendly and the cup match and is in my oppinion correctly noted as Training Week 1 (Season 71).
![image](https://user-images.githubusercontent.com/102049050/183128477-0358a3df-f896-4b09-a2eb-bcb35d17d876.png)

This is the week before that. That are two friendly matches in the off-season and is in my oppionion correctly noted as Training Week 16 (Season 70).
![image](https://user-images.githubusercontent.com/102049050/183128526-ece052a9-8813-4820-b520-855a8dcefeb3.png)

**Comment by wsbrenk** [comment]
it is intentional when your training date is between 21:14 and 22:04 - otherwise, i have to check what was changed in HO7

**Comment by masterpatje** [comment]
Look also at the 5th of August. The training week number differs in HO7 from HO6.

**Comment by Tarotistas** [comment]
Hello When is intended to release HO v6.0? Thanks!

**Comment by wsbrenk** [comment]
@Tarotistas it is released.

**Comment by masterpatje** [comment]
In hattrick the Training Week is consistent with HO6.

The cup week is considered as week 1.

So I think in HO7 for some reason the week number has changed while working on issues. Could you check?

**Comment by wsbrenk** [comment]
@masterpatje i can reproduce this - will check that

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/199571922-af71889e-0890-4708-94b7-0654535f8f74.png)

new 7.0 dev seems to fix that
