### ISSUE TITLE
[BUG] Bought back a youthplayer | difference calculation is odd

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1624]
I sold a player Bloemhoff that I trained up to Defending 15 Playmaking 14 on 10th June **2020**.
![image](https://user-images.githubusercontent.com/102049050/183405569-59b71d11-0121-4ffc-a52a-4d68734fd98d.png)

I bought back that player on 27th March **2022** Defending dropped a level to 14 (-1) passing (+3) and Winger (-1) and XP(+4).
![image](https://user-images.githubusercontent.com/102049050/183405989-d9fc19e6-756e-44b1-a681-5f407edd5a1e.png)

Comparing to the week before that player is bought:
![image](https://user-images.githubusercontent.com/102049050/183405853-fa60a961-4249-4bf5-8419-82f1c950b4b2.png)
Suddenly the increase is Experience (+11) Playmaking (+9), Defending (+8) and Passing (+6)
![image](https://user-images.githubusercontent.com/102049050/183405803-50bcf755-c5d8-4556-a2af-ca765b232077.png)

Any idea what is happening? I have checked and the following HRF files are in the database (just before I sold the player).
![image](https://user-images.githubusercontent.com/102049050/183407036-73a4cb0f-7120-4500-99f1-a66c47046188.png)

**Platform information:**
 - Version HO6 release version

**Comment by wsbrenk** [comment]
Inspecting the source code i got the impression, that this should be a feature.
when the player is not found in the selected hrf instance, the very first hrf where the player appears is taken as compare instance.

**Comment by wsbrenk** [comment]
Thinking helps: The first HRF instance we should take must be downloaded after the selected entry
