### ISSUE TITLE
[FEATURE] Improvements to SubstitutionEditView

### ISSUE THREAD

**Issue by alexeyr** [akasolace/HO#1626]
**Is your feature request related to a problem? Please describe.**
First, I finally found today 
![image](https://user-images.githubusercontent.com/11821502/73590499-7c2fe500-44e3-11ea-8676-5ebb0b219f14.jpg)
from #294. Thank you! But I have some suggestions:

**Describe the solution you'd like**
1. Show effect on LoddarStats and position ratings as well as HatStats (perhaps configurable what to show, or only show what actually changes)
2. Suggest the best substitution time automatically instead of having to hunt for it. 
3. (possible) Color parts of background depending on effect (e.g. minutes which give the best stats are green and minutes which give the worst are red).
4. (this is more of a bug and I can open it as a bug if you'd prefer) Currently it only seems to recalculate when the minute is changed, so if I want to see if a different substitute is better, I have to:
    1. Change the substitute
    2. Move the minute slider a bit
    3. Move it back
    It should recalculate immediately after step 1.

**Comment by masterpatje** [comment]
I like this recommendations. Also the colour bar to indicate when a player looses too much, 100% dark green, 80-100% light green, 60-80% yellow, 40-60% orange and <40% red?

@wsbrenk I think that #4 is indeed a bug, maybe it is good to seperate that one from the other 3 features

**Comment by wsbrenk** [comment]
recalculate rating when players are changed.
