### ISSUE TITLE
[BUG] Authorisation page Hattrick developer user | capitaineFro | still correct?

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1627]
![image](https://user-images.githubusercontent.com/102049050/184308630-b5be0946-05ca-4d08-b5c2-7c1e794ed10c.png)

**Comment by tychobrailleur** [comment]
`capitaineFro` is the owner of the CHPP licence, I don't know this is transferrable at all.  Any idea, @akasolace ?

**Comment by akasolace** [comment]
Yes it can be done ... @wsbrenk can you ask HT official ? I would like to avoid to reactivate my HT account ....

**Comment by wsbrenk** [comment]
@akasolace this is the answer, i got from HTs: 

> 
> 09:57 An dich
> 
> Hi,
> He need to send an official message to transfer the ownership of the app. An external post can't be accepted.
> 
> /CHPP-teles

**Comment by wsbrenk** [comment]
Hi @akasolace, if you again would log into hattrick, could you please send a message to the HTs, that I should get the ownership of the HO chpp license from you?

**Comment by tychobrailleur** [comment]
I was thinking about this the other day, and I was wondering if we could not simply apply for a new CHPP licence, and use it in a new release?

**Comment by wsbrenk** [comment]
@tychobrailleur  Nice to hear from you. Yes, this could be a good idea, as the Hts have also realized that we could run into a dilemma. The statement was, as long as the owner exists, they cannot hand over the license to another user without his consent. However, Akasolace is a Diamond supporter and therefore will not automatically disappear as a user and as long as the HO remains a top ten Chpp application, akasolace will gain this support every year.

The HTs have contacted Akasolace. Hopefully he will answer them as soon as he will recognize, that his account will not be deleted.

**Comment by akasolace** [comment]
Hello @wsbrenk @tychobrailleur,  sorry for not responding previously. I will log into HT and send a mail to HTs right away...
Thank you @wsbrenk for keeping the project alive !

**Comment by akasolace** [comment]
Ok, I just requested CHPP-teles to transfer the HO license to @wsbrenk!

**Comment by tychobrailleur** [comment]
> Hello @wsbrenk @tychobrailleur, sorry for not responding previously. I will log into HT and send a mail to HTs right away... Thank you @wsbrenk for keeping the project alive !

No worries, hope you're keeping well!  Thanks for that, and hope to see you around!

**Comment by akasolace** [comment]
Yes all good thank you just that with my new job I have much less free time than I used to have :-) 
I keep enjoy to do some coding in my spare time, lately it was on some personal project in csharp and my usual Euler project challenges but maybe one day I will find back the motivation to contribute to HO ! Take care !

**Comment by wsbrenk** [comment]
@akasolace thank you

**Comment by wsbrenk** [comment]
it is done - now i'm the owner of the chpp license - thanks @akasolace

**Comment by masterpatje** [comment]
That is great news. Good bye and thanks to the old king. Welcome to the ‘new’ king 👑

Hartelijke groet,

Patrick

Op 17 mrt. 2023 om 19:12 heeft wsbrenk ***@***.***> het volgende geschreven:

﻿

it is done - now i'm the owner of the chpp license - thanks @akasolace<https://github.com/akasolace>
