### ISSUE TITLE
[FEATURE] Add second user via menu

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1628]
I think it would be a good idea if you create a new option in the menu for adding a second user.
This could be directly under the import from HRF for example (also shown in the screenshot).

Now you have to add a second user via the database menu which is a more 'technical solution' than user friendly solution.
Adding a new team will start the same process as with the first team and in the background will add a new database entree in the background.

The current path is shown below that is via the database/user administration:
![image](https://user-images.githubusercontent.com/102049050/184312260-837cdf8e-3678-43ec-9a5b-2d0635ccf666.png)

**Comment by wsbrenk** [comment]
translation (poeditor push) is still missing. have to check that.

**Comment by wsbrenk** [comment]
see #1737

**Comment by akasolace** [comment]
> translation (poeditor push) is still missing. have to check that.
> 
> @akasolace could you help me and tell me how poeditor push is working (poeditor-ho integration)? in build.gradle i only can find the pull.

@wsbrenk  I will have a look today

**Comment by akasolace** [comment]
> translation (poeditor push) is still missing. have to check that.
> 
> @akasolace could you help me and tell me how poeditor push is working (poeditor-ho integration)? in build.gradle i only can find the pull.

@wsbrenk  honestly, I can't recall I haven't look at this for so long ....

**Comment by wsbrenk** [comment]
fixes #1629

**Comment by wsbrenk** [comment]
@akasolace did you try this: https://poeditor.com/github/connect ?

**Comment by akasolace** [comment]
@wsbrenk I will have a look tonight. I will need to install intelliJ first on my new PC. I don't even have an active hattrick account anymore but that should not be a pb.
