### ISSUE TITLE
Download Alignment not possible HO 6.0 Stable version

### ISSUE THREAD

**Issue by Tarotistas** [akasolace/HO#1630]
**Download Alignment not possible **
I updated last HRF on Thursday last week. Yesterday we played Ligue match and today I can't download match Cup.
**To Reproduce**
1. Aligment
2. Select match
3. Download alignment
4. Bottom in gray/no available

**Screenshots**
<img width="602" alt="image" src="https://user-images.githubusercontent.com/65875612/184647206-ed4e4224-cfa0-4e19-8da4-80623ab2514b.png">

**Platform information:**
 - OS: [macOS / Linux]
 - Version (Monterrey)

**Additional context**

**Comment by Tarotistas** [comment]
Hello! Any comment here? Is still happening...

<img width="568" alt="image" src="https://user-images.githubusercontent.com/65875612/190897011-a5516f27-126a-483d-823a-99b8f6240610.png">

**Comment by wsbrenk** [comment]
@Tarotistas this buttons is disabled, if no order is given in HT. 

If you entered the lineup in hattrick (not in HO) you have to download match infos (F11), before you can select those future matches and download their orders.

**Comment by Tarotistas** [comment]
But then what is the sense of Download if this is requires F11? F11 Download everything....

**Comment by wsbrenk** [comment]
hm good point - but F11 does not download orders of future matches (only the info, that an order was stored in hattrick).

the lineup of future matches can only be downloaded by this button for now. download is not needed if you store the lineup with HO.

**Comment by Tarotistas** [comment]
But that was the point of HO 5.2 ..... I don't want to download everyday HRF file.

**Comment by Tarotistas** [comment]
or every time I change my lineup ...... again that bottom was working and not anymore.

**Comment by Tarotistas** [comment]
Hello, Just to show you the BUG if the match belong to League battle then the Download Button is available 

<img width="276" alt="image" src="https://user-images.githubusercontent.com/65875612/193165158-60e0b5da-0b47-4897-9895-97f9c39be747.png">

but for the rest....

<img width="287" alt="image" src="https://user-images.githubusercontent.com/65875612/193165226-789491e3-7a70-464e-95c5-5157edd7e7c2.png">

Hope brings value add to demonstrate what I consider a BUG.
BR
Gaspar
