### ISSUE TITLE
[BUG] Missing Youth players and information on Youth Tab

### ISSUE THREAD

**Issue by vomme2020** [akasolace/HO#1633]
**Describe the bug**
Migrated from 5.2 to 6.0.368 on Ubuntu
Not all Youth players are not showing up in List - has tried to download also form youth page.
Also get NullPointer exception when trying to update on training page. 

**To Reproduce**
1. Go to 'Youth tab'
2. Click on 'F11' to download
3. Save hrf and see missing players
![image](https://user-images.githubusercontent.com/112803830/188308324-23f8eb5d-7224-4039-8b26-50f820000bf2.png)

To update on training tab, click the tab and update training
![image](https://user-images.githubusercontent.com/112803830/188308228-822d6a0f-2a9d-4f65-90b5-ed02e988aa72.png)

**Screenshots**
See Above inline

**Platform information:**
 - OS: [Linux - Ubuntu]
 - Version: 
![image](https://user-images.githubusercontent.com/112803830/188308181-60602575-69d0-4245-bdd5-49ab6d52a69c.png)

**Additional context**
None

**Comment by vomme2020** [comment]
Any thoughts on how to resolve this issue?

**Comment by wsbrenk** [comment]
@vomme2020 if you could upload the backup of your ho5.2 database backup, i could try to debug your issue. backups are zip files in your database folder.

**Comment by vomme2020** [comment]
@wsbrenk - I have uploaded both the 5.2 DB backup that I have migrated from and the 6.0 DB backup that I have migrated to.
The issue on the Youth Tab is in 6.0.
[db_user-2022-09-04 - backup5.2 - migrated from this.zip](https://github.com/akasolace/HO/files/9509208/db_user-2022-09-04.-.backup5.2.-.migrated.from.this.zip)
[db_user-2022-09-04 - backup6.0 - migrated to this db from 5.2.zip](https://github.com/akasolace/HO/files/9509209/db_user-2022-09-04.-.backup6.0.-.migrated.to.this.db.from.5.2.zip)

**Comment by wsbrenk** [comment]
@vomme2020 found the bug. would be not easy to fix.

XMLMatchLineupParser.createTeam has to read starting positions first - otherwise there could be duplicates/wrong positions in stored lineup

**Comment by vomme2020** [comment]
ok - I understand.
I will then move back to 5.2 until issue is fixed.

Thanks for helping out - will you update this when bug has been resolved?

**Comment by wsbrenk** [comment]
error was caused by your match at 30.06.2022 05:00. replacement of injured goalkeeper by a field player was not handled correctly.

**Comment by wsbrenk** [comment]
changes are in new beta of HO6.1

**Comment by vomme2020** [comment]
Good job - that resolved the issue!
![image](https://user-images.githubusercontent.com/112803830/189705265-46453a13-49a0-4c58-b7df-fbbe4a0e93ef.png)

**Comment by vomme2020** [comment]
@wsbrenk - on another note:
from the above screenshot you can see that the sliders takes a lot of space.
Would it be possible to put the graph in a separate "area", so you can re-size the split between sliders and graph?
Kind of what is done on the Lineup tab.
As a feature request?

**Comment by wsbrenk** [comment]
@vomme2020 yes of course - there is a similar ticket, i think.
