### ISSUE TITLE
[BUG] Hrf problem

### ISSUE THREAD

**Issue by Berre11** [akasolace/HO#1635]
Good evening,

from a couple of weeks now I have an issue with Ho6. every time I close the application the information about my team is deleted and when I return I have to re-download the data as if it were the first time I open the application. If i try to import hrf files i get an error message telling me that the files are not readable. I don't know what to do, can you help me? thank you! Attached the database backup file.

[Database backup file.zip](https://github.com/akasolace/HO/files/9592726/Database.backup.file.zip)

**Comment by wsbrenk** [comment]
Hi @Berre11, these are your downloaded hrf files, not the backup of your database. if you installed the win-exe HO, the backups are in the directory %APPDATA%/HO/db* by default. there are zip files. please upload one of them.

if you installed a portable version of HO, die db folder is a subdirectory of the install directory. if you are on MAC, i don't know.

**Comment by Berre11** [comment]
Hi, thanks for the information, I'm not very familiar with these things. I found three zip folders, here they are attached, I hope I have uploaded the right information this time. Thank you!
[db_user-2022-09-12.zip](https://github.com/akasolace/HO/files/9598769/db_user-2022-09-12.zip)
[db_user-2022-09-15.zip](https://github.com/akasolace/HO/files/9598770/db_user-2022-09-15.zip)
[db_user-2022-09-18.zip](https://github.com/akasolace/HO/files/9598771/db_user-2022-09-18.zip)

**Comment by wsbrenk** [comment]
@Berre11 these databases are corrupted - typically this happens when HO is not closed correctly - power down the pc when ho is running for example.

i don't know how this can be fixed. if you don't have older (correct) backups, i fear, you have to start from scratch. delete the files in the database directory and start HO and connect again to your ht team.
