### ISSUE TITLE
[BUG] java.lang.RuntimeException: Exception while painting

### ISSUE THREAD

**Issue by derkleinefips** [akasolace/HO#1644]
any special letters like ä, ö, ü within the path of hattrick organizer (for example E:\ä\Hattrick Organizer v5.2.3945.2\) causes "java.lang.RuntimeException: Exception while painting" issues while hattrick organizer is loading. HO isn't displayed without any problems

problem exists since version 5 of hattrick organizer

[HO-2022-09-28.log](https://github.com/akasolace/HO/files/9664276/HO-2022-09-28.log)
[output.log](https://github.com/akasolace/HO/files/9664277/output.log)
![28-09-_2022_13-07-35](https://user-images.githubusercontent.com/114580101/192764241-a47c3904-23f9-4e0e-9633-1c2a7f5e969c.png)
![28-09-_2022_13-07-52](https://user-images.githubusercontent.com/114580101/192764247-0abb9cc0-e7d5-46d0-8c7f-0bcf2045d01d.png)

**Comment by wsbrenk** [comment]
related to #747

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/193454274-ebf6dcd6-8a4e-4b46-8541-7341750db71f.png)

screenshot shows colors in directory HÄ on top left  and correct colors in directory HO.

**Comment by wsbrenk** [comment]
@weisJ could you give a hint, what is going wrong there?

**Comment by wsbrenk** [comment]
darklaf 3.0.2 looks like this:
![image](https://user-images.githubusercontent.com/11821502/193455117-c0af1ab0-53a0-4385-95f0-4bbbbca9c006.png)

**Comment by weisJ** [comment]
I'll have a look at it.

**Comment by weisJ** [comment]
I'm having some troubles debugging this. The `JerseyIconTest` works for me with `3.0.2` (besides some false warning message). How do I add some players to the table?

**Comment by wsbrenk** [comment]
[db_Juventus Brenk 4-2022-10-02.zip](https://github.com/akasolace/HO/files/9692834/db_Juventus.Brenk.4-2022-10-02.zip)

try to replace your database with this one

**Comment by weisJ** [comment]
Do I put this in `HO/db`?

**Comment by weisJ** [comment]
Ok got it to load the database. It really isn't straight forward. Perhaps I am doing something wrong, but I had to disable the `prepareBuild` task as it was nuking the db folder.

**Comment by weisJ** [comment]
Ok I found the issue.
1. The issue with non-ascii characters ins't present in darklaf 3.0.2. With version 3.0.0 the svg implementation has been replaced, which should make painting more reliable.
2. As for the missing color. This is an oversight on my part (i.e. not testing the custom icon implementations outside of darklaf :D).
   You should be able to fix it by calling
    ````java
	IconLoader.updateThemeStatus(new Object());
   ````
   after the look and feel has been initalized. As I mentioned above some warnings are issued incorrectly. To silence them you can call
    ````java
    LogUtil.getLogger(IconLoader.class).setLevel(Level.SEVERE);
	```` 
    Also the svg implementation will complain about several tags (from the <meta> portion of the svg) that they are not implemented. You can either
   - remove those tags, as they aren't relevant for painting (and non-standard in some cases)
   - Silence the warnings through `Logger.getLogger("com.github.weisj.jsvg.parser.SVGLoader").setLevel(Level.SEVERE);` until I am able to provide a proper API for it.

**Comment by wsbrenk** [comment]
@weisJ Super - Danke, das funktioniert!
