### ISSUE TITLE
[BUG] Training empty from v 3.0

### ISSUE THREAD

**Issue by Dillotu** [akasolace/HO#1651]
**Describe the bug**
The upgrade from V 3.0 to any othe rversion let the training page empty.

**To Reproduce**
Db attached 

**Screenshots**
https://snipboard.io/XpxMmh.jpg
https://snipboard.io/0L6TGV.jpg

**Platform information:**
 - OS: Windows 10

Feedback (negative) for the new  lineup layout v6 
The lineup page layout with a 1920x1080 screen is to big it is impossible to have a good experience. 
V6 https://snipboard.io/5mKUbo.jpg
V3 https://snipboard.io/JTySUh.jpg 

The DB is to big to be attached I can share a Gooogle folder if you send me a privite message (I don't know if is possible)

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/193613898-c42e6ade-f53d-4ddc-a56e-cc6c49d0829c.png)


after first download (F11), the season offset is repaired. 

SeasonOffset was introduced in HO4. Downloads before are calculated with Offset 0 which is wrong for Ireland (-12). First download gets the correct value.

Don't want to make an automatic unintended download to repair this automatically.
