### ISSUE TITLE
[BUG] Startup Error after installation of 6.1 BETA (r379)

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#1654]
**Describe the bug**
Startup Error after installation of 6.1 BETA (r379). (View screenshot)

**Screenshots**
![Bug_StartUp](https://user-images.githubusercontent.com/67096604/193765933-8e2387ca-da40-4104-9bf1-2240e2511103.PNG)

**Platform information:**
![Platform_Information](https://user-images.githubusercontent.com/67096604/193765985-6097bca3-16d9-4063-9337-a991d699832d.PNG)

**Additional context**

**Comment by wsbrenk** [comment]
@johari75 how did you install the HO?

**Comment by wsbrenk** [comment]
@johari75 could it be that you have simply copied the new version to the folder of the old installation. Maybe the old darklaf (2.7.3) files have been preserved. You should delete them.

**Comment by johari75** [comment]
@wsbrenk Update to current version was done by HO feature. Installation was done the usual way. But I copied database from previous version to get current training values.

**Comment by wsbrenk** [comment]
can reproduce it now. it happens when upgrading the portable versions.

**Comment by johari75** [comment]
You are right. Sorry.
Previous version was HO-6.0.315.1-portable-win-BETA-JRE

**Comment by Synthespian** [comment]
Yup.
Just upgraded portable. Same issue.
Now wondering what's going to be the correct way to update it again, having seen this.

**Comment by wsbrenk** [comment]
@Synthespian you can extract the update-zip file by hand. the ho function should have downloaded the correct zip file already (update.piz). You can rename it to .zip and open it with 7-zip. 
the name of the darklafe packages changed, so you have to remove the old files after extracting the new version.

**Comment by Synthespian** [comment]
Tried with new beta.  
Not sure.
![image](https://user-images.githubusercontent.com/48737160/194717904-e05e0fd9-53af-4916-9740-ab9a84e16e14.png)

**Comment by Synthespian** [comment]
The previous version (I kept safe just in case) runs and fails at same point.
I think portable version has wrong exe (or other element) in the JRE file.

**Comment by wsbrenk** [comment]
@Synthespian Thank you for testing - unfortunatly i don't understand how you tested this. the newest beta should not find any newer beta to update to.

if it was a update of the newest beta you tested, there should be a backup folder, which saves the old installation in your directory.

**Comment by johari75** [comment]
@wsbrenk Got the same error as Synthespian 9 days ago after upgrading the portable versions via HO feature. Error message comes up during restart after upgrade.

**Comment by Synthespian** [comment]
Just a nudge, needed this for lookback, that the latest upgrade has given another error, this time where it can't find the java that is part of the download set.
![image](https://user-images.githubusercontent.com/48737160/199952662-1c12a234-6818-43eb-b1dc-9702d998a685.png)
