### ISSUE TITLE
Download Error[BUG]

### ISSUE THREAD

**Issue by Locobauer** [akasolace/HO#1660]
I try to download my team's data but get the following error: java.lang.StackOverflowError
This is the second time I get it and they came from 2 different matches, it messes all the stat calculations of the app.
It keeps trying to download the information from those matches for a long time until you get the error.

![Error1](https://user-images.githubusercontent.com/115485469/194915002-15e0e80a-53a6-4e92-97b0-b2f02995b435.png)

**Platform information:**
 - OS: Windows
 - Version 2022-09 Cumulative Update for Windows 11 for x64-based Systems (KB5017328)

**Comment by wsbrenk** [comment]
if you are using HO5.2, it could be the same as  #1586

**Comment by Locobauer** [comment]
Thank you!
