### ISSUE TITLE
[FEATURE] Training estimation

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1661]
In general for long term it would be interesting to again look at the training estimation.  My experience is that the skill gain in training is a bit quicker then the estimations in HO at the moment. With a 76% training efficiency (based on hattrick calculations) I have the idea that my training speed is quite faster then calculations in HO. If I remember correctly training speed in hattrick has increased since already quite some seasons (>5 seasons). Training is an important aspect in hattrick so maybe for long term re-check the calculations? How can I help with practical findings?

I know there is a module preferences -> training to tweak the training speed a bit, but I am unsure how to use (some of) it. And how important / sensitive the fields are for the calculations. Certainly for the bottom part (factors for the training %).

Ps. The title "presumably trainingweek **per talent**" is a bit unclear.  My assumption is that talent has something to do with age, but what do you exactly mean?
I think that the title probably should be something like "**Estimated** Training Weeks for **Skill Increase (_reference 17 year talent_)** to be more descriptive. And maybe an explanation icon.

![image](https://user-images.githubusercontent.com/102049050/195816355-3c6a1bb0-55cd-453e-ace2-1ae47faee2bd.png)

And what does the option Future weeks do?
![image](https://user-images.githubusercontent.com/102049050/195818712-b0d7bb92-5fe7-4f15-b554-d2b28aec43ef.png)

Hattrick uses training efficiency: (maybe bottom part (factor for the training %) can be shown as an efficiency calculation and recalculates after adjusting. So that there is a better understanding of the effect.
![image](https://user-images.githubusercontent.com/102049050/195819081-8057b066-6d10-410a-9b06-f6d1ed614af1.png)

Hopefully this is usefull to gain insight in possibilities to improve HO in long term.

**Comment by wsbrenk** [comment]
@masterpatje looking on player statistic panel shows the development of the skills very good i think. The displayed skill development fits very well with the actual course. There are no jumps to be seen. The situation is somewhat different with osmosis training, where the development seems to be underestimated.
This is particularly blatant with my goalkeeper, whose development is not taken into account at all in the playmaking training.
and the skill loss of old players is also overestimated.

**Comment by wsbrenk** [comment]
info from Schum's thread concerning skill drops:


First, a little background.
10 seasons ago, namely 08.05.2017, changed the mechanics of skill drops.
In fact, DropAge and DropLevel were separated in time.

DropAge was left, as it was before, on Monday.
And DropLevel was moved to the training update, and summed up with the training.

And if before that, after training the skill to "Colossal" and above, and switching the training to a secondary skill, the main skill began to fall, then after the changes it stopped happening.

As a result, the strategy of leveling the primary skill to "Colossal", and the mandatory switch to a secondary skill, ceased to be relevant.

But in total, the speed of pumping high-level young players has not changed at all.
see https://www88.hattrick.org/Forum/Read.aspx?t=17404127&n=10&v=6

**Comment by wsbrenk** [comment]
skill drop formula from Schum gives much better results.

**Comment by wsbrenk** [comment]
i have to check if the configuration of skill calculation still has any effect - if not i will remove it.

**Comment by masterpatje** [comment]
Before I can give feedback I need probably 5-13 weeks to get an indication for players, because most player still have a build up subskill based on the old skill drop calculation.

Questions:
- Does the changed calculation has an effect on recalculation functions?
- Do you have an idea how I can test the working of the last implementation? (what to look for in your oppinion)
- Is it an idea to seperate the configuration of skill calculation functionality to another ticket? Could you do so?

**Comment by wsbrenk** [comment]
1. the new formula is used in weekly and in recalculation as well. 
2. So you can recalc and check in your statistic panel if there are suspicuous jumps in skill development.
3. yes and yes - i will do so.

**Comment by wsbrenk** [comment]
> 		In the training update, a decrease in skill cannot occur.
> 		But depending on the skill level and age of the player, there is a decrease in the growth of the trained skill.

this message from Schum was not taken into account. i will fix that!

**Comment by masterpatje** [comment]
"skill level and age"
Might that be the reason that I experienced that younger players (<25) were on a high subskill level when on lower skill levels? Because on lower skill and lower age the negative effects are less than in earlier versions of HO?

Or is this a wrong conclusion?

**Comment by wsbrenk** [comment]
@masterpatje the skill drop depended on skill level and age all the time. the amount slightly changed with the new formula i found on Schum's thread.

the mistake i made with the first implementation was, that i reduced subskill in any case. now i interprete the referenced message, that the dropLevel part of skill decrease only reduces the training effect - conclusion: No training No dropLevel descrease.

Beside dropLevel part, there is a dropAge part, that happens on monday independently on training settings.
