### ISSUE TITLE
[BUG] Portable Version AutoUpgrade Can't find Java

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#1681]
**Describe the bug**
When trying to load HO, using a portable version (64 inc JVM), the error is show that it can't find the JVM on the system.

**To Reproduce**
Use portable
Load HO

**Screenshots**
![image](https://user-images.githubusercontent.com/48737160/199953605-4276b081-f5cc-4b59-9d13-b7818c7758f4.png)

**Platform information:**
Windows 10

**Additional context**
Just did an auto-upgrade today.  Can't see which version it's taken me to cos the splash screen doesn't load.
Possibly linked to https://github.com/akasolace/HO/issues/1654 and some code bundling of the portable version?
Have tried to overlay 6.1.384 but that has same issue.

**Comment by Synthespian** [comment]
Also, tried updating Java to 8.351 but that still doesn't help it run.

**Comment by masterpatje** [comment]
Did you use the JRE version? The one with that in the name of the file.

**Comment by masterpatje** [comment]
When I download HO-7.0.396.0-portable-win-DEV-JRE I got:
![image](https://user-images.githubusercontent.com/102049050/199972347-8ed5690e-7122-4610-88f8-eea3238dbfa0.png)

**Comment by masterpatje** [comment]
Also on updating the application did not close by itself. Just checked with HO6 version when auto-updating.
1) auto update via menu
2) choose direct installation
**3) application closes by itself**
4) asked to deinstall previous version
5) updated the version

So maybe with the portable version things works a bit differently when updating? Or there is something wrong with HO 7.0.369?

**Comment by Synthespian** [comment]
hey.
So ... 
1) yes, used JRE of course.  Maybe you looked after my edit of the post.  I said I used JRE, and then tested without JRE to see if it can find the JAVA.  It couldn't.  Neither version of SIX (6) portable works.  
2) auto-update doesn't close by itself but it did ask me to restart HO to apply changes, and nothing else.

your v7 issue is very similar to the error as posted on the item I linked.

**Comment by wsbrenk** [comment]
update failed !java.io.FileNotFoundException: C:\Users\wolfg\Documents\ho6-portable\.\.install4j\i4jinst.dll (Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
	at core.HOLauncher.update(HOLauncher.java:179)
	at core.HOLauncher.main(HOLauncher.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)
java.lang.UnsatisfiedLinkError: no awt in system library path: c:\users\wolfg\documents\ho6-portable\jre\bin
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2403)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
	at java.base/java.lang.System.loadLibrary(System.java:1989)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1388)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:1386)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at java.desktop/java.awt.Toolkit.loadLibraries(Toolkit.java:1385)
	at java.desktop/java.awt.Toolkit.initStatic(Toolkit.java:1423)
	at java.desktop/java.awt.Toolkit.<clinit>(Toolkit.java:1397)
	at java.desktop/java.awt.Component.<clinit>(Component.java:624)
	at core.HO.main(HO.java:141)
	at core.HOLauncher.main(HOLauncher.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:84)
	at com.exe4j.runtime.WinLauncher.main(WinLauncher.java:94)
	at com.install4j.runtime.launcher.WinLauncher.main(WinLauncher.java:25)

**Comment by chelodegli** [comment]
I'm having today the same issue as @Synthespian 
I updated with "auto-update" option from HO_3.0.2.2728.

My notebook is running on Windows 8.1 64bits.

What should I do to fix this? Thanks for your help.

**Comment by wsbrenk** [comment]
auto update of portable installation is defective. 

workaround: 

* download  [HO-6.1.384.2-portable-win-JRE.zip](https://github.com/akasolace/HO/releases/download/6.1/HO-6.1.384.2-portable-win-JRE.zip) (if you are on windows)
* open zip file with 7-Zip (File Manager)
* replace contents of your portable installation folder (do not delete your db subfolders)
  * best way would be to create a new folder with unpacked files and copy/move the db folders to this directory
 * start HO
 
if you replace files in existing portable installation folder, check that the file update.piz does NOT exist. Delete it if you find it in your installation (it is a relict of an buggy update)!

**Comment by masterpatje** [comment]
Confirmation, small addition:
- after copy-paste "db" folder 
- additionally copy "img" folder (in order to prevent hattrick from again downloading avatars en speeding up the process)
The method works.

**Comment by wsbrenk** [comment]
exclude .install4j folder from deletion. i'm not sure if the unpacking of .install4j from update packet will correctly replace the install4j files.

**Comment by wsbrenk** [comment]
cannot delete file animated-gif-lib-1.4.jar
cannot delete file annotations-23.0.0.jar
cannot delete file commons-lang3-3.12.0.jar
cannot delete file commons-logging-1.2.jar
cannot delete file commons-text-1.10.0.jar
cannot delete file darklaf-compatibility-3.0.2.jar
cannot delete file darklaf-core-3.0.2.jar
cannot delete file darklaf-iconset-3.0.2.jar
cannot delete file darklaf-macos-3.0.2.jar
cannot delete file darklaf-native-utils-3.0.2.jar
cannot delete file darklaf-platform-base-3.0.2.jar
cannot delete file darklaf-platform-decorations-3.0.2.jar
cannot delete file darklaf-platform-preferences-3.0.2.jar
cannot delete file darklaf-property-loader-3.0.2.jar
cannot delete file darklaf-theme-3.0.2.jar
cannot delete file darklaf-theme-spec-3.0.2.jar
cannot delete file darklaf-utils-3.0.2.jar
cannot delete file darklaf-windows-3.0.2.jar
cannot delete file fontbox-2.0.24.jar
cannot delete file graphics2d-0.32.jar
cannot delete file gson-2.9.0.jar
cannot delete file HO.exe
cannot delete file HO.jar
cannot delete file hsqldb-2.7.1.jar
cannot delete file install4j-runtime-8.0.7.jar
cannot delete file jackson-annotations-2.13.4.jar
cannot delete file jackson-core-2.13.4.jar
cannot delete file jackson-databind-2.13.4.jar
cannot delete file javatuples-1.2.jar
cannot delete file java.dll
cannot delete file jimage.dll
cannot delete file management.dll
cannot delete file management_ext.dll
cannot delete file net.dll
cannot delete file nio.dll
cannot delete file prefs.dll
cannot delete file jvm.dll
cannot delete file vcruntime140_1.dll
cannot delete file zip.dll
cannot delete file modules
cannot delete file jsoup-1.15.3.jar
cannot delete file jsvg-0.0.9.jar
cannot delete file kotlin-stdlib-1.6.20.jar
cannot delete file kotlin-stdlib-common-1.6.20.jar
cannot delete file kotlin-stdlib-jdk7-1.6.10.jar
cannot delete file kotlin-stdlib-jdk8-1.6.10.jar
cannot delete file logging-interceptor-4.10.0.jar
cannot delete file okhttp-4.10.0.jar
cannot delete file okhttp-tls-4.10.0.jar
cannot delete file okio-jvm-3.0.0.jar
cannot delete file pdfbox-2.0.24.jar
cannot delete file scribejava-core-8.3.2.jar
cannot delete file scribejava-java8-8.3.2.jar
cannot delete file swing-extensions-laf-support-0.1.3.jar
cannot delete file swing-extensions-visual-padding-0.1.3.jar
cannot delete file VectorGraphics2D-0.13.jar
cannot delete file xchart-3.8.1.jar
 [Info]    HO: VERSION: 7.0   versionType:  DEV   RevisionNumber: 405

**Comment by wsbrenk** [comment]
the exception happens when install4j is unpacked.

**Comment by wsbrenk** [comment]
JVM could not found when HO is restarted - the old jre was deleted and the new one not yet unpacked

**Comment by wsbrenk** [comment]
as far as i understand until now, the install4j does not support auto updates for archives (HO portables).

Idea: Disable the auto update option for portable versions. users of the portables should be able to update HO manually.
otherwise we have to reinvent the wheel (install4j)

**Comment by masterpatje** [comment]
I would go for disabling the auto-update function. 

Or maybe even better; when clicking the auto-update; give a pop-up message (or something similar) indicating that portable versions should be manually updated and the steps how to update it manually (downloading, unpacking, copying db (and img) folder from previous installation).

I am confident that you will present something suitable. 

And maybe you can have a long term project (on hold) for new people that want to do development work.

**Comment by Synthespian** [comment]
I agree. Disable. Definitely want a "new version is available" message. 
But then disable and correct install flow.

**Comment by wsbrenk** [comment]
updates are found and downloaded on request 
unpacking has to be done by hand.

**Comment by Synthespian** [comment]
Reoccured with the update to v7 today
Same error.
