### ISSUE TITLE
[BUG] poeditor project is archived

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1691]
no new releases of HO can be build

**Comment by wsbrenk** [comment]
@akasolace what do you think about removing dependency to poeditor tool? The contributions of the translators have gone down so far lately that we could handle this well via issues or pull requests in github.

**Comment by akasolace** [comment]
hi @wsbrenk what do you mean by PoEditor project is archived ? what exactly is the issue with it ? 
btw, I just approved 6 new contributors (they may have waited for a while )  ...

**Comment by wsbrenk** [comment]
hi @akasolace here is the mail i got from poeditor:

Hello Wolfgang,
 
Thank you for your email.
 
I have restored the project hosted on the account [thisisakasolace@gmail.com](mailto:thisisakasolace@gmail.com), so it should once again be accessible to those assigned to it. It was archived because the owner of the account hasn't logged in to their account for over 6 months.
 
Note that projects hosted on paid accounts don't get archived, even if the owner is inactive for a long period, so this is one way to avoid having the project archived again.
The owner of the project can also move the project to another account with more activity, from the project's settings: https://poeditor.com/kb/how-to-move-project-another-account

**Comment by wsbrenk** [comment]
Hi @akasolace, again the workflow build is broken, see (#1716). now it is because of lost dependencies in gradle plugins (poeditor and markdown tools). I'm looking for replacements.
Doing this in poeditor i found that i'm not able to approve translators anymore, since the project was restored. 
Do you agree to assign the owner account to me, to enable me to check all this?

**Comment by akasolace** [comment]
sure, and I would also suggest we transfer the github repo to you or to https://github.com/ho-dev

**Comment by wsbrenk** [comment]
@akasolace very good idea - but if we do so, we need a very good plan, how to move all the users (updaters) to the new repo-url. i think that the current repo has to live for a very long time than. recently i heared from users that still were using 1.4er versions.
