### ISSUE TITLE
[BUG] "Cup Draws for Round 2" Hattrick bug breaks training in HO

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#1714]
**Describe the bug**
Looking at https://www.hattrick.org/goto.ashx?path=/Help/SystemStatus/, there was a bug that made the HT redraw the cup match for week 2. Now that week 2 is over, once you download your data for your team, both the original drawn opponent and the actual opponent appear in the Matches tab.
One of the match will appear as having no line-up (which is normal, since the game didn't actually happen). Training for the week isn't computed, as this looks like a forfeit. Manually deleting the match from the list is enough to be able to compute the subskills again.

**To Reproduce**
Need recent data from one of Italy/Germany/Spain/Switzerland/Poland/Netherlands/France.
Since I already deleted my extra cup match, I don't think my .hrf would contain the needed data for debugging.

**Platform information:**
 - OS: [Windows / macOS / Linux] Windows
 - Version (including build number) 6.1

**Comment by wsbrenk** [comment]
@dominiquelee  this week i didn't download any wrong cup matches from HT. Maybe it was an error on HT side. I will check that.
