### ISSUE TITLE
[FEATURE] Configuration of training formula 

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1718]
* Calculate skill increase of training week (Schum's formula)
	 * T = f(lvl) * K(coach) * K(assist) * K(int) * K(stam) * K(train) * K(age) * K(time),
	 * Source:
	 * https://github.com/akasolace/HO/issues/250#issuecomment-541170338
	 * https://www87.hattrick.org/Forum/Read.aspx?t=17024376&v=4&a=1&n=5
	 * https://www88.hattrick.org/Forum/Read.aspx?t=17404127&n=9&v=6

The old configuration parameters are no longer used. The coefficients of Schum's formula are hard coded for now. 

2 Options:
* remove training parameter dialog and stay with hard coded formula coefficients
* provide new options to edit coefficients of Schum's formula

**Comment by akasolace** [comment]
@wsbrenk you want to remove the top part of the tab Training in Preference (but keep the miscealenous part), right ? : 

![image](https://user-images.githubusercontent.com/1136496/208183899-5a2077d1-6f3a-4c36-b523-1b31b5d5a5db.png)

**Comment by wsbrenk** [comment]
@akasolace you are right - i changed youth formula. it does no longer use this settings
