### ISSUE TITLE
[eBUG] lineup initialization ignores non official game

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#173]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by mistermax80** [comment]
@akasolace could you tell me more information?

**Comment by akasolace** [comment]
@mistermax80  if you download new data in HO it normally puts as lineup the next available lineup. But tournament match are ignored. Hence if your next games are ladder and then league. It will load the lineup of the league.

I think I know where the issue is coming from but I did not had time to check it.
You can look at https://github.com/akasolace/HO/blob/129d6ed435d3ea73873931b9a232613f03d0352b/src/main/java/core/file/xml/ConvertXml2Hrf.java#L177
