### ISSUE TITLE
[BUG] POEditor integration is broken

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#1737]
new strings in english.properties are not pushed to poeditor anymore

**Comment by wsbrenk** [comment]
@akasolace could you fix this - i'm not able to do it

**Comment by akasolace** [comment]
I will have a look ...

**Comment by akasolace** [comment]
@wsbrenk  should be fixed ... I let you check !

**Comment by wsbrenk** [comment]
new terms are pushed - well done
