### ISSUE TITLE
[BUG] Hattrick down and matches

### ISSUE THREAD

**Issue by masterpatje** [akasolace/HO#1738]
Hattrick proposed a solution that matches will be played today that were set for last couple of days. After the match is played the match will be set to original date of the match.

This solution might influence this week downloads. I will not risk downloading hrf files during this periode, but thought I might post this as an potential issue. For example if a match is included on thursday but later is visible as a tuesday match how wil HO cope with that.

Because only today you can test it I thought I would reach out so that you can explore what happens.

**Comment by wsbrenk** [comment]
- CHPP was shut down so save resources. This results in external applications do not work properly (e.g. HT youthclub, NT tracker, ...) [(17518541.138)](https://www82.hattrick.org/Forum/Read.aspx?t=17518541&n=138&v=4&mr=0)

no chance!
