### ISSUE TITLE
Can't download to update - Hattrick Organizer 6.1

### ISSUE THREAD

**Issue by Bojoangel** [akasolace/HO#1739]
**Describe the bug**
Once I start the download procedure to update with the new matches and training, I get an HTTP Response Code 404. I have been getting this code since a long time, but I pressed always OK and could proceed.
What is new now is that a second warning window appears with a generic  An error occurred 
and I cannot go further than that.
The error describes as:
Cannot invoke "org.w3c.dom.Document.getDocumentElement()" because "doc" is null
I press on the down button and a long list appears, first line reads (partial):
at core.file.xml.XML,TeamDetailsParser,getTeamInfo .... etc.etc.

**Platform information:**
 - OS: Windows 10 Home 
 - Version 21H2 OS build 19044.2251

Available for any further clarifications.
Thank you
Bojoangel

**Comment by wsbrenk** [comment]
- CHPP was shut down so save resources. This results in external applications do not work properly (e.g. HT youthclub, NT tracker, ...) [(17518541.138)](https://www82.hattrick.org/Forum/Read.aspx?t=17518541&n=138&v=4&mr=0)

this is also true for HO!
