### ISSUE TITLE
[BUG] I cannot update the data of my team.

### ISSUE THREAD

**Issue by iivan92** [akasolace/HO#1743]
**Describe the bug**
I cannot update the data of my team. The download feature is giving me an error.

**To Reproduce**
1. Go to File -> Download
2. Click on Download
4. See the error

**Screenshots**
<img width="562" alt="Screenshot 2022-12-13 at 13 05 51" src="https://user-images.githubusercontent.com/3332003/207313440-eb1607b8-5f2b-429e-bb4f-c882e361c7b1.png">

**Platform information:**
 - OS: macOS
 - Version 6.1.384.2 (6.1.384.2)

**Comment by markdoubgr** [comment]
The same thing is happening to me

**Comment by l3dz3pp** [comment]
same error here :(

**Comment by wsbrenk** [comment]
the workaround will still show the chpp error message as long as it is not fixed on ht side, but it will continue working with previously downloaded world details.

**Comment by Mojexi** [comment]
I get the same error
![image](https://user-images.githubusercontent.com/100917089/208068347-7e2e3549-406e-4206-9c86-a3630a3af428.png)

**Comment by wsbrenk** [comment]
HT has fixed it
