### ISSUE TITLE
Cannot download the data from the site!

### ISSUE THREAD

**Issue by Mofli10** [akasolace/HO#1745]
Hi,
Tried to load the data from the program, but had a error when download.

1. File
2. Download

![Erro 2](https://user-images.githubusercontent.com/120137860/207692088-e746206c-e2b2-4c08-af8d-6429d93ea1ae.png)
![Erro](https://user-images.githubusercontent.com/120137860/207692093-14c8e9b0-59df-43c2-9e8d-866aad6670bd.png)

Regards

**Comment by wsbrenk** [comment]
same as #1743
