### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by l3dz3pp** [akasolace/HO#1746]
**Describe the bug**
I cannot download HRF file, it returns some java error

**To Reproduce**
1. hit download 
2. errors from screenshot appear

**Screenshots**

**Platform information:**
 - OS: [Windows10]
 - Version 22H2 (OS Built 19045.2311)

**Additional context**

I tried all versions (last stable and beta), with JRE included. I tried erasing db, even erasing the whole directory and cleaning registers...updated java...but no other result.

![error_1](https://user-images.githubusercontent.com/28995637/207713043-99d67647-f83d-4648-8c84-6bb194da0efe.jpg)
![error_1 1](https://user-images.githubusercontent.com/28995637/207713081-cec94a9e-4e62-423d-97fa-58604ad385e0.jpg)
![error_2](https://user-images.githubusercontent.com/28995637/207713113-97f78ef6-400a-430b-98b1-5c7e07fdb6e4.jpg)

**Comment by wsbrenk** [comment]
same as #1743
