### ISSUE TITLE
[BUG] No parameterless constructor defined

### ISSUE THREAD

**Issue by tomtret** [akasolace/HO#1748]
Hi, I have problem, cant download anything. Every time I got message:

[https://i.imgur.com/HflZuYd.png)](https://i.imgur.com/HflZuYd.png](url)

Here is log HO:
[
https://drive.google.com/file/d/18umHUuxYWw05...aring)](https://drive.google.com/file/d/18umHUuxYWw05P6A2xLcF5wiN2yqg2DVp/view?usp=sharing](url)

**Comment by tomtret** [comment]
Didnt see that problem was already reported.

**Comment by rosvid** [comment]
I have the same problem since today.
