### ISSUE TITLE
[FEATURE] Improve first start experience

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#1760]
**Is your feature request related to a problem? Please describe.**
When starting HO for the first time, the experience is somewhat bad, as the application spends an awfully long time downloading past lineups and logos. 

This is in particular confusing because there is a lot of work going on in the background, despite the progress bar being full.

**Describe the solution you'd like**
We could first download the team players, and give interactivity to the user, so they can look at their players, and in the background download the missing records.  This would require some refactoring as to how data is downloaded from CHPP, which would not be a bad thing. :-)

**Additional context**
N/A

**Comment by wsbrenk** [comment]
Default of "Export" directory selection should be changed from c:\ (which might not be accessible) to something like %APPDATA%/HO/hrfs

**Comment by wsbrenk** [comment]
@tychobrailleur improve first download experience (the start of an empty HO happens very fast;-)

**Comment by tychobrailleur** [comment]
> @tychobrailleur improve first download experience (the start of an empty HO happens very fast;-)

Correct, although when I say first start, I think of the app as a whole when using for the first time.  But yes, in particular that first download! ;-)

**Comment by wsbrenk** [comment]
the complete transfer history of the team is downloaded when transfer panel is refreshed. this is not really part of the standard download.

removing the transfer module from auto startup list makes the first download much faster.
