### ISSUE TITLE
HatStats Discrepancies agains Fox trick? Which is correct? HO or them?

### ISSUE THREAD

**Issue by Tarotistas** [akasolace/HO#1778]
**Describe the bug**

**To Reproduce**
1. Go to '...' Aligment
2. Click on '....'HatStats
3. Scroll down to '....'Down
4. See HatStats 403 using

**Screenshots**

**Platform information:**
 - OS: [macOS]
 - Version (Ventrue 13.1)

Foxtrick HatStats
**Additional context**
<img width="490" alt="image" src="https://user-images.githubusercontent.com/65875612/210659366-253e8b1b-41a8-44e2-8490-0f613a40e6fa.png">

HO HatStats
<img width="551" alt="image" src="https://user-images.githubusercontent.com/65875612/210659653-3963d095-4d5f-4b11-9ed2-34c6898c4308.png">

**Comment by Tarotistas** [comment]
Running HO 6.1

**Comment by wsbrenk** [comment]
a little bit better will it be if you select the minute 0 of the HO rating panel
another improvement could be to use the old rating prediction: Simulator->rating prediction type->Old

it is still not perfect and i'm currently looking for a better solution

**Comment by wsbrenk** [comment]
found that the team spirit influence seems to be wrong in HO prediction. Replaced it with the numbers found in [schum's thread](https://www88.hattrick.org/Forum/Read.aspx?t=17404127&n=62&v=0&mr=0)
