### ISSUE TITLE
POEditor and contributing

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#178]
Hi,
I tried to clone my fork of the master repository in order to create a project.

The issue I had, related to "POEditor": build.gradle needs for a value (or a reference) for "POEDITOR_APIKEY" in order to continue to build.
By commenting that row I was able to build the project.

I don't know either this is the right way to proceed or not, but the real solution should be mentioned in the "How to contribute" section.

**Comment by akasolace** [comment]
agree. 
you are not the first one to struggle on that part. The doc should be updated

**Comment by pierpaolocira** [comment]
@akasolace we might create a page with some FAQs on how to set the project up... I have a few that could be really helpful for MacOS users... then the page could grow slowly.
Give me the link in case you think it can be done this way.

**Comment by akasolace** [comment]
@pierpaolocira don’t you want to create a wiki page? You can create one and do a PR or you can wait few days and I will give you writing rights to the wiki this weekend when I am back from my hollidays 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pierpaolocira** [comment]
@akasolace I never worked with PR and Wiki pages, and I don't have time today to see how to do.
Please, you can find the new "FAQ" page, and a small change of the "Contributing-to-HO" page into my fork at (https://github.com/pierpaolocira/HO/wiki/FAQ) and (https://github.com/pierpaolocira/HO/wiki/Contributing-to-HO).
Feel free to port them into the main Wiki and/or to edit the content as you prefer.

**Comment by akasolace** [comment]
Done, thank you !

**Comment by pierpaolocira** [comment]
Anyway, when you have time, please give me rights on the Wiki... ;)
