### ISSUE TITLE
Download lineup comes Black while PUSH

### ISSUE THREAD

**Issue by Tarotistas** [akasolace/HO#1789]
**Describe the bug**
While push Download lineup button HO 6.1 becomes full blank and no lineup updated from HT.

**To Reproduce**
1. Go to Alienation (ES)
2. Click on Download lineup
3. Scroll down to 
4. See lineup that becomes totally blank 

**Screenshots**
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/65875612/216774798-38dffd3b-9298-4610-ae12-c1144e1ca9da.png">

**Platform information:**
 - OS: [macOS ]
 - Version (Ventura 13.1)

**Additional context**

**Comment by wsbrenk** [comment]
same as #1788
