### ISSUE TITLE
[eFEAT] Feedback plugin should also collect and send to the database injury status (healthy, bruised ..) 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#179]
Feedback plugin should also collect and send to the database injury status (healthy, bruised ..)  as it might introduce a bias in regression analysis

**Comment by akasolace** [comment]
@mistermax80  this one is trivial on client side but I am not sure how much work it is on server side.

**Comment by mistermax80** [comment]
@akasolace in the jsonobject already send the field m_iVerletzt --> week injuried, I must check that value in case of plaster
Do you have a player in this status, could you please sent a feedback using that player?

**Comment by akasolace** [comment]
@mistermax80 

I just tried but I got an error message. The data has not been successully sent ... 
Unfortunatly I have no time to invetiguate at the moment. Maybe someone else can confirm the error.

**Comment by akasolace** [comment]
@mistermax80  I tested it again and the error still exist !

**Comment by akasolace** [comment]
@mistermax80 you can obtain the player injury status by calling getVerletzt()
the result is an integer that you can simply store along others player information.

**Comment by mistermax80** [comment]
In JSON object already present that info, so it is not need call that function

**Comment by mistermax80** [comment]
The new server has been updated with this information.
https://hofeedback.000webhostapp.com

**Comment by akasolace** [comment]
@mistermax80 can I close this one ?

**Comment by akasolace** [comment]
closed by 79a7c45ef8c16fc8d6915effd37af63491c01073
