### ISSUE TITLE
Minor request for older people

### ISSUE THREAD

**Issue by henkHV** [akasolace/HO#1805]
Hey, Still a great job what you do with HO.
Just minor question, In the tab teamanalyzer is it possible to make the box with the info of the players adjustible?
When using font size 16
They are a little small to see all the info or name of the player.
It's just for people of my age going to the sixties.

Using font size 14 they're ok but not for 16

Grtz,
H.

**Comment by wsbrenk** [comment]
Many layouts should be adjusted for font size 16

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/221349619-3f614982-31fa-4343-941d-e0cb1d586415.png)

download dialog layout with font size 16 is not OK!

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/221357597-6773ae85-054b-4b1d-bcfb-c814e0ce7f6a.png)

settings dialog layout with font size 16 is not OK
