### ISSUE TITLE
[BUG] Error when downloading to HO

### ISSUE THREAD

**Issue by Megalo1** [akasolace/HO#1808]
**Describe the bug**
The download process takes very long and an error message is displayed.

**To Reproduce**
1. Go to file download
2. Click on download
3. Wait for over 3 minutes
4. See error herunder

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

![Error dowloading to HO](https://user-images.githubusercontent.com/126357656/221379272-34b42527-2499-4e0d-a047-190b5fd213f8.JPG)

**Comment by wsbrenk** [comment]
info from HTs: archive database is offline this week due to server move, this affect chpp too, so the status is normal for now

**Comment by Megalo1** [comment]
Ok, I see, Thanks..
