### ISSUE TITLE
[BUG] HRF file does not update sub skills

### ISSUE THREAD

**Issue by Maestrololz** [akasolace/HO#1811]
**Describe the bug**
When downloading the HRF file no sub skills are increased.

**To Reproduce**
1. Go to 'File -> download'
2. Click on 'save'
3. Compared to the training last week no change (except for the skill pop)

**Screenshots**
https://snipboard.io/pWqvVj.jpg

**Platform information:**
 - OS: Windows 10

**Additional context**
Didn't see this since the last HRF update.

**Comment by wsbrenk** [comment]
@Maestrololz could you please check, if there are logs from that session showing some error logs? And please check in the training tab if your last training info was downloaded correctly.

**Comment by Maestrololz** [comment]
I haven't seen any errors. Where can I check for that log? The training info seems to be downloaded correctly, no odd stuff showing up.

**Comment by wsbrenk** [comment]
the name of the log file folder depends on the installer kind:

windows-installer: %APPDATA%/HO/logs
portable installer: subdirectory ./logs of your installation path

**Comment by wsbrenk** [comment]
concerning treining: please verify the entries in past training table in the training panel.

**Comment by Maestrololz** [comment]
[error.log](https://github.com/akasolace/HO/files/10891982/error.log)
[HO-2023-03-03.log](https://github.com/akasolace/HO/files/10891983/HO-2023-03-03.log)
[output.log](https://github.com/akasolace/HO/files/10891984/output.log)
![screenshot training](https://user-images.githubusercontent.com/126835099/222965712-d98fd217-0acf-4c6e-a16c-35eb6728f8b1.JPG)

I have added what I could find.

**Comment by wsbrenk** [comment]
@Maestrololz thanks - the log helped. Issue should be fixed in new beta

same as #1803
