### ISSUE TITLE
[BUG] Players subskills of trained skills don't get updated after the training 

### ISSUE THREAD

**Issue by manguz** [akasolace/HO#1817]
Hi, I'm training passing so 16 players, and the passing skill don't get updated by the formula after the training.
This happens to me from quite a long time , maybe last version I saw working was 5
May be database upgrade issues? I use old database for my old teams
here's a log

Thanks for you time

[HO-1678402967.log](https://github.com/akasolace/HO/files/10944732/HO-1678402967.log)

**Comment by wsbrenk** [comment]
thanks a lot, will fix it as soon as possible

**Comment by wsbrenk** [comment]
@manguz please try again with new beta (470) and check the log of the first session to verify if database upgrade logs errors.

**Comment by manguz** [comment]
I reverted pre training database and tried 470, still no passing subskill increment, only skillup are shown
I see no errors now
thank you
[HO-1678476552.log](https://github.com/akasolace/HO/files/10945335/HO-1678476552.log)

**Comment by wsbrenk** [comment]
if you would upload the pre training database i could try to debug this.

**Comment by manguz** [comment]
sure, here it is
[db_user-2023-03-08.zip](https://github.com/akasolace/HO/files/10945534/db_user-2023-03-08.zip)

**Comment by manguz** [comment]
Sure, but is it safe to upload the database here?
If not, I can send you a google drive link for email
Thanks

**Comment by wsbrenk** [comment]
You should trust me when you provide me with your database. I will delete them from this thread once I download them so that no one else can get them.

**Comment by wsbrenk** [comment]
If you want to make sure that I can't access your team anymore, you can re-establish the Ht connection for the HO after I'm done debugging.

**Comment by manguz** [comment]
Sure, No problem. Let me know if you need anything else
Thanks for your work

**Comment by wsbrenk** [comment]
i think i found it:

Due to the error i fixed above, the lineups of your last matches were not stored. To fix it 
go to tab Incontri
select a list of matches were no players are shown in the lineup
push refresh button at the bottom on the left side.

this should reload the lineups. A recalculation of the subskills should fix the subskills

**Comment by manguz** [comment]
A selected a batch of game with empty lineup and only one got updated (the last cup game)
I have errors :(
[HO-1678481844.log](https://github.com/akasolace/HO/files/10946126/HO-1678481844.log)

**Comment by manguz** [comment]
wait! now it's working! I first redownload old series game data from "file -> download -> misc -> old series data" for last 3 seasons, then the game download started working

**Comment by manguz** [comment]
Some lineups fail to download still, but they are old tournaments games so not a big deal I think, here's the relevant part

Here is the log of this failure, maybe data are not on HT anymore

[HO-1678483084.log](https://github.com/akasolace/HO/files/10946218/HO-1678483084.log)

**Comment by wsbrenk** [comment]
you're right - match is no longer in your match archive. checked your match on November 3rd 2022.

**Comment by manguz** [comment]
I made same procedure for another instance of 470 with my anniversary team that had same problem:
Redownloaded all old season data, checked lineups (they were there in this case, data were starting from HO 5), recalculated training and all good!
Main team DB instead started from HO 4 and travelled through all versions, lol, and was really messed up.
Thank again for your help and your work!
