### ISSUE TITLE
[eBUG] Not correct building if it is launched from a branch

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#182]
This happens if you have a branch, e.g. HO-xxx and try to build the MacOSX executable.
Then into ./build/macApp you'll find both:
- HO-xxx.app - containing all the effective content for the application (I guess created this way by the macAppBundle plugin)
- HO.app - containing only the file changelog.html (this is manually done in the task `AddResourcesAndZipMacApp`)

This should not be problematic because I imagine release are preparred from the main (only `HO` branch), but build.gradle should be fixed in order not to propagate the issue in case of new features based on the same gradle code.

**Comment by akasolace** [comment]
@pierpaolocira,  I guess the idea is to fix AddResourcesAndZipMacApp and to copy file in HO-xxx.app, right ?  Do you have an idea on how to do this?

**Comment by pierpaolocira** [comment]
> @pierpaolocira, I guess the idea is to fix AddResourcesAndZipMacApp and to copy file in HO-xxx.app, right ? Do you have an idea on how to do this?

@akasolace no, as tolt I'm not an expert with Gradle... but if noone else has time for it, I can try to solve. Please, let me know.

**Comment by akasolace** [comment]
closed by #193
