### ISSUE TITLE
[BUG] wrong "best position

### ISSUE THREAD

**Issue by solimar1963** [akasolace/HO#1822]
in the player overview tab, under the "Skilltester" tab, the "Best position" is always displayed as "Goalkeeper" for existing players.

**Comment by wsbrenk** [comment]
![skilltester](https://user-images.githubusercontent.com/11821502/224819302-0ba5d671-0ef9-4fa8-8539-d8a2e7d8a691.jpg)

i will add the relative rating value (normalizing factors can be set in settings->formula), since this value is used to select the best position not the absolute value.

**Comment by solimar1963** [comment]
It works.
