### ISSUE TITLE
[eBUG] Dev can't send "automatic" lineup 

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#183]
**Describe the bug**
Using button "start assistant", I can't send the lineup right after

**To Reproduce**
1. Go to 'Lineup tab'
2. Click on 'button "start assistant"'
3. Go to 'Upload/Download sub-tab'
4. Click on 'Upload Lineup"
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/62000560-f49f8e80-b0d9-11e9-90dd-1f933d73ea09.png)
the second sentence is in french ???

**Platform information:**
 - OS: [Linux]
 - Version (Ubuntu 16.04)

**Additional context**
Workarround is to change a player on the bench ( add an extra, add a slot 2, change a player from slot 1 (we can back to previous player after))

**Comment by akasolace** [comment]
@DavidatorusF  I just test it and I confirm the bug
I do not have the issue with translation thought
