### ISSUE TITLE
[eBUG] DEV copy "lineup and ratings"

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#185]
**Describe the bug**
little bug using copy "lineup and ratings" in lineup up right

**To Reproduce**
1. Go to 'Lineup tab, windows ratings'
2. Click on 'copy button -> lineup and ratings'
3. Past on HT

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/62006590-cdc97280-b142-11e9-87bf-45be0451757d.png)
then how it look once post on HT
![image](https://user-images.githubusercontent.com/45043004/62006609-141ed180-b143-11e9-9858-ab0624997797.png)

**Platform information:**
 - OS: [Linux]
 - Version (Ubuntu 16.04)

**Comment by akasolace** [comment]
@DavidatorusF  I did not know that functionality ...

**Comment by yaute74** [comment]
I will treat it

**Comment by akasolace** [comment]
closed by #189 (@yaute74 )
