### ISSUE TITLE
[BUG] Phänomen Arabic script ;)

### ISSUE THREAD

**Issue by peppermil** [akasolace/HO#1856]
again and again the arabic numbers come back ;)

this time on the salary as well as on the income and expenses on the "various" tab. The same applies to the currency designation for "transfers".

usern.json file:
[
  {
    "teamName": "Lozärner Löwen 04",
    "dbName": "db",
    "clubLogo": "C:\\Users\\data\\AppData\\Roaming\\HO\\img\\clubLogos\\465805.JPG",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "Lucerne Lions 13",
    "dbName": "db2",
    "clubLogo": "C:\\Users\\data\\AppData\\Roaming\\HO\\img\\clubLogos\\2013751.jpg",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "Lucerne Lions 20",
    "dbName": "db3",
    "clubLogo": "C:\\Users\\data\\AppData\\Roaming\\HO\\img\\clubLogos\\2065118.jpg",
    "backupLevel": 3,
    "isNtTeam": false
  }
]

Windows 11
HO Version: in the new Stable Version 7.0 and in the last Beta Version HOSetup-7.0.487.1-BETA-JRE

Pictures:

![arabic_1](https://user-images.githubusercontent.com/88058929/234118237-8175fecf-f03f-41a8-96aa-d2f609e794ac.jpg)

![arabic_2](https://user-images.githubusercontent.com/88058929/234118275-c2e59aa4-7d16-49eb-89b3-82191c747549.jpg)

![arabic_3](https://user-images.githubusercontent.com/88058929/234118327-469b53b7-71c4-46ea-aedb-8cac26278aae.jpg)

Sorry an thanks
pepper

**Comment by wsbrenk** [comment]
Damn it - where did I get there again?

Could you provide me with your team's DB again so I can debug this?

**Comment by peppermil** [comment]
Voila - thanks

https://1drv.ms/u/s!AjKUl1nPppPXj5oK0p2GX44d3spfgw

**Comment by wsbrenk** [comment]
thanks

**Comment by peppermil** [comment]
i thank you
