### ISSUE TITLE
[BUG] Damaged file error while downloading team data

### ISSUE THREAD

**Issue by ale-pavel** [akasolace/HO#1861]
**Describe the bug**
When trying to download the team data a "Damaged File" error appears (after downloading players' avatars). In particular the exception is the following:

> [Error]   HRFStringParser: Cannot invoke "module.lineup.substitution.model.GoalDiffCriteria.getId()" because the return value of "module.lineup.substitution.model.Substitution.getStanding()" is null

This only happens with my first team (Italy), and not with my second HTAL team. 

I tried selecting less data to download, and starting from a fresh database and the result is the same. I tried downgrading to the last 6.0 HO version but the DB (which was written by HO 7) isn't compatible and asks to install HO >3.0. 

**Using HO 6.0 stable with a fresh database works**, but I lost all the data I had since it can't be imported.

**To Reproduce**
1. Go to 'File'
2. Click on 'Download', again 'Download'
4. Error appears

**Screenshots**
![immagine](https://user-images.githubusercontent.com/27208682/235250254-9905c0fd-3220-43dd-a845-b09ae721eed8.png)

**Platform information:**
 - OS: Windows 10
 - Version 7.0 Build 489

**Comment by wsbrenk** [comment]
HO6 cannot run with database of HO7. If you downgrade from HO7 to HO6 you have to restore an backup of an HO6 database. in standard installations on windows you find them in %APPDATA%/HO/db*/*.zip

**Comment by ale-pavel** [comment]
I noticed that, unfortunately all backups were from HO7 so I reinstalled HO6 and manually entered all decimals from some screenshots I took of the last downloaded HRFs.

The issue does not appear in HO6, and strangely enough HO7 worked fine for a few weeks I think (and still worked for the second team only). Maybe it also has to do with the automatic renaming of some assets' paths when publishing version 7.1:

`[Error]   core.net.MyConnector: https://github.com/akasolace/HO/releases/download/tag_stable/version.properties
`

The path is now /download/7.0/version.properties. Also this error did not appear again in the logs, so it's just an idea.

**Comment by wsbrenk** [comment]
@ale-pavel i just rebuilded the HO stable version. the installer should find the version.properties now.

the new beta tries to fix the error you reported. but i'm not quite sure. would be great if you could run a test with beta 7.1.
if you do so, please check the log file, if there are errors reported.

**Comment by ale-pavel** [comment]
@wsbrenk I tested both 7.1 and 7.0 and they worked fine. Checking the 7.1 logs doesn't show any errors either. I tested with a fresh DB and with my existing 6.0 one.

Not sure if installing 6.0 -> 7.1 -> 7.0 fixed the 7.0 issues, or if it was the properties asset being fixed. I guess **you can close the issue** (reply if I have to instead).

Also another user in the forums mentioned the issue being gone at 15:20 UTC+2 without doing anything (he installed 7.1 the 28/4 morning I think, does it update automatically under the hood?).

**Comment by wsbrenk** [comment]
thanks!
