### ISSUE TITLE
[RLS] stable link not updated to last 1437

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#187]
**Describe the bug**
stable link is not updated to last 1437

**To Reproduce**
https://github.com/akasolace/HO/releases/tag/stable go to HO_1.437.2.1076

even if we have an HO_1.437.2.1081 here https://github.com/akasolace/HO/releases/tag/1.437

**Comment by akasolace** [comment]
I copied the artefacts from 1.437 into stable.
