### ISSUE TITLE
[BUG] Not able to set future trainings

### ISSUE THREAD

**Issue by UNIKR0N** [akasolace/HO#1889]
**Describe the bug**
Brief description:
The "Training" / "Future trainings" / "Edit All" button does not work for me (in both portable and installed versions of HO)

Description:
I've returned to Hattrick on the 30th of June, completely new team, new account, fresh start after almost 2 decades of not playing the game. The first thing I've done was to download the latest version of HO (both portable and installed versions) and everything seems to be working fine, except when I click the "Training" / "Future trainings" / "Edit All" button and the "Edit all future trainings"  dialog pops up, it is not able to set my future trainings.
I've tried different combinations in the dialog and I've also waited my first training to take place, but the issue still persists.
I've also tried changing the number of weeks for future trainings in the Preferences, but still no luck.

**To Reproduce**
1. Go to 'Trainings' tab.
2. Click on the 'Edit All' button in the "Future trainings" section
3. Fill out your training of choice (for me it is Playmaking, 95% intensity, 20% stamina, coach 4, assistants 5)
4. Click the "Apply" button
5. Nothing happens visually, however in the log file I have a ton of errors regarding the training.

**Screenshots**
![image](https://github.com/akasolace/HO/assets/134159637/7a6191ea-dae6-4808-9877-c2b22654a07e)
![image](https://github.com/akasolace/HO/assets/134159637/adf829dc-391e-4494-8f16-142c991b4bf3)
![image](https://github.com/akasolace/HO/assets/134159637/37a7ddd0-ef9f-4213-a4be-b9da6bdee7f0)

**Platform information:**
 - OS: Windows
 - Version 11 22H2, Build: 22621.1848

**Additional context**
[HO-1688729915.log](https://github.com/akasolace/HO/files/11981598/HO-1688729915.log)
[output.log](https://github.com/akasolace/HO/files/11981602/output.log)

EDIT1:
More precisely specified my OS version
EDIT2:
I've asked the person who invited me to play to check his HO and the future trainings list is not populated for him either.
In the meantime I've also tested a 7.0.494.2 portable version and it's the exact same thing in that too.

**Comment by UNIKR0N** [comment]
Hi,
I've tested the following versions and all seem to have the same behaviour (future trainings list is not populated, 5.2 even pops up an error trace)

- 5.2.3945.2-portable
- 6.0.368.2-portable
- 7.0.494.2-portable
- 7.1.506.2-portable
- 7.1.506.2-installer

Could it be related to my team/country/timezone settings? I've changed my computer's timezone settings to reflect my team's timezone, but no luck.

Am I doing something horribly wrong?

Any help is much appreciated!

**Comment by wsbrenk** [comment]
@UNIKR0N Unfortunately, I can't reproduce that with my teams. if you could upload your database (the backup zip file) here, I could try to debug it.

**Comment by UNIKR0N** [comment]
@wsbrenk thank you for your time and effort!

[db_user-2023-07-08.zip](https://github.com/akasolace/HO/files/11990683/db_user-2023-07-08.zip)

**Comment by wsbrenk** [comment]
downloaded and deleted from this thread (no one else can download it)

**Comment by wsbrenk** [comment]
![image](https://github.com/akasolace/HO/assets/11821502/70acac60-4e3b-4ed1-8aef-ee0dab5e6687)

i fear the hattrick changes concerning trainer are causing this error. Hacking your database gives this result.

**Comment by UNIKR0N** [comment]
Is there anything else I can provide to help with the troubleshoot?
Also, do you have any recommendation on how could I fix it? (even if it's just a workaround for now)

**Comment by wsbrenk** [comment]
please give me some information about your trainer  - i could not find it on hattrick. i suspect you have one of the new trainer types introduced this season?

**Comment by UNIKR0N** [comment]
![image](https://github.com/akasolace/HO/assets/134159637/8ed41e90-1305-4d94-b151-6af5ad33dab5)
https://www85.hattrick.org/Club/Specialists/Trainer.aspx?teamId=303172&trainerId=477614136

**Comment by wsbrenk** [comment]
thats it - oliver is not listed as a player in your team. the older trainers are still listed as players. i hope i can find how to access the trainer attributes with the chpp api.

**Comment by UNIKR0N** [comment]
🫰
and thank you for looking into it so quickly!

**Comment by wsbrenk** [comment]
found a way to download attributes of new trainers

**Comment by wsbrenk** [comment]
still testing:

your database now contains wrong datasets of your trainer. i hope to release a new beta version (7.2) tomorrow. 
then 
* you have to download your data (F11)
* delete all hrfs of your latest training week ( see picture)
* download your data again

after that your future training table should show data records

![image](https://github.com/akasolace/HO/assets/11821502/8c2b4fbd-54a4-4737-aca7-b914bf4013b1)

**Comment by wsbrenk** [comment]
for the first, your coach can still be included in an HO lineup - don't know what happens if those lineups will be uploaded. 
I will fix this "feature" in the next major release (8.0).

**Comment by UNIKR0N** [comment]
@wsbrenk wow, I did not expect you to release a fix in such a short time, but you have my undying gratitude!

I've done two test cases:
Test1#: freshly unzipped beta 7.2 r508 with new DB
Result: works perfectly 

Test#2: I've copied over the DB folder and followed the steps as you described
> Download, Delete HRFs between today and 6th of July, Download again
Result: I can see the future trainings, I can change them, works as expected 🥳

Let me know if you need the any files or other test to be conducted, I am more than happy to do so.
Brilliant work! Thank you!

**Comment by wsbrenk** [comment]
@UNIKR0N started working on  #1891. would be great if i may use your database for testing and debuging. When I'm ready you should reestablish the HO authorization of your team. Then I'm no longer able to access your team.

**Comment by UNIKR0N** [comment]
@wsbrenk 
[db_user-2023-07-09.zip](https://github.com/akasolace/HO/files/11995250/db_user-2023-07-09.zip)
Feel free to use it as long as you deem it necessary :)
