### ISSUE TITLE
BUG Next Training with new team

### ISSUE THREAD

**Issue by Sciaqquazza** [akasolace/HO#1899]
**Describe the bug**
Next Training prevision with new team does not work

**To Reproduce**

**Platform information:**
 - OS: Windows
 - Version  22H2

**Additional context**
![Immagine 2023-07-26 183812](https://github.com/akasolace/HO/assets/62815315/2337c41e-558d-40ec-b9d2-6b24d022b974)

**Comment by wsbrenk** [comment]
same as #1889?

Did you test with newest version? 7.2?

**Comment by wsbrenk** [comment]
After deleting HRFs of current training week which were downloaded with previous HO versions, the analyze panel and effect panel no longer displays the player skill ups.

**Comment by ale-pavel** [comment]
> same as #1889?
> 
> Did you test with newest version? 7.2?

I have the same issue with my HAL team, updating from 7.1 Beta to 7.2 Stable didn't fix the issue. Which version tries to fix the issue and needs testing?

**Comment by wsbrenk** [comment]
@ale-pavel after updating to 7.2 (or later, 7.3beta e.g.) you have to download again (F11). After that you have to delete all downloads of the current training week, which were downloaded with the previous HO versions.
(See [here](https://github.com/akasolace/HO/issues/1889#issuecomment-1627507954))

Deleting the downloads also deletes the skillups dispayed in training analyze panel and effect panel too.
This can be repaired with latest beta (HO7.3) with the subskill recalculation feature.

**Comment by ale-pavel** [comment]
@wsbrenk doing the 3 steps fixed my issue with 7.2, I only had to delete one .hrf file.

Thank you.
