### ISSUE TITLE
HO 7.2 - Issue Next match not visible

### ISSUE THREAD

**Issue by Tarotistas** [akasolace/HO#1903]
**Describe the bug**
Issue Next match not visible

**To Reproduce**
1. Go to '...' Alineacion
2. Click on '....' Select Match
3. Scroll down to '....' Check the match list 
4. See error Top match MUST be the right coming match

**Screenshots**
<img width="540" alt="image" src="https://github.com/akasolace/HO/assets/65875612/982136b1-e45c-410f-84d7-66b13af421bd">

**Platform information:**
 - OS: [macOS Ventura 13.5]
 - Version (Ventura 13.5)

**Additional context**

**Comment by wsbrenk** [comment]
@Tarotistas is the match in PRAC united still missing if you download again from Hattrick (F11)?

**Comment by Tarotistas** [comment]
You are right! Please dismiss this issue.
