### ISSUE TITLE
[eFEAT] NT Tactics needs extended style of play / coach type options

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#191]
When reviewing a lineup in HO, the attacking or defending options are set by the style of the coach.
In the NT lineup in HT, you are able to set a slider (in 10% sections) from 100% defending up to 100% attacking.  These adjust the ratings in attack and defence.
In HO there is no way to re-create that.

Suggestion:
* Have at least a 100% defensive, normal and 100% offensive (this matches the three style of coaches)
* Extend to enable variation by 10%.

![NT_Slider](https://user-images.githubusercontent.com/48737160/62736337-057ac900-ba25-11e9-9447-081824daa1c1.jpg)

**Comment by akasolace** [comment]
@Synthespian   is it not what coach type and style of play options are for ? If not please give us some additional information

**Comment by Synthespian** [comment]
Damn.  Sorry. I've said it very badly.
No wonder you were confused. :)

**Coach** = Current coach style (e.g. 100% offensive) and cannot be changed even for a club team.  It has to be neutral for an NT team as there is no coach.
**Style of Play** currently, for a normal club team, allows you to override the style (either attacking, normal or defensive) to review how that might change your team's ratings when choosing your next coach.  When you try the same on an NT team, it doesn't allow you to make the change, and stays on "neither attack nor defence minded" no matter which option you click.

I would suggest the following requirements:
Enable NT coaches to change the defaulted **Style of Play** value to any of the three 100% offensive, normal (balanced) or 100% defensive to see the impact that a change to their coach could make.  This allows NT users a bit more information.
Currently, it is neutral AND FIXED for NT users (as there is no coach)
This is a small change (hopefully) and just to remove a restriction because the team has no coach.  In a normal club team, they will always have some sort of coach, even if it is the original passable one OR their coach they've allowed to run down to wretched coaching skill (not that many would).

**Specific Change for NT teams**
Allow for 10% steps in the **Style of Play** drop-down instead of the standard 3.  Would need a marker in the downloaded HRF to enable this additional set of steps specifically.
e.g.
100% Offensive, 90% Off, 80% Off ... etc ... Normal ... 10% Def, 20% Def ... etc ... 100% Defensive

**Comment by akasolace** [comment]
> Coach = Current coach style (e.g. 100% offensive) and cannot be changed even for a club team. It has to be neutral for an NT team as there is no coach.

in HO I see I can select defense-minded, neither atttack nor defense minded or fond of attacking.
Is not option 2 equivalent to neutral ?  At least I see those options when using HO with regular team, I am not sure of what it looks like for NT team (@yaute74  ??)

> Style of Play currently, for a normal club team, allows you to override the style (either attacking, normal or defensive) to review how that might change your team's ratings when choosing your next coach. When you try the same on an NT team, it doesn't allow you to make the change, and stays on "neither attack nor defence minded" no matter which option you click.

Again I am not a specilist here but my understanding is that you can change style of play only when you got tactical assisstants. If it is set to 0 you can change the style of play (looks correct to me) if you increase that number up to 5 you can then adjust it accordingly.  
(e.g for neutral coach and 5 tactical asstant you can set it up between 50% OFF and 50% DEF with 10% step)    Again this looks correct to me.

@Synthespian  Am I missing something? How exactly would you like this for NT team?  Default to neutral coach and 5 tactical assistant, is that correct ? or for NT team can it really varies between -100 and +100 % ?

**Comment by akasolace** [comment]
@DavidatorusF, @yaute74  do you see an issue here or do you think I can close that bug?

**Comment by DavidatorusF** [comment]
@akasolace 

where is the module nthrf ???

![image](https://user-images.githubusercontent.com/45043004/67016853-29c7e580-f0f9-11e9-8fbb-e1e3905bcfc9.png)

**Comment by yaute74** [comment]
@DavidatorusF  I remove it.
Now when you create a database you have an option to specify if it's a NT or a Club Database.
After that you can use the classic download option in both cases

**Comment by yaute74** [comment]
@akasolace difficult to test it without access :/

**Comment by akasolace** [comment]
> @akasolace difficult to test it without access :/

@DavidatorusF can you find someone to test this?

**Comment by DavidatorusF** [comment]
let me some time, I will ask to a coach

**Comment by DavidatorusF** [comment]
@yaute74 
then... a national coach need obligatory have an HO for his own team before can use it for NT ???

**Comment by yaute74** [comment]
@DavidatorusF of course no, he must set the properties before download
![image](https://user-images.githubusercontent.com/34601782/67042907-23516200-f129-11e9-99fe-bbc475f8a628.png)

**Comment by DavidatorusF** [comment]
@yaute74 on wiki, must I update **NTHRF** https://github.com/akasolace/HO/wiki/NTHRF ?
or add a new topic **NTHRF HO 2.0**
are you agree with:

To import your National Team into HO!

1 Start HO!.
2 Select from menu 'File → Database → Database/User administration'.
3 two way, depend of you already have a team in HO or not :
►you already have your team in HO : Press 'Add'.
►it's the first team in HO : Select "single user" and Press 'Edit'
4 Check National team
5 Enter something as username, for example “National Team”.
6 Press 'Save'.
7 Press 'Close'.
8 Quit HO!.
9 Start HO!.
10 In the new dialog, select the previously inserted username (maybe "National Team" :p).

11 First connexion
For the first connection "F11" or, in the menu bar, "file" -> "download"
You see in the middle of the software a button with "open url" written on it
Click on it and a link appears just below the button while opening a hattrick page in your browser (if this page does not open, copy and paste the link in the browser)
The link looks like this: https://chpp.hattrick.org/oauth/authorize.aspx.…
Enter your login details as requested, Hattrick will give you a code Copy the code into hattrick organizer
Little trick: select the code then CTRL + C to copy it and CTRL + V to paste it

12 Download
"F11" or, in the menu bar, "file" -> "download",
save your nthrf
13 Import
In the menu: file → "import hrf from hard drive" and select the Nthrf file you just saved to have the data of your selection.
You will see the internationals immediately in the list of players.
14 Note
You can only download the Nthrf file once per HO session! - the download button remains disabled after the first activation.

**Comment by yaute74** [comment]
@DavidatorusF  perfect :)

**Comment by DavidatorusF** [comment]
@yaute74 you forgot to answer to my question ^^

update the existant "NTHRF"  on wiki or add a new one "NTHRF since HO 2.0" (mean rename the other one "NTHRF till 143x")

**Comment by yaute74** [comment]
@DavidatorusF for me update because the actual stable version don't work

**Comment by akasolace** [comment]
> @yaute74 you forgot to answer to my question ^^

me also, you both @DavidatorusF, @yaute74 forrget to answer my question :-)   do you think I can close that bug (which is not link to what you recently discussed) ? I am not sure I understand the initial bug report of @Synthespian , hence I am not sure we have a bug at all here. Thank you for shjaring your opinion

**Comment by Synthespian** [comment]
Wow. Been a while. I'll have to re read and recheck.
It wasn't a bug more a feature request. 
I've never had one, but maybe (by having a checkbox to say it's an NT team) it is about enabling the tactical assistant options for an NT coach's db.

**Comment by DavidatorusF** [comment]
@Synthespian 
on HO, you can simulate tactical assistant and coach type for simulate the style of play you want
![image](https://user-images.githubusercontent.com/45043004/67103722-fa32df00-f1c5-11e9-8ec7-7cca8ff3487f.png)

the question is : it is a nice workarround ?

**Comment by akasolace** [comment]
> the question is : it is a nice workarround ?

why would that be consider only a `workaround '?  How is it supposed to be treated ?

**Comment by DavidatorusF** [comment]
@akasolace  workarround for NT

normal users can check the effect of tactical assistant depending of their coach type, then this feature work like a charm for them

NT can use the whole panel from 100% defensive to 100% offensive

hummm...  the new feature can be added to Tactical Assistant a line NT who permit to use to whole panel of style of play (100% defensive to 100% offensive) without check the coach type

**Comment by akasolace** [comment]
@DavidatorusF ah ok you mean if no NT then it works fine
for NT team, we should grey coach type and tactical assistants and always offer -100 to +100 % ?
is it how is it supposed to work for NT coach ?

**Comment by DavidatorusF** [comment]
right

**Comment by Synthespian** [comment]
And it goes in 10% increments only.

**Comment by akasolace** [comment]
@yaute74 considering you have been working on the NT modules maybe you can take this one. If I undestand correctly if it a NT database:  `we should grey coach type and tactical assistants and always offer -100 to +100 %  by step of 10%`.
Please let me know what you think.

**Comment by yaute74** [comment]
@akasolace I can have a look when I have the time

**Comment by akasolace** [comment]
@yaute74 In case this one is time-consuming to fix or if it involves a lot of code change, we will move the milestone from 2.1 to 3.0. I let you decide this. 
Concerning 2.1, the idea is to have a DEV version around the 15th of Jan, a BETA one week later and a release end of the month.

**Comment by akasolace** [comment]
Should be closed by 3363f04

@Synthespian thank you for confirming this is what you expected as soon as new artefacts are released

**Comment by akasolace** [comment]
@Synthespian  @DavidatorusF  can one of you confirm it is now working as expected with latest dev builds ?

**Comment by akasolace** [comment]
@DavidatorusF do you know an NT coach that can test it ? Otherwise do you know @Synthespian  on HT ?

**Comment by Synthespian** [comment]
Hey. Sorry. I will download and test. Not the current u20 coach anymore so might need a bit of help from the current one (even if that's to make me the assistant for a day)

**Comment by akasolace** [comment]
@Synthespian ok great we wait for your feedback then !

**Comment by akasolace** [comment]
@Synthespian ping !

**Comment by Synthespian** [comment]
Positive note, it looks like it works.
Bad note, the player download didn't work.  Hard to test without a comparison on the calculations between the two, but the basic functionality looks sound. :D

**Comment by akasolace** [comment]
> Bad note, the player download didn't work

@Synthespian I don't know what this is but do not hesitate to open a new ticket
