### ISSUE TITLE
[eBUG] Hard to read suggestions in "LineUp"

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#194]
The "tooltip" text is very hard to be read. 
<img width="513" alt="immagine" src="https://user-images.githubusercontent.com/11422667/62838594-ef684500-bc7e-11e9-9c8a-d43e01e90c82.png">

I would suggest to add a background color.

**Comment by akasolace** [comment]
Agree or maybe changing the police color is enough 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pierpaolocira** [comment]
It should be OK now...
