### ISSUE TITLE
[eBUG] NT Linueup empty after download

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#196]
**Describe the bug**
After download NT hrf the linueup is empty
After download a lineup from Hattrick, linueup is also empty

**Comment by yaute74** [comment]
So, @DavidatorusF  @Synthespian @akasolace  we cancel this issue ?

**Comment by DavidatorusF** [comment]
as I now the players are in and module NTHRF work as before
maybe need a test from a NT coach for test it, I mean from a fresh install

**Comment by yaute74** [comment]
@DavidatorusF without modifications, I think it will not work

**Comment by DavidatorusF** [comment]
@yaute74 
oups, I though was an other issue..

you know my mind, for me we can cancel this one

as chpp don't send really the needed information, will be a really hard work to do
