### ISSUE TITLE
[eFEAT] track experience aquisition

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#199]
minute based training according to the following formulas (unwritten manual);

  - [x] initial support of the functionality (PR #363)
  - [x]  consider NT games  (PR ##364)

![image](https://user-images.githubusercontent.com/1136496/63159255-61dc7a80-c01b-11e9-89a9-33e0f703f749.png)

**Comment by mistermax80** [comment]
My suggest is to update this tab:
![image](https://user-images.githubusercontent.com/15519907/66142890-8b228b80-e606-11e9-821a-81c7987209af.png)

**Comment by akasolace** [comment]
@mistermax80 @yaute74 @wsbrenk I am confused here. I opened that ticket following a discussion on slack but it seems there is already that functionality. Is the current functionality broken (i.e not minute based)? Should I close that issue?

**Comment by wsbrenk** [comment]
I'm amazed. this is exactly the module that I built for the HO about 15 years ago. As far as the numbers are concerned, there should be hardly anything left.

**Comment by wsbrenk** [comment]
I think today it is much more easier to implement the experience progress than in those days. I don't know about extra bonus probabilities if the player get hurt or all the other stuff, which was implemented in that ExperienceViewer.

**Comment by wsbrenk** [comment]
Couldn't the experience handled like the other skills. Fix progress for each minute for the separated match classes.

**Comment by akasolace** [comment]
> Couldn't the experience handled like the other skills. Fix progress for each minute for the separate match classes.
I think this would indeed be the best approach, have decimal for experience and keep track of progress...

**Comment by wsbrenk** [comment]
@akasolace:  A small challenge could be the consideration of NT matches at least finding a beta testers for that.

**Comment by akasolace** [comment]
@wsbrenk it is true that this would be a change compare to skill training, I don't know enough about the current training module to assess the difficulty of such change.  @yaute74  any opinion on this one ? as you might be the most knowlegeable about training module.

**Comment by wsbrenk** [comment]
@akasolace I don't know the training module either. Another discrepancy with skill training is that experience counts on both weekly games, i.e. a maximum of 2 times 90 minutes plus nt stakes.

**Comment by akasolace** [comment]
@wsbrenk ok I did not know that actually. Let's wait for @yaute74 inputs ...

**Comment by yaute74** [comment]
Sorry @akasolace  like that I don't know the effort to do it.

**Comment by wsbrenk** [comment]
if nobody else wants to develop here, I would like to attack that as a follow-up project to 299. it has something of nostalgia. but it still has to wait for some days/weeks.

**Comment by yaute74** [comment]
@wsbrenk no problem for me :)

**Comment by akasolace** [comment]
@wsbrenk sure, I change milestone from 2.1 to 3.0, it is more a new feature than a bug fix

**Comment by wsbrenk** [comment]
@akasolace @mistermax80  @yaute74 ; is it correct, that there is no chance in chpp to get the match lineups of nt/u20 team of my national players if i'm not a national trainer? the only small hope i have is the last match container in player details file, which could deliver the played minutes of my national players if i download after nt matches and before the next match is started.

**Comment by akasolace** [comment]
>  there is no chance in chpp to get the match lineups of nt/u20 team of my national players if i'm not a national trainer

I am not sure about this,  I would need to check

**Comment by yaute74** [comment]
@wsbrenk with the API 'matches' you can have the list of matchs if you have the ID of the national team.

**Comment by wsbrenk** [comment]
@yaute74 but there is no lineup isn't it? i need the minutes my player was playing.

**Comment by yaute74** [comment]
@wsbrenk yes. It's because you say "if i download after nt matches and before the next match is started". With this API you can get the old matches id and with this id get the lineup

**Comment by wsbrenk** [comment]
PlayerDetails.LastMatch.PlayedMinutes (if Last Match was national team)
else
PlayerDetails.NationalTeamID -> Matches(teamId=PlayerDetails.NationalTeamID) -> MatchLineup(matchID=Match.MatchId, teamID=NationalTeamId) (that works?)

**Comment by yaute74** [comment]
@wsbrenk I don't know if 'lastmatch' is the good info, because if the manager don't do the download in HO the good day you will have another match.
An interesting info in the player detail is the 'caps' and 'capsU20'. With this info you can know, since the last download, if the player play for national team and how many match he play. (but I don't check if we have the info in the database).

You will implement a 'recalculate' option ? for managers that lost their database and restore with hrf files.

**Comment by wsbrenk** [comment]
@yaute74 good suggestion - and yes the idea is to implement the recalculation feature too. database needs some adjustments (minimum players NationalTeamID, caps are already part of the datamodel)

**Comment by yaute74** [comment]
@wsbrenk great  :+1:

**Comment by wsbrenk** [comment]
![exp](https://user-images.githubusercontent.com/11821502/73139970-eaa01d80-4073-11ea-83c3-0bb2d5f1c62c.jpg)

but that was easy;-) recalc and gui was nearly nothing to do.
national team matches are the next step and then it's ready.

**Comment by akasolace** [comment]
nice, maybe you can push this for 2.1 already even without national team XP, what do you think ??

**Comment by wsbrenk** [comment]
does somebody has a national player (for me). I would need it to be able to continue;-)

**Comment by wsbrenk** [comment]
How to test Experience Sub:
		
		
1. Preparation
1.1 Backup of the HO database
	Copy the HO directory to a new folder
1.2 Installation of the new version
	Zip download https://github.com/akasolace/HO/releases/tag/dev
	Unzip zip into HO folder
	
2. Tests
2.1 Recalculation
	can take hours depending on the DB size and computing power;
	then possibly limit to 7 weeks. After 7 weeks in league games
	is however max. 0.25 subskill achievable. For the test with national players
	one player should take part in a national team match in the 7 week period.
	Action:
	File-> Subskill Recalculation
	Exam:
	- The calculation runs without an error display.
	- Result
		Debug -> SQL editor
		Enter in the command line: select * from spieler
		Execute command: Press F5 or the Execute button
		![debF5](https://user-images.githubusercontent.com/11821502/73254732-43c89800-41bf-11ea-89fe-d7ee34f3ef3c.jpg)

		Current players are at the bottom of the list. Please select the desired international there
		and with its playerId execute the following
		command: select * from spieler where spielerid = 412728156
		After executing this command (F5), the development of this player is displayed.
		In the last two columns (lower scroll bar to the right) the development of the
		selected player should be readable:
		![debsubexperience](https://user-images.githubusercontent.com/11821502/73254768-53e07780-41bf-11ea-8b64-ff0de37317ed.jpg)
		In the lines where the national team was deployed,
		the subskill should show great progress:
		- League 0.035
		- NT-Friendly: 0.07
		- NT-normal: 0.35
		- NT (semi) final: 0.7

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/73593512-81059080-4505-11ea-9212-a745660821a8.png)

added experience sub to statistics page

**Comment by akasolace** [comment]
nice
