### ISSUE TITLE
gradle: create OS X distribution

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#2]

**Comment by whilliam** [comment]
I have attached a few screen shots with explanations below.

![first launch](https://user-images.githubusercontent.com/44447425/47456210-2e063f00-d7d4-11e8-937c-43fedf8304c3.png)
The first time I opened HO I got the above error message. I closed an opened again and nothing happened. After closing and opening HO a few times it suddenly worked and it opened.

![download screen](https://user-images.githubusercontent.com/44447425/47456215-2e9ed580-d7d4-11e8-8d35-0770c97ed729.png)
The download screen appears in front of the CHPP authentication screen making it hard to spot. I could not paste the authentication code into the field and had to type it manually. It worked in the end an I downloaded my data.

![save](https://user-images.githubusercontent.com/44447425/47456213-2e063f00-d7d4-11e8-94da-3937c1818bb7.png)
I got this save screen after downloading data which I didn't really know what to do with. I just clicked save.

![save fail](https://user-images.githubusercontent.com/44447425/47456216-2e9ed580-d7d4-11e8-934a-12536f30d5d8.png)
I got this error message after clicking save. However, it seems the save has worked. I can close the program and reopen it and my team data is still there.

**Comment by akasolace** [comment]
ok thank you for the detailed report. 
In one hand it looks not too bad for a first attempt in the other hand the errors look strange.

- **Bug 1**  Sounds weired that some errors disapears after relaunching the app. Could you please look inside the app folder if a log file was created; if yes and more details about the error are saved in could you also paste the log in here.

- **Bug 2**  I think this is not a bug. looks to me you simply tried to save the hrf in the root directoy "/" where you have no permission to write so the hrf file was not saved. Howerver as you noticed the db was properly updated. The HRF file is simply a backup in case you need to reconstruct your database out of it. I personnaly never did it as a HO user.

Finally if you dont mind, could you for a couple of days use both app in parralel. I mean update you existing HO to keep your DB up to date but use the testing version to check everything is ok (even send your next match orders with the new one or things like this).  For what I understood, except the inital error at launch you dont experience any error message anymore when starting the app?

**Comment by akasolace** [comment]
hello,

so I clearly identified the issue but I do not know how to solve it yet. 
the problem is that under os x latest java version force the current directory to be the home user. Hence most of the relative path are not working when accessing ressource folder or creating db folder. There are 2 solutions:
  1) find a way to change the working dir -> I am really not sure this is feasible
  2) change HO code to move from relative to absolute path -> lot of work
