### ISSUE TITLE
[eFEAT] migrate feedback plugin database to a team accessible server

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#200]
**Is your feature request related to a problem? Please describe.**
At the moment the database is store in @mistermax80  private account and unfortunately he is less and less active in the project.   It seems dangerous to me to build the database in a server that belong to a single user. 
I suggest to create a team account (e.g. https://infinityfree.net/ or  staying at 000webhostapp.com ) and recreate the server there.  The login/password will be shared to few developers of the project.

I don't like that the work done by @Mistermax need to be redone but I think it is best to do it before we actually release 2.0 with the feedback plugin. At least the Java code wont have to be modified and hopefully we can reuse part of what was done on the server side.

If anyone has some expertise in such topic and want to take the lead ....

**Comment by akasolace** [comment]
I will do it

**Comment by mistermax80** [comment]
the migration is completed.
todo update by java side the new link:
remote: https://hofeedback.000webhostapp.com/ws-ho-feedbacks
local: https://hoserver.loc/ws-ho-feedbacks

**Comment by mistermax80** [comment]
@akasolace I tried and the new remote server works fine.
In PR I changed the new server url.
