### ISSUE TITLE
[eBUG] formulas after update stable to dev

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#208]
**Describe the bug**
this bug follow #184 

**To Reproduce**
1. Use the stable (no need to authorise it)
2. File -> preference -> look at formulas
3. File-> preferences -> release channel -> dev
4. Help -> check for update ... then update
5. File -> preference -> look at formulas... the needed numbers are set to 100 for every skills
6. reset formulas ... the numbers are not the same as on 1437

**Screenshots**
example with Formulas for keeper:
stable 1437.2.1081
![image](https://user-images.githubusercontent.com/45043004/63268640-ec7bde80-c294-11e9-95d1-ec118d98e2b6.png)
dev 2.0 r1308
![image](https://user-images.githubusercontent.com/45043004/63268917-8f345d00-c295-11e9-9774-b7af4c03311b.png)
dev 2.0 r1308 after reset
![image](https://user-images.githubusercontent.com/45043004/63269221-11bd1c80-c296-11e9-8316-e25c8528b7ef.png)

**Platform information:**
 - OS: Ubuntu 16.04
 - Version (including build number)

**additional note***
it's the same issue starting from 1.436.2.1072

**Comment by akasolace** [comment]
When updating to 2.0 during the database upgrade the table containing the formula coefficients should be dumped. The release not should be updated accordingly 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
@DavidatorusF I think I closed it but I did not test
let me know if there is still an issue !
