### ISSUE TITLE
[eFEAT] 3 best positions in darkest blue

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#213]
**Describe the solution you'd like**
As you can see in the screen-shot, there's two kind of blue for the value
- blue for normal position
- lightest blue for position with orientation's order

possibility to have a darkest blue for the 3 best positions of the player ?

**Additional context**
![image](https://user-images.githubusercontent.com/45043004/63978385-82deaa00-cab6-11e9-8fdd-28db8c1db9a7.png)

you have those colors in tab "squad", sub-tab "player detail" and in the the player's list in tab "lineup"

**Comment by akasolace** [comment]
Maybe also in combo box in lineup tab

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DavidatorusF** [comment]
@akasolace in combo box, players are sorted by decreasing order for the position...

**Comment by akasolace** [comment]
Yes I know but still somehow player best position could be indicated ... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment]
I think this it is related to #160

**Comment by mistermax80** [comment]
I thought, if we change color for 3 cell per row, the screen will be messy... So I would to think something of simple.
1) chance color text, green for highest value
Or
2) change color for only selected line

What do you think?

**Comment by akasolace** [comment]
@mistermax80 yes maybe only changing text is sufficient (different color or just bold). We could try and see what is best.

**Comment by mistermax80** [comment]
for Player Details see 
line 435- file: module/playerOverview/SpielerDetailPanel.java
`            for (int i = 0; i < playerPositionValues.length; i++) {
            	showNormal(playerPositionValues[i],playerPosition[i]);
			}`

**Comment by mistermax80** [comment]
@akasolace, in paraller to other for 3.0, and after the activities for 2.0, I can take this.

**Comment by akasolace** [comment]
@mistermax80  ok perfect

**Comment by mistermax80** [comment]
I'm trying to color impact:
Change font color is not nice, is very bad, and in selected row the font is black:
![image](https://user-images.githubusercontent.com/15519907/68952974-33f50680-07c1-11ea-88ee-1a5f211f3465.png)

I will try other solution...

**Comment by mistermax80** [comment]
@DavidatorusF @yaute74 @akasolace 
I worked on this, but after I continue, I would like to know your remarks.
I made some tries and the better effect is with bold text, using the color is very bad and it complexs the data reading.
Following some examples:
![image](https://user-images.githubusercontent.com/15519907/69169656-01b51300-0af9-11ea-8d20-ef669569ccfc.png)
![image](https://user-images.githubusercontent.com/15519907/69169686-109bc580-0af9-11ea-93c4-85a5002c1422.png)

**Comment by akasolace** [comment]
@mistermax80 I am ok with the choice of just changing the font. However I think the general approach is not correct. I don't think we should highlight highest absolute contribution. However indeed I think we should highlight all positions that are under a certain relative threshold. 
Imagine we set the tolerance to 5 % ( this could be set in preference at some point). Then for each player, we should look at best relative performance and highlight all position for which the relative performance is such that Relative Performance Position i > 0.95 * Best relative performance.

This will really indicate player that can be positioned in multiple position (multi skill) but unfortunately it is a bit more difficult to implement. In case it is not clear please do not hesitate to ask.

**Comment by mistermax80** [comment]
It Is clear, and also I agree with you opinion....

**Comment by DavidatorusF** [comment]
I'm agree with the bold :p

**Comment by mistermax80** [comment]
@akasolace related your previous comment:

> However indeed I think we should highlight all positions that are under a certain relative threshold.
Ok, I'm agree.

> Imagine we set the tolerance to 5 % ( this could be set in preference at some point). Then for each player, we should look at best relative performance and highlight all position for which the relative performance is such that Relative Performance Position i > 0.95 * Best relative performance.

For the relative performance do you refer % value and not to the absolute contibution?
If you refer to % value (normalized contribution) we have not in table, and use this value for highlith the absolut contribution is very difficult, but if it is more correct, I will think how to work on this.

**Comment by akasolace** [comment]
> For the relative performance do you refer % value and not to the absolute contibution?
If you refer to % value (normalized contribution) we have not in table, and use this value for highlith the absolut contribution is very difficult, but if it is more correct, I will think how to work on this.

Yes I was talking about relative performance ... I agree there is a bit more work.
There is a method that compute the best position, maybe we can modify that method to also identify alternative positions.

**Comment by mistermax80** [comment]
Ok, I will think how to do.
It will be very hard! 😁

**Comment by akasolace** [comment]
@mistermax80 I don't think this is very hard. I have a good idea on how this can be implemented.

At the moment I do not really have time, but I can look at in a couple of days.  Let me know if you need help.

**Comment by mistermax80** [comment]
Could you write me your idea?

**Comment by akasolace** [comment]
There is a function that calculate best position. That function loops over all position and calculate relative contribution and store the max value.
The idea would be to:
   - add "alternative position" filed to Player 
   - amend the function that calculate best position to calculate during that loop the alternative position 
   - the thresold we start with can be 5% but can be changed by user via preference

**Comment by mistermax80** [comment]
@akasolace, current result, I made as you suggest, now are calc normalized.
![image](https://user-images.githubusercontent.com/15519907/69907990-97498000-13e0-11ea-924d-4046eae30178.png)

But I agre with you the alternative best position are related with value position normalized, but the other user can not be agree, so I think if the best position are colulated on normalized value or no it is a user choice. I link this #282 and we will decide on that.

**Comment by mistermax80** [comment]
Other evolution, the combo box for fix the role, now you can see the all personal rating and the alternative posizions have the *:
![image](https://user-images.githubusercontent.com/15519907/69922776-785df300-149f-11ea-8df9-f48e465e04ad.png)

**Comment by akasolace** [comment]
closed by 4ae8995

**Comment by akasolace** [comment]
I have 2 remarks:
    - the bold is not very easy to spot, can't we try something more radical, different background  ?
    - in the settings, 
         - I would call it "Best Position Tolerance (%)"   
         - I would default it to 5% and maybe if it feasible we should limit it to 0-10%

**Comment by mistermax80** [comment]
Different backgrounds make tables messi, but  I can try.
The lab
