### ISSUE TITLE
[eBUG] MacOS - JRELoadError

### ISSUE THREAD

**Issue by tmscardoso** [akasolace/HO#214]
**Describe the bug**
I'm using the app installer (HO_1.437.2.1081_macOS.zip) and when trying to start the app I get a JRELoadError splash window.
Running /usr/libexec/java_home, I get:
/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home

Is it related with the adoptOpenJdk?

**To Reproduce**
1. Go to Applications
2. Click on HO app
3. Error windows appears showing JreLoadError

**Screenshots**

**Platform information:**
 - OS: MacOS X 10.14.5
 - Version: 1.437.2.1081

**Comment by akasolace** [comment]
@pierpaolocira @mistermax80  could one of you have a look to this issue ?

**Comment by akasolace** [comment]
@tmscardoso  I have no idea, hopefully one of the 2 macOS dev can have a look shortly

**Comment by pierpaolocira** [comment]
I use Sierra, but I see some possibilities for this kind of issies:
- either this relates to our #202 that originates from https://github.com/crotwell/gradle-macappbundle/issues/49 (but if I'm not wrong 1.437 was aleady pakaged without JRE)
- or you don't have a JRE8 compatible (but it doens't seem to be your case)
- your your JRE is not compatible/recognised with the gradle-macappbundle launcher that we use (indeed, if I'm not wrong, the launcher embedded into the .APP is the original from Oracle).

@tmscardoso can you be so kind to install an additional (official Oracle) JRE8, set it as a default JRE, and see if it works?
Then you can remove, but at least we'll know if it relates.

Thanks

**Comment by akasolace** [comment]
@pierpaolocira I am very surprised. I was convinced that adoptopenjdk was fully compatible with oracle JDK

@tmscardoso could you first test it you have the same issue with the development release.

**Comment by tmscardoso** [comment]
@akasolace, the development release (2.0.0.1323_macOS) produces the same error window.

Installing Oracle JRE (jre-8u221-macosx-x64) temporarily fixes the issue but since I use the adoptOpenJdk for development purposes I'll need to keep both.

Thanks guys!

**Comment by pierpaolocira** [comment]
@tmscardoso I would suggest you to please open an issue here: https://github.com/crotwell/gradle-macappbundle/ because this plugin doesn't seem be able to support any JRE other than Oracle.

@akasolace I think this issue can be closed, but I would suggest to change title to "MacOS - JRELoadError" without specifying the OS version... this might be helpfull in future for further users... (hopefully not so many)

**Comment by akasolace** [comment]
> temporarily fixes the issue
@tmscardoso what do you mean by temporary?

> @tmscardoso I would suggest you to please open an issue here: 
> https://github.com/crotwell/gradle-macappbundle/ because this plugin doesn't seem be able to 
> support any JRE other than Oracle.

This one could be fixed when we stich to java 11 as I understood that bundling the JRW will work , @pierpaolocira correct?  In the meantime,  I also suggest you raise the issue on  https://github.com/crotwell/gradle-macappbundle

>I think this issue can be closed, but I would suggest to change title to "MacOS - JRELoadError" without specifying the OS version... this might be helpfull in future for further users... (hopefully not so many)

I will do it as soon as @tmscardoso confirms installing oracle JDK on top of openJDK fixes the issue.

Thank you

**Comment by tmscardoso** [comment]
> > temporarily fixes the issue
> > @tmscardoso what do you mean by temporary?
I can't have Oracle software on my machine (it's my work/personal laptop), for me the best solution would be the adoptOpenJdk jre, but I understand if it's not high priority stuff right now for you

> > I think this issue can be closed, but I would suggest to change title to "MacOS - JRELoadError" without specifying the OS version... this might be helpfull in future for further users... (hopefully not so many)
> 
> I will do it as soon as @tmscardoso confirms installing oracle JDK on top of openJDK fixes the issue.
Confirmed, it works installing Oracle JRE on top of adoptOpenJDK, you can close.

Thanks again guys.

**Comment by akasolace** [comment]
@tmscardoso  maybe you should have a look to this one  https://medium.com/solacedotcom/switching-to-adoptopenjdk-8d4a4aed16b8
