### ISSUE TITLE
Missing Details in Player Analysis

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#218]
**Describe the bug**
Missing Details in Player Analysis --> see screenshoot
![Cattura](https://user-images.githubusercontent.com/15519907/65495391-f78ae580-deb6-11e9-82b9-ed93b5b06707.jpg)

**Comment by akasolace** [comment]
I can confirm this behaviour on Windows. Has anyone a screenshot of how it looked previously ?

**Comment by pierpaolocira** [comment]
<img width="751" alt="immagine" src="https://user-images.githubusercontent.com/11422667/65539653-25e5e080-df0a-11e9-83b3-fd8fb7495593.png">

Just taken from my 1.437

**Comment by akasolace** [comment]
@pierpaolocira  or @mistermax80  were those real stars as per HT match report ?

**Comment by akasolace** [comment]
closed by a186d50
