### ISSUE TITLE
Player Analysis errors - Compare Player

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#219]
1) Missing positions
2) column ordering doesn't work
![Cattura](https://user-images.githubusercontent.com/15519907/65495622-59e3e600-deb7-11e9-9a23-58257478cd9a.PNG)

**Comment by akasolace** [comment]
Issue confirmed on Windows

**Comment by mistermax80** [comment]
OK the bug resolved, but the ordering for skill column doesn't work. Leave the issue open

**Comment by akasolace** [comment]
indeed I forgot that one.
@mistermax80 do you know by any chance if this was working in 1.437 ?

**Comment by mistermax80** [comment]
@akasolace I don't remember, but Often I used that tab, so if it was wrong, I noticed.

**Comment by akasolace** [comment]
I guess it also does not work in Lineup tab .. but need to check that

**Comment by akasolace** [comment]
I think my latest commit f2985a6 fixes it but I let you check before closing the issue

**Comment by mistermax80** [comment]
ok fixed
