### ISSUE TITLE
There no FW normal value in PlayerCompare (TAB Player Analysis)

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#22]
![schermata 2018-12-02 alle 17 25 49](https://user-images.githubusercontent.com/15519907/49342140-6f9dcb80-f657-11e8-97a7-149cf7ba4fa1.png)

**Comment by mistermax80** [comment]
No this.
Following my preference - columns - squad:
![schermata 2018-12-02 alle 21 07 56](https://user-images.githubusercontent.com/15519907/49344372-66702700-f676-11e8-950a-8f36af538184.png)
And I have the issue in PlayerCompare:
![schermata 2018-12-02 alle 21 09 20](https://user-images.githubusercontent.com/15519907/49344391-b6e78480-f676-11e8-851c-631062830be7.png)
As you can see missing the FW value.

MMX80

**Comment by akasolace** [comment]
@mistermax80 
are you making progress on this one ?

**Comment by mistermax80** [comment]
No yet... Firstly I must complete my dev environment.
I have and issue on LookAndFeel Aqua when run in Intellij
I'm using macos.

**Comment by akasolace** [comment]
@mistermax80 
It is a dependency issue. 
You should synchronize your gradle project. did you follow that [guide](https://www.jetbrains.com/help/idea/gradle.html#gradle_import)?

**Comment by mistermax80** [comment]
I closed for error.

**Comment by mistermax80** [comment]
@akasolace 
Sorry, but I don't understand how oper an PR.
Can you help me?

**Comment by akasolace** [comment]
so you manage to run the code and to close the bug on your local installation, right?
Now you want to push  your changes?

I see that 

may be you can look at the contribution guidelines and in case you have further questions please let me know.
https://github.com/akasolace/HO/blob/master/docs/contributing.md

If you are new to git it may look intimidating, but you will soon appreciate how powerful it is

**Comment by mistermax80** [comment]
@akasolace  ok thanks, I will update you soon...

**Comment by mistermax80** [comment]
@akasolace 
I think to do done :)
Now I don't know what I will do.
Can you help me for the ultimate step?

**Comment by akasolace** [comment]
Thank you !!
