### ISSUE TITLE
Feedback Plugin - Parsing error

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#220]
HT copy in Italian
HO in italian.
The system shows error.
![Cattura](https://user-images.githubusercontent.com/15519907/65495885-bcd57d00-deb7-11e9-997b-4a6226d58d4c.PNG)

**Comment by akasolace** [comment]
I also have an issue with feedback plugin but not the same as yours.

I think yours have to do with Italian Language.  Looks like attitude and tactic are not recognized ....

@mistermax80  Can you try to see where this is coming from otherwise I would need to setup my HO and maybe HT in Italian (if I could avoid that would be nice).

**Comment by mistermax80** [comment]
@akasolace Ok, I can to try...

**Comment by mistermax80** [comment]
@akasolace 
this function uses languagese, in input we passing the value retrieve fron json git hub, but in json the lang is only english.
            int iTactic = MatchRating.TacticTypeStringToInt(requirements.tactic);
            int iAttitude = MatchRating.TacticTypeStringToInt(requirements.attitude); (this row is wrong --> the correct AttitudeStringToInt)
I'm procede uses the json label in append to string "ls.team.tactic." and "ls.team.teamattitude."

**Comment by akasolace** [comment]
@mistermax80 I got the issue but I am not sure how you intend to fix it.

Should we not simply modify  `TacticTypeStringToInt` function to first look for english terms and if not found test translated terms. What do you think ?

**Comment by akasolace** [comment]
@mistermax80 ok I made the required change.  
Does this solve part of the issue or the full issue ?

**Comment by mistermax80** [comment]
@aka doenst resolve... I'm coding these fix... Ok I re pull and I will make the other fix...

**Comment by akasolace** [comment]
@mistermax80  I made new artefacts, in case you want to test with latest translations that you made.

**Comment by akasolace** [comment]
@mistermax80  There is something wrong. The plugin works well when I test it from IDE but it fails if I try from installed version "Server returned HTTP response code: 400 for URL: https://hofeedback.000webhostapp.com/ws-ho-feedbacks"  maybe more information available from the server or you will need to do more logging expliclty paste the json maybe

**Comment by akasolace** [comment]
I also just check on the server, no example of feedback sent from installed HO (always from IDE). So that issue is not new

**Comment by mistermax80** [comment]
@akasolace OK, asap I will test and fix it.

**Comment by akasolace** [comment]
feedback and test required before closing

**Comment by akasolace** [comment]
@mistermax80     it is working now for me ...  on a side now ... it took me a while to get why HO was complaining about my lineup. It was because I was in PIC instead of Normal for the attitude.  I guess we could make the error message more specific.  What do you think ?

**Comment by mistermax80** [comment]
@akasolace, yes I noticed same thing. If the requirements are not complies, the button "send" doesn't ligth, I think can insert a message, in order to state the requirements are not complies.
Let me know how you want I do options:
1) an message generic
2) specific message per requirements

**Comment by akasolace** [comment]
I think we might simply modify the hover message to something more specific. I forgot I made those checks :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment]
I afraid, the user doesn't read hover message on button turned off.
I'm going to introduce the new message.
After if you can take ok, else we find an other solution.

**Comment by mistermax80** [comment]
this is the effect, in some minute I will send new PR.
![image](https://user-images.githubusercontent.com/15519907/65817928-fd612d80-e20c-11e9-8cc9-1ccedbc75e30.png)
