### ISSUE TITLE
Missing rating value in Training Screens

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#222]
![Cattura](https://user-images.githubusercontent.com/15519907/65504820-1c3b8900-dec8-11e9-8994-a9f4f4a20709.PNG)

It wiil be nice, in this screen the players in training are highlighted

**Comment by mistermax80** [comment]
@akasolace in my previus message, I required this:

> It wiil be nice, in this screen the players in training are highlighted

This nigth I was inspired, and so I made, if you want I send PR.
![image](https://user-images.githubusercontent.com/15519907/65809763-42e81100-e1a1-11e9-922c-c68686561ffb.png)

**Comment by akasolace** [comment]
@mistermax80 this looks fine. However maybe that for consistency  we should use the same color as in the other tabs light/dark blue/grey ? What do you think ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mistermax80** [comment]
@akasolace It Is the same colour the next tab

**Comment by mistermax80** [comment]
@akasolace 
following you can try the screenshot, you can see the color are the same:

![image](https://user-images.githubusercontent.com/15519907/65816699-7063a780-e1ff-11e9-991f-9fd6b14a6ee6.png)

![image](https://user-images.githubusercontent.com/15519907/65816713-8709fe80-e1ff-11e9-8199-f460f5c0a0d5.png)

**Comment by akasolace** [comment]
I meant same color as in the squad tab (see below)   what do you think ?

![image](https://user-images.githubusercontent.com/1136496/65835387-02de7680-e2e6-11e9-9e86-57f29b22ae2f.png)

**Comment by mistermax80** [comment]
Ok It Is fine! I will change them

**Comment by mistermax80** [comment]
@akasolace in my squad tab the training bars are green colour, I'm training attack... So I don't know if can reproduce the same color, because these colours (in training tabs) doesn't depend from training week, but on estimate training in future weeks.
So, we can introduce the training bar (as in squad tab) also in training tab.
What do you think?

**Comment by akasolace** [comment]
@mistermax80  In squad tab, there are 4 colors (light/dark green/grey) for partial/full passed/upcoming training. The logic to define the color was already implemented by @yaute74. Can't you reuse what was done for the training tab ? Also the minute played as you mentioned? I dont know how  @yaute74 implemented this but maybe those infor can be estimated once and stored somewhere (player attribute ?) and called in different places (e.g training tab).  What do you think?

**Comment by yaute74** [comment]
I create new source in core/training/TrainingPreviewPlayers method calculateWeeklyTrainingForPlayer.
I check the time playing in training position and check lineup of futur match. 

I don't know if we can use the same functions, I don't check the source code of Training tab.

**Comment by yaute74** [comment]
Just to be sure, you want to have the same info in the training tab player list ? or you want to merge the code (training calculation) ?

**Comment by mistermax80** [comment]
@akasolace @yaute74 By quick look, the yaute function can be used, but the topic is not this.
The yaute function analyze the lineup passed or future in current week.
The trainig tab uses logics on this (and it shows the possibile skill up):
- players ideal position
- training set in future week
- doesn't see the trianing in the week
So, the 2 different functions (youte function and tarining tab) are different concept.

I think the better way is that do a merge, the result can be the following:
![image](https://user-images.githubusercontent.com/15519907/65877822-e0536880-e38c-11e9-8355-b1529c510ae8.png)

I this way, you can see the possibile training evolution, and the player trained in week or player will trained.

**Comment by akasolace** [comment]
@mistermax80 I am sorry but I think I am not getting the point. You want to see in the training tab, indication of which player will be trained this week (the ones who already played and the one who are planned to be aligned on upcoming game), right ? If is is the caes I don't see why you can't reuse @yaute74 logic.  If you are trying to achieve something different, could you please explain it again ...

**Comment by mistermax80** [comment]
> You want to see in the training tab, indication of which player will be trained this week (the ones who already played and the one who are planned to be aligned on upcoming game), right ?

Yes, and we can use the yaute logic, but we should not remove the actual logic (rows higlighed)

**Comment by akasolace** [comment]
> Yes, and we can use the yaute logic, but we should not remove the current logic.

@mistermax80 indeed only your last modification (green background on trained player) should/could be adapted by replacing it with light/dark green/grey color as per the squad tab.  
We do not change anything else on the training tab (at least for the moment).
If you agree with that, do you think you could:
     - reuse @yaute74 logic ?
     - reuse @yaute74 logic  without recalculating? (e.g. saving training information on player level and getting it from there). On this one maybe @yaute74 could share his opinion

**Comment by mistermax80** [comment]
> @mistermax80 indeed only your last modification (green background on trained player) should/could be adapted by replacing it with light/dark green/grey color as per the squad tab.

Yes, I can change the colour, but in training tab the colors are 2:
- green for player in position that receive all training
- yellow for player in position that receive partial training
for example in case of cross traiinig:
- green for wings
- yellow for back wings
this logics consider only position and future training and these don't see the lineup.
The yaute logic do:
green (ligth/or no light): for player received total training in terms of time
grey: for player will receive training in terms of time.

So, I would like see in the tab training both information. My idea is use yaute logic for to show the icon and tooltip, and leave current logic as is (just change color if need)

The yaute logics is an static function, and it is usable in each part of code.

**Comment by akasolace** [comment]
@mistermax80  I am sorry but I still don't get it. I suggest you go with it, I guess I will understand when I will look at the PR. 
For my information, and again considering I don't know what you are planning to do, do you see it as a low/medium/high effort?

**Comment by akasolace** [comment]
@mistermax80 maybe best if you open a dedicated issue for this one as it is not more related to missing rating values.

**Comment by mistermax80** [comment]
Ok, I opened a new issue.
https://github.com/akasolace/HO/issues/234

**Comment by akasolace** [comment]
> Ok, I opened a new issue #234

@mistermax80 perfect, do you intend to close it for 2.0 ? In order for me to put the right milestone.

**Comment by mistermax80** [comment]
Yes I would like insert in 2.0.
The effort I think is low/medium.

**Comment by akasolace** [comment]
Ok

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaute74** [comment]
In principle I agree. I think you can use the same object than me for the user column and leave the rest as it is.

Just a remark, aren't you afraid it'll give too much information to the user ?
