### ISSUE TITLE
[eBUG] Feedback plugin the value rating are different in lineup tab

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#227]
![Cattura](https://user-images.githubusercontent.com/15519907/65787527-6d15e080-e159-11e9-9712-5632b081f7eb.jpg)

**Comment by akasolace** [comment]
This is normal. One is the t=0 rating to be compared to HT whereas the other is the 90 min average rating. This is intended ! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
@mistermax80 is there something else or should we close this?

**Comment by mistermax80** [comment]
No I verified, it is ok, I close.
