### ISSUE TITLE
discussion about linux migration

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#23]
To continue the discussion about linux migration [post=17225693.44]
When a user will upgrade to the 1.435 he will start with en empty database.
To prevent this problem I propose to modify the script ho.sh (to copy the database) like this:

```
#!/bin/sh
LAUNCHDIR="$(dirname "$0")"
LAUNCHDIR="`eval echo $LAUNCHDIR`"
HOHOME="~/.ho"
HOHOME="`eval echo $HOHOME`"
HOOLDHOME="~/.hattrickorganizer"
HOOLDHOME="`eval echo $HOOLDHOME`"

start(){

HODIR=/usr/lib/ho/

if [ ! -d "${HOHOME}" ]
then
echo "creating ${HOHOME}"
mkdir -m 777 "${HOHOME}"
echo "copying required ressource"
cp -R "${HODIR}/." "${HOHOME}"
fi

# For old versions
if [ ! -d ${HOHOME}/db ] && [ -d ${HOOLDHOME}/db ]
then
cp -r ${HOOLDHOME}/db ${HOHOME}/db
fi
..
```
Why did you say on the hattrick forum: "What you propose I guess will not work as you expect" ?

You propose to do it in the post install, but in the ho.sh script we create HOHOME directory, copy some files from HODIR. In that case it should be do in the post install, no ?

You plan to add it in the 'rpm' and 'deb' package ?
I don't know how Gradle work, but I can try to help you, if you need

**Comment by akasolace** [comment]
@yaute74 ,  actually , I read too quickly your post in the forum this morning.
Now I see what you want to do, and you proposal looks good to me -yes, it will be done both for the .deb and the .rpm.
You can either open a pull request or I can make the changes you proposed myself, up to you, just let me know how you want to proceed

On another topic, as you are a Linux user.  What do you think of AppImage format? Do you think it would make sense to use it to distribute HO?

**Comment by akasolace** [comment]
> -change ~/.ho by ~/.local/share/ho (because it's more standard for new product)

I actually did that in the version of the 1.435 beta, and some users complained about it, saying it was too difficult to find  :-)

> copy the db directory

copy it where ?

> do a backup of .hattrickorganizer

with current script, this folder is being left untouched, hence why do you want to back it ?

> If we can easly generate appimage with Gradle I think it's will be nice to propose deb, rpm and appimage.

Unfortunalty I do not think it is easy, I will leave as is for the time being,

**Comment by akasolace** [comment]
closed by PR
