### ISSUE TITLE
[eBUG] Decimal Skills doesn't present in Trining Tab

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#236]
![image](https://user-images.githubusercontent.com/15519907/65955508-9465f980-e448-11e9-8d9d-4995144af7b2.png)

![image](https://user-images.githubusercontent.com/15519907/65955544-b0699b00-e448-11e9-9dca-9bc94dbf5ff9.png)

**Comment by akasolace** [comment]
closed by 6c809630a377f7c2e325743ad85254c782152361
