### ISSUE TITLE
>  "League tab", Button download game, not activated for some past game

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#237]
>  If I undestand correctly it is not possible to do so for games for which match details are not in the database. @DavidatorusF is that correct?

Yes, past matches have not details in db their have status = 2 (match not played)
The solution shuld be that download match.
You can see this effect also in the following screen:
![image](https://user-images.githubusercontent.com/15519907/65878401-4e4c5f80-e38e-11e9-8fb7-91659f47c1d6.png)

_Originally posted by @mistermax80 in https://github.com/akasolace/HO/issues/181#issuecomment-536538055_

**Comment by akasolace** [comment]
surely same fix as #181 will apply (see d2eb14d999127c7e719a18b801984bc946537a86)  
can't fix it myself at the moment as I can't reproduce ( never skipped a download :-) ) I will fix it next week if no one did it before ...

**Comment by mistermax80** [comment]
Ok, else you can update an past match with status =2 in your dB, in order to replicate the case.

**Comment by akasolace** [comment]
closed by 18ed0c0
