### ISSUE TITLE
improve design of league details panel

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#238]
Improve the readability of league details panel

**Screenshots**
![image](https://user-images.githubusercontent.com/1136496/66074655-f9f5db00-e559-11e9-80b4-45387a8c07ac.png)

by: 
   1) improving color on the graph (more distinctive colors) and make maybe bold lines
   2) remove color on the table for relegation and promotion  and replace them by separation (line break maybe). also if information is available via CHPP we can upate relagation rule (for example I am in D VI and it is not possible to go down)
  3) replace the wWlLLwwLWlww by something with more impact, for example what is use in real life soccer table (green / grey / red circles):
![image](https://user-images.githubusercontent.com/1136496/66074909-9fa94a00-e55a-11e9-8a92-4bd065ebb08e.png)
  4) introduce league statistics (similar to HT supporter statistic)

**Comment by mistermax80** [comment]
For point 3, we should understand how to show the information in home or away... Tooltip?

**Comment by akasolace** [comment]
>For point 3, we should understand how to show the information in home or away... Tooltip?
I suggest we just remove this (don't see a need for a tooltip)

**Comment by mistermax80** [comment]
OK

**Comment by mistermax80** [comment]
new HT layout:
![image](https://user-images.githubusercontent.com/15519907/68630945-3ddce800-04e9-11ea-9552-9266305c4aad.png)

**Comment by akasolace** [comment]
@mistermax80  yes this is what I had in mind. Now we have a model :-)

**Comment by mistermax80** [comment]
yes 😀

**Comment by akasolace** [comment]
@brokenelevator would you be interested working on this one? It is decorrelated from the rest, hence you could work on it at your own pace ... let me know

**Comment by akasolace** [comment]
@tychobrailleur should we close this one or is there other thing you want to do here ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur should we close this one or is there other thing you want to do here ?

No, all good here.  I think my changes covered all your initial requirements, so I'll close.
