### ISSUE TITLE
collect player's TSI and age as part of the existing feedback plugin.

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#243]
As @mistermax80 suggested we will simply start to collect player's TSI and age as part of the existing feedback plugin. Hence we will start accumulating data as soon as 2.0 is release

_Originally posted by @akasolace in https://github.com/akasolace/HO/issues/235#issuecomment-538272775_

**Comment by mistermax80** [comment]
HO side there no anything to do, the json object already has the all player.
HO server side, add new view in order to player visualization data.

**Comment by akasolace** [comment]
@mistermax80  I would let you close this one when it is done on server side ... thank you !

**Comment by mistermax80** [comment]
Made all, Just I should update files in server and git!

**Comment by mistermax80** [comment]
by this commit we can close: https://github.com/akasolace/HOserver/commit/1bc1e1485449d95ddfaff6a4a0460a8321ebda09

**Comment by akasolace** [comment]
great thank you
