### ISSUE TITLE
[eBUG] Stamina training must greate or equal to 10%

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#249]
On hattrick we can not have a stamina percent lower than 10.

**Comment by akasolace** [comment]
@yaute74 this is not set via CHPP download? When does the user need to setup this manually?

**Comment by yaute74** [comment]
@akasolace I speak about that:
![image](https://user-images.githubusercontent.com/34601782/66674541-71ff8780-ec63-11e9-8a3f-5548422fbe52.png)

**Comment by mistermax80** [comment]
I can manage it.

**Comment by akasolace** [comment]
@mistermax80 ok

**Comment by akasolace** [comment]
closed by bbff5b4e452852211065bcc5ff2e74253858ca5a
