### ISSUE TITLE
[DOC] update Wiki MacOS update

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#253]
Update  MacOS update part on the [wiki](https://github.com/akasolace/HO/wiki/Installing-HO)

At the moment,  description is incorrect:

> MacOS: not supported (because the app is not signed)

**Comment by mistermax80** [comment]
@akasolace @DavidatorusF ,

I tried update from 1.436, 1.437 and the update is ok.
For update I mean, drag HO.app (lasta version) in Application folder (or in location of the previus installation).
Maybe the error I faced beacuse old installations...

**Comment by akasolace** [comment]
ok good to know. As said on slack, I will release the BETA today
@DavidatorusF I will do the forum announcement based on your documentation
cheers

**Comment by DavidatorusF** [comment]
@mistermax80 are you agree with ?

* **MacOS**: not supported  (because the app is not signed)
you have to do it manually: download the last HO.macOS.zip, extract it then drag HO.app in Application folder (or in location of the previous installation)

**Comment by akasolace** [comment]
@DavidatorusF @mistermax80 for me it has nothing to do with the fact the app is not signed.
I suggest we just say

> MacOS: not supported
> you have to do it manually: download the last HO.macOS.zip, extract it then drag HO.app in Application folder (or in location of the previous installation)

**Comment by DavidatorusF** [comment]
https://github.com/akasolace/HO/wiki/Installing-HO

we can close here
