### ISSUE TITLE
[eBUG] no support of plawer specialty "support"

### ISSUE THREAD

**Issue by zerebart** [akasolace/HO#259]
**Describe the bug**
https://image.noelshack.com/fichiers/2019/42/5/1571385242-bugerror8.jpg
 HO v2.0 1374 this morning error message during download of team data.
No possibility to access HO after this error

Before today and since september I had no bug at this step (no change on my PC too : java platform 8.0.1720.11 10/05/2018 09:40).

What I've done? ...

=>  Trying another time ... same error
=> Donwload of version 1382
=> installation
=> downloading datas : another error 8

BUT at this step I can close the error message and THEN access HO interface : everything seems to work properly and I can see the 3 downolads I have made this morning

I hope I'm not the only one in such case so that I'm not only an "exception error"

**Comment by akasolace** [comment]
@zerebart have you always been on DEV channel or did you just give it a try after experiencing the bug?  If I understand correctly, now you always have that error on download, but HO still seems to work normally afterward?  Do you have a backup of your database made prior to today error ?

**Comment by zerebart** [comment]
The bug I report here ls the FIRST bug I encounter with HO2.0 v1374 since I installed it in september.

I'm not accustomed with github and I dont understand why I could (should) have been on what you call DEV Channel

Finally, no, I didn't make any back up of my DB since mid of september.

**Comment by akasolace** [comment]
> I'm not accustomed with github and I dont understand why I could (should) have been on what you call DEV Channel

DEV channel is in HO preference (if you downloaded HO 1.437, by default you were on STABLE channel, it means you have not been notified of updates since).  

can you send me a copy (as a zip) of your db folder ? (you can drop the zip as attachment here directly in github or you can send it to me via Firefox Send.  I will need it to replicate the bug you are experiencing. 

> Finally, no, I didn't make any back up of my DB since mid of september.  Hopefully they are still some backup inside the db folder (they are made automatically)

**Comment by zerebart** [comment]
[db-zerebart.zip](https://github.com/akasolace/HO/files/3745397/db-zerebart.zip)

Here is the db

**Comment by akasolace** [comment]
@zerebart it says your zip file is invalid. I can't open it. Can you try again please

**Comment by zerebart** [comment]
i send it another time
[db-zerebart.zip](https://github.com/akasolace/HO/files/3747958/db-zerebart.zip)

**Comment by akasolace** [comment]
@zerebart ok thank you. This week I won't have time but I will have a look next week. 
For my info, do you still have the same behaviour?

**Comment by mistermax80** [comment]
Ok perfect! So Just the table and data are ready I will create a new API service from service for expose the data

**Comment by akasolace** [comment]
@mistermax80 @DavidatorusF can one of you open this archive? it appears as invalid to me .... thank you

**Comment by mistermax80** [comment]
@akasolace, I able to open by my smartphone... And I see the content.

**Comment by DavidatorusF** [comment]
@akasolace look on slack

**Comment by akasolace** [comment]
@pierpaolocira @yaute74 @mistermax80 if one of you has time to look at this one in the coming days please do. Otherwise I will do it in the week of 4th of November. At this stage I am not even sure we really have an issue here hence it might not worth to block 2.0 release for this ....

**Comment by yaute74** [comment]
@akasolace I have a look, it's a real problem. Must be corrected before the release of the 2.0.
We have it when we have a player with speciality 'support'
We have 7 different speciality but 'support' speciality has id 8 and array are created with a size of 7!

**Comment by akasolace** [comment]
thank you @yaute74  !
@zerebart I will release new built Sunday or Monday evening
@DavidatorusF can you please amend the release note accordingly !

**Comment by akasolace** [comment]
closed by da1f294d66d76dccb927f5acdd5009824a820e47

**Comment by DavidatorusF** [comment]
@yaute74 can you explain me what was the mistake with support player ?

I though this one was already solved...

@akasolace whatever, I added it to release note

**Comment by yaute74** [comment]
@DavidatorusF it's because the function is not the same in 1.437
I will try to by a support player ...

**Comment by akasolace** [comment]
> I though this one was already solved...

true, yesterday I did not pay attention but yes this one was supposed to be fixed in 1.435, Now I recall that when it was release users were saying it was fixing their issue)

> it's because the function is not the same in 1.437 

fmi, can you tell me what reintroduced a bug ?

> I will try to buy a support player ...

good lick with that :-)

**Comment by akasolace** [comment]
> @yaute74 can you explain me what was the mistake with support player ?
I though this one was already solved...

I looked at the commit made by @yaute74.  I think that in 1.435 we close one bug that was making impossible for a user to download data if they had a support player.  Here @yaute74 went further and change other part of the code that raised issue if player with suport specialty was put in the lineup.

I would say for the release note we can add something generic like "close additional issues related to player with support specialty"

We will also need to confirm this time all works well for such player. I will also look around for such a player which would allow me to do in depth check.

**Comment by yaute74** [comment]
@akasolace it's because in b663a32f7f387c6f6d89e58394725895411dd83e we remove 

```Java
if (specialty < SPEC_NONE || specialty >= SPEC_ALL)
    specialty = SPEC_NONE;

**Comment by zerebart** [comment]
Thanks for all your job! Suprisingly (to me... I didn't change anything since last friday when I got 1.438 version) I didn't have any error today

**Comment by yaute74** [comment]
@zerebart maybe you change your lineup on hattrick and remove your 'support' player

**Comment by zerebart** [comment]
Possible (if the problem is the support "player" then my bug was because I prepared my team for satursday's friendly and there was my support player in it).

Hope you will make a great job for this 2.0 version (from now on I encounter also some presentation's unpleasantnesses, sepcially in the lineup tab)
