### ISSUE TITLE
[eFEAT] two new flag

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#262]
**Is your feature request related to a problem? Please describe.**
Hattrick added two new country
LeagueID=155 RD Congo  🇨🇩 
LeagueID=156 Ethiopie  🇪🇹 

**Describe the solution you'd like**
IFA need them

**Comment by akasolace** [comment]
@yaute74 @mistermax80 @pierpaolocira @cyrill10 would anyone of you have time to do this one? I was really busy recently and it will be the case at least until end of next week.

**Comment by yaute74** [comment]
@akasolace I can do it this week

**Comment by akasolace** [comment]
@yaute74  thank you !

**Comment by DavidatorusF** [comment]
🇨🇩 RD Congo LeagueID=155
link=http://www.iconarchive.com/show/flags-icons-by-wikipedia/CD-Congo-Kinshasa-Flag-icon.html

🇪🇹 Ethiopia LeagueID=156
link=http://www.iconarchive.com/show/flags-icons-by-wikipedia/ET-Ethiopia-Flag-icon.html

**Comment by akasolace** [comment]
closed by e415d8d33a86750fd5cebc0c43774940f540efc6
