### ISSUE TITLE
[eFEAT] icons similar to HT

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#265]

**Comment by akasolace** [comment]
@mistermax80 
As part of #339 I will need icons similar to HT, this will include specialty icons which are used for some SE. I had a quick look and I could find most of icon files except the ones related to specialty. When I llok at that page it seems the icon are from police listed in CSS style document. I don't know anything about it, maybe you can have a look ....

**Comment by akasolace** [comment]
It will be treated as part of #309

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/72204842-829ae600-347c-11ea-8a65-e4fe16dffd64.png)

@akasolace hi, i merged your changes and found this half red cross in my player overview. if i rescale this column everything looks fine. but i think, it should be displayed completly even it i don't rescale the column.

**Comment by akasolace** [comment]
fixed the first one

![image](https://user-images.githubusercontent.com/1136496/72209890-0cb27100-34b4-11ea-82bc-564fc5309f18.png)

**Comment by akasolace** [comment]
also replaced 999 with infinity symbol
