### ISSUE TITLE
[eBUG] Missing Download match orders

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#266]
I set an order for an player who will be substitute to 85 min if the match is in advantage for more 1 gol.
This order in HP doesn't download.
HT:
![image](https://user-images.githubusercontent.com/15519907/67643107-c9644f80-f913-11e9-9c0c-054276ee57e3.png)

HO:
![image](https://user-images.githubusercontent.com/15519907/67643098-ac2f8100-f913-11e9-8621-da9eedeb52e2.png)

**Comment by DavidatorusF** [comment]
@mistermax80 
what is the position of the player ? on the field and as substitute ?

**Comment by mistermax80** [comment]
GK

**Comment by DavidatorusF** [comment]
work for me... if it's the next match after updated my team

@mistermax80 
lineup -> upload/download tab; select the match and [download lineup], do you see your order ?

**Comment by mistermax80** [comment]
@DavidatorusF no, it doesn't work...
I made test from lineup -> upload. I tried in italian, english and french, same result.

**Comment by mistermax80** [comment]
I found the issue... if in HT you don't set the captain and kicker, the match orders will not download...

**Comment by akasolace** [comment]
closed by c1ab6b80376f1ab7190e14943e86863529962959

**Comment by akasolace** [comment]
once BETA 2 is released, we will test issue is fixed before closing it.
