### ISSUE TITLE
[eFEAT] Would be cool an uptuion to click for beta or stable

### ISSUE THREAD

**Issue by eskwire** [akasolace/HO#267]
**Is your feature request related to a problem? Please describe.**
Its not a problem but would say like a future that you could click a box ot something to get the stable or the beta version.

**Comment by akasolace** [comment]
@eskwire can you give more details? How that would differ from existing release channel menu?

**Comment by DavidatorusF** [comment]
@eskwire 

file -> preference -> tab [release channel]

I assume lambda managers will not use this

those who are curious and want testing or helping for development can use beta or dev channel

**Comment by akasolace** [comment]
I close the issue
@eskwire feel free to reopen it and provide additional information
