### ISSUE TITLE
[eBUG] IFA flag of recently added countries (Congo and Ethiopia) are missing

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#268]
**Describe the bug**
flag icon don't appear as well, actually it's [?] for DR Congo and Ethiopia

in the same time, DR Congo and Ethiopia are may be enough... in place of the full country name

**To Reproduce**
1. Go to 'IFA'
2. Click on [I]nfo in coolness
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/45043004/67699643-bce00580-f9ac-11e9-8933-1f5bb8525e65.png)

**Comment by akasolace** [comment]
relates to #262

**Comment by yaute74** [comment]
thank @akasolace you were faster than me :)

**Comment by DavidatorusF** [comment]
nice fix ^^

you forgot my suggestion: 
DR Congo and Ethiopia are may be enough... in place of the full country name

![image](https://user-images.githubusercontent.com/45043004/67792351-49f09080-fa79-11e9-86c5-a50ea48e2515.png)

**Comment by akasolace** [comment]
@DavidatorusF not sure where the name is coming from. I think it might be as it is referred on HT. I am traveling till the end of the week, hence I won’t have time to look at it... 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
