### ISSUE TITLE
Introduce minute base ratings 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#27]
next steps:

- [x]  introduce 90 minute average in ratings
- [x] change from int minutes to double 
     - ratings just after HT will be available at 45+EPSILON or  90+EPSILON
     -  match order set on a whole 5 minutes will be shifted by 2 EPSILON to be visible in the graphs 
- [x] put back ratings default to avg90  
- [ ]  t=0 ratings should be available using a switch
- [ ] change of GUI (do something HT style with graph showing evolution per minute, and sliders, ...)
- [ ] do testing and validate ( match orders, stamina effect formula, averaging ...)

**Comment by akasolace** [comment]
Part 1: @akasolace  derive formula and code refactoring => 99% complete
Part 2: @brokenelevator leverage part 1 features via GUIs  => WIP

**Comment by akasolace** [comment]
next steps:
  - [] reintroduce hatstats and loddarstats values (currently set to "0")  (it will default to t=0 for consistency)
  - [] introduce 90 minute average in ratings
  - [] should we default to t=0 or t=90 ?   (this will change anyway when @brokenelevator works on GUI)

**Comment by akasolace** [comment]
now weather impacts are considered in prediction ratings

**Comment by akasolace** [comment]
> introduce 90 minute average in ratings

@brokenelevator hello do you want me to do this or are you doing it?

**Comment by akasolace** [comment]
Hello @brokenelevator,

Do you have an idea will this one will be finished? This is the last open issue one before beta release !!

**Comment by brokenelevator** [comment]
Hi there,
I have been busy with things lately (couple months now) and not sure how it will be now.
I'd like to finish it by the end of coming week but I have no idea if I'll have time to work on it.

**Comment by akasolace** [comment]
Hi @brokenelevator, thanks for the update.
Looking forward to this commit !

**Comment by brokenelevator** [comment]
@akasolace So, here is an update about current situation. It is not done yet. The work in progress version is available on my account (charts branch).
I'll need few more days to finish it.

**Comment by akasolace** [comment]
@brokenelevator ok thanks for the update I will have a look at your branch

**Comment by brokenelevator** [comment]
@akasolace it has not been the best week, but progress is being made.
The branch is continuously updated.
I will not make another ETA. It simply will be done ASAP.

**Comment by akasolace** [comment]
closed by #248
