### ISSUE TITLE
[eFEAT] Add Value for Forward Technical Defense

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#272]
Add new evaluation for player has specialty technical

**Comment by akasolace** [comment]
it is implemented already. Can you give more details?

**Comment by mistermax80** [comment]
Where?
For eg, the formula for forward defence is different by formula for forward technical defence

**Comment by akasolace** [comment]
you can make the test:
take a player and look at his contribution as Fwd DEF. Then toggle on/off the tech specialty and you will see the contribution to adjust accordingly

**Comment by mistermax80** [comment]
Ok I will try, but if it is true, we should add a new parameters for formula in preference.
Otherwise we don't change for that.

**Comment by mistermax80** [comment]
Yes it work fine.
But we have not control on formula...

**Comment by akasolace** [comment]
> But we have not control on formula...

for sure it can be tweaked via the xml. I tought it would be also possible to do it via the GUI but maybe it is not.

**Comment by mistermax80** [comment]
Yes by gui preference is not possible.

**Comment by mistermax80** [comment]
@akasolace neither by xml, it is possible set the formula value for that.

**Comment by akasolace** [comment]
@mistermax80 what do you mean neither by xml ?  it is in the block <FW_D_TECH> ....

**Comment by mistermax80** [comment]
I didn't see, but I will do a new check!

**Comment by mistermax80** [comment]
I have not that tag.
Following, my export:
[formula.xml.txt](https://github.com/akasolace/HO/files/3801697/formula.xml.txt)

**Comment by akasolace** [comment]
@mistermax80  I guess the mapping is not done in the preference
but if you look in resources/prediction/defaults.xml  you will see it
