### ISSUE TITLE
[eBUG] Penalty takers

### ISSUE THREAD

**Issue by reaphil** [akasolace/HO#273]
**Describe the bug**
Penalty takers from HO! are not sent to Hattrick

**To Reproduce**
Define the penalty takers within HO and send the list to Hattrick.org. The penalty takers will not be taken over.

**Platform information:**
 - OS: Windows
 - Version 2.0 r1391

**Comment by mistermax80** [comment]
@akasolace I can not test this, I am not a supporter...

**Comment by akasolace** [comment]
@mistermax80 I will test tomorrow

**Comment by akasolace** [comment]
@yaute74 in case you have time to give a look at this one .... maybe it can be done for 2.0 instead of wait for 3.0 ....

**Comment by yaute74** [comment]
@akasolace Ok I will have a look ...when I have a moment

**Comment by akasolace** [comment]
thank you @yaute74  !!

closed by 9bb63b63e0cb811afe7422b571f39a49f21028bc
