### ISSUE TITLE
[eBUG] Issue on translate with apostrophe and {0} placeholder

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#277]
In italian lang this string:
`feedbackplugin.dataTooOld = I tuoi dati non sono recenti, l'ultimo aggiornamento è {0}. Aggiorna i tuoi dati da Hattrick (scarica).`
Appears:
![Schermata 2019-11-06 alle 23 49 24](https://user-images.githubusercontent.com/15519907/68345263-3ab0b900-00f1-11ea-8351-f21aec8f067f.png)

modifing the code as following, the message appears correctly traslated.
`feedbackplugin.dataTooOld = <html>I tuoi dati non sono recenti, l&rsquo;ultimo aggiornamento è {0}. Aggiorna i tuoi dati da Hattrick (scarica).</html>`

@akasolace 
I think, it can a issue on the java/text/MessageFormat.java uses for traslate message, but I didn't see if fix in message format or modify the text in poeditor.
What do you think?

**Comment by akasolace** [comment]
> In Italian lang this string 

I guess this is non specific to Italian but should affect other language (to be confirmed)

@mistermax80  Why would the following not be enough ?

`feedbackplugin.dataTooOld = <html>I tuoi dati non sono recenti, l&rsquo;ultimo aggiornamento è scarica. Aggiorna i tuoi dati da Hattrick.</html>`

**Comment by mistermax80** [comment]
sure It is not a issue on italian, but there is apostrophe and placeholder.

**Comment by akasolace** [comment]
@mistermax80 have you read my previous message ? I think it just come down to translating the variable name. If it is unclear to you, I can fix this tonight.

**Comment by mistermax80** [comment]
"download" is not a variable, it is only text. do you think the HO read "download" as an variable?
If you try italian lang and remove the apostrophe in the sentence, it works fine, for this I think the issue is the apostrophe and placeholder {0} in the same sentence.
Anyway, in this moment I don't know how to resolve, so if you have time, you can try.
Thanks.
