### ISSUE TITLE
[eBUG] training estimation does not consider secondary cups

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#278]
**Describe the bug**
players who were aligned this Wednesday for the Ruby cup do not appear has being trained

**Comment by akasolace** [comment]
@yaute74  I assigned it to you because this is "your" part of the code :-)
I set the milestone for 3.0, so there are no urgency here

**Comment by yaute74** [comment]
@akasolace ok I will check it

**Comment by akasolace** [comment]
closed by bb8613c731f2ab8f4c754a488dc3c851f50ac509
