### ISSUE TITLE
[eFEAT] ideal position: absolute contribute vs individual performance 

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#282]
The new individual performance is creating some confusion some users:
![image](https://user-images.githubusercontent.com/15519907/68596199-2414b400-049b-11ea-8118-006707bd5be9.png)

My proposal is:
- insert the individual performance value (%) in all screen where it is visible the "ideal position" column
- insert news preference in order the user can select which value wants see: absolute contribute or individual perfromance value

following, reported the screens where it is visible the ideal position column:
*** in player overview ***
1)
![image](https://user-images.githubusercontent.com/15519907/68596199-2414b400-049b-11ea-8118-006707bd5be9.png)
2)
![image](https://user-images.githubusercontent.com/15519907/68596469-91c0e000-049b-11ea-9eb0-76a89aa943e3.png)
3)
![image](https://user-images.githubusercontent.com/15519907/68596520-aa30fa80-049b-11ea-8b03-26bb5dfa45ad.png)
*** in lineup tab ***
4)
![image](https://user-images.githubusercontent.com/15519907/68596693-e6645b00-049b-11ea-9d2d-e7fca8bbb3ef.png)
*** in player analysis ***
5)
![image](https://user-images.githubusercontent.com/15519907/68596756-0562ed00-049c-11ea-8ec9-2323a4731493.png)
6) player compare
![image](https://user-images.githubusercontent.com/15519907/68597103-ad78b600-049c-11ea-9b6b-6189555fa3a9.png)

![image](https://user-images.githubusercontent.com/15519907/68597161-c5503a00-049c-11ea-9e75-a13469ceeda0.png)

*** in training tab ***
7)
![image](https://user-images.githubusercontent.com/15519907/68596920-570b7780-049c-11ea-8a05-97b234ccb4af.png)

**Comment by akasolace** [comment]
for sure we can make sure it is consistent in all screen
Everywhere it refers to ideal position it should be using the relative performance in %, otherwise it should be the absolute contribution

**Comment by mistermax80** [comment]
Consider also the logic beside #213

**Comment by akasolace** [comment]
To be changed in 

**1 Player Details:**

![image](https://user-images.githubusercontent.com/1136496/70265381-8ad77580-179a-11ea-9144-5f3f57d84bf3.png)

**2 Skill Tester:**

![image](https://user-images.githubusercontent.com/1136496/70265491-cf631100-179a-11ea-9815-2fab23a69b50.png)

**3 Player Compare:**

![image](https://user-images.githubusercontent.com/1136496/70265595-06d1bd80-179b-11ea-8cf2-e5b45cc5ef61.png)

**4 Transfer Scout:**

![image](https://user-images.githubusercontent.com/1136496/70265656-2832a980-179b-11ea-84f2-6a26ac3d9c39.png)

**5 Training Tab:**

![image](https://user-images.githubusercontent.com/1136496/70265747-59ab7500-179b-11ea-8cd1-fe8d9449f051.png)

**Comment by mistermax80** [comment]
Ok, I can work on this, I put in my queue 😄 

I think we should find a way to explain to user the difference between the both value.

**Comment by akasolace** [comment]
@mistermax80 I already assigned it to me.
I am almost done with this one.

**Comment by akasolace** [comment]
closed by ff95aaa

**Comment by mistermax80** [comment]
@akasolace so, this beaviour is not configurable in user preference.
Why do you think is not need?

**Comment by akasolace** [comment]
@mistermax80 which behaviour?

**Comment by mistermax80** [comment]
if ho shows the individual performance vs absolute contribute (in that cells)

**Comment by akasolace** [comment]
no HO continue to show both, the problem was that for best position it was using absolute contribution which was incorrect.
