### ISSUE TITLE
[eBUG] manage new division battle match  icon + game specifics

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#284]

**Comment by akasolace** [comment]
@pierpaolocira  @yaute74 @brokenelevator  @konved  has any one of you time to look at it ?

**Comment by akasolace** [comment]
Actually I am not even sure there is something to be done here, looks like a league tournament match .... what do you think ?

![image](https://user-images.githubusercontent.com/1136496/68619228-550cdd00-04cb-11ea-9c5b-37aeab08688d.png)

**Comment by yaute74** [comment]
@akasolace I can have a look on this next week

**Comment by yaute74** [comment]
@akasolace you are right, for division battle match, CHPP return code 50 for MatchType, same ID than for tournament. 
But after some tests it seem to works, so just an icon problem

**Comment by akasolace** [comment]
@yaute74 but then how to differentiate them to allocate the right icon ?

**Comment by yaute74** [comment]
@akasolace I don't know if it's possible :(

**Comment by mistermax80** [comment]
I think, the HT in the future add a new chpp for the tournament details and maybe the match I'd will change...

**Comment by akasolace** [comment]
@yaute74 @mistermax80 I will ask HT devs

**Comment by akasolace** [comment]
I just asked the devs, in the meantime I thought that maybe match timestamp might be sufficient to identify them. To be confirmed

**Comment by yaute74** [comment]
We can create a tournament when we want, no ? So I think we can create a tournament at the same hour

**Comment by akasolace** [comment]
@yaute74  according to devs, to identify them we can use Tournament type 10. Can you have a look? I think we should close this one before 2.0. If you have no time I can assign it to myself. Let me know ..

**Comment by akasolace** [comment]
closed by b8a1c79
