### ISSUE TITLE
[eFEAT] Add in transert tab, current bid information

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#285]
we can use this API:
https://www82.hattrick.org/Community/CHPP/NewDocs/File.aspx?name=currentbids

in order to show:
- Shows all active, recently finished or hotlisted transfers for the specified team.
- Removes the tracking of a specific transfer, for Supporters only. Only possible for losing bids, hotlisted and finished.
- deleteAllFinished - Removes the tracking of all finished transfers in one go, for Supporters only.

**Comment by DavidatorusF** [comment]
sincerely, I think Mercattrick did this job... not sure HO have to do the same

https://www.hattrick.org/goto.ashx?path=%2FCommunity%2FCHPP%2FChppProgramDetails.aspx%3FApplicationId%3D4953

**Comment by akasolace** [comment]
I tend to agree with @DavidatorusF, I am not sure this what we should focus on.
Mercattrick did a pretty good job at it.

**Comment by mistermax80** [comment]
Ok I will check, I don't know that tool.

**Comment by mistermax80** [comment]
Hi guys, I saw that tool, it is fantastic, I didnt know.
My idea is that, an tool for supports the manager in the buy process.
We can close this issue.

Thanks so much.
