### ISSUE TITLE
[eBUG] Ho doesn't calculate the skill drop

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#286]
I don't undastand if HO calculate the skill drop, but there are some part of the code that seems treat this.

Guys, do you know about this?

**Comment by akasolace** [comment]
It is supposed to be considered ... I will check that this weekend

**Comment by mistermax80** [comment]
ok thanks @akasolace !

**Comment by akasolace** [comment]
@mistermax80 for me it is working ...

**Comment by mistermax80** [comment]
@akasolace how do I check if it works?
Clould you send me an screenshot?

**Comment by akasolace** [comment]
@mistermax80, I just see that skills are decreasing for my "old" players. I just selected previous HTRF and in player tab. I can paste screeenshots tonight.

**Comment by mistermax80** [comment]
@akasolace If you are refering to the different value between different HRF, no it works fine, I 'm referring to the prediction to skilldrop, in order to predic the effect skilldrop for old players...

**Comment by akasolace** [comment]
ah you mean like training prediction ... to see how fast skill will drop for old players ?
in that case no this is not implemented

**Comment by mistermax80** [comment]
yes I mean like training prediction... but I saw some part of code that treat this, I think old code, and maybe not sill used....
I like to have the skilldrop prediction, usefull also when I buy the players....
So I see the code and I will find beacuse it doesn't work or beacuse it dismissed.

**Comment by akasolace** [comment]
@mistermax80 ok

**Comment by mistermax80** [comment]
@akasolace 
HO calculate the skilldrop in order to indicate the accurate skill value (in current week) and predict training, but doesn't exist a functionality for predict the skilldrop.

We can use the function already present in order to predict the skill drop.

**Comment by akasolace** [comment]
@mistermax80 ok for me

**Comment by mistermax80** [comment]
We can inspire to this tool...
http://ht4u.altervista.org/

**Comment by wsbrenk** [comment]
@akasolace What do you think of an expansion of the training forecast table? One could enter the calculated skill devaluations there.

![grafik](https://user-images.githubusercontent.com/11821502/79118057-0e2e5680-7d8d-11ea-906d-222e5c8faec3.png)

**Comment by akasolace** [comment]
@wsbrenk  yes I guess that would be the most natural place to show that information ...

**Comment by wsbrenk** [comment]
progress report:

this is what i reached up to now:
![grafik](https://user-images.githubusercontent.com/11821502/79640612-c21b5180-8192-11ea-9f9a-37f1f451cebd.png)

the color of the skill drops is not OK
and the first column of the training history table is no longer the type of training but the skill that changed

the many skill drops in the first week are a bit ugly, with all the unknown sub-skills (0)

**Comment by akasolace** [comment]
@wsbrenk 

I notice you have skill dro pfor player wwo are less than 27 ... is that really possible ?
maybe you can remove the skill description in letter and replace it with the digit
Then up and bottom arrow green / red and the skill (either in black or in color) something like
| 12 Playmaking     and  | 6 Passing
First case the bar represents a green top arrow  ....
Second case the bar represents a red bottom arrow  ....

What do you think ?

**Comment by wsbrenk** [comment]
@akasolace cite from SkillDrops.getSkillDrop:
		/* First column is for age 29 and below */

concerning display am i investigating the magics of HO's icon colors

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/79695711-b5712900-8278-11ea-9630-7caa0612cb7a.png)

>I notice you have skill dro pfor player wwo are less than 27 ... is that really possible ?

you were right, the age calculation had an error - now it looks better
the color of skill drops is now the same as of skillups

skill drops could be more than one in a week. Currently only "the upper" one is displayed.
the training history table should be optimized too.

**Comment by wsbrenk** [comment]
progress for today (morning):

![grafik](https://user-images.githubusercontent.com/11821502/80278029-736e3a00-86f3-11ea-8222-1d8735d067f9.png)

- training history table shows icons
- sub skill values are displayed in both tables (history and recap). .00 sub skills are definatly unrealistic for skill drops

further possible improvements:
- the first 3 colums of recap table are not resizable in forecast panel

@akasolace @tychobrailleur: any other idea i should do?

**Comment by akasolace** [comment]
@akasolace @tychobrailleur: any other idea i should do? 

@wsbrenk looks good to me as it is really ....

**Comment by tychobrailleur** [comment]
> @wsbrenk looks good to me as it is really ....

Yeah, same here – I am not entirely sure what the issue is, if any.
