### ISSUE TITLE
Exclude HTOIntegretad games at download

### ISSUE THREAD

**Issue by murko69** [akasolace/HO#290]
A feature request - as asked in [16904776.98](https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D16904776%26n%3D98%26v%3D4)
-----------------

I really seldom play HTOIntegrated games (ladders, tournaments) but now and then I participate in the tournaments in between seasons and now also the division battles are included and I thought that was a great feature, but I really don't want these games to be included on the matches tab in HO.
I delete these every season, but as long as they show up in recent matches on HT they will be added in HO

I could uncheck recent matches in HO I guess (?) but is it possible to make an exception instead?

See image 
![hto](https://user-images.githubusercontent.com/12071221/69484650-2af5dc00-0e36-11ea-801e-64cf6a1c9bd2.png)
If checked __don't__ download matches with "SourceSystem=HTOIntegrated"

edit:typo

**Comment by akasolace** [comment]
@wsbrenk @DavidatorusF do you think this is a good idea and should be considered for 3.0 ?

**Comment by wsbrenk** [comment]
@akasolace I think the idea is not bad, but I would prefer a filter tree instead of an exclude. A Folder "match data" could have match type specific sub selections.

since some days i'm looking for a java tree view selection solution.

**Comment by murko69** [comment]
> 
> 
> @akasolace I think the idea is not bad, but I would prefer a filter tree instead of an exclude. A Folder "match data" could have match type specific sub selections.
> 
> since some days i'm looking for a java tree view selection solution.

I like that idea. It gives a lot more options to disable/enable download of any specific game type you'd like, rather than just to exclude HTO-matches 100%.
Maybe someone doesn't want friendly games but do want the division battle games (if I understood corectly)....

**Comment by akasolace** [comment]
> @akasolace I think the idea is not bad, but I would prefer a filter tree instead of an exclude. A Folder "match data" could have match type specific sub selections.

since some days i'm looking for a java tree view selection solution.

@wsbrenk  that sounds a good approach. Maybe you can open a feature ticket and I will link this one to the newly created ... cheers !

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/77852593-bebe2700-71df-11ea-9b85-c581cd92d5a6.png)

with the help of @tychobrailleur i did some preliminary steps

**Comment by akasolace** [comment]
@wsbrenk I like it a lot !
nice work !

**Comment by wsbrenk** [comment]
@tychobrailleur today i'm looking for some hours how to set the text of the node so that no ellipsis will occure. Read something about nodeChanged which should be called. Up to now i didn't manage it. Could you please give me a tip how to do that.

**Comment by tychobrailleur** [comment]
> @tychobrailleur today i'm looking for some hours how to set the text of the node so that no ellipsis will occure. Read something about nodeChanged which should be called. Up to now i didn't manage it. Could you please give me a tip how to do that.

Yes, of course.  I did a bit of digging as well, and [this](https://gist.github.com/tychobrailleur/8d691bb9c28dc41a9b04a279b3760fe1) seems to work.

![Screenshot 2020-04-04 at 15 09 07](https://user-images.githubusercontent.com/114285/78452917-43002680-7686-11ea-83bc-763d678ba7bd.png)

**Comment by wsbrenk** [comment]
@tychobrailleur great - thank you

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/78473577-0db90e80-7742-11ea-9e8a-22b9912348d2.png)

found a downloadPanel in OptionenDialog which has to be adapted too.

**Comment by wsbrenk** [comment]
Currently the selection in the download dialog is not saved, instead the settings in the options dialog are used when DownloadDialog is initialized.

Should we change this or keep it as it is (with modified OptionenDialog)?

**Comment by akasolace** [comment]
I guess the best / most natural would be:
   1) include the check bock  "show save dialog ... HRF"  in the dialogue panel
   2) store the selection in the download dialog is not saved in the database
   3 remove the download tab from preference

@wsbrenk what do you think?

**Comment by wsbrenk** [comment]
@akasolace sounds very good. But i have to find out, what that "Show save dialog..." means. I speculate that it activates the display of the download dialog, so we could not include it to the download dialog. with your suggestion it would be enabled and could not be disabled anymore.

**Comment by wsbrenk** [comment]
@akasolace my speculation was wrong. this checkbox only controls the appearance of a file selection box for hrf file store, if standard file already exist or no path for the hrf storage is set.
So your idea could be implemented.

**Comment by akasolace** [comment]
@wsbrenk ok great

**Comment by wsbrenk** [comment]
@akasolace Slowly comes the time that you have to explain to me how it works with the international strings. is it only by introducing a property name and moving the english string to the file English.properties?

**Comment by akasolace** [comment]
@wsbrenk surprised you haven't encountered it yet

yes you simply enter a new term in main/resources/sprache/English.properties 
let say  `ls.foo =bar` then you can access it with `hoVerwaltung.getLanguageString("ls.foo")`
translations are done via PoEditor, so do not touch German files because you will loose it next time I build artefacts.  Also if the translated term is not found it uses English. 
The new terms are available for translations next time I do artefacts.

**Comment by akasolace** [comment]
@wsbrenk  I assigned to you as I know you are about to push some code that is fixing it ...

**Comment by akasolace** [comment]
closed by #440
