### ISSUE TITLE
[eFEAT] Sorting position and strengh

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#293]
When you sort, the strengh it is not consider for sorting:
![image](https://user-images.githubusercontent.com/15519907/69820735-1cc30980-1202-11ea-957e-15f9717eb4c3.png)

**Comment by mistermax80** [comment]
![image](https://user-images.githubusercontent.com/15519907/69822567-fb185100-1206-11ea-97a9-cd647a1299e8.png)

**Comment by mistermax80** [comment]
By d99783e666230d11f2326ea0130b5eaaaa1bf17b
I had in head for just do in training tab.
![image](https://user-images.githubusercontent.com/15519907/69822658-361a8480-1207-11ea-9600-1090ce7fdcb4.png)

**Comment by akasolace** [comment]
closed by b8e9f4b90248961f8ca47ff3c795d81b4bcaf386
