### ISSUE TITLE
[eFEAT] substitution calculator

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#294]
As the tool https://github.com/tagliala/StaminIA 
http://lizardopoli.altervista.org/staminia/
integrated in HO in lineup tab.

**Comment by wsbrenk** [comment]
@mistermax80 @akasolace concerning this feature i have the idea to pass the current lineup to the SubstitutionEditView and recalc the ratings when the substitutions are changing, especially when the minutes/when-slider is changed.
If we display hatstats in the View, the user could easily find the best minute when the substitution should happen.
What do you think?

there maybe one problem if rating recalc is not fast enough to keep the when-slider responsive enough.

**Comment by akasolace** [comment]
substitutions are already considered in prediction rating calculation.  Which kind of GUI do you exactly imagine ?

**Comment by wsbrenk** [comment]
the SubstitutionEditView is this one:
![subseditview](https://user-images.githubusercontent.com/11821502/73309648-e82ff600-4222-11ea-87ee-ede8b7f58235.jpg)

The aim of the feature is to find the best minute for the exchange. I would add two additional fields.
 First will display the initial ratings of the lineup before the substition is edited, the second one should be updated each time one part of the substitition is changed, especially the minute, when the change should happen. On this way the user could easily find the optimal time for the exchange.
I guess that meets the idea of ​mistermax

**Comment by akasolace** [comment]
ok I see looks good to me

**Comment by wsbrenk** [comment]
![subseditview](https://user-images.githubusercontent.com/11821502/73590483-252a1000-44e3-11ea-8007-580ff668a7dd.jpg)

current status. fine tuning of minutes increases the overall hatstats by 1 point.

**Comment by akasolace** [comment]
would we see the change of HatStats when we first introduce the subtitution ?

**Comment by wsbrenk** [comment]
>would we see the change of HatStats when we first introduce the subtitution ?

yes of course. the "old" hatstats value would be the average without substitution. the new value is displayed when a valid substition or position change is entered, both players are given for example.

**Comment by wsbrenk** [comment]
I'm almost done with this feature. However, swapping positions and new behavior have no influence on the calculated ratings. Is that correct? it only works with normal substitutions.

**Comment by akasolace** [comment]
> swapping positions and new behavior have no influence on the calculated ratings. Is that correct? it only works with normal substitutions.

yes this is correct, it still need to be implemented (cf:  begining of function setLineupEvolution https://github.com/akasolace/HO/blob/92efca10c171e6511987da238ca9045f30f90a4d/src/main/java/core/rating/RatingPredictionManager.java#L114)

... I create a ticket for this.

**Comment by akasolace** [comment]
It is working well but I have now huge amount of warning messages when I compile with the IDE, is it the same for you ?
