### ISSUE TITLE
[eBUG] decimal negative difference missing in player panel

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#295]
![image](https://user-images.githubusercontent.com/15519907/69836444-17d57880-1249-11ea-9579-f48228ad2e01.png)

![image](https://user-images.githubusercontent.com/15519907/69836453-2ae84880-1249-11ea-81fd-a6efe5c15e24.png)

**Comment by akasolace** [comment]
@mistermax80 I don't get what is the issue here ... can you give me more info ?

**Comment by mistermax80** [comment]
Issue not important, but if you see my screenshot (refer both same player) you can notice in the first there is the negative different are marked, but in second are reported only positive differences.

**Comment by akasolace** [comment]
@mistermax80 ok I see now. Also what is wiered is that REGIA is 1.80 on one screenshot and 1.79 in the other !
