### ISSUE TITLE
CHPP Error 59 [eBUG]

### ISSUE THREAD

**Issue by SortePlov** [akasolace/HO#304]
Just recently, I've been having this new error, when trying to download from Hattrick:
"CHPP Error 59 - (59) - Additional info: The supplied teamid does not refer to a team managed by the requesting user".

The error comes up three times in a row, when it's attempting to fetch different data files - and then bombs out with a NULL exception, probably due to having no data to work on.

I tried updating to HO 2.0, but the issue persists.

I tried removing the authorization under "Preferences::CHPP products", but it made no difference whatsoever, as I get the exact same errors.
You would think that it would re-initiate a CHPP authorization process?

Platform: Windows 7
Version: 0.1437.1393 and 2.0.1458

**Comment by SortePlov** [comment]
[HO-2019-12-06.log](https://github.com/akasolace/HO/files/3943865/HO-2019-12-06.log)

**Comment by akasolace** [comment]
@SortePlov I had no time yet to look at it. Can you try the following just in case:
   1) make a backup of the db folder
   2) remove the authorisation  under "Preferences::CHPP products"
   3) delete HO and make fresh install
   4) start HO and fetch data
   5) close HO and restore the db folder you saved at step 1
   6) start HO again and see if it still works

**Comment by SortePlov** [comment]
Followed your steps and installed the latest HO 2.0. After restoring the db folder (moving the old 'db' files back into the new installation), I fire it up and get the exact same errors as described.

**Comment by akasolace** [comment]
@SortePlov ok thank you for confirming the issue
@yaute74 when you worked on NTHRF issue I think you had to run db from another user, right? Just to confirm whether or not this is feasible, as I am not sure otherwise how I can replicate the beahviour ...

**Comment by yaute74** [comment]
@akasolace no, I send jar with debug info to the user

**Comment by akasolace** [comment]
@yaute74 would you mind looking at that one when you got some time, maybe it is similar to issues you have been working on previously ...

**Comment by yaute74** [comment]
@akasolace I have no idea of the problem and I don't think it's similar because it was specific to NT team.
@SortePlov do you have the problem with a clean database (after import hrf files, if you have them) ?

**Comment by SortePlov** [comment]
If I try to download on a fresh database with nothing in it, it seems to work.

**Comment by SortePlov** [comment]
If I subsequently import all my HRF files (over ten years worth), it also seemingly works with downloading afterwards.

**Comment by yaute74** [comment]
@SortePlov  ok great :)

**Comment by akasolace** [comment]
ok good so I will close that issue
