### ISSUE TITLE
[eBUG] Installation On Mac OsX

### ISSUE THREAD

**Issue by dade1333** [akasolace/HO#305]
**Describe the bug**
When I install on Mac and click on the installer to launch the programme, I receive the following error message "JRE Load Error" (see screenshot)

**To Reproduce**

**Screenshots**
![image](https://user-images.githubusercontent.com/58575763/70283974-b53d2900-17c2-11ea-823d-a8a5b84ff16e.png)

**Platform information:**
MacOs Mojave
Version 10.14.6

**Additional context**

**Comment by akasolace** [comment]
@dade1333 do you have a proper installation of Java? It needs version 8 at minima.

**Comment by akasolace** [comment]
@dade1333 any follow up ? otherwise I will close the ticket.

**Comment by dade1333** [comment]
@akasolace yes you were correct. I was missing the latest Java installation. Thank you for support

**Comment by akasolace** [comment]
@dade1333 ok thanks for the update, I close the issue then
