### ISSUE TITLE
[eFEAT] Special Events

### ISSUE THREAD

**Issue by DavidatorusF** [akasolace/HO#309]
**Is your feature request related to a problem? Please describe.**
can you add all the missing SE in module "Special Events"

**Comment by akasolace** [comment]
I started to work on this one yesterday and it is actually a big one.
I have to refactor MatchHiglight class. When this is done I will work on a match report similar to what Foxtrick provide (cf #339)

I will continue to work on it but maybe it will make sense to have it for 3.0 considering the big refactoring and that 2.1 should be more focus on small bug fixes ...

**Comment by akasolace** [comment]
step 1 is #344

**Comment by akasolace** [comment]
I think all Special Events are now included, @DavidatorusF do you see something to be changed or added? The problem I see are more GUI related:
    - the lines height which are not automatically adjusting to the match event icon height
    - maybe we can remove columns Match-ID and the 2 columns with the black arrow
    - we could also merge Match Date and icon and make the icon clickable to match tab (as already done by @steffanots in player analysis module)

Anything else ?
