### ISSUE TITLE
doesn't work the functionality update "rating prediction formula"

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#31]
I don't know if It was disable, If yes why?
Following the 2 case:
1) the correct situation:
![schermata 2018-12-10 alle 11 41 42](https://user-images.githubusercontent.com/15519907/49728258-8a34fd80-fc72-11e8-81ce-5b2f60603020.png)
2) the incorrect situation:
![schermata 2018-12-10 alle 11 44 29](https://user-images.githubusercontent.com/15519907/49728342-bbadc900-fc72-11e8-99cd-d3a29d7aad5c.png)

**Comment by akasolace** [comment]
I just disable it with one of my latest commit: 12e1b320794008890dbb07d6c798c76a8ca0601b
If you pull latest change and build, you will see the option disappeared from the menu.

I do not think this option was making sense anymore because the formula are really tight to a given HO version. I would have required to mainain a dictionary of ratings know to work for certain version. It would have been a lot of work for little added value, at least in my opinion.

**Comment by mistermax80** [comment]
ok, but m question is:
Is it the better version 7 or the version include in dev branch?
After update to version 7 I saw only default, In dev branch I saw more version...
I don't understand what prediction to use.
Could you help me to understand?

**Comment by akasolace** [comment]
@mistermax80 

to be honest, I am not sure I fully understand your question.
Prediction ratings have not been updated for a while ( it will be the big focus of version 1.436, and if you are up to it, we can work together on this one as it may be a big new feature but gonna also be interesting).
In you prediction folder, you should have default, default(1426), newB if I recall correctly.  This should be true for 1.434, and 1.435dev7. Personally I made some quick test and I prefer to use default but some users are preferring newB.  As said, I hope that 1.436 will greatly improve that.

If you are keen in staying evolved for 1.433, should we use setup gitter to discuss topic without polluting the issue tickets on GitHub?

Let me know.

**Comment by mistermax80** [comment]
@akasolace 
Ok, You are more clean than me... sorry but my english is rusty...
Now I understand the cause for disabling.

> should we use setup gitter to discuss topic without polluting the issue tickets on GitHub?

Ok I'm agree with you for doesn't pollution issue tkt on github... but Could you explain what's gitter?

**Comment by mistermax80** [comment]
I prefer to use slack. How do we do for this? Do you know? Else I can try to study it.

**Comment by akasolace** [comment]
I just googled some comparison of the different services and it looked like people are recommending discord. Can you also have a look and shared your thoughts? 
If you really have a preference for slack it is fine for me but what I read is that their free plan is quite limited (they delete old chats) which is quite bad, no ?

**Comment by mistermax80** [comment]
I have not specific preference, in my company in more people uses slak, but maybe beacuse there is a specific buiness plan.
We can use discord, I say... We try it!!!

**Comment by akasolace** [comment]
@mistermax80 
ok perferct lets try this, should I let you take care of setting it up as you proposed ?

**Comment by mistermax80** [comment]
I'm registered, you should do it. After I Will invite in HO! Server! :)
