### ISSUE TITLE
[eBUG] Training Preview shows wrong training

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#311]
SetPieces Training.

HT situation in half week (after match league and before cup/friendly match):
![image](https://user-images.githubusercontent.com/15519907/70444114-ad6ad680-1a99-11ea-910e-603d1d3f9df0.png)
HO situation:
![image](https://user-images.githubusercontent.com/15519907/70444241-e014cf00-1a99-11ea-8c39-c62c8169673e.png)

**Comment by yaute74** [comment]
@mistermax80 do you test with this modification #308 ?

**Comment by mistermax80** [comment]
@yaute74 now I have a doubt... I will know you.

**Comment by mistermax80** [comment]
@yaute74 
current situation with last code:
HO:
![image](https://user-images.githubusercontent.com/15519907/70516050-90d0ac00-1b36-11ea-8a6d-57349c040245.png)

HT:
![image](https://user-images.githubusercontent.com/15519907/70516107-ae057a80-1b36-11ea-99db-595372f15742.png)

**Comment by yaute74** [comment]
@mistermax80 reproduce, I do a PR

**Comment by akasolace** [comment]
closed by bfc9e18
