### ISSUE TITLE
[eBUG] error reloading saved match lineup

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#316]
Set pieces taker will not be reloaded if one load the lineup stored by the user in the lineup panel

1. Go to lineup panel
2. Select set pieces taker
3. Select load/reload panel (discette on the right sight)
4. Select save lineup
5. Select load lineup
6. Set pieces taker slot is empty
![err](https://user-images.githubusercontent.com/11821502/70740493-92a69500-1d19-11ea-9f91-1b74d4d40139.jpg)

**Platform information:**
 - OS: [Windows]
 - Commit: 75a5a5c87d1197fcf4ce225976bcbc099afa3ff9

**Comment by akasolace** [comment]
closed by 6e15b3390fd2605077c1eddccf8a1e3488927775
