### ISSUE TITLE
[eBUG] unexplained difference in contribution in skilltester tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#317]
**Describe the bug**
when loading a new player, the performance o the player seems slightly off

![image](https://user-images.githubusercontent.com/1136496/70850238-7aa15380-1e88-11ea-9ff6-cce759f359e6.png)

**Comment by mistermax80** [comment]
I know. The difference is in some case the position values is calculated with 2 decimal positions in other case the round is applied after the calculation

**Comment by akasolace** [comment]
@mistermax80 I only looked at it quickly but I am not sure this is a question of rounding ... tbc

**Comment by akasolace** [comment]
actually there is no bug, it is simply that skill decimals are not considered as per the values in the combobox
