### ISSUE TITLE
[eBUG] training page not analyzing old matches

### ISSUE THREAD

**Issue by AchimGrube** [akasolace/HO#319]
**Describe the bug**
I've set up a new computer and tried to use HO without copying the old database. After downloading all matches and league data ranging back to 08-2014, I've had all my data back in the HO database. So far, so good, but when I clicked on the training tab, no data was present but the actual training week. Even when recalculating sub-skill or importing some matches by hand, no history is shown and every player has a sub-skill of x.00

**To Reproduce**
1. make fresh installation of HO
2. download all data from HT
3. go to training tab
4. miss training history

**Screenshots**
![matches](https://user-images.githubusercontent.com/12234126/70929582-b3316080-2033-11ea-825a-9fb4a6112739.PNG)
![training](https://user-images.githubusercontent.com/12234126/70929175-c3950b80-2032-11ea-9c17-3305aff5cd4a.PNG)

**Platform information:**
 - OS: windows
 - Version: 10 (17763.914)

**Comment by yaute74** [comment]
@AchimGrube it's normal, it's not a bug. Hattrick don't send the training of each weeks.
You need to import our old hrf files (if you kept them).

**Comment by AchimGrube** [comment]
Oh okay. I thought it would be possible to calculate the training history by checking the minutes played for each player on the relevant positions.

**Comment by yaute74** [comment]
We have the minutes played but not the training.
It's a good idea to keep hrf files :)
