### ISSUE TITLE
[eBUG] Module matches "show my cup games" is faulty

### ISSUE THREAD

**Issue by murko69** [akasolace/HO#320]
When I go to modlue "Matches"  and chose option "Show My Matches" the first tab shows me a list of the 1914 games (+ a few upcoming) I've chosen to leave in HO - I delete all HTOIntegrated games - see my feature request #290 about that :) .

So far so good. Everything is correct on this option. I can see this seasons cup games - 3 from national cup + 2 from Sapphire Cup (see image below)
 ![ho1](https://user-images.githubusercontent.com/12071221/71005381-dfa4b580-20e3-11ea-9c80-46a05696142d.png)

Now I change the option to "Show My Cup Matches" instead.
I get a list of 254 games. That's not correct.
I have a total of 256 cup games played (226 national, 3 Emerald, 12 Ruby, 12 Sapphire and 3 Consolation cup games)
All but the last two played cup games (this seasons 2 Sapphire games) are shown. (see image)
![ho2](https://user-images.githubusercontent.com/12071221/71006165-32cb3800-20e5-11ea-9028-c6f8e458973b.png)

Just compare the two images and you'll see my last two are missing in the second image.
The second image also show that the matchTyp all show the same icon for all cup games (and that's not correct either)

I don't know if you should add options here like "Show ALL My Cup Matches", "Show Nationsl Cup Matches", "Show Emerald........." etc and get all the icons correct, but for now my MAIN ISSUE is that HO somehow refuses to show my two Sapphire cup games from THIS season under "Show My Cup Matches"

**Comment by murko69** [comment]
@yaute74 I made a database cleanup as we talked about in HT-mail.
I removed all matches and then downloaded old matches from my start (2000-11-19) so it took a while :)

The issue is pretty much the same as mentioned above 
I should have 256 cupmatches total shown, but earlier today I only saw 254 (this seasons sapphire games was gone)

After the db cleanup I only have 226 cup matches total. That's equal to my total national cup matches so **all** Secondary Cup matches are now missing from option Show my Cup Matches instead.

I'm guessing this is more "correct" and what is now needed is for you to actually add a filter also for the secondary Cups?

**Comment by yaute74** [comment]
@murko69 
So it's normal to have only national cup match.
I create a filter for secondary cups match, so for me there is no bugs.

**Comment by murko69** [comment]
Thanks.
I close this one and hope the new filter(s) will fix this

**Comment by murko69** [comment]
I know this is a closed issue, but instead of creating yet another one I'd like to just comment on this one.
Using BETA 2.1 and I see that secondary cups and qualification games are actually added as filters on Matches-TAB, which is great but.....
Would it be possible to actually show all secondary cup games separately instead of mixed together? Meaning: Adding filters for Emerald, Ruby, Sapphire and Consolation instead of just the one "Secondary cups" -filter!

I for one would love the see history of a each and every one of my game-types (including "the four sub-types" of the secondary cups)
I know some countries have different names for them, but that's up to the translators to name them Apollo or whatnot :).

The original names for them are always:

- Challenger cup (Emerald)
- Challenger cup (Ruby)
- Challenger cup (Sapphire)
- Consolation cup
