### ISSUE TITLE
[eBUG] Hatstats and Loddastats incorrectly displayed

### ISSUE THREAD

**Issue by propivo** [akasolace/HO#321]
**Describe the bug**
Hatstas and Loddastats are not displayed correctly in the "TeamAnalyzer" tab. Both are displayed as "0" (the number zero)

**To Reproduce**
1. Go to 'TeamAnalyzer'
2. Click on 'Analyze'
3. See error

**Platform information:**
 - OS: [Windows 10 Pro]
 - Version 10.0.18362
 - Hattrick Organizer 2.000

**Comment by akasolace** [comment]
This is a duplicate of #324

**Comment by yaute74** [comment]
yes I close my issue
