### ISSUE TITLE
[eFEAT] secondary cup filter in match list

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#323]
We must create a filter for secondary cups in:
- matches tab
- statistics tab, sub tab matches and arena 

For division battle we can add them into tournament filter

**Comment by murko69** [comment]
As long as we are on the subject of more filters in match list.
I  kinda miss qualification games in there as well.
I know most users only have a few of these (I have 18 and am pretty sure that there are users with plenty more out there) and they are marked on HT with a separate icon-type so I think they should have  a filter of their own in HO as well.

Only way to list qualifying matches in HO today are:
**Show my matches** (shows all games, including qualifying games)
**Show my competition matches** (shows national cup games, league games and qualifying games)
.....and then sort by matchType and scroll

**Comment by akasolace** [comment]
closed by 7c61ec0

**Comment by yaute74** [comment]
@murko69 you can open an issue it's a small modification

**Comment by yaute74** [comment]
Issue for qualification matches #326
