### ISSUE TITLE
[eBUG] MatchDayPanel NullPointerException

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#337]
![MatchDayPanel](https://user-images.githubusercontent.com/11821502/71600786-d0e0e880-2b50-11ea-8917-b31f510c1555.jpg)

**Comment by akasolace** [comment]
@wsbrenk can you tell me more about that issue: 
    - how does it occurs?
    - is it related to #291?

**Comment by wsbrenk** [comment]
this is my embarrassing error that I built into the MatchDayPanel. It happens when you call up the Matchday panel.

**Comment by akasolace** [comment]
closed by 4b79646
