### ISSUE TITLE
[eFEAT] improve match report

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#339]
make it events-driven similar to FoxTrick

**Comment by akasolace** [comment]
step 1) is #344

**Comment by akasolace** [comment]
@wsbrenk  @tychobrailleur 

this afternoon I started work on this issue. I started from highlight panel and made adjustments to it.

Left is 2.1  and right is development branch.

The problem is that so far I cannot make the vertical scrollbar appear.
In highlights tab it works well but not on this one. 

I tried the following without success:
```
		pane = new JScrollPane(panel, ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED,
				ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		mainlayout.setConstraints(pane, mainconstraints);
		add(pane);
```

If one of you is familiar with Swing and want to have a look at my branch https://github.com/akasolace/HO/tree/feature/339  ...

that would be super appreciated :-)

![image](https://user-images.githubusercontent.com/1136496/77092809-6aaa8a00-6a0a-11ea-8fe1-04c208bdd11c.png)

**Comment by tychobrailleur** [comment]
@akasolace Yeah, I have seen this about a lifetime ago, and solving it was a PITA.
The easiest way to solve this would be to use a wrapper panel, like so: 

https://gist.github.com/tychobrailleur/91f17cee849f533526bc3c0d821d16a5

![Screenshot 2020-03-19 at 22 31 00](https://user-images.githubusercontent.com/114285/77120727-6b0a4b80-6a31-11ea-8f05-8b104048c77e.png)


The problem now is the horizontal scrollbar — but it should be possible to get rid of it with preferred size.

**Comment by tychobrailleur** [comment]
(nice work BTW)

**Comment by akasolace** [comment]
> @akasolace Yeah, I have seen this about a lifetime ago, and solving it was a PITA.
> The easiest way to solve this would be to use a wrapper panel, like so:
> 
> https://gist.github.com/tychobrailleur/91f17cee849f533526bc3c0d821d16a5
> 
> ![Screenshot 2020-03-19 at 22 31 00](https://user-images.githubusercontent.com/114285/77120727-6b0a4b80-6a31-11ea-8f05-8b104048c77e.png)
> 
> The problem now is the horizontal scrollbar — but it should be possible to get rid of it with preferred size.

cool, I will have a look at what you did and see if I can get rid o that horizontal scrollbar

**Comment by akasolace** [comment]
> (nice work BTW)

thank you

**Comment by tychobrailleur** [comment]
> cool, I will have a look at what you did and see if I can get rid o that horizontal scrollbar

So far, no luck on my side.  The closest I have got to is the latest version of the gist:
https://gist.github.com/tychobrailleur/91f17cee849f533526bc3c0d821d16a5

but the height is wrong and truncates the report.

**Comment by tychobrailleur** [comment]
The problem seems to be caused by the `JLabel`s with html, they expand the whole width to contain the text.  I have managed to get a correct result by setting the width of the html:

https://gist.github.com/tychobrailleur/91f17cee849f533526bc3c0d821d16a5

![Screenshot 2020-03-20 at 07 55 28](https://user-images.githubusercontent.com/114285/77145438-78025b80-6a80-11ea-9b23-5fa5652d0553.png)

It should be possible to set the right width depending on the position of the slider, but that can get tricky.

**Comment by akasolace** [comment]
@tychobrailleur I did this in parallel starting from your gist andI come up with the same thing ...
Thank you for the help !
