### ISSUE TITLE
Cannot start new release on Linux: bad file format

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#34]
Hello,
We cannot start HO with the new release (.deb), because the file 'ho.sh' is in dos format not in unix format.
In git it's ok, so maybe a problem with package build.

**Comment by akasolace** [comment]
this is strange
@DavidatorusF did you not had the opposite isssue ? .sh from fresh install working but .sh from zip not working?
@yaute74 it is the postinstall file that make the sh executable so I am surprised. However, I could imagine that sh from the zip or sh from zip in case of update could be not working . What is surprising thought, is it that it went unoticed for so long.

**Comment by DavidatorusF** [comment]
@akasolace 
.sh was working from r5 to r7
for r8 I said you there's a mistake... but I haden't time to check it more

.deb, the update r8 worked, I hadn't check fresh install with .deb

**Comment by DavidatorusF** [comment]
copy/paste .sh from previous version did the trick

I let you understand what's wrong in the last one

**Comment by akasolace** [comment]
@yaute74 @DavidatorusF 
based on last comment from yaute74, `^M`, mean the EOL is incorrect
it is easy to fix. I just don't know why the file got corrupted again.
The fact that the file is correct in github, this is because git automatically checkout with unix EOL.

**Comment by yaute74** [comment]
As I wrote in my last comment, with git we can force the  EOL with a .gitattributes and inside "*.sh text eol=lf"
Maybe it's the solution

**Comment by akasolace** [comment]
yes this is what I meant in my previous message.
To fix that bug, I will create a .gitattributes that contains:
* text=auto
*.sh text eol=lf

cheers

**Comment by akasolace** [comment]
@yaute74 @DavidatorusF 
could one of you control, the binaries save in https://github.com/akasolace/HO/releases/tag/dev are now ok 
thank you

**Comment by DavidatorusF** [comment]
@akasolace .zip work

**Comment by yaute74** [comment]
@akasolace  it's also ok for rpm and deb ;)

**Comment by akasolace** [comment]
ok cool 
I close the issue then
