### ISSUE TITLE
[eBUG] refactoring of MatchEvent

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#344]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by akasolace** [comment]
Considering that it will fixes a lot of existing bug, I will make it part of 2.1
However, this would be a massive commit, and will requires a lot of testing (@DavidatorusF @mistermax80  the usuals bugs hunter :-) ) before releasing 2.1

**Comment by mistermax80** [comment]
@akasolace ok for me!!! 😄

**Comment by akasolace** [comment]
Almost done .....


![image](https://user-images.githubusercontent.com/1136496/72183631-be876a00-33ee-11ea-87fb-3e154594ab1e.png)
