### ISSUE TITLE
[eFEAT] pre match analysis

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#347]
This functionality is not supported for not supporter and supporter silver, so, I think can be useful we have an similar information in HO:
![Screenshot_2020-01-03-20-36-59-528_org hattrick hattrick](https://user-images.githubusercontent.com/15519907/71744968-237c1680-2e69-11ea-8c35-ead90d0f2b86.jpg)
@akasolace I know you are supporter, could you share here information presente in that page?

**Comment by wsbrenk** [comment]
![Screenshot_20200104-002411_Hattrick](https://user-images.githubusercontent.com/11821502/71754984-dc058280-2e88-11ea-96c5-6c8b8ed65daf.jpg)

if it is this, what you mean, than it is comparable to team analyzer

**Comment by mistermax80** [comment]
No in check line up, meanwhile you setup the line up, you have to click match detail, and after click on opponent squad. As it says, opponent details as latest Transfer, yellow and red cards etc...

**Comment by akasolace** [comment]
![image](https://user-images.githubusercontent.com/1136496/71765153-4e11b200-2ef1-11ea-9db5-29b2e64afb72.png)

**Comment by akasolace** [comment]
or this one that I got in tactic room ?

![image](https://user-images.githubusercontent.com/1136496/71765231-4272bb00-2ef2-11ea-98e8-a9453e8616d6.png)

**Comment by mistermax80** [comment]
No, I think other screen... Could you try:
From app you can click on list next matches:
![IMG_20200105_162728](https://user-images.githubusercontent.com/15519907/71782245-63154080-2fd8-11ea-8b86-acff75c07151.jpg)
And so click on tab opponent:
![IMG_20200105_162743](https://user-images.githubusercontent.com/15519907/71782252-76c0a700-2fd8-11ea-9ce6-efaa2c8dcd04.jpg)

**Comment by wsbrenk** [comment]
![screenshots](https://user-images.githubusercontent.com/11821502/71784279-35d58c00-2ff2-11ea-97f5-757d5928e4d2.jpg)

**Comment by mistermax80** [comment]
Yes, I start from these information.
@akasolace @yaute74 @wsbrenk @DavidatorusF could you think on this, it is a good new feature?

**Comment by akasolace** [comment]
@mistermax80 yes but I would personally see it as an extension of team analyser not an additional module.

**Comment by wsbrenk** [comment]
I would confirm that

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/209150792-5d3c0a75-b23d-429c-b3a8-d9f2fde3001b.png)

Current status of development
