### ISSUE TITLE
[eBUG] bumping version of gradle has broken some task(s)

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#359]
**Describe the bug**
Gradle script needs to be fixed in order to reproduced similar output has 2.0.
`osXjar` task is broken, others looks ok

@tychobrailleur, can you please work on this one? 

Thank you

**Comment by tychobrailleur** [comment]
Sure, I'll have a look when I get the chance.  Ah, it couldn't have been that easy, right? ;-)

**Comment by akasolace** [comment]
@tychobrailleur I noticed afterward the change of path from `\\` to `/`, maybe the issue only comes to that ... is it working on your machine as it is ?
To me, the gradle does not give me any error message and that I can't debug the script. I am using intellij IDEA, and step by step debugger not working, I dont see variable values.  
I have to admit that the configuration/build/run phase of gradle script are very cryptic to me. 
If in other hand you are familiar with graddle, and you see room for improving the build script, please feel free :-)

**Comment by tychobrailleur** [comment]
> I have to admit that the configuration/build/run phase of gradle script are very cryptic to me.
If in other hand you are familiar with graddle, and you see room for improving the build script, please feel free :-)

I am more of a Maven guy myself, but I'll give it a shot.  I would have thought the forward slash approach was more portable, so I'd be surprised if that was the issue.  Apologies for the troubles, I'll look into it when I'm free.

In the meantime, I can send a PR later reverting the gradle version change to resolve releases issues.  WDYT?

**Comment by tychobrailleur** [comment]
So I found what the problem is: the nested task `ZipMacAppDistribution` is simply not getting called.  Looking through history, the `execute()` call has been removed.

Digging deeper, that `execute()` method doesn't exist any more in Gradle 5.x so I am now looking into an alternative.
