### ISSUE TITLE
[eFEAT] Youth Academy

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#367]
Hattrick Youthclub is a great tool for youth academy, but i cannot integrate selected youth player to the future trainings plan of my senior team. This could be done in HO.
Additional we could show the complete history of our homegrown players, not only the time, when they were adults.
Some overviews in the youth club could be improved, I think. When I train my youth for the market, only the skills that can be achieved with 17.0 count. this is not shown by the youthclub, but could be done by HO.

**Comment by akasolace** [comment]
@wsbrenk you basically suggest to have a module youth academy within HO?

**Comment by wsbrenk** [comment]
Yes, this would be my idea, that i would like to discuss. since i'm managing 3 teams of homegrowns, i'm missing the integration of my youth team application with HO.On the other hand, I accept that it would be a lot of work to do. Finally, the HO application could eventually become too fat, including the database.

**Comment by akasolace** [comment]
> Yes, this would be my idea, that i would like to discuss. since i'm managing 3 teams of homegrowns, i'm missing the integration of my youth team application with HO.

I agree that it would be a nice addition, quite often requested

>On the other hand, I accept that it would be a lot of work to do.

I do not have a YA myself, but last time I played (few year ago) I had one, and for what I recall HYC was doing a lot of different things, so yes I guess this would be a lot of work !

>  Finally, the HO application could eventually become too fat, including the database.

I am not too concern by this. Also does HYC keeps fully history o youth players incl games ?

It is a topic that defintly worth to be discussed.

**Comment by wsbrenk** [comment]
> Also does HYC keeps fully history o youth players incl games ?

No, i don't think so. HYC only displays the current status of skills. There are progress calculations and only Money is managed historically.

**Comment by akasolace** [comment]
ok

**Comment by yaute74** [comment]
With foxtrick the infos are automatically send to HYC it's a big advantage. With HO we must do all the updates manually, so I am not sure that a lot of player will use it if we integrate it.

**Comment by wsbrenk** [comment]
@yaute74 hi, i don't understand what you mean with "we must do all the updates manually". i think it is possible to add a new selection box "youth academy" to the download filter and every time the user will download (F11), the youth data is updated automatically with last match data and so on. 

on the other hand i'm with you. if we do not integrate some feature, that is not already handled by HYC, then no one will use it. 
and yes, i think it would be a good idea to integrate some manual input options, for example entering the starting skills of the players.

what i would really like as homegrown players manager would be the integration of selected youth players to the future trainings plan of HO.

**Comment by yaute74** [comment]
@wsbrenk I mean that when you change the training, a scouter, play a match, etc info are send automatically to HYC.

With HO you must download the data at the good time. For example if you change the training, play a match, change the training another time and play another match and if you don't download the datas between this two match I think you loose the info of the first training. But maybe I'm wrong.

**Comment by wsbrenk** [comment]
@yaute74 now i understand what you mean and yes, you are right. Users who will not download regularly may miss important information. These should be editable in HO.
but isn't that the case for the adults too?? Training is editable in HO, isn't it?

btw: i would not miss any download;-)

**Comment by yaute74** [comment]
@wsbrenk yes it's the case with the senior but with the senior but we have no equivalent in web application.
You are motivated so do it ;-)

**Comment by akasolace** [comment]
@wsbrenk @yaute74 what would help for both senior and youth team is the availability of last team event via CHPP ...
There is a request about it maybe we can try to push for this one ....

**Comment by wsbrenk** [comment]
@yaute74 @akasolace today i found that there still is no chance to download any training infos of the youth team via chpp. that is of course lousy.

**Comment by akasolace** [comment]
CHPP is ridiculously feature-poor

**Comment by wsbrenk** [comment]
the only thing i'm missing in chpp is the youth training information

according to chpp documentation, the following information is available
* player details
* match lineups

A youth panel could show
- player overview table
  - name
  - age
  - number of matches
  - specialty
  - skill estimations/potential
  - scouting information
  - promotion date/info
- player details view (of selection in overview)
  - scouting information 
    - date (readonly)
    - age (readonly)
    - scout's messge words (ro)
    - scout's starting/potential skills or specialty message (ro)
    - overall skill info
    - skill adjustments (rw)
    - promotion date (ro)
  - lineup information
    - match date
    - lineup position(s)
    - minutes
    - training information (from trainings view, see below)
    - skill estimations (calculated from training and position/minutes info)
- training view
  - historical training view (list of finished youth matches)
    - date (ro)
    - league/friendly match type (ro)
    - 1st training (rw)
    - 2nd training (rw)
  - future training plan (one entry per  future week, ignore friendlies and league changes within 2 days)
    - future hattrick season, week
    - 1st training (rw, default previous training)
    - 2nd training (rw, ...)

**Comment by wsbrenk** [comment]
download youth team basic information:

![image](https://user-images.githubusercontent.com/11821502/97804978-7bcfa080-1c53-11eb-9039-190f72702f79.png)

**Comment by akasolace** [comment]
@wsbrenk cool. This is a big one, let me know if you want me to help on some parts of this one ...

**Comment by wsbrenk** [comment]
youth player details have reached the hrf file:

[youthplayer262719284]
Name=Achim Knäppchen
Age=17
AgeDays=60
ArrivalDate=2020-06-27 09:05:00
CanBePromotedIn=-17
PlayerNumber=100
Statement=
OwnerNotes=
PlayerCategoryID=0
Cards=0
InjuryLevel=-1
Specialty=0
CareerGoals=1
CareerHattricks=0
LeagueGoals=0
FriendlyGoals=2
PlayerCategoryID=0
KeeperSkill=
KeeperSkillIsAvailable=False
KeeperSkillIsMaxReached=False
KeeperSkillMayUnlock=False
KeeperSkillMax=
KeeperSkillMaxIsAvailable=False
DefenderSkill=7
DefenderSkillIsAvailable=True
DefenderSkillIsMaxReached=False
DefenderSkillMayUnlock=
DefenderSkillMax=7
DefenderSkillMaxIsAvailable=True
PlaymakerSkill=
PlaymakerSkillIsAvailable=False
PlaymakerSkillIsMaxReached=False
PlaymakerSkillMayUnlock=False
PlaymakerSkillMax=4
PlaymakerSkillMaxIsAvailable=True
WingerSkill=
WingerSkillIsAvailable=False
WingerSkillIsMaxReached=False
WingerSkillMayUnlock=False
WingerSkillMax=5
WingerSkillMaxIsAvailable=True
PassingSkill=4
PassingSkillIsAvailable=True
PassingSkillIsMaxReached=True
PassingSkillMayUnlock=
PassingSkillMax=4
PassingSkillMaxIsAvailable=True
ScorerSkill=4
ScorerSkillIsAvailable=True
ScorerSkillIsMaxReached=False
ScorerSkillMayUnlock=
ScorerSkillMax=5
ScorerSkillMaxIsAvailable=True
SetPiecesSkill=
SetPiecesSkillIsAvailable=False
SetPiecesSkillIsMaxReached=False
SetPiecesSkillMayUnlock=False
SetPiecesSkillMax=
SetPiecesSkillMaxIsAvailable=False
ScoutId=563942
ScoutName=Siegmar Kopplin
ScoutingRegionID=238
ScoutComment0Text=Wir haben einen aussichtsreichen Kandidaten zu beurteilen. Er trägt den Namen Achim Knäppchen und ist 16 Jahre alt.
ScoutComment0Type=1
ScoutComment0Variation=1
ScoutComment0SkillType=262719284
ScoutComment0SkillLevel=16
ScoutComment1Text=Ich würde seine Fähigkeiten in Torschuss zurzeit ungefähr auf schwach schätzen.&nbsp;
ScoutComment1Type=4
ScoutComment1Variation=0
ScoutComment1SkillType=6
ScoutComment1SkillLevel=4
ScoutComment2Text=Ehe du dich versiehst, könnte dieser Spieler in Verteidigung gut werden, falls du ihn richtig trainierst.&nbsp;
ScoutComment2Type=5
ScoutComment2Variation=2
ScoutComment2SkillType=3
ScoutComment2SkillLevel=7
ScoutComment3Text=Sollen wir ihn unter Vertrag nehmen, Chef?
ScoutComment3Type=7
ScoutComment3Variation=2
ScoutComment3SkillType=0
ScoutComment3SkillLevel=0
YouthMatchID=116634859
YouthMatchDate=2020-11-03 04:10:00
PositionCode=100
PlayedMinutes=90
Rating=2

**Comment by wsbrenk** [comment]
youth player details have reached HO database:

![image](https://user-images.githubusercontent.com/11821502/98439291-3e569180-20f1-11eb-9c25-e24ef9c69482.png)


![image](https://user-images.githubusercontent.com/11821502/98439281-2b43c180-20f1-11eb-9a1a-bea35461ebe0.png)

**Comment by wsbrenk** [comment]
@akasolace , @tychobrailleur 
now we could easily split the further processing. If someone wants to take over the test of loading and realizing the display of the data in a new YOUTH Academy module, he is welcome.

**Comment by akasolace** [comment]
@wsbrenk let's discuss this on slack... see exactly what is required and we can split the effort. Personally for 5.0 I had in mind to work on allowing theme for all icons (including match events) for this I imagine a dedicated tool that would allow external help from the forum. But we would have time as all of this is for 5.0.

**Comment by wsbrenk** [comment]
chpp match details and lineup files are identical in hattrick and youth source system. I would like to introduce a column SourceSystem to the matchdetails and matchlineup tables and use the same download and database access methods in both systems.

**Comment by akasolace** [comment]
yes make sense

**Comment by wsbrenk** [comment]
youth match lineup players have reached the database (SourceSystem==1):

![image](https://user-images.githubusercontent.com/11821502/99182656-6ddf4c80-2736-11eb-95d6-1dcee1a00589.png)

**Comment by wsbrenk** [comment]
next, we need
- a youth match training table to store user input of primary and secondary trainings for each played match
- in this table of another one we could store info about future training plans for youth players (since matches are only available for a few future matches, we should manage this information per week)
- some skill estimation routines

**Comment by wsbrenk** [comment]
YouthTraining classes are based on an estimate of what might happen in CHPP in the future. 
For the time being, the data must be entered by the users.

**Comment by akasolace** [comment]
@wsbrenk ok, for the time being I can't really look at what you are doing on this one as I am fairly busy on other issues/bugs

**Comment by wsbrenk** [comment]
@akasolace no problem - than i would progress a little slower and i will learn a lot more about gui programming in java;-)

one idea concerning conventions about method naming:

MyConnector methods should start with "download" or "upload"
DBManager methods should start with "load" or "store" 
only java classes should use "get" and "set"

**Comment by akasolace** [comment]
fine for me ...

**Comment by wsbrenk** [comment]
I've been at the gui programming for a few days now and I'm still having a bit of a hard time doing it. in addition, the merges of the master-branch are becoming more and more complicated.

do you think there would be a chance to merge this on master and you @akasolace  and @tychobrailleur would have a look on what i'm doing wrong. why the cells in my youth table view will not display what i expect?

since all the problems are part of the new youth module which is not invoked by default, they should not hinder anyone.

**Comment by akasolace** [comment]
@wsbrenk ok go ahead and open a PR ....

**Comment by wsbrenk** [comment]
@akasolace @tychobrailleur any idea, what i'm doing wrong?

**Comment by akasolace** [comment]
I asked you if you could share your dB

**Comment by akasolace** [comment]
I can t test at the moment as I have no youth team

**Comment by wsbrenk** [comment]
[db_Juventus Brenk 2-2020-12-01.zip](https://github.com/akasolace/HO/files/5625974/db_Juventus.Brenk.2-2020-12-01.zip)

**Comment by akasolace** [comment]
@wsbrenk I made a commit fixing your issue

**Comment by wsbrenk** [comment]
@akasolace thanks

**Comment by wsbrenk** [comment]
beside the NPE discovered by @tychobrailleur there will be some kind of "weak" breaking changes in the current commits of my #367 branch(es). 

i changed the youthplayer table for example and i will handle this by resetting my own development database by a current HO4 database, which will be updated to a new and correct HO5 candidate. I don't want to enable DbUpdater to take care of intermediate HO5 versions. But this would require that any developer has to do it the same way if he wants to work with youth player table.

Alternativly i could enable DbUpdater to fix intermediate table candidates (remove no more needed columns, add or change new ones)

What is your opinion?

**Comment by wsbrenk** [comment]
![SkillInfoColumn](https://user-images.githubusercontent.com/11821502/101278783-1a54a180-37be-11eb-9917-8c74733958cd.png)


my next project could be some kind of SkillInfoColumn which displays a colored bar, presenting all the info about youth skill as shown above.

**Comment by wsbrenk** [comment]
@akasolace @tychobrailleur Will one of you get that in half a day? If not, will I deal with it in the next few weeks.

**Comment by wsbrenk** [comment]
question to the experienced hsql experts: is it reasonable to include the line-ups of the youth players in the table matchlineupplayer? wiithout youth contents the rows count is around 124.000 records for my first team. Including the youth matches would increase this by 50% approximatly. Senior 2 matches per week, yuniors a little bit more than 1.
is that an amount that hsql can still withstand a while or is it better to create a separate youth lineup table?

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/103443038-74307600-4c5b-11eb-83d1-6e3fffc006c1.png)


edit youth training is working

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/103443075-d4bfb300-4c5b-11eb-9a4b-974a04ae732a.png)

youth player overview and details view. 

i'm working on skill calculation now. View needs a lot of tuning (not fine tuning;-)

**Comment by akasolace** [comment]
@wsbrenk you are making good progress !

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/104837634-22702880-58b6-11eb-9a4f-6a56dde68872.png)

right now i'm quiet happy with the training history skill numbers  in youth player's details table

next steps to attack could be:
- skill info display in overview table
- start skill value editor to adjust player's start skills which are now all set to 0 if there are no messages from the scout

the second point could be a good followup of the first one. I would like to start this editor on double click on skill info in overview table.

so now i would like to continue the discussion on how to display skills. @akasolace suggestion to use colored bars is a very good one, i think!

**Comment by akasolace** [comment]
@wsbrenk is there still a lot to do on the Youth module ?

**Comment by wsbrenk** [comment]
@akasolace some ui beautifying by ui experts. the skill editor is an extra ticket. could all be done in new tickets, i think.
