### ISSUE TITLE
Two lines instead of one in Lineup combobox

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#370]
Starting by v2.0 in Lineup players uses 2 lines instead of one.

Just to be clear this is how it looks like
<img width="193" alt="immagine" src="https://user-images.githubusercontent.com/11422667/73386740-add06280-42cf-11ea-91ac-080f3214fee6.png">
but with v1.x everything (tshirt, name, special ability, score) was into one single line.

This is neither crucial, not pure cosmetics, because it obliges people to scroll down in order to see the Reserve list.

**Platform information:**
 - Tested on MacOS X, MacBook Pro 15" retina (2880 x 1800)

**Comment by akasolace** [comment]
I agree it is not ideal on small screen, I did not really notice it because I got a large screen.
maybe we can remove the shirts information -personally I always thought it was useless- and make it all one one line by:
     - increasing a bit the width
     - changing display name like initial and familly name only

If you are interested, you can assign it to yourself ....

**Comment by pierpaolocira** [comment]
Hi,
Yes, with low pace I can work on it... but I would need to be sure on what has to be done.

- I think the tshirt is useful only in order to find esily the player, in the list on the bottom. Indeed if I see, e.g., a black tshirt in the lineup, I simply search for a black tshirt in the list. Maybe it's not very useful, but perhaps we need some other opinions on it before removing?
- Yes, I can slightly increase the with, but I am not sure what is the minimum resolution to take in consideration (just to avoid horizontal scrollbars). Do you have any idea?
- Yes, we can have only the initial of the name and, then, reduce the number of characters before cutting the name and concatenating ellipses. I can do some tests


In any case, I'm wondering what is the difference with v1.x... why was it displaying properly there and then it changed? Do you know?

**Comment by akasolace** [comment]
> perhaps we need some other opinions on it before removing? 

yes let see what other have to say about it

> Yes, I can slightly increase the with, but I am not sure what is the minimum resolution to take in consideration (just to avoid horizontal scrollbars). Do you have any idea?
Yes, we can have only the initial of the name and, then, reduce the number of characters before cutting the name and concatenating ellipses. I can do some tests

I think best will be something like initial and truncated name but again let see 

> In any case, I'm wondering what is the difference with v1.x... why was it displaying properly there and then it changed? Do you know?

I think it is the additional of the color bar on the left indicating i player has received training during the week, maybe we can put that bar on top of the name, this will also save some space on the width

Other possibilities, keeping the 2 lines but
        - (easy) removal of box title (keeper, inner midifeld, ......) and indicate on the field the goal and midfield to make it clearer which are the positions (similar to HT)
        - (difficult) remove the combobox for the order and we replace it overlay object to set the order (similar to HT)


> with low pace I can work on it 

It can clearly be a low pace project, as it is not attached to any release

**Comment by yaute74** [comment]
I use two lines because player could have a long name and you have several infos on the second line:
![image](https://user-images.githubusercontent.com/34601782/74083489-f5d84d80-4a64-11ea-9ff1-783f59377f9f.png)

**Comment by akasolace** [comment]
I can add that personally, I am also fine with the 2 lines.

**Comment by pierpaolocira** [comment]
Sorry, but on 15" retina (2880 x 1800, that is not really small) the screen is unusable!
I need to scroll horizontally and vertically in order to use it...

<img width="1099" alt="immagine" src="https://user-images.githubusercontent.com/11422667/74087667-d7874780-4a8e-11ea-9528-d8b0dc701f2e.png">

I am not telling that two lines are useless, but many people will be umcomfortable like this... and in Hattrick 1.x all those info were visible on a single line.
