### ISSUE TITLE
Cosmetic: unrecoverable injury

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#371]
In Hattrick, in case of an infinite injury you can see the symbol of "infinite" as estimation of the injury.
<img width="170" alt="immagine" src="https://user-images.githubusercontent.com/11422667/73389370-4ff24980-42d4-11ea-9536-fac6027695b5.png">

In HO it shows the number 999
<img width="235" alt="immagine" src="https://user-images.githubusercontent.com/11422667/73389387-58e31b00-42d4-11ea-93b6-77e0e250dfcd.png">

I think "999" is a simple way for Hattrick to store an unrecoverable injury (because it is most probably a numeric field in the DB), so we can simply align this behaviour in HO.

This can be assigned to me, because the player with an unrecoverable injury is the trainer of my team, so I won't fire him for the time being... :)

**Comment by akasolace** [comment]
@this has been chaned already, I think you are not using latest dev

**Comment by akasolace** [comment]
![image](https://user-images.githubusercontent.com/1136496/73393442-f3932800-42db-11ea-8b6a-61cac88dce40.png)

**Comment by pierpaolocira** [comment]
No.. I'm using the stable version, I saw it and so I reported...
I just aligned my my fork with your master and, indeed, I can see it as fixed.
I'm going to close it, sorry.

**Comment by akasolace** [comment]
ok perfect, 
I guess you know but binaries for dev are produced very regularly...

**Comment by pierpaolocira** [comment]
Yes, I simply prefer to use Stable for my daily activities on HO with my Hattrick team, and a recent copy of my DB in the folder of the source code for development.
Otherwise, being on MacOS, the dev version will work on my real DB... :(
