### ISSUE TITLE
[eFEAT] add a line in player overview with sum/average value

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#373]
Could be nice to add a line in player overview with sum/average value, hence after training see the evolution of tsi, salarry, rating .... at team level 

![image](https://user-images.githubusercontent.com/1136496/73573206-199f0080-4473-11ea-87d5-ee7cb617b6b4.png)

**Comment by tychobrailleur** [comment]
I have something similar that I have somewhat [adapted](https://github.com/tychobrailleur/HO/commit/87749556cd8d34f65a3f992d9c93902dfd3c236e) to match the above:

![Screenshot 2020-02-01 at 16 46 32](https://user-images.githubusercontent.com/114285/73595608-959c5580-4512-11ea-9cbc-a135d9dbfdf8.png)

It displays below the team overview, and doesn't show trends when TSI/form changes, but I can look into it if there is any interest.

**Comment by akasolace** [comment]
@tychobrailleur that is great, do not need the trend (was just a copy past from tommatrick)  but what could be nice is the change when another HRF file is selected
Something like:

Total TSI 46, 210 (+1,500)  Average TSI 1'593 (+345), Average Form 5.31 (+0.12) ... with green and red delta as per indication next to player

I think also that average stamina could be nice

**Comment by tychobrailleur** [comment]
Sounds good.
I was also thinking of adding the number of players, average age and average salary — WDYT?

**Comment by akasolace** [comment]
yes sounds good!!

**Comment by tychobrailleur** [comment]
I still have to sort out some layout issues, but this is[ what I have so far](https://github.com/tychobrailleur/HO/tree/team-summary):

![Screenshot 2020-02-02 at 13 39 43](https://user-images.githubusercontent.com/114285/73609081-09496b80-45c2-11ea-9f06-48a963f7b606.png)

**Comment by akasolace** [comment]
I really like it, I do not really notice any layout issue to be honest ...

**Comment by akasolace** [comment]
@tychobrailleur  when I merge your work on that one, I will release 2.1 alpha.

**Comment by tychobrailleur** [comment]
> @tychobrailleur when I merge your work on that one, I will release 2.1 alpha.

Ok — right now I can't test updates as my team is playing, so I'll only be in a position to create the PR in a couple of hours.

For info, there are some labels that will need translating in this feature.

**Comment by akasolace** [comment]
closed by #375

**Comment by akasolace** [comment]
@tychobrailleur what is your username in HT ?

**Comment by akasolace** [comment]
few remarks / details, I would suggest the following:
    - remove digit for change in number players
    - 2 digits for average age
     - remove digits for average salary ( current and change)
     - remove digit and thousand separator for change in total TSI and average TSI

Also, if not too much work, would it be possible to group the actual values and the delta ?

Otherwise thank you for the fast implementation !

![image](https://user-images.githubusercontent.com/1136496/73614826-028f1880-4603-11ea-82e3-0e2c31765a7e.png)

**Comment by tychobrailleur** [comment]
> @tychobrailleur what is your username in HT ? I will add you in the list of HO devs

[tychobrailleur](https://www97.hattrick.org/Club/Manager/?teamId=280747), funly enough.

**Comment by akasolace** [comment]
@tychobrailleur can you accept CHPP developer licence on HT

![image](https://user-images.githubusercontent.com/1136496/73615512-cc549780-4608-11ea-97cc-1707cb939ed4.png)

**Comment by tychobrailleur** [comment]
> @tychobrailleur can you accept CHPP developer licence on HT
> 

That's done now.

**Comment by tychobrailleur** [comment]
I have most changes done now, except the following where I am not sure what you're asking:

> separator for change in total TSI and average

Are you asking for the separator to be removed from the main value, or the separator to be added to the delta?

![Screenshot 2020-02-03 at 20 24 09](https://user-images.githubusercontent.com/114285/73688262-91fc0080-46c3-11ea-9b6e-aeb8c5ff5781.png)

**Comment by akasolace** [comment]
> I meant to have it for both (thousand separator and no decimal)
