### ISSUE TITLE
[eFEAT] consider all match orders in prediction rating manager

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#385]
At the moment only substitution are considered, RPM should also consider:
      - change of behaviour
      - position SWAP

cf:
https://github.com/akasolace/HO/blob/92efca10c171e6511987da238ca9045f30f90a4d/src/main/java/core/rating/RatingPredictionManager.java#L114

**Comment by wsbrenk** [comment]
@akasolace isn't it the lineup.UpdateLineupWithMatchOrder which needs some extensions?

**Comment by wsbrenk** [comment]
I would have an approach for this. It is part of my branch feature#294. i will create a pr of it in the next minutes. i think it should be merged after release of v2.1. otherwise it should be tested very thoroughly.

**Comment by akasolace** [comment]
> @akasolace isn't it the lineup.UpdateLineupWithMatchOrder which needs some extensions?

yes possible I would need to look into it in mode details

**Comment by akasolace** [comment]
> I  think it should be merged after release of v2.1. otherwise it should be tested very thoroughly.

yes it is the plan it will be merged after 2.1 release
