### ISSUE TITLE
make build.gradle platform independant

### ISSUE THREAD

**Issue by pierpaolocira** [akasolace/HO#389]
Hi @akasolace , 
I am working on 372 and I wanted to test the behaviour when the application is finally packaged as an .APP

But any attempt I do in order to build, I receive the same issue with gradle:
```
Evaluating root project 'HO-pierpaolocira' using build file '...build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '...build.gradle' line: 6

* What went wrong:
An exception occurred applying plugin request [id: 'nebula.ospackage', version: '5.0.4']
> Failed to apply plugin [class 'com.netflix.gradle.plugins.packaging.SystemPackagingBasePlugin']
   > Could not create an instance of type com.netflix.gradle.plugins.packaging.ProjectPackagingExtension.
      > Could not find matching constructor for: org.gradle.api.internal.file.copy.DefaultCopySpec(org.gradle.api.internal.file.BaseDirFileResolver, org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator)
```

Do you have any idea on the issue?

Netflix??? Are you able to replicate? 

It happens also with a simple:
`gradle clean installDist AddResourcesInDistrib ZipDistribution`

Thanks

**Comment by pierpaolocira** [comment]
Additional comment:
I'm sorry to say, but the `build.gradle` file seems to be a disaster now, and it cannot be easily used (maybe with the exception of some computers).

Some comments:
- I hat to change version of the nebula.ospackage plugin
- As usual I had to comment to apiKey line
- I had to empty the githubRelease task
- I had to remove any reference to "AddResources*" (why don't they exist anymore?)
- I had to empty the "resetDB" task because it cannot find "D:\\Program Files\\HattrickOrganizerDev\\db" on my computer
- Still the file is full of references to "D:" , Windows directory separator (e.g. \docs\changelog\md)... that I cannot manually change everytime I get the new version from the repository

To do a PL for the #372 I need to run proper tests with the .APP (IDE is not enough) and I cannot find an easy way... I cannot spend more time to build than to develop and test. :)
Is there any suggestion on how to do?

Some months ago it was working like a charm... how is it possible to have such big regression?

**Comment by akasolace** [comment]
>  hat to change version of the nebula.ospackage plugin

the version specificied in build.gradle work flawleslly for me. I don't know why it is not working for you. You are also running the script using gradlew, not with your local install, right?

> As usual I had to comment to apiKey line

if you want/need to use PoEditor task you need a PoEditor key in your parameters, otherwise just not call the task.

> I had to empty the "resetDB" task because it cannot find "D:\Program 
Files\HattrickOrganizerDev\db" on my computer

You currently have this issue during the configuration phase ?
I will put the path as parameter and it will then work as PoEditorTask in the meantime you can put the path in the doLast clause.

> I had to empty the githubRelease task

same, you don't have to comment it out,  you can simply ignore it,

> Windows directory separator (e.g. \docs\changelog\md)... that I cannot manually change everytime I get the new version from the repository

 replacing '\' with '/' or File.separator should do the trick

> To do a PL for the #372 I need to run proper tests with the .APP (IDE is not enough) and I cannot find an easy way... I cannot spend more time to build than to develop and test. :)
Is there any suggestion on how to do?

A quick solution would be the following, keep in build.gradle only what you need to build the macOS app. Let see afterward how to fix the build.gradle to make it works for all of us. It should not be too much work, simply removing hard reference and specific windows path separator. 

> Some months ago it was working like a charm... how is it possible to have such big regression?

I don't know, we move to gradle 5 and some changes were required. Also as far as I know the script is working (relatively) well for @tychobrailleur who is also under macOS.

**Comment by pierpaolocira** [comment]
Hi, @akasolace ...

> You are also running the script using gradlew, not with your local install, right?
In truth no, I now tried with the wrapper and something works better, but still not final solution... by simply trying with a `gradle clean` I have errors

> > As usual I had to comment to apiKey line
> if you want/need to use PoEditor task you need a PoEditor key in your parameters, otherwise just not call the task.
This was just to mention one of the many issue I though people can experience with this build.gradle... indeed I just suggested to comment this line in the HO wiki


> > I had to empty the "resetDB" task because it cannot find "D:\Program
> > Files\HattrickOrganizerDev\db" on my computer
> 
> You currently have this issue during the configuration phase ?
> I will put the path as parameter and it will then work as PoEditorTask in the meantime you can put the path in the doLast clause.
Yes, it happens also with a simple clean

> > I had to empty the githubRelease task
> 
> same, you don't have to comment it out, you can simply ignore it,
> 
Sorry also in this case the simple clean fails because I didn't set a token and sommenting the line won't solve.
Perhaps there is a way to check if a variable exists and then run the code only in that case?

> > Windows directory separator (e.g. \docs\changelog\md)... that I cannot manually change everytime I get the new version from the repository
> 
> replacing '' with '/' or File.separator should do the trick
> 
I know... :)
I'm simply mentioning all the issue found in this version of the file


> A quick solution would be the following, keep in build.gradle only what you need to build the macOS app. Let see afterward how to fix the build.gradle to make it works for all of us. It should not be too much work, simply removing hard reference and specific windows path separator.
> 
> > Some months ago it was working like a charm... how is it possible to have such big regression?
> 
> I don't know, we move to gradle 5 and some changes were required. Also as far as I know the script is working (relatively) well for @tychobrailleur who is also under macOS.

Yes, maybe this issue can be kept open as a reminder for the task of the build file.

In the meanwhile, can someone help me with this file? I can try slowly to do that, but I would prefer spending time in developing and testing the app, then in building.
I'm really not an expert of gradle.

I'm wondering how @tychobrailleur can build a final .APP with this script. @tychobrailleur, can you please help and share what you finally do in order to build the app? Thanks

**Comment by tychobrailleur** [comment]
> 'm wondering how @tychobrailleur can build a final .APP with this script.

I hadn't built it since the `build.gradle` refactoring, but yes, issues would be expected.  As I mentioned somewhere else (I cannot find the comment any more), I have to maintain a set of local changes to even be able to compile in the IDE:

- commenting out the `POEDITOR_APIKEY` and `GITHUB_TOKEN` bits and replace with dummy values,
- replace all the `\\` to `/`

I haven't addressed because I really don't want to break the build on other platforms (in particular @akasolace's, since he makes the releases) — and I have no way of testing changes.

A quick experiment shows that I can build after disabling `poeditorPull` and `createLanguageFileList` (one depends on the another in more than one way, it seems), and the changes above, `./gradlew createApp ZipMacAppDistribution` builds fine.

**Comment by pierpaolocira** [comment]
Thanks @tychobrailleur,
I was interested in your experience with the current build and in `./gradlew createApp ZipMacAppDistribution`

Can you please tell me if you are able to open the generated APP file?
By applying several changes (your suggestions are not enough, as you can see in my orevious posts) I am able to build, but the final .APP cannot be open because of a "file corrupted" message. I feel something else is missing.

@akasolace did you already distributed any APP built with this version of the build file?

Thanks

**Comment by akasolace** [comment]
> @akasolace did you already distributed any APP built with this version of the build file?

2.1 version was made with that version of build.graddle

**Comment by pierpaolocira** [comment]
> > @akasolace did you already distributed any APP built with this version of the build file?
> 
> 2.1 version was made with that version of build.graddle

It's so strange... I just built with `./gradlew createApp ZipMacAppDistribution` and the final APP is marked as damaged... I tried different times... :(
Because I see no huge rush on #372, I could work and find a suitable solution to this issue with Gradle (unless a Gradle expert that has a MacOS can work on it)... and then on the other issue of the folder location...

**Comment by akasolace** [comment]
I will try to make a 3.0 dev release just to confirm it works well on my PC

**Comment by tychobrailleur** [comment]
> > > @akasolace did you already distributed any APP built with this version of the build file?
> > 
> > 
> > 2.1 version was made with that version of build.graddle
> 
> It's so strange... I just built with `./gradlew createApp ZipMacAppDistribution` and the final APP is marked as damaged... I tried different times... :(

Ah, same here.  The app folder is missing the `MacOS` folder (containing `JavaAppLauncher`), and the `Resources` folder (with `HO.icns`)

**Comment by pierpaolocira** [comment]
Thanks @tychobrailleur ... 
@akasolace please test and let us know, because this issue seems to be more important than expected... :(

(Anyway in the worst case we can replace JARs inside a working APP and have a new release... it **should** work as a temporary workaround, if needed)

**Comment by akasolace** [comment]
@pierpaolocira @tychobrailleur is the 2.1 app working for you ?
I will do my best to build artefacts this week, next week I am skiing so not the best time. ...

**Comment by pierpaolocira** [comment]
@akasolace in the meanwhile can you please try to do your usual build with this version of the file (simply remove .txt extension)? I put some conditions and it allows me to succesfully build on MacOS.

The final APP is still the broken, but these changes should allow both to build a standard APP on MacOS and to do the complete build from your PC.

If that's not the case, I will go for some parameters.
[build.gradle.txt](https://github.com/akasolace/HO/files/4216477/build.gradle.txt)

**Comment by akasolace** [comment]
@pierpaolocira sure I will test this and let you know

**Comment by akasolace** [comment]
@pierpaolocira  @tychobrailleur   I just made artefacts (https://github.com/akasolace/HO/releases/tag/dev) with existing build.gradle
Can you confirm whether or not they work for macOS ?

**Comment by tychobrailleur** [comment]
> @pierpaolocira @tychobrailleur I just made artefacts (https://github.com/akasolace/HO/releases/tag/dev) with existing build.gradle
> Can you confirm whether or not they work for macOS ?

Yup, all good here.

![Screenshot 2020-02-18 at 20 46 11](https://user-images.githubusercontent.com/114285/74776621-d248aa80-528f-11ea-8890-c24760d00959.png)

**Comment by akasolace** [comment]
ok so at lest it confirms the build.gradle at least works for me.
Now we have to find out why it is so broken under macOS.
Tomorrow I will test the version you sent me

**Comment by pierpaolocira** [comment]
After a simple `diff` between my local generated APP and the one from @akasolace 

> 
> # diff -qr HO-pierpaolocira.app/ HO-v3-dev.app/
> Files HO-pierpaolocira.app/Contents/Info.plist and HO-v3-dev.app/Contents/**Info.plist differ**
> Files HO-pierpaolocira.app/Contents/Java/HO.jar and HO-v3-dev.app/Contents/Java/HO.jar differ
> **Only in HO-v3-dev.app/Contents: MacOS**
> Files HO-pierpaolocira.app/Contents/PkgInfo and HO-v3-dev.app/Contents/**PkgInfo differ**
> **Only in HO-v3-dev.app/Contents: Resources**
> Files HO-pierpaolocira.app/changelog.html and HO-v3-dev.app/changelog.html differ

I put in bold the differences that might be the cause (maybe not all of them)... but this seems to be a packaging issue.
If I have time I'll do some test this evening

**Comment by tychobrailleur** [comment]
@pierpaolocira The minimum `build.gradle` changes I need to have to properly build the Mac app is:

```
diff --git a/build.gradle b/build.gradle
index 0d67976..b70ea25 100644
--- a/build.gradle
+++ b/build.gradle
@@ -86,7 +86,7 @@ markdownToHtml {
 // Configure poeditor plugin ================================

 poeditor {
-    apiKey = POEDITOR_APIKEY
+//    apiKey = POEDITOR_APIKEY
     projectId = '206221'

     trans type:'properties', lang: 'bg', file: 'src\\main\\resources\\sprache\\Bulgarian.properties'
@@ -578,7 +578,8 @@ task ReleaseToGitHub(dependsOn: tasks.getByName('githubRelease')){
 }

 githubRelease {
-    def _token = GITHUB_TOKEN  // required token for your personal access with repo permissions
+//    def _token = GITHUB_TOKEN  // required token for your personal access with repo permissions
+    def _token = 'xxx'
     owner = 'akasolace'
     repo = 'HO'
     releaseAssets = file("$target_dir").listFiles()
@@ -619,8 +620,8 @@ githubRelease {
 //    task.dependsOn preparingBuild
 //}

-compileJava.dependsOn preparingBuild
-installDist.dependsOn createLanguageFileList
+//compileJava.dependsOn preparingBuild
+//installDist.dependsOn createLanguageFileList
 poeditorPull.dependsOn pullhtml
 markdownToHtml.dependsOn pushmd
 buildDeb.dependsOn installDist
```

Does this also work for you?  It doesn't process the language files at all, but gets up and running for me.

Note that I also comment out the dependency of `compileJava` on `preparingBuild`, startup times to run the app in the IDE was driving bananas.

**Comment by pierpaolocira** [comment]
> @pierpaolocira The minimum `build.gradle` changes I need to have to properly build the Mac app with `./gradlew createApp ZipMacAppDistribution` are:
> 
> ```
> diff --git a/build.gradle b/build.gradle
> index 0d67976..b70ea25 100644
> --- a/build.gradle
> +++ b/build.gradle
> @@ -86,7 +86,7 @@ markdownToHtml {
>  // Configure poeditor plugin ================================
> 
>  poeditor {
> -    apiKey = POEDITOR_APIKEY
> +//    apiKey = POEDITOR_APIKEY
>      projectId = '206221'
> 
>      trans type:'properties', lang: 'bg', file: 'src\\main\\resources\\sprache\\Bulgarian.properties'
> @@ -578,7 +578,8 @@ task ReleaseToGitHub(dependsOn: tasks.getByName('githubRelease')){
>  }
> 
>  githubRelease {
> -    def _token = GITHUB_TOKEN  // required token for your personal access with repo permissions
> +//    def _token = GITHUB_TOKEN  // required token for your personal access with repo permissions
> +    def _token = 'xxx'
>      owner = 'akasolace'
>      repo = 'HO'
>      releaseAssets = file("$target_dir").listFiles()
> @@ -619,8 +620,8 @@ githubRelease {
>  //    task.dependsOn preparingBuild
>  //}
> 
> -compileJava.dependsOn preparingBuild
> -installDist.dependsOn createLanguageFileList
> +//compileJava.dependsOn preparingBuild
> +//installDist.dependsOn createLanguageFileList
>  poeditorPull.dependsOn pullhtml
>  markdownToHtml.dependsOn pushmd
>  buildDeb.dependsOn installDist
> ```
> 
> Does this also work for you? It doesn't process the language files at all, but gets up and running for me.
> 
> Note that I also comment out the dependency of `compileJava` on `preparingBuild`, startup time to run the app in the IDE was driving bananas.

Thanks @tychobrailleur 
What I sent to @akasolace is a version of the build file that should be equivalent (except that it should be able to work also on MacOS, because it checks if a task can run and, in case of missing properties, will report in the console and skip the task).

I have to check properly the differences between or files... but I didn't understant if, by generating the APP with your file, you are now able to have a working APP or not.

**Comment by tychobrailleur** [comment]
> but I didn't understant if, by generating the APP with your file, you are now able to have a working APP or not.

With those changes I have a working app in the zip:

```
~/dev/HO (master) 🔰‏ patch -p1 < build.patch
patching file build.gradle
Hunk #1 succeeded at 85 (offset -1 lines).
Hunk #2 succeeded at 577 (offset -1 lines).
Hunk #3 succeeded at 619 (offset -1 lines).
~/dev/HO (master *) 🔰‏ ./gradlew clean createApp ZipMacAppDistribution
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.6.4/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

> Configure project :
Configuration start
Project:  HO 3.0.0.2642 .....................

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

> Task :AddResourcesMacApp
adding resources folder

> Task :ZipMacAppDistribution
zipping MacApp distribution

BUILD SUCCESSFUL in 23s
13 actionable tasks: 13 executed
~/dev/HO (master *) 🔰‏ ll build/artefacts/
total 20920
drwxr-xr-x  11 tychobrailleur  tychobrailleur   352B 19 Feb 18:48 ..
drwxr-xr-x   3 tychobrailleur  tychobrailleur    96B 19 Feb 18:48 .
-rw-r--r--   1 tychobrailleur  tychobrailleur    10M 19 Feb 18:48 HO_3.0.0.2642_macOS.zip
~/dev/HO (master *) 🔰‏ tar xvf build/artefacts/HO_3.0.0.2642_macOS.zip
x HO.app/
x HO.app/Contents/
x HO.app/Contents/Resources/
x HO.app/Contents/Resources/HO.icns
x HO.app/Contents/Java/
x HO.app/Contents/Java/gson-2.8.5.jar
x HO.app/Contents/Java/jgoodies-common-1.8.1.jar
x HO.app/Contents/Java/error_prone_annotations-2.2.0.jar
x HO.app/Contents/Java/checker-qual-2.5.2.jar
x HO.app/Contents/Java/HO.jar
x HO.app/Contents/Java/failureaccess-1.0.1.jar
x HO.app/Contents/Java/guava-27.1-jre.jar
x HO.app/Contents/Java/jgoodies-looks-2.7.0.jar
x HO.app/Contents/Java/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
x HO.app/Contents/Java/commons-codec-1.4.jar
x HO.app/Contents/Java/scribe-1.3.0.jar
x HO.app/Contents/Java/j2objc-annotations-1.1.jar
x HO.app/Contents/Java/animal-sniffer-annotations-1.17.jar
x HO.app/Contents/Java/hsqldb-2.4.1.jar
x HO.app/Contents/Java/jsr305-3.0.2.jar
x HO.app/Contents/Java/jcalendar-1.4.jar
x HO.app/Contents/Info.plist
x HO.app/Contents/PkgInfo
x HO.app/changelog.html
x HO.app/Contents/MacOS/
x HO.app/Contents/MacOS/JavaAppLauncher
~/dev/HO (master *) 🔰‏ open -a HO.app
~/dev/HO (master *) 🔰‏
```

**Comment by wsbrenk** [comment]
>Now we have to find out why it is so broken under macOS.

@akasolace sorry, it is not only broken under macOS, but also on windows. i cannot build with current build.gradle too.

**Comment by pierpaolocira** [comment]
@wsbrenk the issue you mentioned has been fixed in my version of the build file (see my previous comment).

@tychobrailleur thanks, I will try to merge your changes into my solution

I simply wait for @akasolace to know if my idea can be working also when building on his Windows ... then I'll proceed

**Comment by akasolace** [comment]
> I simply wait for @akasolace to know if my idea can be working also when building on his Windows ... then I'll proceed

I had not time wet but I promise I will try this one tomorrow. Having a look at it I think it will work but better to confirm.
For my info would it not have been simpler if you had set those properties on your end, even leaing therm empty? Maybe I am missing something

**Comment by pierpaolocira** [comment]
@tychobrailleur this is my output (I did the "clean" just some seconds before):
```
./gradlew createApp ZipMacAppDistribution
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
Configuration start
Project:  HO-pierpaolocira 2.1.0.2536 .....................
No POEDITOR_APIKEY defined: skipping task 'poeditor'...
Resetting DB: CANNOT copy DB
No GITHUB_TOKEN defined: skipping task 'githubRelease'...

> Task :preparingBuild
Deleting build and execution files ....

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :createLanguageFileList
listing available translation 

> Task :init SKIPPED
The build file 'build.gradle' already exists. Skipping build initialization.

> Task :AddResourcesMacApp
adding resources folder

> Task :ZipMacAppDistribution
zipping MacApp distribution

BUILD SUCCESSFUL in 21s
17 actionable tasks: 17 executed

#tar -xvf HO-pierpaolocira_2.1.0.2536_macOS.zip 
x HO-pierpaolocira.app/
x HO-pierpaolocira.app/changelog.html
x HO-pierpaolocira.app/Contents/
x HO-pierpaolocira.app/Contents/Info.plist
x HO-pierpaolocira.app/Contents/Java/
x HO-pierpaolocira.app/Contents/Java/animal-sniffer-annotations-1.17.jar
x HO-pierpaolocira.app/Contents/Java/checker-qual-2.5.2.jar
x HO-pierpaolocira.app/Contents/Java/commons-codec-1.4.jar
x HO-pierpaolocira.app/Contents/Java/error_prone_annotations-2.2.0.jar
x HO-pierpaolocira.app/Contents/Java/failureaccess-1.0.1.jar
x HO-pierpaolocira.app/Contents/Java/gson-2.8.5.jar
x HO-pierpaolocira.app/Contents/Java/guava-27.1-jre.jar
x HO-pierpaolocira.app/Contents/Java/HO.jar
x HO-pierpaolocira.app/Contents/Java/hsqldb-2.4.1.jar
x HO-pierpaolocira.app/Contents/Java/j2objc-annotations-1.1.jar
x HO-pierpaolocira.app/Contents/Java/jcalendar-1.4.jar
x HO-pierpaolocira.app/Contents/Java/jgoodies-common-1.8.1.jar
x HO-pierpaolocira.app/Contents/Java/jgoodies-looks-2.7.0.jar
x HO-pierpaolocira.app/Contents/Java/jsr305-3.0.2.jar
x HO-pierpaolocira.app/Contents/Java/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
x HO-pierpaolocira.app/Contents/Java/scribe-1.3.0.jar
x HO-pierpaolocira.app/Contents/PkgInfo
```
Build not so different... outcome confirms results of my previous diff


> For my info would it not have been simpler if you had set those properties on your end, even leaing therm empty? Maybe I am missing something

@akasolace yes, maybe it is. My idea was to have a build file that completely skips tasks that connet be performed by default (just to avoid issues, such as what wsbrenk just reported).
Indeed another possibility is to provide the property file with those value already empty, so that it works on any computer (and only you have your own different local copy)... but I was not sure that running a task without good values into variables would have allowed a proper build.

**Comment by akasolace** [comment]
>@tychobrailleur this is my output (I did the "clean" just some seconds before): ...

@pierpaolocira yes this is what I meant in various messages. Simply put a project level properties file with those property being defined and not populated because they will be under version control. Those who needs it (me) will have those override with local properties file. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pierpaolocira** [comment]
> @pierpaolocira yes this is what I meant in various messages. Simply put a project level properties file with those property being defined and not populated

Sorry @akasolace , just tried (both as undefined and with dummy value), but it doesn't work.

```
> Task :poeditorPull FAILED
401 Request missing API token
401 Request missing API token
[...]


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':poeditorPull'.
> Multiple task action failures occurred:
   > A failure occurred while executing de.jansauer.poeditor.PullRunnable
      > Request missing API token
[...]
```

Unless I'm missing something, the only way is to check for their existence in the script itself...

**Comment by pierpaolocira** [comment]
Ok... I managed to have the file working by adding another onlyIf to the POEditor.

Anyway I still continue to have the issue on Contents/MacOS and Contents/Resources that are missing, so the final APP cannot be opened.

I am using `./gradlew clean createApp ZipMacAppDistribution` as suggested... and the following is in the log
```
> Task :AddResourcesMacApp
adding resources folder
```
I think is something silly, which works on your Win, but not on Mac...

**Comment by pierpaolocira** [comment]
I think the `macAppBundle` plugin is not starting at all if I run `./gradlew clean createApp ZipMacAppDistribution`  ...

**Comment by pierpaolocira** [comment]
@akasolace I found that, by commenting the following 2 lines, the APP is built properlyç
```
compileJava.dependsOn preparingBuild
installDist.dependsOn createLanguageFileList
```
What do you prefer?
1. I attach here the new build file and you test it. If it works I do a PL, otherwise I continue to investigate
2. I do a PL and you test it before merging

**Comment by akasolace** [comment]
> Do you think it can be problematic for your build?

@pierpaolocira  yes that would be problematic. Those tasks `preparingBuild` and `createLanguageFileList` are really basic. I guess that if you replace \\ with File.separator it should run without issue on your side, no ?

Otherwise when you have something "final" please do a PR and I will test it before merging it.

**Comment by pierpaolocira** [comment]
@akasolace I already replaced "\"... but did't solve the issue...  
Anyway, can you confirm that "/" will work on your side when replacing "\\"?

I thought not having those dependencies would not be problematic because, without them, I have a fully working 3.0.DEV APP file...
And I see both of them being part of the `makeAll` task... so if you build via that task, it should not be problematic.

I'm sorry if it takes so long, but I'm spending a lot of time to fix something that was commited without being tested outside your PC. Don't misunderstand me: in standard conditions it's OK, because we can simply test our code without building a MacOS binary... but now I'm working on something that needs to be launched by a .APP file on MacOS in order to be tested and I'm blocked...

For me that change was already final. Simply tell me: if you use `makeAll` in order to prepare the build, then I will do a PR as it is now... if not I will continue to dig...

**Comment by pierpaolocira** [comment]
@akasolace  I finally managed to make it working in any case (without commenting those lines).

Everything was failing because of the instruction `project.delete(files("${buildDir}/"))` in the task `preparingBuild`.
I removed it and replaced task declaration with `task preparingBuild(dependsOn: clean) {`
By reading the documentation, the `clean` tasks does exactly a clean of the build folder, so it should be the same final effect.

To me this is final.
I will PR and you can try whenever you have time.

**Comment by akasolace** [comment]
ok cool I will test it asap
