### ISSUE TITLE
[eBUG] HO does not recognize league changes

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#391]
user from the german question forum reports:

> 
> After I changed the league in the last exchange period, the ho does not update it!
> 
> In the selection options in the League table tab, only my last league tables and the current table of my last league, from which I have switched, are displayed. What do I have to do so that the ho also finds my new league?

i think ho should check the league number after each download and handle a league change automatically.

**Comment by wsbrenk** [comment]
the user wass able to delete the current league and reload it by the next download interactivly.

**Comment by akasolace** [comment]
> i think ho should check the league number after each download and handle a league change automatically.

yes this can be implemented ...

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/75611513-62ea7a80-5b1b-11ea-86b4-d7194da9f57e.png)

i found that table SPIELPLAN stores 2 entries per season, when i went up or down a league. the order is arbitrary. 

i think the person who reported this issue only didn't see the correct entry, because it wasn't in first/upper position.

on the other hand there are a lot of plans in the database which do not belong to your own seasons.

**Comment by akasolace** [comment]
@wsbrenk is there something that needs to be done here, or should we close this one ?

**Comment by wsbrenk** [comment]
@akasolace i think it is an error, that ho stores plans from seasons, that are not from your own team. i would like to fix this.

**Comment by akasolace** [comment]
@wsbrenk ok understood

**Comment by wsbrenk** [comment]
SpielplanTable.storeSpielplan changed:
should ignore plans that are not from our own team

now i would like to get rid of all the foreign plans that were stored in the ho db. could be done manually, but a step in DBUpdater would be fine.

**Comment by akasolace** [comment]
ok  sounds good !
