### ISSUE TITLE
[eFEAT] Squad Tab, ordering of best position column is not saved on closing

### ISSUE THREAD

**Issue by orgogliobauscia** [akasolace/HO#397]
**Is your feature request related to a problem? Please describe.**
Since I upgraded to 2.1 the players are shown in reverse order of position (from strikers to goalkeepers).

**Describe the solution you'd like**
I'd like to set HO in order to have players shown from goalkeepers to strikers.

**Additional context**

**Comment by akasolace** [comment]
@orgogliobauscia I do not understand what the issue is about. Can you please give more details, also maybe screenshot to compare before vs 2.1
Thank you

**Comment by orgogliobauscia** [comment]
Il giorno dom 1 mar 2020 alle ore 11:43 akasolace <notifications@github.com>
ha scritto:

> @orgogliobauscia <https://github.com/orgogliobauscia> I do not understand
> what the issue is about. Can you please give more details, also maybe
> screenshot to compare before vs 2.1
>

Whenever I open HO, the players' order is from Strikers to Goalkeepers:
[image: Screenshot 1.jpg]

If I press the Best position column everything is ok, from Goalkeepers to
Strikers:
[image: Screenshot 2.jpg]

If I close HO and re-open it, the order is again from Strikers to
Goalkeepers:
[image: Screenshot 1.jpg]

I'd like to choose by myself the players' order.

Many thanks for your help.
-- 
Fulvio

Con i colori del cielo e della notte, infinito amore, eterna squadra mia.
(Gianfelice Facchetti)

**Comment by akasolace** [comment]
@orgogliobauscia Unfortunatly I can't see the pictures but now I get the issue ...

**Comment by tychobrailleur** [comment]
Hey @yaute74, I wonder if you could enlighten me on that one, as this seems to be the origin of this issue.  

I see `TableSorter`'s direction is ascending in this [new constructor](https://github.com/akasolace/HO/blob/master/src/main/java/core/gui/comp/table/TableSorter.java#L56) (as opposed to descending in the others).  I am not sure I understand the meaning of `thirdColSort` & `iThirdSort`, and what [this logic](https://github.com/akasolace/HO/blob/master/src/main/java/core/gui/comp/table/TableSorter.java#L182) is.  Would you be able to those two iVars are, and what they do?  Thanks in advance!

**Comment by yaute74** [comment]
Hi @tychobrailleur,
The goal is to have the possibility to sort a column in three way.
For example, for the column for which I implement:
- First click sort by name ascending
- Second click sort by name descending
- Third click sort by training/stamina
- Fourth click sort by name ascending
- ...

thirdColSort: is the id of the column who use the sort implementaton
iThirdSort: is the id of the cycle, to know if it's the third click

**Comment by tychobrailleur** [comment]
> Hi @tychobrailleur,
> The goal is to have the possibility to sort a column in three way.

Thanks @yaute74, that makes sense.  I'll see what I come up with this one, and might get back to you for review, if that's ok.

**Comment by wsbrenk** [comment]
Hi @tychobrailleur, do you think your changes could repair ticket #401 too? Could never reproduce this error.

**Comment by tychobrailleur** [comment]
> Hi @tychobrailleur, do you think your changes could repair ticket #401 too? Could never reproduce this error.

I think this is unlikely.  Is #401 an issue you're still experiencing?

**Comment by wsbrenk** [comment]
> I think this is unlikely. Is #401 an issue you're still experiencing?

not really - have not seen it again since the recording and since it occurred with many npe errors, I hoped that it was an interaction with those errors.
