### ISSUE TITLE
[eBUG]Counterattackrating calculation beyond divine is bugged

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#398]
kopsterkespits schrieb:

https://www.hattrick.org/Forum/Read.aspx?t=14250446&v=4&a=1&n=187

Counterattackrating calculation beyond divine is bugged. 4 defs give me 17.27 but after adding the 5th wich adds 5.03 when adding him in a 4 def lineup HO tells me 19.73 instead of 22.30. It has been like this in all versions. Would be nice to fix that.

I think the same happens with AOW and AIM around divine +2

**Comment by akasolace** [comment]
@DavidatorusF do you have a reference formula, external tool to calculate the tactic level ?
Is unwritten manual any good? 
CA Level Formula = 0,017272a + 1,042313
where a = sum of [Form{(2*defense passing skills)+(defense defending)}]

**Comment by DavidatorusF** [comment]
I'm not a scientific, sorry

but  LA-Alpa-UHS [userid=7514635] always update the unwritten with the last news from the community 

 micha1100 give some explanation in this topic [17308340.1] https://www.hattrick.org/goto.ashx?path=%2FForum%2FRead.aspx%3Ft%3D17308340%26n%3D1%26v%3D0
