### ISSUE TITLE
Player Compare Tab is missing some columns information for specific languages

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#41]
![schermata 2018-12-14 alle 11 09 32](https://user-images.githubusercontent.com/15519907/49997125-0f7d2280-ff91-11e8-8704-5b0820f9de5c.png)
With English lang, This is not verified, but in In italian lang is verified.
The column with error are POR and ATT.

**Comment by akasolace** [comment]
could you pleaes put the same screenshot but when having language English to show what is wrong ...

**Comment by mistermax80** [comment]
In english:
![schermata 2018-12-14 alle 11 43 42](https://user-images.githubusercontent.com/15519907/49998852-a350ed80-ff95-11e8-921b-ab697fc67b6f.png)

**Comment by akasolace** [comment]
@Davidatorus is this bug also exist on the french version?

was it introduced on the latest release, or was it also existing in the development versions?

**Comment by mistermax80** [comment]
I tried in Frenc, there is error, but on different colums:
![schermata 2018-12-14 alle 12 55 27](https://user-images.githubusercontent.com/15519907/50002264-d26c5c80-ff9f-11e8-89e3-6b62382dbad0.png)

**Comment by mistermax80** [comment]
I understand the error, if there is a column blu with same name column yellow, the column blu get error.
For this it is depend from languages. Infact with english lang, the columns yellows have different name columns blue.
Now I don't yet understand the code piece that check this.

**Comment by akasolace** [comment]
ok, just looking at the file main/java/module/playeranalysis/skillCompare/MyTableCellRenderer.java I  think I understand the bug, but **I don't understand why it was not present in 1.434**
basically, it looks at column title, and then there is list of elseif
so for french:
`table.getColumnName(column).equals(HOVerwaltung.instance().getLanguageString("ls.player.skill_short.keeper")) is True` so it gets yellow 
and it is not tested for `table.getColumnName(column).equals(HOVerwaltung.instance().getLanguageString("ls.player.position_short.keeper"))` which is located after

hence it is easy to fix, but before to do that, we need to look at how it was working in 1.434

**Comment by mistermax80** [comment]
In local I made fix: adding in 2 if the condition column<19 for yellow and column>=19 for blue.
This playertable is not depend from cinfiguration column list.
however I wait to propose, I think this bug there is sinse always.

**Comment by mistermax80** [comment]
I dubugged the code also in Player Overview, and in Player Overview the color cell is set by position attribute, it's present in object.
I module PlayerAnalysis this concept is not present, therefore, I think for this and the playeranalysis module is no depend by configuration column list, insert the condition <19 for yellow cell and >=19 for blue cell is the better solution.
I think is not convenient use more time for futher analysis.
@akasolace, could you think about this?

**Comment by akasolace** [comment]
@mistermax80 
I haven't look at the code in details, but do you think that background color can be passed as argument at column creation. After that the loop would set background color based on  column["color"] instead of column["name"], we would not have to use translations anymore, what do you think?

if it is too complicated to implement we can go with your proposal but addind some warning in the code.

Also, was it confirmed the bug also exist in 1.434 ?

**Comment by mistermax80** [comment]
I didnt seen of there Is present in 1.434, I Will check in this weekend, but I sure that code Is present since Always.

**Comment by akasolace** [comment]
closed by #47
