### ISSUE TITLE
[eBUG] Database folder "db" on MacOS located below /Users/<userid>/

### ISSUE THREAD

**Issue by masher82** [akasolace/HO#410]
The database folder on MacOS is located below the folder mentioned above. Instead it should be located below one of the following folders:

* `/Library/Preferences/<application name>/`
* `~/Library/Preferences/<application name>/`
* `/Library/Application Support/<application name>/`
* `~/Library/Application Support/<application name>/͏͏͏͏`
* `/Library/<application name>/`
* `~/Library/<application name>/ ͏͏͏͏`

**Comment by tychobrailleur** [comment]
This is a dupe of #372

**Comment by masher82** [comment]
> This is a dupe of #372

Yap. Thanks for the gibt.
