### ISSUE TITLE
[eBUG] calculation of age on player analysis page is wrong

### ISSUE THREAD

**Issue by AchimGrube** [akasolace/HO#422]
**Describe the bug**
player analysis page shows wrong age at specific dates

**To Reproduce**
1. Go to 'player analysis'
2. Pick any player
3. Scroll right to 'Age'

**Screenshots**
![player_age](https://user-images.githubusercontent.com/12234126/77197305-41aaf780-6ae5-11ea-8605-d0a5804b4272.PNG)

**Platform information:**
 - OS: Windows
 - Version 2.100

**Comment by wsbrenk** [comment]
i found the bug. i will prepare a pull request

**Comment by akasolace** [comment]
closed by #423
