### ISSUE TITLE
Match event table error

### ISSUE THREAD

**Issue by Gesjos** [akasolace/HO#424]
A java error appearance when try to open the match table.

Using macOs and HO 3.0 r2650 

![Näyttökuva 2020-03-23 kello 23 10 07](https://user-images.githubusercontent.com/62571678/77363700-da4aad00-6d5b-11ea-8a50-c84ca8b9b4a5.png)

and the rest.

![Näyttökuva 2020-03-23 kello 23 14 33](https://user-images.githubusercontent.com/62571678/77363915-3ad9ea00-6d5c-11ea-9979-e3bcbede6893.png)

already reinstalled HO and clean database.

**Comment by wsbrenk** [comment]
HI, could you please check the HO  log in folder logs if there is a sql error given. Should start with JDBCAdapter.executeQuery ....

**Comment by Gesjos** [comment]
Hi! don't know if this is it but,

23:46:01 [Error]   core.db.JDBCAdapter: JDBCAdapter.executeQuery : java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: MATCH_EVENT_ID
Statement: SELECT MATCH_EVENT_ID, COUNT(*) AS C FROM MATCHHIGHLIGHTS JOIN MATCHESKURZINFO ON MATCHHIGHLIGHTS.MATCHID = MATCHESKURZINFO.MATCHID WHERE TEAMID=554369 AND MATCH_EVENT_ID IN(104, 114, 124, 134, 154, 164, 174, 184, 204, 214, 224, 234, 254, 264, 274, 284) GROUP BY MATCH_EVENT_ID
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: MATCH_EVENT_ID

**Comment by wsbrenk** [comment]
same as #396. is fixed with HO_2.2.0.2644.
the fix is committed to the dev branch but not yet released, so it is not in HO 3.0 dev version yet.

One thing you could do, is to install HO_2.2.0.2644 and update it with the HO 3.0 dev version. Then it should work.

**Comment by wsbrenk** [comment]
@akasolace or could you release a new dev version.

**Comment by akasolace** [comment]
@wsbrenk ok I will do that tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akasolace** [comment]
@wsbrenk done !

**Comment by Gesjos** [comment]
I will update my HO and try it later, i tried to do it now, but i have a cup match ongoing so it doesn't let me update the HRF file. 
Anyway, i will try it tomorrow. This was probably the fasted error fix i have ever ask. Thanks guys!

**Comment by wsbrenk** [comment]
@Gesjos only updating r2650 to r2670 will not work, since no database update would be done. you have to init a clean database by installing a new r2670 instance.
