### ISSUE TITLE
[eBUG] Simulate button not visible in TeamAnalyzer until moving split pane divider

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#430]
**Describe the bug**
The “Simulate” button is not visible on the TeamAnalyzer tab until the split pane between the list of games and the Special Events section is lowered

**To Reproduce**
1. Go to TeamAnalyzer
2. Select a team in the drop down, and click “Update”
3. Click “Analyze”
4. Observe that the “Simulate“ button is not visible below Special Events.
5. Lower the split pane divider
6. Observe that the “Simulate” button has appeared.

**Screenshots**
Step 4.

![Screenshot 2020-03-26 at 20 20 16](https://user-images.githubusercontent.com/114285/77693109-b8da0300-6f9f-11ea-91d1-56261ac97692.png)

Step 6.

![Screenshot 2020-03-26 at 20 20 24](https://user-images.githubusercontent.com/114285/77693126-be374d80-6f9f-11ea-980e-5670b51f5d56.png)

**Platform information:**
 - OS: macOS 
 - Version: master HEAD

**Additional context**
This seems to be related to the Special Events feature that was recently merged.

**Comment by wsbrenk** [comment]
@tychobrailleur this IS related to special events feature. 
Commit: f03ef8b65583b3184f3cc5e6940e337acd4924c9 was the try to repair this. 
could you try to verify what was wrong with your userparameters concerning the divider positions?

**Comment by akasolace** [comment]
@tychobrailleur @wsbrenk I am using 3.0 r2670 and I can't reproduce ....

**Comment by tychobrailleur** [comment]
Before executing on my DB v. 25:

![Screenshot 2020-03-27 at 08 32 14](https://user-images.githubusercontent.com/114285/77737314-a2669280-7005-11ea-8e10-b59e20a45866.png)



The `DBUpdater` executes correctly (i.e. deletes the three values for `teamAnalyzer_`:

![Screenshot 2020-03-27 at 08 12 23](https://user-images.githubusercontent.com/114285/77735648-dab8a180-7002-11ea-91fb-5063d0994bc6.png)

After shutting down HO:

![Screenshot 2020-03-27 at 08 35 12](https://user-images.githubusercontent.com/114285/77737471-f5d8e080-7005-11ea-84dd-78b9bffbc1b5.png)


I will investigate further later to understand how this button is added, but this could be LAF-related based on my OS, or even a screen resolution issue.
