### ISSUE TITLE
[eBUG] Training is only applied to subbed-off players

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#431]
On 2.100, on a fresh account with only a few HRFs:
![image](https://user-images.githubusercontent.com/1204726/77729941-20279f80-7000-11ea-9aa2-bee13ecf04c2.png)
My training looks like this, where 10 players should have been impacted:
![image](https://user-images.githubusercontent.com/1204726/77730000-37ff2380-7000-11ea-805a-d16ffa6cf881.png)
3 full trainings (only to those that played on Wedsneday a 120-minute game and were subbed-off at 90' ([657739486](https://www.hattrick.org/Club/Matches/Match.aspx?matchId=657739486&sourceSystem=Hattrick&teamId=9059&BrowseIds=655187206%2C657483313%2C655187207%2C657583125%2C655187213%2C657663664%2C655187217%2C657739486%2C655187221%2C657813882%2C655187228%2C655187232%2C655187236#tab0))) and 3 osmosis (all 3 played both matches).

This might be related to #278 and #306 

PS: XP is similar.

**Comment by wsbrenk** [comment]
#520 could be the fix concerning experience failure

**Comment by wsbrenk** [comment]
tried to reproduce with v3.0:

on 6.5.2020 my team had a penalty shot out in a friendly match and Wilbert Pander entered in minute 90 for Pit Drexler. 

Situation in HO before training is:
![wpbeforetraining](https://user-images.githubusercontent.com/11821502/84065193-3cfb2e80-a9c4-11ea-8fdd-4b3201c84576.png)

situation on 8.5 (after training) is:

![wpaftertraining](https://user-images.githubusercontent.com/11821502/84065228-4f756800-a9c4-11ea-8096-4967c68ec81f.png)

in this case pander got training.

**Comment by wsbrenk** [comment]
@dominiquelee could you try to verify if this is still an issue in v3. are the training effects OK if you run a recalc of the subskills?

**Comment by wsbrenk** [comment]
#522 did some changes on minutes calculation concerning subskills

**Comment by wsbrenk** [comment]
@akasolace found this in MatchStatistics.getMatchEndMinute

...
			MatchEventID me = MatchEventID.fromMatchEventID(hls.get(i).getiMatchEventID());
			if (me == MatchEventID.MATCH_FINISHED){endMinute = hls.get(i).getMinute();}
			else if ((me == MatchEventID.RED_CARD_2ND_WARNING_NASTY_PLAY	||
					  me == MatchEventID.RED_CARD_2ND_WARNING_CHEATING ||
					  me == MatchEventID.RED_CARD_WITHOUT_WARNING ||
					  me == MatchEventID.MODERATELY_INJURED_LEAVES_FIELD ||
					  me == MatchEventID.BADLY_INJURED_LEAVES_FIELD ||
					  me == MatchEventID.INJURED_AND_NO_REPLACEMENT_EXISTED ||
					  me == MatchEventID.INJURED_AFTER_FOUL_AND_EXITS)  &&
					hls.get(i).getSpielerID() == spielerId) {endMinute = hls.get(i).getMinute();}}
		 return endMinute;

you are the expert on MatchEvents. do you think that there could be some changes that hurts this minute calculation? I would suggest a method near to MatchEvent called isPlayerLeaveMatchEvent or something like this.

**Comment by wsbrenk** [comment]
as first approach i added INJURED_AFTER_FOUL_AND_NO_REPLACEMENT_EXISTED

**Comment by wsbrenk** [comment]
next is KEEPER_INJURED_FIELD_PLAYER_HAS_TO_TAKE_HIS_PLACE should be handled like a substitution

**Comment by wsbrenk** [comment]
isInjured() || isRedCard() will do the job?!

**Comment by dominiquelee** [comment]
Sorry for the delay, here's the db: 
[db_singleUser-2020-6-11.zip](https://github.com/akasolace/HO/files/4774431/db_singleUser-2020-6-11.zip)

**Comment by wsbrenk** [comment]
@dominiquelee thanks a lot - i found a bug. I have to check whether this is responsible for your ticket.
