### ISSUE TITLE
[eFEAT] in Lineup tab display X. Lastname instead of just Lastname in player checkbox

### ISSUE THREAD

**Issue by cr0ssw1nd** [akasolace/HO#435]
Lineup boxes are too narrow, long player names are not displayed properly. Left and right from lineup boxes is unused space. Please size the boxes in width according to the space left, minus a few px (20-30px or so) border. That would make player names much more readable.

**Comment by akasolace** [comment]
In 3.0 only the last name of players is displayed. It should fix that issue you are experiencing

**Comment by cr0ssw1nd** [comment]
Well, I don't know if displaying only last name is a good idea. There 
are teams, mainly from smaller country, where the same last name appears 
more than twice or three times... however, it will solve my current 
issue :-)

Am 05.04.20 um 16:27 schrieb akasolace:

**Comment by akasolace** [comment]
it is actually replicating HT interface ... do you know if HT does anything special if 2 players with same last name are aligned?

**Comment by cr0ssw1nd** [comment]
New lineup page is displaying only last name, but old one is displaying 
first letter of first name dot last name, i.E.  J. Odhiambo, or B. 
Odhiambo, which would make sense imho. Would be easy to implement and 
very helpful... :-)


Am 05.04.20 um 17:58 schrieb akasolace:

**Comment by akasolace** [comment]
@cr0ssw1nd  I put it for under consideration after 3.0

**Comment by akasolace** [comment]
This has been solved by info bull information in 3.0
