### ISSUE TITLE
[eBUG] fix multiple issues about player names (especially when composed)

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#451]
1) Retrieve player first name and nickname during CHPP download 
2) Store the 3 information separately (nickname, firstname and lastname) in the database
3) modify function get shortname, et first name ... accordingly 

@tychobrailleur  @wsbrenk   what do you think about this one ?

**Comment by tychobrailleur** [comment]
Do you have examples of the issues that arise?  I think it's good idea, it would be more flexible for us, it may be tricky to migrate existing databases, though.  Do you intend to re-download all names? It's probably the less error-prone approach, but the heaviest in terms of processing.

**Comment by akasolace** [comment]
I think it is done .... I will have to test it a bit more before I commit so I keep it aside for one more day.
