### ISSUE TITLE
[eBUG] AutoLineup: error in player selection when starting changing states of inclusion checkboxes

### ISSUE THREAD

**Issue by AchimGrube** [akasolace/HO#459]
**Describe the bug**
Marking the checkbox of players to select them for auto-lineup feature doesn't work.

**To Reproduce**
1. Select Checkbox of some players
2. Click on 'Start Assistant'
3. Compare chosen players with the once you marked before

**Screenshots**
![ho_auto](https://user-images.githubusercontent.com/12234126/79876685-a3fc5e00-83eb-11ea-99d4-e8a44241d9d2.png)

**Platform information:**
 - OS: Win 10
 - Version 2.1 (2635)

**Additional context**
It doesn't matter how many players you choose, I just took 11 for simplicity.
10 players get into the lineup, second CD doesn't even get picked while there are players left (checked and unchecked).
Marked but ignored striker is 2 levels stronger then the picked one, so player strength isn't causing the problem.
When activating "Exclude Last Lineup", different players will be selected, but still wrong ones and there's also just 10 players in the lineup.

Edit: When restarting HO, there's another selection of players which exactly (minus the ones booked or allready played) matches the players picked by the assistant, but I've never made this selection and after changing and restarting, it's reset to the wrong ones again.

**Comment by akasolace** [comment]
@AchimGrube  uncheck "exclude last lineup"

**Comment by AchimGrube** [comment]
Ups, that's just a typo. I meant deactivating "Exclude Last Lineup".

After some more testing, I'm sure HO is saving the status of all Checkboxes somewhere and isn't updating their status. Whenever I restart HO, the same players are selected and even when I change and Checkboxes, those players being selected after loading are the once put in the lineup.

**Comment by akasolace** [comment]
is your issue is only there with "Exclude Last Lineup" checked ? Or do you always have less than 10 players aligned while removing all restrictions?

**Comment by tychobrailleur** [comment]
(apologies, totally unrelated to this, but am I right in saying you use a JGoodies skin, @AchimGrube ?  We were considering removing them in later releases, but if people do actually use them, we should keep them...)

**Comment by AchimGrube** [comment]
@akasolace The issue happens no matter if "Exclude Last Lineup" is checken or not. But I'd say after some testing, the issue itself is that HO did save some selected players in the history and won't change that selection, no matter what I do.

@tychobrailleur I just found it a nice skin, you don't have to keep it just for me :D

**Comment by akasolace** [comment]
@AchimGrube not sure what the error is ... can you share your database with us, we will try to reproduce it ....

**Comment by AchimGrube** [comment]
[db_singleUser-2020-4-25.zip](https://github.com/akasolace/HO/files/4533665/db_singleUser-2020-4-25.zip)

When I start HO using this DB, following players are selected for Auto-Lineup. When I change that to any other selection (others, everyone, noone) and restart HO, it's the same players again as if I didn't change anything.
![ho_bug1](https://user-images.githubusercontent.com/12234126/80287075-a0d8d900-872f-11ea-98b6-55b0157beccc.PNG)

For simplicity, let's just change the status of every combobox and start the assistant. As you can see by the colored shirt icons, HO still takes the players seen in the first screen and ignores the changed selection:
![ho_bug2](https://user-images.githubusercontent.com/12234126/80287165-3aa08600-8730-11ea-9c0e-920e7e3fc1a0.PNG)

**Comment by akasolace** [comment]
@AchimGrube I have never used those check boxes before (did not really noticed them before :-) )

FYI, personally I am only playing with squad letter to do those selection.  Usually what I do, after my league game, I import my game assigned the player aligned to the team A. Then I use the assistant by ignoring player with Team A. 

But as those check boxes exist, I will check whether or not they are working. 
For info, just made a test with my HO! and it seems to work. I will do some test with the db you provided and come back to you

**Comment by akasolace** [comment]
@AchimGrube I confirm the bug, now I am not sure if we should we fix that bug or remove that functionality. The assistant should already consider, the team selection, the last lineup, the best position first, the advance injured/suspended ... it is clearly prone to errors. Could you find a process without that checkbox?

@wsbrenk  @tychobrailleur   what do you think ?

**Comment by tychobrailleur** [comment]
I don't really use that feature, other than to exclude the coach and certain old players, which makes me think there can be some use to it.

The list of selected players should be the initial input before applying all the other criteria, IMHO (if it's not how it works currently).

**Comment by akasolace** [comment]
>  The list of selected players should be the initial input before applying all the other criteria, IMHO (if it's not how it works currently).


@tychobrailleur   At the moment it is very erratic. I made some test, it works until it does not and after that it stays broken. I haven't look at the code and I have no idea how easy or difficult it would be to fix it. I just wanted whether or not we want to fix it but it seems that it is being used ... so we will need to fix it.

**Comment by akasolace** [comment]
@AchimGrube can you please check if you still have this issue with the latest build version 3.0.1.2725 ?
Thank you

**Comment by AchimGrube** [comment]
Sorry, I didn't find the time earlier. I'll check it out next days and give you feedback.
