### ISSUE TITLE
[eFEAT] Allow manual adjustment of experience level (similar to other skills)

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#463]
After some years I reinstalled HO! again for my team. After downloading my latest .hrf I found I **cannot edit the experience rating** of my players, I only got the full levels from Hattrick, no sub levels are shown. I have no old .hrf files.
Same issue with new bought players from transfer market.

I would like to edit the experience data of my players manually.
I kept offline track of recent XP gain and can use data from foxtrick, too.

Even better would be an automatic XP calculation /estimate similar to foxtrick, I do not know if this is possible.

Thanks for your work, best regards!

**Comment by akasolace** [comment]
closed by #467
