### ISSUE TITLE
[eBUG] Too high HatStats and LoddarStats in TeamAnalyzer

### ISSUE THREAD

**Issue by velikodsky** [akasolace/HO#464]
**Describe the bug**
HatStats in TeamAnalyzer is almost 4 times greater than those in Matches Analyzer (or Matches) for the same match. LoddarStats in TeamAnalyzer is almost 4 times greater than it must be as well.

**To Reproduce**
1. Go to 'TeamAnalyzer'
2. Select own team
3. Click 'Analyze'
4. See HatStats and LoddarStats in the table of matches
5. Go to 'Matches Analyzer' or to 'Matches'
6. See HatStats for the same matches and compare with TeamAnalyzer's values

**Platform information:**
 - OS: Linux
 - Version 3.0 r2708 (the same was in ver. 2.1)

**Comment by wsbrenk** [comment]
@akasolace i want to select #66 as my next work. There may be interference with this ticket.

**Comment by akasolace** [comment]
@wsbrenk  #66 is a big one for 4.0.  This one is a quick fix for 3.0, I was planning to do it the coming days but I haven't started, if you want you can assign it to yourself.

**Comment by wsbrenk** [comment]
@akasolace i will try to get #66 working. but by the way, i do not find any button that lets me assign to an issue, are there some privileges missing?
