### ISSUE TITLE
[eBUG] Lag in displaying selected row in PlayerOverviewTable

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#465]
**Describe the bug**
When selecting a player in `SpielerUebersichtNamenTable`, the row for the same player is also selected in `PlayerOverviewTable` (and vice-versa).  There is a however a noticeable between the moment the player is selected in one, and the moment when it is selected in the other, which is even more obvious in dark mode.

**To Reproduce**
1. Go to Squad tab
2. Click on a player's name 
3. Notice lag in selecting the rest of the details

**Screenshots**
The colours in the capture below are incorrect, but that is irrelevant for this issue, and will be taken care of.

![lag](https://user-images.githubusercontent.com/114285/80279197-de1f7580-86f3-11ea-824e-c8249803d906.gif)

**Platform information:**
 - OS: macOS
 - Version 2726

**Additional context**

**Comment by akasolace** [comment]
@tychobrailleur I can't reproduce it ....

![aaaaa](https://user-images.githubusercontent.com/1136496/80282445-d53d9c80-8711-11ea-9a7a-ba38b00679a0.gif)

**Comment by tychobrailleur** [comment]
> @tychobrailleur I can't reproduce it ....
> 
> ![aaaaa](https://user-images.githubusercontent.com/1136496/80282445-d53d9c80-8711-11ea-9a7a-ba38b00679a0.gif)

It is there, but not as pronounced: for example when you select Zbigniew, the row of details is select, and a fraction of second later, his name is selected.

I think darklaf is causing a paint performance issue, making the problem even worse, I'll see if there is a way to mitigate.

**Comment by akasolace** [comment]
yes indeed, I did not see it in first place.
When the row selection change:  highlight is updated as well as player details. Maybe player details is populated first which could explain the time lag... Obviously it does not explain why this is so much visible with darklaf

**Comment by tychobrailleur** [comment]
That one is a tricky one: the `ListSelectionEvent` triggered updates the other table in `Squad`, but also in `Lineup` , which each one in turn causes `setPlayer` to be called each time.

There seems to be indeed some ordering whereby `Lineup` tables are set first, and `Squad` next, but swapping would cause a similar issue in the `Lineup` tab, I would imagine...

More experiment needed here.

**Comment by akasolace** [comment]
sounds like a tough one ....
I am surprised lineup and squad interact one with another. I don't see why this is required...
