### ISSUE TITLE
[eBUG] HRFs import not working on 3.0 ...

### ISSUE THREAD

**Issue by steffanots** [akasolace/HO#469]
I have bug message on start.
![start log](https://user-images.githubusercontent.com/64475678/80486517-969b2280-895b-11ea-9e8d-be0e43d07d26.jpg)
I can't load any match.  My matches tab is empty. I can't load match in leage.
![load match log](https://user-images.githubusercontent.com/64475678/80486612-c4806700-895b-11ea-8f20-bdbf0d14fd16.jpg)

**Platform information:**
 - OS: Windows 
 - Version 3.0
- Java 14

**Comment by akasolace** [comment]
@steffanots there is clearly an issue with your db, you upgraded from 2.2 ?

**Comment by akasolace** [comment]
@steffanots could you paste here a link to your database ?

**Comment by steffanots** [comment]
> @steffanots there is clearly an issue with your db, you upgraded from 2.2 ?

No I don't
I loaded hrf files in 3.0 version.

[db.zip](https://github.com/akasolace/HO/files/4546099/db.zip)

**Comment by steffanots** [comment]
Just a note :
 had a problem with matches in  2.1 version. After 2.1 version I use dev2,2.

**Comment by akasolace** [comment]
@steffanots  could you try to delete 3.0 database.  Copy inside a copy of your 2.1 or 2.2 database and start HO again.

**Comment by steffanots** [comment]
I delete db as you told me. Than I copy only from 2,2 version. Now, I have matches. :)
Hrf files look ok at first sight. Maybe one of them has no some property or wrong property.

**Comment by akasolace** [comment]
@steffanots  ok cool but this confirm me that we might need to drop HRF and just rely on the db...

**Comment by tychobrailleur** [comment]
I am torn on that one: I like the idea of the HRF files, because they are text-based, and I know people tend to keep them around.  But if they are not backward-compatible, there's not much point...

I wonder if this is a feature that could be moved into some sort of optional module, somehow.

**Comment by akasolace** [comment]
@tychobrailleur  to be think about but I don't see how easily support this ...

**Comment by steffanots** [comment]
I know I'm not part of your team, but as a programmer and gamer (HT and FM) I can tell you that it's no problem to remove files, but if they keep my history and you don't give me any other way to see it then it's a big mistake. 
Keeping compatibility is an art of programming but also necessary to continue HO. 
I have been playing HT since 2007 and stopped in 2016 because some 'software engeener' is fucked  HT. 
I am offering help as much as time permits me. I have a job and kids. :)

**Comment by akasolace** [comment]
> I know I'm not part of your team, but as a programmer and gamer (HT and FM) I can tell you that it's no problem to remove files, but if they keep my history and you don't give me any other way to see it then it's a big mistake.
> Keeping compatibility is an art of programming but also necessary to continue HO.
> I have been playing HT since 2007 and stopped in 2016 because some 'software engeener' is fucked HT.

It is just that if database is corrupted re-importing all HRF files will not do the trick (I think this functionality has been broken for years). In theory it is possible to introduce versioning of HRF file along versioning of database and ensuring import of HRF can be made over a long period but it would be a lot of work. I suggest we focus on having more reliable database backup (more than 3? on-demand data backup ?)

> I am offering help as much as time permits me. I have a job and kids. :)

I think we all have jobs, kids and not enough time  :-)   If you are willing to help (and I understood you are a Java dev) you are more than welcome. Pick up any non-assigned issue (that one for example ? ) and give it a try ...

**Comment by steffanots** [comment]
> I think we all have jobs, kids and not enough time :-)

True.

I cloned a project. I standard problems.
Gradle project not worked on 14 so I took 12. After that can't compile ... move sdk to 8.
Finally I start HO. :)

**Comment by akasolace** [comment]
>I cloned a project. I had standard problems.
Gradle project not worked on 14 so I took 12. After that can't compile ... move sdk to 8.
Finally I start HO. :)

@steffanots  cool,  let me know if you pick up an issue to work on !

**Comment by steffanots** [comment]
I need a time to introduce in code. After that I will let you know.

**Comment by akasolace** [comment]
@tychobrailleur @steffanots @wsbrenk    I just had a look at what exactly HRF files contains. 
It is actually only data about players, staff, economy and few more things but nothing about matcches. Hence, the HRF files might not be broken. 

@steffanots  when you reported the bug. You simply had downloaded 3.0 and imported your hrf files ?  After that you had an error when trying to download new data or import new games, right ?

If it is the case I don't know what it is but it might not be related to HRF as I first thought.

**Comment by akasolace** [comment]
I made a quick test, 

1) launch new 3.0 without DB
2) Import HRF files
3) try to import / download match   =>  this does not work !

@steffanots  I think this is what you expereinced.

**Comment by wsbrenk** [comment]
@akasolace the question is, if it is broken since 1.437 or only since 2.0. I think a lot of users are still using the old version and if we kill there backup method we could have problems with their acceptance.
on the other hand we should introduce a new and better backup concept that not only stores the last 3 db dumps.

**Comment by akasolace** [comment]
> @akasolace the question is, if it is broken since 1.437 or only since 2.0

I don't know really.  I will have a look, see how easy/difficult it is to fix it, and then we decide what we do ...

**Comment by wsbrenk** [comment]
@akasolace concerning backup concept: i would suggest to keep backup of
- last season
- last month
- last week
- last 3 sessions

**Comment by wsbrenk** [comment]
concerning hrf support. I think we have to keep this hrf-table to select the date of comparison. And if we will keep the delete button, some kind of restore would be good.

![hrf](https://user-images.githubusercontent.com/11821502/80741953-ce9c9400-8b1a-11ea-9e61-447a22bd34e0.png)

**Comment by tychobrailleur** [comment]
> > @akasolace the question is, if it is broken since 1.437 or only since 2.0
> 
> I don't know really. I will have a look, see how easy/difficult it is to fix it, and then we decide what we do ...

Totally agree with that, not much point in speculating. :-)

As I mentioned earlier, I do see some value in the HRF files, so we could maintain the HRF stuff in a separate project (incl the HRF Explorer) as a set of tools.

If we however remove them from HO, we need to keep track of download dates to be able to show what @wsbrenk is showing above – I don't if this is done today or not, I have not looked at how we deal with historic data.

**Comment by akasolace** [comment]
@tychobrailleur @wsbrenk  ok lets keep it

I cleaned a bit the HRF section but this particular bug has in the end nothing to do with HRF but is caused by that commit  abff7bcaa13a63c3b6deef43ac4188514509350e

So the database in 3.0 is broken for everyone not upgrading his database

**Comment by steffanots** [comment]
> @steffanots I think this is what you experienced.
Yes

I try to reproduct and I saw an error in Lineup. 
Can I try to solve the problem of importing HRF files?

**Comment by akasolace** [comment]
> I try to reproduct and I saw an error in Lineup.
Can I try to solve the problem of importing HRF files?

@steffanots  I think it is now solved on master branch. If you still have an issue could you please share here the problematics HRF files (i.e the ones you can't import).

**Comment by steffanots** [comment]
I'm sorry to say, but the problem persists.
I need to add that I took a team on 3 round this season. 
[hrfs.zip](https://github.com/akasolace/HO/files/4563195/hrfs.zip)

**Comment by akasolace** [comment]
@steffanots  ok there is another bug
in some of your hrfs files (he most ancients) you have some attitude parameters without values I don't know how this could be caused but I will fix this
`installning=`

**Comment by steffanots** [comment]
> installning=
I saw this when I said "the problem persists."
Maybe you could give me a BUG with small priority for start.
I'm a team leader but I'm a beginner here. :)

**Comment by akasolace** [comment]
@steffanots I will look at open bug tickets and selects some that I think could be a good introduction to HO! development...

**Comment by akasolace** [comment]
@steffanots I think #461 could be a good start.  What do you think?
You can also join us on Slack. There is not a lot of activity but we still discuss on it couple of time a week. 
https://join.slack.com/t/ho-tle6272/shared_invite/zt-d8hl9bnl-NRE1_TIwMfFVDco6TuJLwg
