### ISSUE TITLE
[eBUG] NPE in Match tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#472]
from HO forum 

> Hi, i have a problem.
> Match-Next Match (single game) - right arrow , simulation- error.
> It only works on games already played.

![image](https://user-images.githubusercontent.com/1136496/80532005-c833de00-899b-11ea-86db-c9ff448063ea.png)

**Comment by akasolace** [comment]
@wsbrenk @DavidatorusF  I would like to look into this one, for sure solving the NPE error.
I never really used that functionality so I am not sure of what was the intended behaviour. For past game, simulation is done on actuals ratings that is ok. For future games, only the button for simulation is activated so I guess this was intentional but how the simulation was supposed to work without knowing the ratings ? For future games, simulation should only be launched from Team Analyser, no ?  In short my question is:
    - should I simply deactivate the simulation button for upcoming game ?
    - should simulation be allowed but in that case which ratings should be used?

Maybe one of you recall how this was working in the past.

**Comment by DavidatorusF** [comment]
@akasolace 
for upcoming matches, users have to set himself the opponent's ratings
by default, they was set to the minimum

![image](https://user-images.githubusercontent.com/45043004/80628431-9da45c80-8a51-11ea-8df1-2018a7724f6b.png)

**Comment by akasolace** [comment]
@DavidatorusF  and for own team I guess it is rating from current lineup ... if so it is very easy to restore that functionality
