### ISSUE TITLE
[eBUG] unwanted match types re-downloaded (automatically?)

### ISSUE THREAD

**Issue by murko69** [akasolace/HO#473]
**Describe the bug**
After Beta 3.0 that introduced the possibility to uncheck unwanted match types to download, the very same matches I didn't want was downloaded automatically(?) when visiting module Match Analyzer.

**To Reproduce**
1. If you have for instance a recently played a HTO-integraded game, delete that one or more from your matches tab. (I think the bug works on all recent played games, I'm just making an example)
2. Press F11
3. Uncheck the option for the deleted game type so you don't download it again
4. Download
5. Go to module Match Analyzer

Somewhere around here (maybe I clicked something or maybe I didn't. Actually just think I changed team.....) I noticed something was downloading in the background.
I went back to matches tab and changed to "view all my matches" and noticed that almost all my HTO-integrated games that I first deleted and then unchecked for download, was downloaded again without me really 'doing anything'!

Since I don't use the Match Analyzer I figured it was best to just de-activate it instead and start over. This works for me but maybe this is worth looking over so the module doesn't start downloading match types you just opted-out from.

**Comment by akasolace** [comment]
@murko69 I guess you clicked analzed on an opponment and has a result had few non official games downloaded, right?

**Comment by wsbrenk** [comment]
@murko i had a look to the source and i think you are right. the match analyzer starts a match archive download of the analyzed team. this function does not use the new filter settings.

in my ho the match analyzer module is deactivated. i never used it;-(
is it expected that the match analyzer should use the same filter settings as the normal download?

**Comment by murko69** [comment]
> 
> 
> is it expected that the match analyzer should use the same filter settings as the normal download?

IMO it should use the same filter settings. If a user opts-out of a certain match type at download, he might still get it if/when using match analyzer and that seems wrong.

**Comment by wsbrenk** [comment]
@murko69 @akasolace the easiest solution would be to disable the storing of downloaded matches by the  match analyzer

**Comment by wsbrenk** [comment]
the team analyzer uses the same download function with parameter store=false. ta uses it's own filter settings to reduce the match list.

**Comment by akasolace** [comment]
> @murko69 @akasolace the easiest solution would be to disable the storing of downloaded matches by the match analyzer
> the team analyzer uses the same download function with parameter store=false. ta uses it's own filter settings to reduce the match list.

@wsbrenk so you are saying currently TA use same download function but with `store=false` which is what we want. Does it mean the parameter is not respected as the games are stored anyway?

**Comment by wsbrenk** [comment]
@akasolace the parameter in OnlineWorker is respected. The MatchAnalyzer uses store=true.

**Comment by akasolace** [comment]
@wsbrenk  ok sorry I misread team analyser and match analyser ... so yes I guess passing store=false is the way to go ...

**Comment by wsbrenk** [comment]
there are 3 situations, that download ALL matches without filtering:

CHeck Old matches in normal DownloadDialog (store=true)
![grafik](https://user-images.githubusercontent.com/11821502/80641105-aa7e7b80-8a64-11ea-85a5-bd75df68e729.png)

TeamAnalyzer Update Button, uses it's own filter (store=false), matches are filtered and stored afterwards:
![grafik](https://user-images.githubusercontent.com/11821502/80641315-f7625200-8a64-11ea-9a51-cb7d963496c4.png)

MatchAnalyzer starts automatically, i think (didn't check up to now)

**Comment by akasolace** [comment]
> MatchAnalyzer starts automatically, i think (didn't check up to now) 

Yes I think so considering how slow it is to get the tab activated.

@wsbrenk @wsbrenk   but more generally I don't see what MatchAnalyzer really brings compare to TeamAnalyzer. It is a bit more visual but there are no additional information. Is it really a module we need to keep? What do you think ?

**Comment by wsbrenk** [comment]
@akasolace I would be for it, maybe you start a question in hattrick (umfrage) whether this is still used. (same with hrf files and experience viewer)

![grafik](https://user-images.githubusercontent.com/11821502/80737602-0fdd7580-8b14-11ea-9078-7f06ad0df1e0.png)

**Comment by akasolace** [comment]
@wsbrenk I have been looking at it again and it seems really useless. I can ask on HO forum but then it is not really up to us anymore ...

**Comment by wsbrenk** [comment]
@akasolace OK, then i will remove the match analyzer - it is a long weekend this time, should be a nice job.

**Comment by tychobrailleur** [comment]
> > MatchAnalyzer starts automatically, i think (didn't check up to now)
> 
> Yes I think so considering how slow it is to get the tab activated.

The calls could be made asynchronous, the same way I have done it for the Promotion manager, but I am in favour in removing it: its look and feel is out of place, and not really useful.

The one thing I use it for is to see tactics and formations used by opponents – that would be nice to see that at a glance in Team Analyzer.

**Comment by akasolace** [comment]
> The one thing I use it for is to see tactics and formations used by opponents – that would be nice to see that at a glance in Team Analyzer.

yes I think this module is useless but that some part of it should be implemented in matches (details HatStats def/attck/mid ) and the remaining in Team analyser (tactics, formation)

**Comment by wsbrenk** [comment]
@akasolace good plan. who will take the photos of the match analyzer to describe the features for ticket no 2?

**Comment by akasolace** [comment]
This issue will be tackle by #476 and #477

**Comment by wsbrenk** [comment]
@akasolace i think here is one point left. downloading the old matches in the DownloadDialog will still load all matches. i would like to introduce the new FilterSettings to this download function.

**Comment by akasolace** [comment]
@wsbrenk ok I did not know the filters were not applied to download all games...

**Comment by wsbrenk** [comment]
@akasolace i've got a problem testing my  changes since all my hto matches are no longer in hattricks match archive. i deleted them from my test database, did a reload of old matches and was happy that they weren't reloaded when filter was setted accordingly. then i tried to reload them and that didn't work.
Should i commit my changes and anyone of you is able and willing to test that for me, or should i wait until i played a hto match?

**Comment by wsbrenk** [comment]
Filtering of "official matches" works as expected. I will create a pull request.

**Comment by akasolace** [comment]
closed by 2967caa
