### ISSUE TITLE
[eBUG] confusion about date used for comparison for Average TSI, Age, Salary, ..... 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#475]
Follow up of skills and TSI for individual player is done between last data and the one selected in compare HRF table. However for the global data (Average TSI, Age, Salary, ..... ) it is a different behaviour (not sure what is being used for comparison).

We can see in the example below

![0N7Eh0AQI0](https://user-images.githubusercontent.com/1136496/80788974-fa576280-8b8a-11ea-8cd1-6539643a991f.gif)

**Comment by tychobrailleur** [comment]
@akasolace Is it possible this was just after a new download?

**Comment by akasolace** [comment]
> @akasolace Is it possible this was just after a new download?

@tychobrailleur  yes I confirm this is just after download. If I close HO! and then reopen it, it is then display as expected.
