### ISSUE TITLE
[eFEAT] recover selected functionalities of removed Match Analyzer module

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#476]
include selected functionalities of Match Analyzer module into:
  - matches module  (details HatStats def/attack/mid ) 
  - Team analyser (tactics, formation) => actually already there

Anything else?

![image](https://user-images.githubusercontent.com/1136496/80789215-9a14f080-8b8b-11ea-830c-b38673da238a.png)

**Comment by Staut-Stefanita** [comment]
The matches analyzer module is a very useful comparison tool and easy to read. Please add to a future release, it's not available in 3.0 build.

Thank you,
Stefanita

**Comment by Staut-Stefanita** [comment]
Also add coach to best position drop down list in player profile.

**Comment by akasolace** [comment]
let's close this one and instead improve the display of ratings in match module
