### ISSUE TITLE
Message box for updates in MacOs Version

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#48]
1)
Create the visit button to open the url of updates in MacOs Version.
Create the button in the following message box:
![stable](https://user-images.githubusercontent.com/15519907/50060864-eed3e900-0199-11e9-810b-0b82c33f7bc1.png)
2)
The link in message it should go a macos file setup.

**Comment by akasolace** [comment]
@mistermax80 
Eventually I assigned it to myself because as I know how to do it and it will be really quick (I did something similar yesterday)

**Comment by mistermax80** [comment]
@akasolace Ok It's good, after, I will test it

**Comment by mistermax80** [comment]
![schermata 2019-01-08 alle 01 29 50](https://user-images.githubusercontent.com/15519907/50801440-10ca1280-12e5-11e9-8c9a-a0c1917575ce.png)
@akasolace Let me know It prefer show the button (open browser) respect to link.

**Comment by akasolace** [comment]
looks really good like this.
can you make the PR ? I suggest we push to beta just after that

**Comment by mistermax80** [comment]
@akasolace 
Yes I will can in night..... but It's need you test on not mac version (regression), and I cannot do it.
Can you do before merge the code?

**Comment by akasolace** [comment]
yes, I will test and comment the PR before merge
However, I believe the the two lines you circled, will only be visible on mac, this is the intent, correct?
cheers

**Comment by mistermax80** [comment]
also that, but the principal intent is the update message (not mac) work fine, I would like to do an regression test, but I cannot do it.

**Comment by akasolace** [comment]
fixed by 9d8f32227c838790c1e58527062652002a45f791
