### ISSUE TITLE
[eFEAT] "better" display of columns in Squad Tab 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#484]
Maybe we could have important information more easily visible, for example
   - move Leadership and XP  between SP and GK column
   - move the column TSI (and maybe wages and last game #461) to the left (between age and best position ?)
    - column Positioned (should we keep it ? should we change the name?)
    - best position should we move it to the right between the skills and the position rating (i.e. just before GK) ?
    - status is quite wide because it does not resize well in case of injured player. 
    - new last match column (#461) on the left (maybe after best position) 
 - [ ] hide Market value column (who knows, we might reactivated it one day)

 what do you think ?

**Comment by tychobrailleur** [comment]
All good proposals. One thing re. “Positioned” (other than its translation should be fixed), it is currently lined up (pun intended) for the new jersey icon:

![Screenshot 2020-05-02 at 10 02 16](https://user-images.githubusercontent.com/114285/80859976-900ef280-8c5c-11ea-9cf8-30d75e6d94b1.png)

(We should add some tooltip on those jerseys, I don't it's obvious to anyone what the colours mean)

**Comment by akasolace** [comment]
+1 for the tooltip, we might also simply remove the column title ...

**Comment by steffanots** [comment]
take

**Comment by steffanots** [comment]
Proposal:

![image](https://user-images.githubusercontent.com/64475678/91719278-4a741f00-eb95-11ea-890e-51e92e83bba6.png)

**Comment by steffanots** [comment]
> +1 for the tooltip, we might also simply remove the column title ...

Positioned has tooltip. Should I remove title or column :)

**Comment by steffanots** [comment]
Column widths can be adjusted by the users themselves. Example for best position is also problematic.

My proposal is to move TSI before FO and attributes.

**Comment by akasolace** [comment]
> Positioned has tooltip. Should I remove title or column :)

Yes I would remove column title

> My proposal is to move TSI before FO and attributes.

+1

Maybe (if not too difficult) we could merge MC and status, I mean put the MC symbol inside status to save some space, what do you think? Just an idea ...

**Comment by steffanots** [comment]
Status is realtime data and MC static information. So, 👎 

MC near flags?

**Comment by akasolace** [comment]
> MC near flags?

you mean next to the specialty which are also static information?

**Comment by steffanots** [comment]
near nationality or in one column for mother club like 
![image](https://user-images.githubusercontent.com/64475678/91731814-a3e54980-eba7-11ea-8838-0f64de7bd7af.png)
:)

**Comment by steffanots** [comment]
![image](https://user-images.githubusercontent.com/64475678/91731994-e60e8b00-eba7-11ea-958b-49cda8975658.png)

**Comment by akasolace** [comment]
how are you generating those? are they svg ?

In order to save some space, we could either: 
   - replace the nationality and MC column with the icons you are proposing (option 1)
   - put the mc heart next to the specialty and drop the dedicated column  (option 2)
   - put the MC heart in status even if this one is a static info (option 3)

@steffanots @tychobrailleur @wsbrenk @DavidatorusF  any preference ? 

me I would say 2 > 3 > 1   (because option 1 even if beautiful might not be as clear for HO users)

**Comment by tychobrailleur** [comment]
I am not sure I understand what the deal is with MC indicator?  it is not taking that much space, compared to the Status or Last Match fields.  
If it really has to go I'd prefer option 3 but ny preference would be to keep it.

**Comment by tychobrailleur** [comment]
(Especially since that column may be disabled by config, or even reordered by the user)

**Comment by akasolace** [comment]
> If it really has to go I'd prefer option 3 but ny preference would be to keep it.

The idea was not to remove it but see if there was a more appropriate positioning of the column, but indeed I forgot option 4) leave it as it is in a dedicated column:-) .....

**Comment by steffanots** [comment]
> (Especially since that column may be disabled by config, or even reordered by the user)

I am of the opinion that there is no need for one column because a foreigner is not a mother club. If someone sorts by nationality, they can immediately sort by MC.
We are creating additional work for me, but as far as I can see, we are not for that, let two columns remain. Maybe the suggestion that they stand next to each other is enough?

**Comment by akasolace** [comment]
> If someone sorts by nationality, they can immediately sort by MC

not true, you can be a player with same nationality as your club (for salary reason) but he will not have the MC bonus ....

**Comment by steffanots** [comment]
> > If someone sorts by nationality, they can immediately sort by MC
> 
> not true, you can be a player with same nationality as your club (for salary reason) but he will not have the MC bonus ....

of course.
I thought that when sorting by nationality to separate first MC then other from own country

**Comment by steffanots** [comment]
![image](https://user-images.githubusercontent.com/64475678/91759774-84afe180-ebd2-11ea-8d2e-e6825c5268ac.png)

or  uglier i think :)

![image](https://user-images.githubusercontent.com/64475678/91760812-44e9f980-ebd4-11ea-92ca-78c92e422c59.png)

**Comment by akasolace** [comment]
Yes I would stick with top version :-)

**Comment by steffanots** [comment]
![image](https://user-images.githubusercontent.com/64475678/91981438-25181a00-ed29-11ea-8d9a-77112ac3479e.png)

**Comment by steffanots** [comment]
this feature for squad tab, but i think to do in lineup like :
![image](https://user-images.githubusercontent.com/64475678/91981665-788a6800-ed29-11ea-9460-9952a9f43353.png)

**Comment by akasolace** [comment]
nice !
yes it clearly should be the same in lineup !

**Comment by steffanots** [comment]
> the same in lineup !
smaller view. I am of the opinion not to put tsi for lineup...

we have player analysis table!?

**Comment by akasolace** [comment]
should be fixed by #684 => to be close after testing
