### ISSUE TITLE
[eFEAT] include Last rating information into player panel and make it a link to match report 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#485]
Open points:

 - [x] include last match information in player details
 - [ ] remove Rating information
 - [ ] replace ball icon with corresponding match type
 - [ ] update release notes and changelog 

![image](https://user-images.githubusercontent.com/1136496/81501746-351f7000-92da-11ea-9722-14803140376e.png)

IDEA: rename Rating into  "Last rating" which gives also the date of the last game (#461) 
what could be nice is to make this clickable and goes to the corresponding match report 

Last rating    *****  (28.04.2018)
  
what do you think  ?

![image](https://user-images.githubusercontent.com/1136496/80815266-9e61fd80-8bcd-11ea-88d6-ecba68e123f2.png)

**Comment by steffanots** [comment]
> IDEA: rename Rating into "Last rating" which gives also the date of the last game (#461)

I'm not sure this is true
Rating is last training match. You can see here.
![image](https://user-images.githubusercontent.com/64475678/81222106-0fe1e780-8fe4-11ea-92d2-7b9ae9d93a2d.png)

**Comment by akasolace** [comment]
> > IDEA: rename Rating into "Last rating" which gives also the date of the last game (#461)
> 
> I'm not sure this is true
> Rating is last training match. You can see here.

You mean rating is currently last training match so ignoring non offical game wheras Last Match Rating considers those non official game, right ?  If this is correct we  might want to change this and only keep last rating behaviour ..

> ![image](https://user-images.githubusercontent.com/64475678/81222106-0fe1e780-8fe4-11ea-92d2-7b9ae9d93a2d.png)

**Comment by steffanots** [comment]
LastMatch in player.xml is last match in HT. I think it's an irrelevant type of match (As I was testing I also saw a preparation match). I will test duel and preparation match tommorow.

**Comment by tychobrailleur** [comment]
> what could be nice is to make this clickable and goes to the corresponding match report

The match report in Team Analyser, right?

**Comment by steffanots** [comment]
> The match report in Team Analyser, right?
No, tab Matches.

**Comment by akasolace** [comment]
@steffanots I still don't get what are the difference in rating in your example ... 4 grey stars vs 4.5 gold stars...

![image](https://user-images.githubusercontent.com/1136496/81266168-929a8f00-9044-11ea-9488-c5f14ce339d7.png)

**Comment by akasolace** [comment]
> > The match report in Team Analyser, right?
> No, tab Matches.

Yes I was also thinking a link to the match tab as it is a played game ...

**Comment by steffanots** [comment]
>  I still don't get what are the difference in rating
Example from picture:
My player Veselinovic on last match (league) has 1,5 star and 4 star in last training week.  
Gray stars is for league match, gold star for cup/friendly match. 
This code is on german so maybe wsbrenk worked on. :)
![Untitled](https://user-images.githubusercontent.com/64475678/81270585-3edf7400-904b-11ea-8f97-32b3b1f6616c.png)

**Comment by akasolace** [comment]
@steffanots I see. It looks broken to me. What I would suggest is to simplify/clarify it as follow:
   - we get rid of rating
   - we get rid of grey / yellow star
   - in last match we will have:
         - yellow stars from last game (the avg rating not the rating at the end)
         - the clickable icon indicating the match type (league, friendly, cup, whatever ...)
         - the date 

This would summarize all in we want in a single place.  In the column, I guess we could here also introduce 3 clicks sort (date defaults, rating and match type) 

@wsbrenk @tychobrailleur @steffanots  what do you think? ok for you?

**Comment by steffanots** [comment]
Fine be me. 
So, I will add this 
> the clickable icon indicating the match type (league, friendly, cup, whatever ...)

**Comment by akasolace** [comment]
> Fine by me.
I add icon of ball but if you agree I' ll add this

Yes I saw, you put a ball icon nut I think replacing it with the match type give an additional piece of information right away and more clearly than the stars color

> We also have one column in two tabs.

Yes correct one column in squad tab and one in lineup tab. In the code there are example of third click sort if needed.

**Comment by steffanots** [comment]
After I played duel match and pripare match I looked at xml and didn't get those matches as last match. I will try to catch xml after local update at 16:30.

**Comment by akasolace** [comment]
@steffanots I tested it and it seems to work fine ... well done !
Looks all implemented except the icon type instead o the ball. Could you do that last one to close that ticket?  

My previous remark about 3 clicks sorting belong to #461 I will put it there
> This would summarize all in we want in a single place. In the column, I guess we could here also introduce 3 clicks sort (date defaults, rating and match type)

**Comment by akasolace** [comment]
@steffanots I summarized open point on first thread https://github.com/akasolace/HO/issues/485#issue-610799870

I will release first 4.0 artefacts when this ticket is closed

**Comment by akasolace** [comment]
I merged your PR but it does not work for me ....



![image](https://user-images.githubusercontent.com/1136496/81908479-90e34500-95c9-11ea-9983-a3e5c326ec2a.png)

**Comment by akasolace** [comment]
closed by 3e0b4e2a107e3eca7cc6dc6572f1573259e2da77
