### ISSUE TITLE
[eBUG] no matches data after download

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#488]
After downloading with a fresh installed HO! 3.0 r2716 I see only my Team Players but no matches at all in tab "matches" and match analyzer .

All boxes in download procedure (download filter >current matches / >series data / >Team data) are checked before download. I can see the download bar animation but no matches show up afterwards.

Same happens when I try to download a specific match or download box "old matches" with month old date. In "League details" I can push the blue circle buttons to download specific league matches of the season and the download bar animation starts and finishes quickly, but those matches do not show up and the blue circle box is not checked green.
So I guess some match data was downloaded but cannot be processed and shown.

I added my db.zip if this is any help, thx.

**Platform information:**
 - OS: win 10 Pro 64bit 1909 Build 18363.778
 - Version 3.0 r2716
[db_rogon rsf-2020-5-2.zip](https://github.com/akasolace/HO/files/4568539/db_rogon.rsf-2020-5-2.zip)

**Additional context**

**Comment by akasolace** [comment]
this is a known bug (it is mentioned in the announcement on HT  forum) it will be fixed in the second beta.
