### ISSUE TITLE
[eBUG] In "Best Position" I cannot select "Coach" anymore

### ISSUE THREAD

**Issue by amoll1910** [akasolace/HO#489]
**Describe the bug**
In combobox "Best Position", I cannot select "Coach" anymore.

**To Reproduce**
1. Go to tab "Squad"
2. Select a player
3. Click on combobox "Best Position"
4. The entry "Coach" is not listed anymore

**Screenshots**
![NoCoachBestPosition](https://user-images.githubusercontent.com/64730829/80912388-efdcca80-8d3c-11ea-8b9f-909f059da561.jpg)

**Platform information:**
 - HO 3.0 r2716
 - OS: Windows 10
 - Version 1909 18363.778

**Comment by akasolace** [comment]
This was removed by mistake but we have to decide if we want to restore this possibility or not (I do not really see the purpose of this)
The only result of this is I guess to make sure the player is not selectionable by auto lineup (right @amoll1910 ? )   if that is the case I suggest to make it cleaner and to remove "coach" by "can't play" and that would be linked to the checkboxes in lineup tab. There would still be plenty of ways to do the same thing but at least we would remove one.   @wsbrenk  @tychobrailleur  what do you think ?

**Comment by wsbrenk** [comment]
@akasolace i use it, only to classify my players. As far as i know, it is only a display feature.

**Comment by amoll1910** [comment]
"can't play" instead of "coach" is nice and describes it even better for my purposes.
Then the player would not appear at training estimation as well (this was one reason why I marked some players as "coach").
