### ISSUE TITLE
Incoming Cash in section Arena in Statistics TAB

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#49]
Add a new column "Incoming Cash" in section Arena in Statistics TAB:
![schermata 2018-12-17 alle 01 29 38](https://user-images.githubusercontent.com/15519907/50060981-6ce4bf80-019b-11e9-96ac-4257218f2a99.png)

**Comment by mistermax80** [comment]
@akasolace @brokenelevator @DavidatorusF @yaute74 

					case LEAGUE:
					case CUP:
					case QUALIFICATION:
					case TOURNAMENTGROUP:
					case TOURNAMENTPLAYOFF:
					case FRIENDLYCUPRULES:
					case INTFRIENDLYCUPRULES:
					case FRIENDLYNORMAL:
					case INTFRIENDLYNORMAL:
					case MASTERS:
					case NATIONALFRIENDLY:
					case NONE:
					case NATIONALCOMPCUPRULES:
					case INTSPIEL:
					case NATIONALCOMPNORMAL:


I would like ask you if you can indicate the match type, above there is the list of match type, I should categorize the match in relation to (from manual):
League matches: The home team takes all the income.
Cup matches: The home team takes 2/3 of the income and away team gets 1/3.
Friendlies and qualifiers: Income is split evenly

The layout result now is:
![schermata del 2019-02-13 23-03-09](https://user-images.githubusercontent.com/15519907/52747255-a2632900-2fe3-11e9-8e6f-441396089ce3.png)
If you want suggest anythings, I will hear you.

**Comment by DavidatorusF** [comment]
as I know, it's like this

case LEAGUE: home 100% away 0%
case CUP: 2/3% 1/3%
case QUALIFICATION: 50% 50%
case TOURNAMENTGROUP: 0
case TOURNAMENTPLAYOFF: 0
case FRIENDLYCUPRULES: 50% 50% 
case INTFRIENDLYCUPRULES: 50% 50% (away -6000€)
case FRIENDLYNORMAL: 50% 50% 
case INTFRIENDLYNORMAL: 50% 50% (away -6000€)
case MASTERS: 50% 50%
case NATIONALFRIENDLY: 0
case NONE: 0
case NATIONALCOMPCUPRULES: 0
case INTSPIEL: 0
case NATIONALCOMPNORMAL: 0

**Comment by akasolace** [comment]
@mistermax80  should I consider that issue close or are you intending to do some extra ?

**Comment by mistermax80** [comment]
@akasolace You can consider closed.
