### ISSUE TITLE
[eBUG] Matches - null pointer exception

### ISSUE THREAD

**Issue by MrGespant** [akasolace/HO#496]
**Describe the bug**
Whenever I try to get to the tab "Matches" it throws null pointer exception

**To Reproduce**
1. Click on 'Matches'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/10485419/80946111-9bddee80-8ded-11ea-8f51-ffab55db4cf9.png)

**Platform information:**
 - OS: Windows
 - Version (including build number): 2.100

**Comment by akasolace** [comment]
@MrGespant  hello, could you please check your issue still exist in 3.0 BETA 2 (released today).  
We are about to release this new version and we are focusing bug hunting on this upcoming release.

thank you

**Comment by MrGespant** [comment]
Yeah, works it like a charm. Thanks ;-)

**Comment by akasolace** [comment]
@MrGespant ok great I close the issue then
