### ISSUE TITLE
[eBUG][3.0 Beta 2] Subskill recalculation fails to update trained players

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#498]
I deleted the db folder and started anew by importing the .hrf.
Even after "Subskill recalculation", the only subskills I see are those that come from old players regressing. The trained youngsters all only show their last full level gain.

**Screenshots**
![image](https://user-images.githubusercontent.com/1204726/80961452-4ca6b680-8e0b-11ea-9a39-26d9b0c9ce86.png)
The two youngsters that just upped are properly visible. The two following ones should have a visible subskill. The one before is an old guy and subskills are visible for him.

**Platform information:**
 - OS: Windows
 - Version 3.0 r2725

**Comment by akasolace** [comment]
@dominiquelee  thank you for reporting it.
Could you please put a zip of your db in the ticket.

**Comment by akasolace** [comment]
@wsbrenk  again a subskill recalculation issue (like 2 out of 3 bugs reports on HO). I think you are the most knowledgable on this issue. Would you mind having a look?

**Comment by dominiquelee** [comment]
Here you go: [db_singleUser-2020-5-4.zip](https://github.com/akasolace/HO/files/4574395/db_singleUser-2020-5-4.zip)

**Comment by akasolace** [comment]
thank you

**Comment by wsbrenk** [comment]
@akasolace i can try it

**Comment by wsbrenk** [comment]
@dominiquelee your database does not contain any match. Did you try download old matches?

![grafik](https://user-images.githubusercontent.com/11821502/80999851-9a401500-8e45-11ea-846a-341bc7774ab6.png)

**Comment by dominiquelee** [comment]
It"s indeed working way better with the old matches in. I thought they would already be embedded in recent .hrf.
Apologies for having missed this easy fix.

**Comment by wsbrenk** [comment]
@dominiquelee  no problem
