### ISSUE TITLE
[eFEAT] Check Box Yes/No SkillDrops

### ISSUE THREAD

**Issue by Dillotu** [akasolace/HO#501]
Hi Team

It could be possible to set a check box to see or not the SkillDrops in the Training tab >> Prediction?

Thanks

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/81020145-7641fb00-8e68-11ea-8705-2f7355d11f17.png)

Displaying skill drops in trainings prediction can now be turned off.

**Comment by akasolace** [comment]
@wsbrenk wow that was quick, was not expecting a fix before 4.0
well done !
