### ISSUE TITLE
[eBUG] One player can not occupy more than one substitute slot

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#506]
Dillotu wrote in Hattrick forum:

Hi

In Lineup >>> Substitutes we cannot set the same player in two or more positions

**Comment by akasolace** [comment]
@wsbrenk this was also a limitation in 2.X right?  Is it a change in HT or was it broken in HO for super long?  Also I guess this should go in a quick 3.1 release, what do you think?

**Comment by wsbrenk** [comment]
@akasolace I am afraid that I have made this error with issue #299 in february
