### ISSUE TITLE
[BUG] No players in the team

### ISSUE THREAD

**Issue by titico60** [akasolace/HO#509]
**Describe the bug**
It only happens with my second team.

Every time I open HO, my players are missing.

Then, I download the data and they show up.

If I try to download a previous HRF, the players disappear again...

**Screenshots**

![HO](https://user-images.githubusercontent.com/64963460/81291793-6261e900-9062-11ea-846d-578f11ab1a36.jpg)

[db2.zip](https://github.com/akasolace/HO/files/4592753/db2.zip)

**Platform information:**
 - OS: Windows 10
 - Version 3.0 Beta

**Comment by akasolace** [comment]
@titico60 did you had that bug already in 2.X ?

**Comment by titico60** [comment]
No.

With 2.0 all matches were missing, but that problem was solved when I updated to 3.0.

**Comment by wsbrenk** [comment]
db is two weeks old. it does not contain spieler table columns LastName, FirstName and Nickname, but the dbversion is set to 301.

**Comment by wsbrenk** [comment]
to fix this, we could introduce the next patch version with dbversion incremented to 302, where the SpielerTable update is done again.

**Comment by titico60** [comment]
That would be great, tks ;)

**Comment by akasolace** [comment]
> to fix this, we could introduce the next patch version with dbversion incremented to 302, where the SpielerTable update is done again.

@wsbrenk  do you have any idea how he could end up with such a database in the first place?

**Comment by wsbrenk** [comment]
@akasolace i remember we had a time with an exception in dbupdater and I wasn't entirely blameless. maybe the db was created before and such an update did break it.
it would be even worse if there was another error in the update routine. Last time it was the cleanup loop that deleted foreign seasons from the DB. Maybe there is another hole. we should put it to the end of the update routine.

**Comment by wsbrenk** [comment]
after @titico60 updated to this patch, he needs to download again, before he could see his players again. I couldn't test this.

**Comment by akasolace** [comment]
closed by 120247a
