### ISSUE TITLE
[eBUG] manage local vs HT time zone

### ISSUE THREAD

**Issue by fjrn** [akasolace/HO#514]
Even after updating the time difference in preferences and restarting HO, the country's local time is not updated.

![TimeHT](https://user-images.githubusercontent.com/64761641/81593147-63ae5100-9395-11ea-980d-cb0a62b4f602.JPG)

**Comment by akasolace** [comment]
Can you put a screenshot of the match tab from HT ? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fjrn** [comment]
It is in Portuguese, if you need it I can send it in English.

![Match_HT](https://user-images.githubusercontent.com/64761641/81602474-0f11d280-93a3-11ea-8bbf-07b851265e8f.JPG)

**Comment by akasolace** [comment]
@fjrn ok thank you, last thing, could you also join a copy of your db in the ticket.

**Comment by fjrn** [comment]
> 

> @fjrn ok thank you, last thing, could you also join a copy of your db in the ticket.

Sorry, but I don't know what this information is.
Can you guide me, please?

**Comment by akasolace** [comment]
If you can copy your db folder from HO, then zip it and paste it here as an attachment.

**Comment by fjrn** [comment]
Please see if this is the information you want.

[db.zip](https://github.com/akasolace/HO/files/4617821/db.zip)
