### ISSUE TITLE
[BUG] Don't run on linux ubuntu

### ISSUE THREAD

**Issue by adicomdotir** [akasolace/HO#518]
It stays on during loading
Message "prepare to show"

Ubuntu version 18.04
Java version 1.8.0_242
HO version HO-3.0.2.2728

**Comment by DavidatorusF** [comment]
@adicomdotir 

On ubuntu, there's two way, choose the one you want

1. Via the HO.deb / rpm
◦ Install the file via your software library

2. Via the .zip
◦ Extract the downloaded file
◦ Launch the HO.sh
▪ if necessary, right click on HO.sh> property> permissions> check "allow file execution as a program".
▪ click on a folder -> edit (in the menu) -> preferences -> behavior -> executable text file -> ask each time
• https://itsfoss.com/shell-script-opens-text-editor/

**Comment by adicomdotir** [comment]
The first way didn't work for me
But the second way worked
Thanks
