### ISSUE TITLE
[FEATURE] Promotion Status more visible

### ISSUE THREAD

**Issue by murko69** [akasolace/HO#521]
End of season, Hattrick makes this:
![Screenshot](https://user-images.githubusercontent.com/12071221/82050570-a4b9a480-96b8-11ea-942c-58b0edc8e4fb.png)
The color makes it 'pop-out' a bit. Otherwise users tend to miss information.

IMO this area needs to pop-out more than it does today:
![57caadc7ee86724dc28b36c6bec4aa88](https://user-images.githubusercontent.com/12071221/82051260-d4b57780-96b9-11ea-810a-77767ef7c5f2.png)

As I understand it, the web page you built (https://ho-pm-status.anvil.app/) needs HO-users to click on this button, to work for all users in that particular country?
Then actually highlightning this feature a bit extra at the end of the season, since that's the only time it will be visible, would benefit everyone!

**Comment by tychobrailleur** [comment]
I have made a first pass at this, I need to do more testing to make sure things get displayed properly for everything that gets displayed there.

![Screenshot from 2020-07-28 19-12-04](https://user-images.githubusercontent.com/114285/88705459-79672300-d107-11ea-8dc2-fd70f032ee1e.png)
![Screenshot from 2020-07-28 19-11-30](https://user-images.githubusercontent.com/114285/88705461-79ffb980-d107-11ea-9df7-d2ed45e08352.png)

**Comment by akasolace** [comment]
seems good like this ... but a big fat red font would have also do the trick I guess .... as you prefer

**Comment by akasolace** [comment]
closed by #653
