### ISSUE TITLE
[BUG] java.lang.NullPointerException

### ISSUE THREAD

**Issue by homarques** [akasolace/HO#534]
**Describe the bug**
When the application is started by the command java -jar Ho.jar the following exception occurs:
java.lang.NullPointerException

**To Reproduce**
java -jar HO.jar
**Platform information:**
 - OS: macOS Catalina 10.15.4
 - Version: HO_3.0.2.2728.zip
 - Java: java 14.0.1
 -JRE: 8u

[HO-2020-05-22.log](https://github.com/akasolace/HO/files/4670748/HO-2020-05-22.log)

**Comment by tychobrailleur** [comment]
Hi @homarques thanks for the report!  HO does not support java 14 yet, this is something I am currently working on (see #106 targeted for 5.0).  For now java 8 is the way to go!

**Comment by tychobrailleur** [comment]
Closing as HO is in the process of migrating to java 14.
