### ISSUE TITLE
[eBUG] Friendly not appear in TeamAnalyzer

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#537]
**Describe the bug**
When we have two friendly match in the same week (week-end/middle-week) we cannot see the friendly match of the week-end.

_In the source code, to fill the combo we use:_

```
  module.teamAnalyzer.manager.TeamManager.getTeamsMap()
```
 We load the combo with:
``` 
-loadDivisionTeams => teams of the series
-getNextQualificationOpponent => qualification match
-loadTournamentteams => tournament matchs
-getNextCupOpponent => Search cup matchs and friendly matchs order by date desc and keep the first it find (if it's not finish).
```
 So if we have friendly match the week-end and no frienldy schedule for the middle of the week we see the match
 **But if the match is schedule we don't see the week-end match because we keep only the last match sorted by date.**

**Comment by akasolace** [comment]
should be closed by da4f3a4

**Comment by akasolace** [comment]
@yaute74 If I understand correctly we won't be able to test this one before end of the season break, right ?

**Comment by yaute74** [comment]
@akasolace for the bug yes.
But I modify other thing that we can test during the season

**Comment by akasolace** [comment]
yes I just had a look and it seems all good to me. Really nice adjustments. I think we can close the issue but I that is ok with you ....

**Comment by yaute74** [comment]
it's ok for me

**Comment by akasolace** [comment]
closed by da4f3a4

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/84858147-e00a1300-b06a-11ea-8fa7-48650c1fe5d5.png)

neither the mouse over highlighting nor the colored tagging of the next opponent is visible in the new version. was that intended. grafik shows v3 situation.

**Comment by akasolace** [comment]
hi @wsbrenk  colored tagging of the next opponent has been replaced by @yaute74 with match icons and I think this is much clearer, don't you think?

> mouse over highlighting

I don't see what you are referring to. Can you give some details please ?

Cheers

**Comment by wsbrenk** [comment]
@akasolace @yaute74 the colored (red) line showed the next opponent. if that is now done by the order of the lines (first line is next opponent), that is really better then. the other point i wanted to show by the picture above. see the gray (selected) line in the combo box. in the new version this line is as gray as the background and no longer recognizable. since i'm old and short-sighted i miss that a little bit and hitted to the wrong line already;-)

**Comment by yaute74** [comment]
@wsbrenk yes normally the order must correspond to the order of the matches

**Comment by akasolace** [comment]
>  the other point i wanted to show by the picture above. see the gray (selected) line in the combo box. in the new version this line is as gray as the background and no longer recognizable

@wsbrenk  which theme are you using ?  with darklaf themes it is super visible :

![image](https://user-images.githubusercontent.com/1136496/84935691-5d6c6c80-b0d9-11ea-9b48-e3b7cd0a374d.png)

**Comment by wsbrenk** [comment]
@akasolace  settings tells skin is nimbus - do you mean that? i'm not a friend of dark screens, sorry.

**Comment by akasolace** [comment]
yes this is what I meant, might be a display issue with Nimbus.  If it generalized we might want to open a ticket for this.
