### ISSUE TITLE
[FEATURE] clickable match link open ht website

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#547]
@steffanots while you are at it, for consistency the behaviour should be the same as in the special event modules (shift click opens in browser):
     - player details 
     - overview / lineup tab #461

**Comment by steffanots** [comment]
teke

**Comment by akasolace** [comment]
@steffanots  it should be without the quote otherwise it is interpreted as quote block ...

**Comment by steffanots** [comment]
I don't understand where it is necessary to have a link to a hattrick

**Comment by akasolace** [comment]
@steffanots you mean where or why ?

**Comment by steffanots** [comment]
Where and what :)
Player or match?

**Comment by akasolace** [comment]
the idea is to implement shift+click => open HT website

![image](https://user-images.githubusercontent.com/1136496/85059284-b1438800-b1a3-11ea-9049-64b1b01f4f51.png)

**Comment by steffanots** [comment]
I create link on shift+click

**Comment by akasolace** [comment]
@steffanots perfect
