### ISSUE TITLE
make release notes available before update process

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#55]
if user check update and that new update is available, 
on the confirmation windows (do you want to proceed?) a button should exists that offer to display the short version of the release notes  (either by opening an url to the file, or pasting the content in a JPanel ...)

**Comment by yaute74** [comment]
@akasolace ok I will work on it

**Comment by yaute74** [comment]
For info in my last commit I forget to remove a test condition I use for the test.
So ho will always tell you that you have to update it.
I will correct it when I commit this issue.

**Comment by yaute74** [comment]
I commit : 46e01a0d77dbe7bb525843daa9213e6dfe7cbbfc (next time I will add the # in the commit message).
Wait your feedback before close.

**Comment by akasolace** [comment]
Hello,
As just said on discord I am off for 2 weeks. I will not be active during that period. If you are comfortable you can close the issue (don’t forget to update the release notes accordingly) otherwise you ask someone else to test, for example mistermax  on Mac platform.
Thanks again ! Enjoy your holiday (I hope you have some ) and happy Xmas !

**Comment by yaute74** [comment]
done

**Comment by akasolace** [comment]
fixed by 177f5583cd8217b4b4ec94c4c244a3e6f246f2bf

**Comment by akasolace** [comment]
@yaute74 

Sorry for the late check but I am not sure this is working as expected.
Looks to me your function looks for release_notes on local folder instead of the fie on the net.

to makes things simpler, maybe during build test, we can export release_notes to html pages as for the version number.

For example similarly to https://akasolace.github.io/HO/latest.html  I can create 
https://akasolace.github.io/HO/latest_release_notes.html , https://akasolace.github.io/HO/beta_release_notes.html 
https://akasolace.github.io/HO/stable_release_notes.html 
and you will show the correct release note depending of what the user intend to download.

what do you think ?

if that is ok for you:
I can take care of creating the html   and you take care of updating your code.
What do you think ?

**Comment by yaute74** [comment]
Something like this:
![image](https://i.imgur.com/I59XDtA.png)

ps: we can also do the same thing with the macos zip url

**Comment by mistermax80** [comment]
IMHO I prefer much the current layout.
I think generally the standard users don't read the release notes, and by link, it's probably that they don't read.

**Comment by akasolace** [comment]
@yaute74  @mistermax80  it is not what I meant. I also really like the current layout. I just noticed it was not pointing to the correct release notes. When I tried it was looking for local release note (i.e of installed version) instead of online release notes (i.e for version about to be install).

I hope it is clearer now.

**Comment by brokenelevator** [comment]
@yaute74  Me three, with the current layout.
The github.io page is a good idea. As @akasolace noticed it should be release notes of the 'to be downloaded' version, not the one already installed.

**Comment by akasolace** [comment]
seems we all agree on that one.

**Comment by akasolace** [comment]
d193859ea26330329f80e123e4de31f0a28fb214 fixes step 1,   
release notes are now uploaded online during build phase in the following location:

https://akasolace.github.io/HO/release_notes(dev).html
https://akasolace.github.io/HO/release_notes(beta).html
https://akasolace.github.io/HO/release_notes(stable).html

**Comment by yaute74** [comment]
> @yaute74 @mistermax80 it is not what I meant. I also really like the current layout. I just noticed it was not pointing to the correct release notes. When I tried it was looking for local release note (i.e of installed version) instead of online release notes (i.e for version about to be install).
> 
> I hope it is clearer now.

I was clear, I just propose other option because:
- if you want to create an html structured page or a markdown page etc... (not just a text page) it's better to have a link.
- some users are not interested by release notes so it's a shame to download a page for nothing

**Comment by akasolace** [comment]
Personally I am open on this one. It is true that it is standard for software to only display a link to release notes.   (To follow std, the check update, should be within help menu instead of file)

@brokenelevator @mistermax80 @yaute74 @DavidatorusF  
so it is really up to you, I would be fine with whatever you decide.

**Comment by yaute74** [comment]
@akasolace I'm the only one who prefers the link, I'll keep the current layout ;)

**Comment by akasolace** [comment]
@yaute74  let's others have a second look maybe.

By curiosity I check few software I got. They have all the same design:
   - Check for updates in Help menu   (I just created a ticket for this)
   - Release not are shown as a link

So you defintly had a valid point :-)

**Comment by mistermax80** [comment]
I prefer to see it in the same screen without link.
Because I am one who read the release notes.
But I agree with @yaute74, there is not need to download data if the user is not interested.
I think if we want incite the users to read it or not, Inthe first case the release notes will be in the screen, else link.
For me it the same.

**Comment by brokenelevator** [comment]
@akasolace @mistermax80 @yaute74 I wonder who we should cater to more. New? Those would expect it in Help. Old? It has always been in file and I see no one complaining about that. So I guess old would expect it in file. For me it makes no real difference where it will land. I would not touch that, but that is more of a 'not broken, don't fix it' or stay with legacy if there is no good reason to change it.

As for release notes. I stand by what I said. I have used software that has shown it directly and I like it. For those uninterested we can do checkbox to hide it or a button (or other control like a radio) to fetch it. They can also just ignore it, who cares about those few KiB?
So I would leave it, and set up an radio to toggle 'show release notes'.

**Comment by yaute74** [comment]
@akasolace @mistermax80 @yaute74 
Soif I resume action i can do:
- check update as describe in #73 
- move 'check update' in help menu #82
- add link to the 'release note' into help menu (for user who want to read the release note after installation). In this cas open release note into browser.
- for message box I use a JTextPane. It work with our release note page but I do some tests with other html pages and it don't work when the page is more complicated. So if our page will always be as simple as ever as its now we can add an URL 'see release note' and if user click on it, we open the release note directly inside the Message Box.

**Comment by mistermax80** [comment]
@yaute ok!

**Comment by akasolace** [comment]
@yaute74  sounds perfect to me    @brokenelevator  also good with you?

1.436 is getting close

**Comment by yaute74** [comment]
Modification done
Finally I left the release note panel visible because the hide/show mode doesn't make it very good.

**Comment by akasolace** [comment]
ok cool.
I'll test this tonight.
Thank you

**Comment by akasolace** [comment]
@yaute74    

I was exptecting the release note link in the help menu to point to current version ( the file stored locally) whereas is users do check update he got the release notes for the version about to be installed.
Is current implementation what you had in mind or is it a mistake?
@mistermax80 @brokenelevator  @DavidatorusF   what do you think ?

Thank you for the feedback

**Comment by yaute74** [comment]
> I was exptecting the release note link in the help menu to point to current version ( the file stored locally) whereas is users do check update he got the release notes for the version about to be installed.
> Is current implementation what you had in mind or is it a mistake?

So you speak about the issue #82. Yes it's what I have in mind because I understood that you remove the local release note file and create html page to replace it.
But if it's not the case we can open the file localy ;)

**Comment by brokenelevator** [comment]
@akasolace i haven't tested it myself yet. Putting release notes back is one option. Do it have to be release notes though? Changing the help menu link for changelog would be the other.

**Comment by akasolace** [comment]
@brokenelevator @yaute74
In order to close the PR I suggest based on what you said that we go for a minimal change. We simply put the link to local changelog and we rename it accordingly. We leave as it is the release note before update.

**Comment by brokenelevator** [comment]
@akasolace It shall be so then :)

**Comment by yaute74** [comment]
@akasolace ok

**Comment by akasolace** [comment]
Changelog is here 
It is a text file in src/main/ressources but
we will have to change it to html for the link.
Maybe you can create the html version and today or tomorrow I will delete the text file and adopt the build file accordingly. Hence, you will not have to wait for me.
