### ISSUE TITLE
[BUG] HO not opening - database crashed?

### ISSUE THREAD

**Issue by Dergelbe** [akasolace/HO#551]
**Describe the bug**
capitaineFro requested to open an issue for this thing here:
 
Database crashes on opening HO. You can find the error message attached as screenshot.
[error](https://www.bilder-upload.eu/bild-ae4851-1590646753.jpg.html)

When trying to open HO the 2nd time after this, the opening procedure stops at "inizialize database"

[database](https://www.file-upload.net/download-14107131/db_singleUser-2020-5-22.zip.html)

**Platform information:**
 - OS: Windows

**Comment by akasolace** [comment]
@Dergelbe  Thank you or opening a ticket and sharing your database. However as explained in the forum what would help is a version of your db which is not corrupted ...  do you have any copy prior to this one ?

![image](https://user-images.githubusercontent.com/1136496/83915542-c0721100-a773-11ea-9663-675399be941b.png)

**Comment by Dergelbe** [comment]
no, i don´t have a copy before that. i would have the old .hrf but i don´t know if there are helpful

**Comment by akasolace** [comment]
you have all the hrfs files ?

**Comment by akasolace** [comment]
the hrfs  https://workupload.com/file/hxxygzz9QX6

**Comment by akasolace** [comment]
@Dergelbe importing the hrfs files seems to work ... have you tried yourself ?
Just delete the db folder. Launch HO! then select files importing hrs files, you go to your folders (ctr+a to select them all)  ... click ok and then apply to all ... 
The only thing that will be missing are the games but you can download them from file download -> old   ...

@wsbrenk can you remind me/us the difference between old matches and old serie data ?


![image](https://user-images.githubusercontent.com/1136496/83966329-e0135180-a8b9-11ea-8163-9ac0826c3fee.png)


![image](https://user-images.githubusercontent.com/1136496/83966340-f7523f00-a8b9-11ea-9524-492124bbfcd8.png)

**Comment by wsbrenk** [comment]
@akasolace file=leaguefixtures is the chpp file read by old series data 
file=matchesarchiv is read if old matches is selected.

**Comment by akasolace** [comment]
ok thank you !

**Comment by akasolace** [comment]
I will close this issue which is specific and will be treated in a more general one in #558
