### ISSUE TITLE
[FEATURE] create database repair tool

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#558]
Plenty of users have database in more or less corruption state. One of the symptom to recognize corrupted database is the constant presence of .backup file and non updated .data

It appears the corruption mostly come from the introduction of new non null field in the database.
Previous rows had no entries and the dbupdater is not tackling this correctly. The dbupdater should have introduce default values while upgrading the database.
The creation of indices on those wrong entries is corrupting the database:
 
**Describe the solution you'd like**
In the future we should treat correctly those case directly in DBUpdater but knowing it will happen again and there are already plenty of corrupted database out there we need a proper tool to fix corrupted db. The tool would:
     - create data dump of the database as SQL insert entries 
     - create a fresh db
     - populate the db with SQL insert made at step 1

**Comment by wsbrenk** [comment]
@akasolace is the dbupdater the only reason of corrupted database. If so i would suggest to introduce save db update methods which do those checks you propose.

in the past i very often observe that my database get corrupted when HO terminates in an unforeseen way - programm errors or maybe power failure. do you see any chance to attack those corruptions too?

**Comment by tychobrailleur** [comment]
> **Describe the solution you'd like**
> In the future we should treat correctly those case directly in DBUpdater but knowing it will happen again and there are already plenty of corrupted database out there we need a proper tool to fix corrupted db. The tool would:
> - create data dump of the database as SQL insert entries
> - create a fresh db
> - populate the db with SQL insert made at step 1

@akasolace Do you see this as a standalone tool, or a tool that's part of HO?  If the former, I'll create a new project under the `ho-dev` org.


> in the past i very often observe that my database get corrupted when HO terminates in an unforeseen way - programm errors or maybe power failure. do you see any chance to attack those corruptions too?

It's difficult; I think – it's the nature of hsqldb.  It only writes the data file upon shutdown.  We could possibly increase the frequency of backups but this would not get rid of the issue entirely (cf. http://www.hsqldb.org/doc/2.0/guide/dbfiles-app.html)

**Comment by wsbrenk** [comment]
@tychobrailleur concerning backup we discussed earlier that it could be a good idea to hold some backup for a longer time ( maybe one for a week and another one for a season). by this way we could handle errors which were undetected for the last 3 session (which could be a real short period).

**Comment by akasolace** [comment]
Yes as mentioned already I also think we will never avoid neither recover database corrupted by abrupt shutdown (like power outage). The solution should be to give more control to the user for database backup.

> @akasolace Do you see this as a standalone tool, or a tool that's part of HO? If the former, I'll create a new project under the ho-dev org.

I think it will be part of HO as I would like to avoid duplicated code for database logic. However  I am not 100% sure of what the final deliverable should do. What I did so far is a dump of the data as a list of sql inserts but I realized afterward that might not be ideal for archiving because it is link to db structure as time of data dump. I think what the tool should do is a set of functionalities

1) DB backup
     - initialize new db
     - populate new db with **curated** data from current db
     - save new db

2) DB restore
    - load new db from HO interface (the current manual process is not ideal for some users)

3) DB cleanup
    - would do 1) and 2)
     - would offer the existing option to reduce db size:
              - delete dome games
              - reduce number of hrfs
              - ....

**Comment by tychobrailleur** [comment]
I have an initial version of such tool there:
https://github.com/tychobrailleur/hodb-repair

For now transitions are [limited](https://github.com/tychobrailleur/hodb-repair/blob/master/src/main/java/io/github/hodev/dbrepair/App.java#L126), I'll expand as I get test databases to verify.

**Comment by akasolace** [comment]
ok great. Do you see it as a standalone tool or to be incorporated in HO somehow?

**Comment by tychobrailleur** [comment]
It could potentially be both: for now it is standalone, but it could be added as a dependency to the app too.
When you get a chance, would you mind sharing your “broken” database with me so I can test the tool on it?  Thanks a mil.

**Comment by akasolace** [comment]
@tychobrailleur here it is:   https://send.firefox.com/download/61b6c78d6dc83466/#A3YLM4NJgF9awWaay2ylzg

**Comment by tychobrailleur** [comment]
Thanks a lot, I came across an issue with my code where Windows line end were not handled, so it is now fixed.
This seems to work now: I ran the tool, and got a db that I could use with HO 4.0

So next step is to try to integrate the tool with HO.  The export functionality also works, it exports the DB as SQL inserts in a zip, but will not solve cross-version issues, we may need to export to a neutral format first.

**Comment by akasolace** [comment]
@tychobrailleur  ok cool !  There is a user on the forum who apparently has major db issue following 3.0 upgrade. I asked him to open a ticket on GH with a copw of its db, it will ba another good test for your new tool

**Comment by akasolace** [comment]
@tychobrailleur have you tried your tool with db from #597 ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur have you tried your tool with db from #597 ?

I don't believe I have — and it appears that Firefox Send is in maintenance as we speak.

**Comment by akasolace** [comment]
@tychobrailleur  The tool exists so I close this issue. If at some point we decide to integrate the tool inside HO we would open a new ticket for this.
