### ISSUE TITLE
[FEATURE] Game results should be given with information about extra time or penalty shoot out

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#561]
Game results of cup rule games in game panel (and maybe teamanalyzer) should be include information about extra time or penalty shoot out.

In german it would be 
2:1 n.V. (nach Verlängerung), means after extra time
or
5:3 n.E. (nach Elfmeterschießen), means after penalty shoot out

today i had to search very long for a extra time game;-)

**Comment by akasolace** [comment]
hi @wsbrenk can you precise what you have in mind? At the moment these information are in the game report, where else do you want them ?

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/84177644-6b8c0e80-aa83-11ea-8ef7-12bfed9a7623.png)

in the selected line of list of matches should the result be changed to "4:5 n. E."

**Comment by akasolace** [comment]
ok I see, what does it look like on the tabs highlight and match summary ?

**Comment by wsbrenk** [comment]
could be everywhere the same - teamanalyzer too

**Comment by akasolace** [comment]
ok .... it is just that I thought I did it in the highlights tab but I might be wrong

**Comment by wsbrenk** [comment]
it is quite difficult to get this information. one way could be the special events, already stored in HO database. another option could be to add match details file information about "FinishedDate" and or "AddedMinutes".
next i will investigate how the special events were downloaded and check if it is a good idea to copy infos about extra time to the MAtCHKURZINFO or MATCHDETAILS table(s).

**Comment by wsbrenk** [comment]
Again this is a tricky thing. Whereas loading the information from the highlights was quite easy the display part is pretty violent. There are at least 4 different classes that are holding the number of goals and the way to MatchKurzinfo or MatchDetails is quite far.

The panel that uses the MathDetails is the player analysis panel:

![grafik](https://user-images.githubusercontent.com/11821502/84805194-2c6e3800-b004-11ea-9978-e19365a917d6.png)

**Comment by akasolace** [comment]
@wsbrenk maybe we can get this from CHPP directly. If not and e need to parse it, lets do it once and stored in appropriate place. Again, as said above, have you check the match summary? I think the info is displayed in there, no ?  I will have a look tomorrow ...

**Comment by wsbrenk** [comment]
@akasolace As a first attempt, I took over the information in the MatchDetails and thus achieved the display shown. I think I would better put them into the MatchKurzInfo and use them in the desired displays.

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/84946931-b5ab6a80-b0e9-11ea-89ca-c6236665587d.png)

@akasolace @tychobrailleur what do you think about that? Are the abbreviations a.e. and a.p. correct for after extension and after penalties?

**Comment by akasolace** [comment]
@wsbrenk usually the regular score is indicated and next to it extra information, for example:
    -   0-0 
    -   0-2  (extra-time)
    -   0-0  (2-4 on penalites)

**Comment by wsbrenk** [comment]
@akasolace here is my current solution:
![grafik](https://user-images.githubusercontent.com/11821502/85221699-44eca280-b3b6-11ea-8525-e04a94246a49.png)

discussion please:
- isn't there an abbreviation of extra-time and on penalties? Long version seems to long for me.
- currently i use the duration of the match (last minute from match events) to decide if it is extra-time (duration > 110 minutes) or penalties (duration > 120 minutes). some years ago a golden goal period exists. those matches have duration between 90 and 110 minutes and will not give an extra-time signature. 4 candidates are in my database history and i could live with that.

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/85225497-111f7600-b3d2-11ea-8427-9adfbb713bd7.png)

@tychobrailleur i introduced your suggestion to use language sensitive result separators. in your example, you used spaces around the dash. i got it working with the trailing space but the leading one was discarded from the property. Do you have a solution for that?

next i will try to find out, how to left align the cells

**Comment by wsbrenk** [comment]
now i learned how to introduce leading spaces in java properties (\ ). 
@akasolace is that a problem for the translation workflow?

**Comment by akasolace** [comment]
> @akasolace is that a problem for the translation workflow?

@wsbrenk  I guess it might be,  can't we handle the space thing in Java instead of property file ? We will have more control. I mean we can't be sure translators will do it correctly ...

**Comment by wsbrenk** [comment]
> I guess it might be, can't we handle the space thing in Java instead of property file ? We will have more control. I mean we can't be sure translators will do it correctly ...

@akasolace i think this would be the better solution. it has only one handicap, if there are languages that don't want spaces around there separator.

**Comment by akasolace** [comment]
> @akasolace i think this would be the better solution. it has only one handicap, if there are languages that don't want spaces around there separator.

even miscrosoft office does not allow such customization :-)  I think we can go ahead :-)

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/85953675-7b0bc280-b972-11ea-9582-f7f336634921.png)

the topic is really a challenge. Since the update of the highlights is very time-consuming, it happens bit by bit. In the graphic above you can see the result display as requested by @akosolace and below a preliminary display (2-1 a.e.) that will be corrected by future downloads.

there is still some room for improvement. 
- DbUpdater takes a long time to update the tables match details and match highlights. I want to try to add several columns at the same time to accelerate this
- i would be glad if you are fine with the result's format, otherwise we could implement some customization configs

there are now several result methods in Matchdetails class, to output the results in different formats. they could be used in other contexts.

**Comment by wsbrenk** [comment]
It looks like hsqldb can only add columns one by one. that is really bad, since on my database the update took many minutes.
