### ISSUE TITLE
[FEATURE] Clicking on a match in Player Analysis should bring to the Match report 

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#569]
**Is your feature request related to a problem? Please describe.**

No, it is a UX enhancement.

**Describe the solution you'd like**
When clicking on a match in the Matches tab of the Player Overview module, this should bring to the Match report in the Matches module:

![Screenshot 2020-06-12 at 08 28 52](https://user-images.githubusercontent.com/114285/84477007-deb1a280-ac86-11ea-9d88-f65abd1ca735.png)
Clicking (or double-clicking if preferred) the first row should bring to:

![Screenshot 2020-06-12 at 08 30 41](https://user-images.githubusercontent.com/114285/84477137-128cc800-ac87-11ea-8f57-637e9e2b6df9.png)

The same pattern used in other places could be used here, Shift-click could bring directly to the Hattrick match report.

**Additional context**

N/A

**Comment by akasolace** [comment]
and for consistency  shift+click open HT website  (this is linked to #547)

**Comment by tychobrailleur** [comment]
> and for consistency shift+click open HT website (this is linked to #547)

Thanks, I have corrected from ctrl-click to shift-click.

**Comment by steffanots** [comment]
take

**Comment by akasolace** [comment]
@steffanots  it should be without the quote otherwise it is interpreted as quote block ...

**Comment by steffanots** [comment]
I try take, 'take', "take"

**Comment by steffanots** [comment]
I finish link to match tab but I can find any code with link to ht website!
do we have any code?

**Comment by akasolace** [comment]
@steffanots look here  https://github.com/akasolace/HO/blob/d4abaa7df667a1e3908c3f8c68b4b528257d6d1d/src/main/java/module/specialEvents/Match.java#L151
