### ISSUE TITLE
[BUG] New League Prediction (error in league structure)

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#581]
Warning about this... Spain V.238 and V.239 have not consecutive IDs... It jumps from 5751 to 5754
And new leagues...

Saint Vincent and the Grenadines | 157 | 258519 | 258520 | 258524
Belize | 158 | 258540 | 258541 | 258545
Madagascar | 159 | 258561 | 258562 | 258566
Botswana | 160 | 258582 | 258583 | 258587

**Comment by tychobrailleur** [comment]
AFAICT this is a server-side change, is the code available somewhere?

**Comment by akasolace** [comment]
> AFAICT this is a server-side change,

is it ? my bad sorry

> is the code available somewhere?

I need to import the repo into github .... on my todo list  :-)

**Comment by akasolace** [comment]
@tychobrailleur actually this one is here:

https://github.com/akasolace/HO/blob/master/utils/pythonScripts/UpdateLeagueStatusDetailsTable.py
