### ISSUE TITLE
[BUG]  Select File->Preference throws a NPE

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#586]
**Describe the bug**
Select File->Preference throws a NPE

**To Reproduce**
Select File->Preference

**Screenshots**

![image](https://user-images.githubusercontent.com/1136496/84986292-a0acf680-b13e-11ea-9f8a-b32ce5f825d1.png)

**Platform information:**
 - OS: Windows
 - Version: 4.0 r2946

**Comment by tychobrailleur** [comment]
I have a fix for this, but the colours set in the preferences are not persisted.

We have two options:
- Either we remove entirely the colour selection panel in the preference panel, and let themes handle those colours,
- Or persist colours in userconfiguration table.

Any preference @akasolace ?

**Comment by akasolace** [comment]
@tychobrailleur what do you think ?   Personnaly I would rather remove colours in userconfiguration table...

**Comment by akasolace** [comment]
@tychobrailleur 
more generally, I don't really like those colours, maybe we want to remove that ....
First of all it is absolutly no clear what they mean and also they are redundant with Status column.  Only missing icons is tranfert listed but we can simply add this one and get rid of the colours, what do you think ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur what do you think ? Personnaly I would rather remove colours in userconfiguration table...

Sorry, missed that one: I was favouring not making those colours configurable, and add them to theme, but I wouldn't miss them.

**Comment by tychobrailleur** [comment]
Can this be closed @akasolace , now that the status colours have been removed?
