### ISSUE TITLE
[BUG] missing several players in "prediction" tab of trainings

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#587]
**Describe the bug**
I´m missing several players in the "prediction" tab of trainings. 
In the the overview of the "training" tab there are all players available.
I set the "Futur Trainings" for 32 weeks. (I also tried 48 weeks without success)
I´m using HO since several years in different versions. So I had a lot of .hrf files imported.
I found out that the amount of players in the "prediction" tab depends on the flags at the bottom of the "training" tab in the options. By enabling/disabling of each flag the amount varies. But no combination leads to desired result.

**To Reproduce**
1. Go to 'Training' module
2. go to 'Training" tab
3. count players
4. go to 'prediction" tab
5. count players
6. go to "Main" menu
7. click "options"
8. restart HO
9. go to 'Training" tab
10. change one of flags at the bottom of the page
11. repeat step 1 till 5

You can check all combinations concerning these flags. 

I got asked to add my database
[db.zip](https://github.com/akasolace/HO/files/4797721/db.zip)

**Screenshots**
![options](https://user-images.githubusercontent.com/67096604/85005106-a4e60d80-b158-11ea-8df4-bf7d169ee675.JPG)

![Training_overview](https://user-images.githubusercontent.com/67096604/85005108-a57ea400-b158-11ea-9da5-4c1a2d55691d.JPG)

![Training_prediction](https://user-images.githubusercontent.com/67096604/85005111-a6173a80-b158-11ea-81b4-8c3e6e9ab35d.JPG)

**Platform information:**
 - OS: Windows 10 home
 - Version 1909 (Build 18363.904)

**Comment by akasolace** [comment]
@wsbrenk  maybe we want to rethink which players are displayed and/or highlited in the prediction tab.  What do you think ?

**Comment by wsbrenk** [comment]
@akasolace we can do so. the current version should list all players that will get skill ups during the period that is analyzed, if configured as shown by @johari75 . 
if skill downs should be displayed too, the list could be a little longer.
Another chance to include further players to the forecast list, will be to change their position in the player overview list, so that they are no longer handled to get no trainings effect.
If they should get skill ups on the selected position during the analyse period and they are not displayed in the forecast list, it is a bug, that we should fix.

**Comment by wsbrenk** [comment]
Currently it is intended that player with no skillups or -downs are NOT listed in the forecast
by  configuration the skilldown display can be suppressed - only players with skillups are listed
green means the player receives training on primary position (e. g. inner midfield when playmaking is selected)
yellow means the player receives training on secondary position ( e. g. winger when playmaking is selected)
white is for osmose training (i think)

we could add light red marking for players with only skill downs
we could add a configuration option to display the players without changes too

I'm rather undecided on that

**Comment by akasolace** [comment]
@wsbrenk  what you described above make sense and I would like it but this is not what I observe

You can see that in my case the player highlited are selected by their best position instead of the training they receive.   Is it not the case for you ?


![image](https://user-images.githubusercontent.com/1136496/85202404-8160c580-b306-11ea-9599-522d1d5837bf.png)

**Comment by wsbrenk** [comment]
@akasolace I am surprised that your wingers are not marked in yellow. i guess you are training playmaking. inner midfielder will get full trainings-> green (HOColorName.PLAYER_SKILL_SPECIAL_BG). the training speed of winger should give yellow (PLAYER_SKILL_BG). see module\training\ui\TrainingRecapTable.java line 78.

**Comment by wsbrenk** [comment]
@akasolace i found the error
it should look like this:
![grafik](https://user-images.githubusercontent.com/11821502/85206179-80d52880-b320-11ea-85f4-71e97900a084.png)

**Comment by akasolace** [comment]
@wsbrenk in your exemple it seems color is still based on "best position", no?
It should be based on training received .... or am I missing something?

**Comment by wsbrenk** [comment]
@akasolace you are right. color is made by the maximum trainingspeed the player will get during the analyzed future. and this is directly depending from best position selection.

in a former version the average speed was used to select the color. there was a user and i had the same observation, that when you change the trainings in your future plan very often, you would only get uncolored lines.

what I would really like would be a way to be able to set each player's training position on a weekly basis.

**Comment by akasolace** [comment]
I think selection should be made from last trained position no?

**Comment by wsbrenk** [comment]
@akasolace No, not the former training position is used, but the future planed trainings. here you get the ticket, that introduced the last change on this: #296

**Comment by akasolace** [comment]
Using future plan training make sense. The issue is the player selection:
using best position in not good. I think we can:
  - use last position ?
  - let HO user decide? How ?

How is it done in HT ?

**Comment by wsbrenk** [comment]
> How is it done in HT ?

there is a team view that gives duration to the next skill up for each player getting full training
![grafik](https://user-images.githubusercontent.com/11821502/85221912-f4764480-b3b7-11ea-98b3-2d5dc5c1ebaa.png)

or a player view showing all skillups depending on selectable training an position (full training, secondary trainining, osmose training)

there is no overview showing all weeks and all players like it is in HO.

**Comment by akasolace** [comment]
@wsbrenk   I think we need to decide what we want to do. HT! offers 3 differents functionalities:
 - HT training planner
 - HT team training estimation 
 - HT player training estimation

At the moment we have a mix of those functionalities and it is quite confusing. I think we need to decide, either we implement one of this functionality or all of them but I don't think we can have it all in a single table.
I think it would be a safe bet to replicate HT functionalities .....

**Comment by wsbrenk** [comment]
@akasolace you are right. but i'm not a friend of hts training planer. so bad, that i forgot it already;-)

the overview given by hos forecast table is great i think. the only thing that i'm missing is the selection of individual training positions for each trainee (primary, secondary would be enough).

**Comment by akasolace** [comment]
@wsbrenk just to make sure I understand correctly. We keep as it is but we  let user select which player recevies full training and which one receive partial training and we remove osmose training.  If this is waht you have in mind it sounds good to me. It will fixes a lot of complaints of users not happy with the player selection in that tab

**Comment by wsbrenk** [comment]
@akasolace, @tychobrailleur:  exactly. what do you think of a combo box in each cell that allows you to select the training position (primary, secondary) for either the selected week or all further weeks

**Comment by akasolace** [comment]
@wsbrenk you mean one combox next to each player to select full or partial training ? It is also how I see it personnaly

**Comment by wsbrenk** [comment]
@akasolace no i'm thinking of one combo box in each cell of the table. the user is able to select the position of each week and player individually if he wants. 

further could some constraints be considered, that tooks into account the maximum number of trainees allowed on each training positions per week

**Comment by wsbrenk** [comment]
new database table futurePlayerTraining is ready. FutureTrainingsManager calculation is changed. Since there is no entry in the new table, the results of the training forecast are unchanged.

Now i need a good idea how to implement the editing of the individual future training plans. my very first idea was to add combo boxes to the cells of the training forecast overview table. can someone tell me if that's a stupid idea?

**Comment by akasolace** [comment]
@wsbrenk I am not sure I got it right,  
  1. it would be a combobox next to each player ?
 
I imagine either we can select multiple training (trining plans) or only one (simple training forecast).  For the full training plan, I imagine we would need possibility to do things like:
   2.  PM Full Training for 8 weeks and then Pass for the remaing of the period

For the forecast I imagine we would only need half of the entries you mentioned, no ?

**Comment by wsbrenk** [comment]
@akasolace your suggestion to select the training weeks is the most comfortable solution i think. if someone could help me to implement it would be really great. to make sure we mean the same thing, here's a picture:
![trainingsplan](https://user-images.githubusercontent.com/11821502/87220055-0583f700-c361-11ea-880d-e3331e7d7647.png)

what we need is some kind of selection on the forecast table cells and a popup menu to finish the user training selection.

**Comment by wsbrenk** [comment]
a little bit is working already:

![grafik](https://user-images.githubusercontent.com/11821502/87253620-1164db80-c47d-11ea-85e4-a8b0423a8e93.png)

**Comment by akasolace** [comment]
@wsbrenk  on your screenshot, I do not see where you select the training plan for individual players ....

> line 3 shows the other goolkeeper trainee. he's getting automatic training because of his best position. this is not tagged by light green cells.

I thought the plan was not to rely on best position anymore but on user selection of full training / partial training / ......  is it not how it works ?

> partial training could be planned for goolkeeper, which is not possible in the real hattrick virtuality

We will have to restrict this,  HO will need to be make aware this is not possible ....

>  some kind of aggregation, sums of full, partial training positions and warnings if those exceeds the real limits.

agree this could be a nice addition

> the feel of the selection and popup menu is not yet optimal. the ui experts have to help me, this is new territory for me.

I do not see how it looks on the screenshot ....

**Comment by wsbrenk** [comment]
> I thought the plan was not to rely on best position anymore but on user selection of full training / partial training / ...... is it not how it works ?

for the lazy users i want to keep this function as it is. so when no individual training is planned, the calculation still uses the best position or the user's position settings.

**Comment by akasolace** [comment]
> for the lazy users i want to keep this function as it is. so when no individual training is planned, the calculation still uses the best position

@wsbrenk  I think this leads to incorrect behaviour most of the time,  I would suggest for lazzy user to rely on the players who received last training, what do you think ?

**Comment by wsbrenk** [comment]
>  I think this leads to incorrect behaviour most of the time, I would suggest for lazzy user to rely on the players who received last training, what do you think ?

Not sure, i understand you correctly. Currently I'm used to set the trainings priority by the best position of the players. i can set them in the player overview. I would not like that a player will loose this setting when he is injured for a week or because of another reason, he could not play on a training position.

i set the number of future weeks to the maximum (80 weeks), to plan the whole homegrown training cycle. with this new feature i could improve the settings for those player who should train more than one skill during these 80 weeks.

**Comment by akasolace** [comment]
>  I would not like that a player will loose this setting when he is injured for a week or because of another reason, he could not play on a training position.

I take the point ...

**Comment by tigro7** [comment]
Hi! I'm here from the HO forum.
Glad to know that i'm not the only one who had this idea :)
I would really like to have the possibility to choose which player of the team will get the training in a selected week, so:
you can choose it in the table, or you can choose it when you set the future trainings...

**Comment by wsbrenk** [comment]
> I do not see how it looks on the screenshot ....

![grafik](https://user-images.githubusercontent.com/11821502/87813274-dd652e00-c861-11ea-814b-74d18c77ffa1.png)

individual training plan is edited by selecting weeks with left mouse and popmenu which is created by right mouse click. i don't know if users are able to find this feature. 

now training prios that are not possible on selected training type are disabled. see picture, where i train goalkeeper and partial and osmosis training are disabled.

what i want to test next is to select weeks with different types of training
