### ISSUE TITLE
[BUG] “DB is too old” error after restarting in dev

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#590]
**Describe the bug**

I have a consistent issue in /development/ when copying a database.

The first execution is ok:

```
sql> select * from userconfiguration where config_key = 'DBVersion';
CONFIG_KEY  CONFIG_VALUE
----------  ------------
DBVersion   399
```

When stopping and restarting the app, I get the following issue:

![Screenshot 2020-06-18 at 18 22 24](https://user-images.githubusercontent.com/114285/85052451-d8dd2500-b190-11ea-81f6-92d8c6719a49.png)

Looking into the db, the `DBVersion` is gone:

```
sql> select * from userconfiguration where config_key = 'DBVersion';
CONFIG_KEY  CONFIG_VALUE
----------  ------------

Fetched 0 rows.
```

hsqldb `database.log` is present:

```
/*C2*/SET SCHEMA PUBLIC
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='DBVersion'
INSERT INTO USERCONFIGURATION VALUES('DBVersion','399')
COMMIT
ALTER TABLE MATCHESKURZINFO ALTER COLUMN isDerby SET DATA TYPE BOOLEAN
ALTER TABLE MATCHESKURZINFO ALTER COLUMN isNeutral SET DATA TYPE BOOLEAN
CREATE INDEX IF NOT EXISTS matchdetails_heimid_idx ON MATCHDETAILS (HEIMID)
CREATE INDEX IF NOT EXISTS matchdetails_gastid_idx ON MATCHDETAILS (GASTID)
CREATE INDEX IF NOT EXISTS matchkurzinfo_heimid_idx ON MATCHESKURZINFO (HEIMID)
CREATE INDEX IF NOT EXISTS matchkurzinfo_gastid_idx ON MATCHESKURZINFO (GASTID)
CREATE INDEX IF NOT EXISTS matchhighlights_teamid_idx ON MATCHHIGHLIGHTS (TEAMID)
CREATE INDEX IF NOT EXISTS matchhighlights_eventid_idx ON MATCHHIGHLIGHTS (MATCH_EVENT_ID)
ALTER TABLE VEREIN ADD COLUMN GlobalRanking INTEGER
ALTER TABLE VEREIN ADD COLUMN LeagueRanking INTEGER
ALTER TABLE VEREIN ADD COLUMN RegionRanking INTEGER
ALTER TABLE VEREIN ADD COLUMN PowerRating INTEGER
ALTER TABLE VEREIN DROP TWTrainer
ALTER TABLE VEREIN DROP Physiologen
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='DBVersion'
INSERT INTO USERCONFIGURATION VALUES('DBVersion','399')
COMMIT
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='spielerUebersichtsPanel_horizontalRightSplitPane'
COMMIT
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='aufstellungsPanel_verticalSplitPane'
COMMIT
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='aufstellungsPanel_horizontalRightSplitPane'
COMMIT
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='aufstellungsPanel_horizontalLeftSplitPane'
COMMIT
DROP TABLE IF EXISTS FAKTOREN
CREATE CACHED TABLE FAKTOREN( PositionID INTEGER NOT NULL PRIMARY KEY, GKfactor REAL NOT NULL, DEfactor REAL NOT NULL, WIfactor REAL NOT NULL, PSfactor REAL NOT NULL, SPfactor REAL NOT NULL, SCfactor REAL NOT NULL, PMfactor REAL NOT NULL, NormalisationFactor REAL NOT NULL  ) 
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='DBVersion'
INSERT INTO USERCONFIGURATION VALUES('DBVersion','399')
COMMIT
DELETE FROM USERCONFIGURATION WHERE CONFIG_KEY='LastConfUpdate'
INSERT INTO USERCONFIGURATION VALUES('LastConfUpdate','1.436')
COMMIT
```

**To Reproduce**
1. Copy an existing db in a development 
2. Start application 
3. Stop application
4. Start application again.
5. Error should appear at startup.

**Screenshots**
Cf. above.

**Platform information:**
 - OS: macOS
 - Version HEAD master

**Additional context**

**Comment by akasolace** [comment]
@tychobrailleur  I just tried with my master branch I can't reproduce ....

**Comment by tychobrailleur** [comment]
> @tychobrailleur I just tried with my master branch I can't reproduce ....

This happens to me when trying with the davidatorus db: unpack the db into the db folder (making sure it doesn't get overwritten), start, stop, and start again.

**Comment by akasolace** [comment]
ok I will try again ...

**Comment by akasolace** [comment]
1st start

![image](https://user-images.githubusercontent.com/1136496/85103225-8d655e00-b206-11ea-879c-d3fbc8be6718.png)

I select 1srt user and it loads normally
![image](https://user-images.githubusercontent.com/1136496/85103261-a0782e00-b206-11ea-8007-1837c6190df6.png)

I close the app

2nd start, it also loads normally

![image](https://user-images.githubusercontent.com/1136496/85103299-aff77700-b206-11ea-8d29-b7fb3e884e67.png)

![image](https://user-images.githubusercontent.com/1136496/85103329-be459300-b206-11ea-911f-8aeebe85a4ad.png)

**Comment by akasolace** [comment]
I have the following json file:

`[
  {
    "teamName": "davidator",
    "dbName": "db",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "davidakaria",
    "dbName": "db2",
    "backupLevel": 3,
    "isNtTeam": false
  },
  {
    "teamName": "HTLStest",
    "dbName": "db3",
    "backupLevel": 3,
    "isNtTeam": false
  }
]`

**Comment by tychobrailleur** [comment]
> 1st start
> 
> ![image](https://user-images.githubusercontent.com/1136496/85103225-8d655e00-b206-11ea-879c-d3fbc8be6718.png)

Ok, so maybe this is due to how I run the app in dev?  

To test this:
- I decompress the db zip into `./db/`
- I run `core.HO` in IntelliJ

In particular I don't get the window prompting for selecting the db.

It's probably a dev env thing, but I want to get to the bottom of this because:
- I want the DBUpdater to be reliable in all environments,
- The behaviour whereby `DBVersion` disappears is what caused the issue in #584

**Comment by akasolace** [comment]
> I decompress the db zip into ./db/

This is not sufficient, you might have a look at the doc which I am preparing  

https://ho.readthedocs.io/en/latest/installing_ho.html#how-to-upgrade-from-ho-3-0-to-ho-4-0

**Comment by tychobrailleur** [comment]
I am going to close this one out if this happens for no one else, I will reopen if I get more details on it.
