### ISSUE TITLE
[BUG] move log folder for installed app

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#591]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by akasolace** [comment]
@yaute74  @tychobrailleur   can you tell me where the logs are at the moments (i.e error.log and output.log) under Linux / macOS and where they should be moved.
In windows they are in the same folder level as /db in roaming.

I think it is only applicable for the installed version of HO because it should works well for zip folder.

**Comment by yaute74** [comment]
@akasolace on linux in 3.0 and 4.0 logs are in ~/.ho.logs

**Comment by tychobrailleur** [comment]
> @yaute74 @tychobrailleur can you tell me where the logs are at the moments (i.e error.log and output.log) under Linux / macOS and where they should be moved.

I believe I answered in another ticket.  Let me know if you need anything else on this.
