### ISSUE TITLE
 I CAN'T DOWNLOAD TEAM AND LEAGUE DATA

### ISSUE THREAD

**Issue by nhpenab** [akasolace/HO#592]
Hello, I downloaded ho 3.0 again and when I download it, it shows me ... access denied access error ... what do I do? Thank you
then I have to close the program and when I open it my team appears but the league or anything else does not appear
Editado el 17-06-2020 20.10 por nhpenab.

IN ADDITION IT ASKS ME FOR EACH URL I WANT TO DOWNLOAD DATA
![image](https://user-images.githubusercontent.com/67122426/85064462-35c8e300-b171-11ea-824f-4404ed396dd5.png)

**Comment by nhpenab** [comment]
now it is worse after entering the url code it is blocked and does not download anything
help me please

**Comment by nhpenab** [comment]
![image](https://user-images.githubusercontent.com/67122426/85065108-3c0b8f00-b172-11ea-8fb8-4e6f93fbda72.png)

**Comment by tychobrailleur** [comment]
Hi @nhpenab , not sure I understand the problem exactly.  Have you followed the steps in the installation instructions here: https://github.com/akasolace/HO/wiki/Installing-HO#English ?  They explain the OAuth flow with screenshots.

If this doesn't help you, let us know the exact steps you're following.

**Comment by akasolace** [comment]
@nhpenab which OS are you using?  Which version of HO?  Installed or standalone?  How are you launching HO ?

**Comment by akasolace** [comment]
> Hi @nhpenab , not sure I understand the problem exactly. Have you followed the steps in the installation instructions here: https://github.com/akasolace/HO/wiki/Installing-HO#English ? They explain the OAuth flow with screenshots.
> 
> If this doesn't help you, let us know the exact steps you're following.

I think it is a write access failure.  This would be definitly fixed in 4.0 ....

**Comment by nhpenab** [comment]
[image: image.png]


Well the truth is I think I have done all the steps well .. Every time I
want to download new data from the team and the league asks me again for
the URL ... is that normal?

**Comment by nhpenab** [comment]
I enter the URL and it stays thinking ...... it does nothing and won't let
me press "download"

**Comment by nhpenab** [comment]
[image: image.png]


finally ... now I press "save" and this appears ....

**Comment by nhpenab** [comment]
I pressed "accept" and apparently everything was fine ... I don't know

**Comment by akasolace** [comment]
@nhpenab  is it fixed?  should we close this issue ?

**Comment by nhpenab** [comment]
NO
MIREN AHORA

[image: image.png]

[image: image.png]

**Comment by nhpenab** [comment]
NOW IT DOESN'T EVEN OPEN

**Comment by nhpenab** [comment]
[image: image.png]

**Comment by tychobrailleur** [comment]
Hi @nhpenab, we cannot see the images you posted on Github, so we have no idea what your actual problem is.  We suspect this may be a write access failure, but you are not providing us with enough details for us to help you.

I would also appreciate if you could please refrain from “shouting” at us in all caps – this is not helpful.

**Comment by nhpenab** [comment]
excuse me I don't know English and I have to use the translator and that's
the size of the letters. At no time do I intend to yell at them

**Comment by nhpenab** [comment]
I have sent them images ... and apparently they are sent without problems

**Comment by nhpenab** [comment]
pity I don't know how else to explain ...

**Comment by nhpenab** [comment]
Can you give me a personal email from one of you to send you the
information, to see if they look good out there?

**Comment by nhpenab** [comment]
please don't get mad at the size of the lyrics ... it would be very
wasteful to have to rewrite what the translator translated

**Comment by akasolace** [comment]
@nhpenab please look at this post directly in GH and not through your emails you will realize how unclear this thread is. Also, you will be able to attach the pictures correctly.

**Comment by akasolace** [comment]
@nhpenab  what about here :-) :    https://github.com/akasolace/HO/issues/592#issuecomment-648943744

**Comment by nhpenab** [comment]
[Errores ho.docx](https://github.com/akasolace/HO/files/4827701/Errores.ho.docx)

**Comment by nhpenab** [comment]
this is what appears as an error and does not leave april ho

**Comment by nhpenab** [comment]
enel gmail me llegaban losmensajesen ingles y me tocaba traducir y aqui todo esta en español

**Comment by nhpenab** [comment]
ho abrio alcance a descargar  los datos del equipo y  no volvio a abrir  y  cuando bajaba los datos aparecia esto : https://github.com/akasolace/HO/issues/592#issuecomment-646269604

**Comment by nhpenab** [comment]
please

**Comment by nhpenab** [comment]
Errores ho.docx

**Comment by tychobrailleur** [comment]
The error I am seeing in the document is an OutOfMemoryError, when loading the app, which is somewhat peculiar.

Have you tried to fully reinstall HO?  Would you be able to share your db so we can have a look (not sure where on Windows it resides, as I am on Mac)?

**Comment by akasolace** [comment]
@nhpenab are you still experiencing problem or should we close this issue ?

**Comment by nhpenab** [comment]
EL PROBLEMA SIGUE ...  ya deje de tratar....  la verdad ud no me ayudaron les he enviado todos lo que me aparece al inentar ingresar y nada
