### ISSUE TITLE
remove  player information ?

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#594]
Do we want to keep this ? 

![image](https://user-images.githubusercontent.com/1136496/85122130-5acb5d80-b226-11ea-83fd-e7fd0d70f9c8.png)

**Comment by wsbrenk** [comment]
I use it occasionally to classify my training candidates

**Comment by akasolace** [comment]
how do you do it exactly ? You are using an icons for your wingers and anothers for your IM training ?

**Comment by akasolace** [comment]
if we keep the functionality we might have more clear icons and maybe infobull text like:
    - full trainee
    - 50% trainee
    - future coach 
    - transfer listed
    - ...

**Comment by wsbrenk** [comment]
@akasolace i will give you an insight of my hattrick voodoo;-)

first part of my classification is done by the groups A to F
A: trainees in league matches
B: trainees in friendly or cup matches
C: osmose player in league matches
D: osmose player in other matches
E: transfer listed
F: oldies and bank

trainer icon for current and future trainers (Good leadship)
extreme green smily trainees with long term perspective (full training over long period)
green smily (secondary training or shorter period)
yellow (old players or only short period of training)

**Comment by akasolace** [comment]
ok, I see ....
what about we let the user customize it. We introduce couple of recognizable icons and the user can edit the description in preference which will then be displayed in infobulle ? 
Could be something to be develop down the road after 4.0 ... what do you think ?

**Comment by wsbrenk** [comment]
@akasolace great luxury 

i would dispense on them if i get the detailed training plan option for each individual player in the training forecast;-)
