### ISSUE TITLE
[FEATURE] add transert listed status icon

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#596]
Trnasfert liste player are indicated by green light in HO! We might want to use an icon indicator like in HT! and then remove the unclear colors indication  cf  #586

![image](https://user-images.githubusercontent.com/1136496/85122596-1ab8aa80-b227-11ea-99a4-534f94378d80.png)

![image](https://user-images.githubusercontent.com/1136496/85122524-fbba1880-b226-11ea-9259-82d0a278efb6.png)

**Comment by akasolace** [comment]
@yaute74  @tychobrailleur 

icon can be copied from here into the /gui folder: 
https://github.com/akasolace/HO/blob/master/src/main/resources/img/icons/official/icomoon/SVG/transferlisted.svg

I am not sure how to load SVG icon and it seems to be still an open topic .... 

You will see that some of the icons which are currently png format can be found in this folder under an svg format ...

**Comment by akasolace** [comment]
@tychobrailleur  I don't have players on sale at the moment so I can't test it but I think you closed this one if I am not mistaken ....

**Comment by tychobrailleur** [comment]
This one should now be addressed, with #639 
![Screenshot from 2020-07-28 10-16-22](https://user-images.githubusercontent.com/114285/88645002-8a8a4280-d0bb-11ea-9d02-901e81526771.png)

**Comment by akasolace** [comment]
closed by #639
