### ISSUE TITLE
[FEATURE] additional links to player rows in lineup and squad tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#609]
as a follow up of #461 the idea is to make row in lineup / squad tab clickable

    1) full row but match column  (shift click   opens HT link to the player)
    2) in match column similar behaviour as player details (double click opens match tab,  shift + click opens HT)

**Comment by steffanots** [comment]
I add links.
Link for player is from column Name

**Comment by steffanots** [comment]
take

**Comment by akasolace** [comment]
should be closed by #675  => needs test before closing
