### ISSUE TITLE
[dev env] Add git ignore .DS_Store 

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#61]
Add:
`# macos Desktop Service Store
.DS_Store`
[https://en.wikipedia.org/wiki/.DS_Store](.DS_Store)

**Comment by brokenelevator** [comment]
forgive me, but I don't see the problem. Isn't this as easy as adding '.DS_Store' line to .gitignore file? With or without the # comment on a separate line?
If so, just push or PR it.

**Comment by mistermax80** [comment]
@brokenelevator,

Yes It's no a problem, the code is:
`# macos Desktop Service Store
.DS_Store`

I thought that for tracking for each request I should opened a issue.
Ok For the next similar case I push a PR withuot passing from issue.

**Comment by brokenelevator** [comment]
@mistermax80 Maybe you should, I don't know. I don't. But why didn't you make a PR after making the issue? And closed it when merged?

**Comment by mistermax80** [comment]
@brokenelevator,
ok, I reopened, when push and it will merge, this will be closed.
I'm newby on git... 😄

**Comment by mistermax80** [comment]
#63

**Comment by akasolace** [comment]
closed by PR #63
