### ISSUE TITLE
[BUG] remove last rating columns in squad and lineup tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#610]
as a follow up of #461 we need to remove last rating columns in squad and lineup tab (now duplicated information with last match)

**Comment by steffanots** [comment]
Since I added column LastMatchRating and now delete for display the Rating column, I have a problem with the configuration of the columns.
Are we doing a reset or are we going to update something?
Line code line 133 in UserColumnsTable will do job, but it not nice code.

**Comment by steffanots** [comment]
I create a branch feat_610 and i push the code, but i didn't PR until somebody see the code.

**Comment by akasolace** [comment]
@steffanots for this you can open a PR and mark it as draft (it means your code is not ready but you want early code review)

**Comment by akasolace** [comment]
should be closed once #611 merged => to be tested
