### ISSUE TITLE
[BUG] In lineup tab, no more highlight for selected players

### ISSUE THREAD

**Issue by yaute74** [akasolace/HO#612]
**Describe the bug**
In version 4.0, In lineup tab, no more highlight for selected players

**Screenshots**
What we have in 3.0
![image](https://user-images.githubusercontent.com/34601782/85449569-3231c380-b598-11ea-97a7-b2cc9901c94e.png)

**Additional context**
it's due to commit https://github.com/akasolace/HO/commit/183455aa1066ca6160f52045e5ddd957d4b65126

This part in src/main/java/core/gui/comp/entry/SpielerLabelEntry.java was removed:
```java
        if (m_bSelect)
            m_clComponent.setBackground(Color.LIGHT_GRAY);
        else if (m_bAssit)
            m_clComponent.setBackground(new Color(220, 220, 220));
        else
            m_clComponent.setBackground(isSelected ? HODefaultTableCellRenderer.SELECTION_BG : ColorLabelEntry.BG_STANDARD);
```

**Comment by yaute74** [comment]
@tychobrailleur can you have a look ? I don't want to break you modification.

**Comment by tychobrailleur** [comment]
> @tychobrailleur can you have a look ? I don't want to break you modification.

Sure, will do!
