### ISSUE TITLE
[BUG]  layout issue in case of multiple screens

### ISSUE THREAD

**Issue by Lactoo** [akasolace/HO#618]
I don't know if this is a bug or a feature request. Anyway, to me it feels like a bug, as I did not have the same issue in HO 1.

When I start HO 3.0 the layout is a bit weird. It has full screen height, but is very narrow.

I can then full screen it and adjust the windows.

The the "player name" and "player details" windows are very narrow and to the left. I then adjust the windows to how I like it.

Is there any way to save the layout so it will look the same the next time I open HO 3.0?

As it is now it resets the layout every time I start HO.

Possible useful note:
I'm using 2 screens. HO opens on the right screen.

Below some screenshots:

1. When I open:
![image](https://user-images.githubusercontent.com/67468579/85858872-9c2ab280-b7bc-11ea-87b3-a509b71dde94.png)

2. After I maximize HO
![image](https://user-images.githubusercontent.com/67468579/85859026-deec8a80-b7bc-11ea-8de6-5f50a833902e.png)

3. After I have adjusted layout to how I want it:
![image](https://user-images.githubusercontent.com/67468579/85859096-faf02c00-b7bc-11ea-8016-57bdfe4ad231.png)

4. After I have closed HO 3.0 and re-opened:
![image](https://user-images.githubusercontent.com/67468579/85859212-25da8000-b7bd-11ea-910b-c182e972029a.png)

**Platform information:**
 - OS: Win10
 - HO 3.0 build 2728 (the latest according to check for update)

**Comment by akasolace** [comment]
The issue still exist on master branch

**Comment by akasolace** [comment]
I just had a quick look. I haven't found the issue et but something look really broken in method load of userconfigurationtable.java

**Comment by tychobrailleur** [comment]
Is there a remote chance this could be the cause of these weird issues disappearing from `USERCONFIGURATION`, sometimes causing the app to refuse to start?

**Comment by akasolace** [comment]
@tychobrailleur  so I know why I observe this on master  ....because of updateDBv400
I have to check if I have this on 3.0

**Comment by tychobrailleur** [comment]
> @tychobrailleur so I know why I observe this on master ....because of updateDBv400

OK.  The deletes in `updateDBv400` are supposed to reset the divider location, is this causing a problem for you on master?

**Comment by akasolace** [comment]
> OK. The deletes in updateDBv400 are supposed to reset the divider location, is this causing a problem for you on master?

no, it is just that I did not noticed that commit in first place. Recently I saw that this parameter was not saved so when I saw that bug ticket I thought this was related but it was not the case => I will change the status of this issue to "information needed" because in fact I can't reproduce it

However the good this is that looking at it I come across a really dirsty piece of code that I fixed and I think it should bring some startup improvement. I will open PR now

**Comment by akasolace** [comment]
@Lactoo  I cannot reproduce could you please share your DB ?

**Comment by Lidegand** [comment]
It happens the same to me. I am using also two screens and HO opens in right screen two (not the main one). Screenshots shared by reporter show exactly the same I can see in my computer. What I can add is that as I have more than 1 team, when I execute HO, team selection dropdown appears on left screen (the main one) and with correct size. Then, it opens on right screen and very narrow

Windows 7 (64 bits)
HO 3.0 build 2728 (the latest according to check for update)
2 screens with 1920x1080

**Comment by Lactoo** [comment]
> @Lactoo I cannot reproduce could you please share your DB ?

How do I share a DB? :)

**Comment by akasolace** [comment]
you zip your db folder and share it via mozilla send or something equivalent ....

**Comment by Lactoo** [comment]
[db-zup BUG618.zip](https://github.com/akasolace/HO/files/4841797/db-zup.BUG618.zip)

Here is my DB-fil. Hope thats what you looking for.

**Comment by tychobrailleur** [comment]
Thanks @Lactoo.  That's a strange one: I can see when starting the app that it is indeed all squished, which is normal given the parameters stored in the db:

```
hoMainFrame_PositionX                             1912
hoMainFrame_PositionY                             0
hoMainFrame_height                                1056
hoMainFrame_width                                 8
```

But here I can resize the window, change the different dividers, quit, and the dimensions get saved.
The problem might be caused by the screen position (`1912`), when the width is saved, the following is calculated:

```
		parameter.hoMainFrame_width = Math.min(getSize().width, getToolkit().getScreenSize().width
				- parameter.hoMainFrame_PositionX);
```

I am not sure I understand the rationale behind the second arg of `min`.  

But in any case, any idea why position X is 1912?  Do you have multiple screens?  If you make sure the window is as left as possible on the screen (and a reasonable width), and exit HO, what happens?

**Comment by akasolace** [comment]
@Lactoo  can you test if latest dev version is fixing this issue ? PLEASE do not upgrade or touch your exisintg install, just test using the zip version on a copy of your db.  Dev Version is still highly UNSTABLE and might break your db so just work on a copy ...

**Comment by Lactoo** [comment]
> @Lactoo can you test if latest dev version is fixing this issue ? PLEASE do not upgrade or touch your exisintg install, just test using the zip version on a copy of your db. Dev Version is still highly UNSTABLE and might break your db so just work on a copy ...

Where do I find this version?

Also, something to add. When I close HO 3.0 on my main screen, it does not do all the funny buisness and forget the settings. It's only when I close it on my secondary screen.

If I open on main screen, and then drag it to my secondary screen it forgets all the settings while dragging. It's really very odd.

**Comment by tychobrailleur** [comment]
> Where do I find this version?

You can find it here: https://github.com/akasolace/HO/releases/tag/dev 


> Also, something to add. When I close HO 3.0 on my main screen, it does not do all the funny buisness and forget the settings. It's only when I close it on my secondary screen.
> 
> If I open on main screen, and then drag it to my secondary screen it forgets all the settings while dragging. It's really very odd.

Great, this confirms my assumption, and hopefully [this fix](https://github.com/akasolace/HO/pull/630) should address the problem (the description explains the actual issue, if you're interested).
