### ISSUE TITLE
[BUG] no training reported?

### ISSUE THREAD

**Issue by noujazeg** [akasolace/HO#623]
Hello,

HO didn't report any training last friday. Concrete: my trainees didn't get any better in their skill i'm training (defending). Nevertheless they all got a higher TSI, so I suspect they did get their training after all. All players did play, although one match was a walkover, because the opponent didn't lineup a full team.

These are the 2 matches in which my 10 trainees played:

https://www97.hattrick.org/Club/Matches/Match.aspx?matchID=661971790&SourceSystem=Hattrick&TeamId=209495&UpdateViewedReport=False&BrowseIds=658785615,661971782,662591943,661971785,662790133,661971790,662954689,661971794,663097408,661971798,661971802,661971805

https://www97.hattrick.org/Club/Matches/Match.aspx?matchID=662954689&SourceSystem=Hattrick&TeamId=209495&UpdateViewedReport=False&BrowseIds=658785615,661971782,662591943,661971785,662790133,661971790,662954689,661971794,663097408,661971798,661971802,661971805

I'm running HO 2.0 on a Windows 10 laptop.

I sorted the players on their defending skill. The first 10 players are my 10 trainees. Overste even declined in his skill, but he's being trained (he's gonna be my coach someday) and normally his skill is increasing a bit every week. 

![2020-06-27](https://user-images.githubusercontent.com/67507299/85922605-f8f1a000-b884-11ea-9e7f-28e3aa81771f.png)

a second screenshot, which includes the training of June 19th, so you can see how it normally looks:

![2020-06-27 (1)](https://user-images.githubusercontent.com/67507299/85922691-a19fff80-b885-11ea-9b62-605d4eca9043.png)

**Comment by wsbrenk** [comment]
first match is a walkover match
second one is saphir cup

**Comment by noujazeg** [comment]
> first match is a walkover match
> second one is saphir cup

yes, but players receive training in matches like that as well.

**Comment by wsbrenk** [comment]
@noujazeg i know - I just wanted to write down what the reason for the error you found might be

but as far as i know, there is no experience increase in case of walkover, isn't?

**Comment by wsbrenk** [comment]
#306 could solve the training of the saphir cup match

**Comment by noujazeg** [comment]
> @noujazeg i know - I just wanted to write down what the reason for the error you found might be
> 
> but as far as i know, there is no experience increase in case of walkover, isn't?

ah, thanks then.

i don't know about the latter, but it would be sad as i probably have 4 walkover matches this season.

**Comment by akasolace** [comment]
@wsbrenk @noujazeg  sounds like this ticket can be closed; what do you think ?

**Comment by wsbrenk** [comment]
@akasolace i'm not sure if we handle walkover matches correctly

**Comment by wsbrenk** [comment]
► When you play against a Walkover team, you will win 5-0, get the formation experience and training for the full 90 min and the TS will be affected as usual (PIC, Normal, MOTS). There is no gain of Experience for your players, though.

it is from https://www83.hattrick.org/Forum/Read.aspx?t=17308544&n=18&v=0

**Comment by wsbrenk** [comment]
i could reproduce that in walkover matches HO will calc NO training and NO experience. The later is OK.
