### ISSUE TITLE
Configurable Training Period 

### ISSUE THREAD

**Issue by Sciaqquazza** [akasolace/HO#624]
I would like to suggest allowing training period to be set up for a number of days greater than the single season.
Thanks in advance, regards 
Uccio

**Comment by wsbrenk** [comment]
@Sciaqquazza Files -> Settings -> Various -> Future Weeks

do you mean that?

**Comment by tychobrailleur** [comment]
Can we close this, @Sciaqquazza ?

**Comment by tychobrailleur** [comment]
Will close for now, please reopen if this doesn't address your issue.
