### ISSUE TITLE
[BUG] Can not see the next opponent at Rubin-Cup

### ISSUE THREAD

**Issue by PecataM** [akasolace/HO#625]
**Describe the bug**

In the Drop-Down Menu in "Тeam analysis" I can not see the next opponent for the Rubin Cup.

**Comment by tychobrailleur** [comment]
Is that something you've seen before, @wsbrenk?

**Comment by wsbrenk** [comment]
@yaute worked on that last

**Comment by tychobrailleur** [comment]
Would you be able to share your db with us @PecataM so we can try to replicate?

**Comment by miloszatko** [comment]
[db_singleUser-2020-7-4.zip](https://github.com/akasolace/HO/files/4873158/db_singleUser-2020-7-4.zip)

I have the same problem

**Comment by miloszatko** [comment]
![image](https://user-images.githubusercontent.com/20202008/86516820-fa424000-be23-11ea-9709-f936ade644e9.png)

Only next league match is showed in drop down menu.

**Comment by tychobrailleur** [comment]
This seems to be working on master:

![Screenshot from 2020-07-04 21-49-29](https://user-images.githubusercontent.com/114285/86520804-5ca93980-be40-11ea-97fc-d3f35bb763a3.png)

**Comment by tychobrailleur** [comment]
I have cherry-picked the relevant commit and created a PR to the 3.x release branch.  This should be fixed in the next 3.x release.
