### ISSUE TITLE
[BUG] NT names

### ISSUE THREAD

**Issue by RenosG** [akasolace/HO#629]
When I download the database for the NT, I can't see the names of the players

**To Reproduce**
1. Open HO 3.0
2. Select NT Database
3. Click on File>Download
4. Press Start
5. Save hrf file in database folder
6. Press OK
7. Click on File>Import from HRF
8. Select saved hrf file and press open
9. Press yes on confirmation popup window
10. See error

**Screenshots**
[url=https://ibb.co/nrxXRKd][img]https://i.ibb.co/H75cX9w/Screenshot-8.png[/img][/url]

**Platform information:**
 - OS: [Windows]
 - Version: Microsoft Windows 10 Professional 64-bit (Build 18363)

**Comment by akasolace** [comment]
Hi @RenosG

>Click on File>Download
Press Start
Save hrf file in database folder

If you download file, you should not have to reimport the hrf just after ... this is not the intended workflow.

are you still experiencing this issue? If it is the case, may I ask you to share your database folder?

**Comment by akasolace** [comment]
hi @RenosG, should I close this issue ?

**Comment by RenosG** [comment]
Hello,

I am experiencing this issue only with the NT Team database. When I press
start nothing happens, so I always needed to reimport the hrf and then it
worked. This time though the player names are blank. How do you want me to
share the database?

**Comment by akasolace** [comment]
@RenosG basic question but just to be sure, you are still an active NT coach?

> how do you want me to share the database?

https://wetransfer.com/

**Comment by RenosG** [comment]
Yes I am, Cyprus Nt Coach

**Comment by akasolace** [comment]
> Yes I am, Cyprus Nt Coach

@RenosG ok can you please share your db via https://wetransfer.com/

**Comment by akasolace** [comment]
@RenosG we can't work on this issue without db, for the time being I postpone it to next version.

**Comment by akasolace** [comment]
@RenosG without news on this issue and no database to investigate I will close this issue.
Please feel free to reopen it if still valid
