### ISSUE TITLE
[BUG] man marking order

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#632]
**Describe the bug**
When I download a match with a man marking order and then try to upload it returns an error

**To Reproduce**
1. Go to 'Lineup'.
2. Open "Upload/Download".
3. Select match and click on "Download lineup".
4. Click on "Upload lineup".

**Screenshots**
error message
![2020-07-13_1425](https://user-images.githubusercontent.com/67824966/87310771-50933b00-c516-11ea-9cb7-49f70e1cbec0.png)

If I delete the man marking order the the error disappears.
![2020-07-13_1426](https://user-images.githubusercontent.com/67824966/87310848-6e60a000-c516-11ea-9925-ec6913700faf.png)

**Platform information:**
 - OS: Windows
 - Version 3.000

**Comment by akasolace** [comment]
unfortunatly man marking is not yet supported by CHPP but what you described is a bug ....
it should give a propwer warning instead of throwing an error.

**Comment by aristodemos2008** [comment]
The man marking order only shows in the HO list if I have 4 substitutions planned in HT. Usually I have 5 and then the man marking does not show up in the list.

**Comment by wsbrenk** [comment]
new order type 4 is man marking:

downloaded a lineup with man marking in place:

      <PlayerOrder>
        <PlayerOrderID>0</PlayerOrderID>
        <MatchMinuteCriteria>-1</MatchMinuteCriteria>
        <GoalDiffCriteria>-1</GoalDiffCriteria>
        <RedCardCriteria>-1</RedCardCriteria>
        <SubjectPlayerID>444593266</SubjectPlayerID>
        <ObjectPlayerID>421945637</ObjectPlayerID>
        <OrderType>4</OrderType>
        <NewPositionId>-1</NewPositionId>
        <NewPositionBehaviour>-1</NewPositionBehaviour>
      </PlayerOrder>

**Comment by akasolace** [comment]
@wsbrenk  I saw that in the xml but it was not listed in the api documentation, I asked the officials but they had no information (I guess you can follow the discussion on HT forum).  I haven't tested it but yes maybe it works and only the documentation is incomplete... worth to give it a try

**Comment by wsbrenk** [comment]
@akasolace maybe i will see the surprise when i send those match orders back to HT.

**Comment by wsbrenk** [comment]
today i succeeded in sending a man marking match order to Hattrick. This was the result:

<?xml version="1.0" encoding="utf-8"?>
<HattrickData>
  <FileName>matchorders.xml</FileName>
  <Version>3.0</Version>
  <UserID>1757369</UserID>
  <FetchedDate>2020-08-02 11:52:03</FetchedDate>
  <MatchID>663472286</MatchID>
  <IsYouth>False</IsYouth>
  <MatchData OrdersSet="True" />
</HattrickData>

the man marking was correctly set in Hattrick! I'm optimistic that we can do man marking in near future. Now we need especially some good ideas how to implement the UI.

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/89120603-f7387f00-d4b7-11ea-9548-cfe9e3217617.png)

- kind of order is missing (easy)
- icon of order is missing (not so easy for me)
- name of opponent player is missing (the right challenge for me)
- view to edit man marking with opponent team members to select from (!!!!)

**Comment by wsbrenk** [comment]
![grafik](https://user-images.githubusercontent.com/11821502/89124500-b7818f80-d4d7-11ea-8a2d-f93b365a16e6.png)

1st and 3rd point of the list are done. there is still a slightly discrepancy in the opponents player name.
2nd point a new icon name is implemented showing to the same icon than the substitution. this has to be replaced when a new icon is available.

Now i need good ideas for the 4th point.

**Comment by tychobrailleur** [comment]
This is pretty awesome @wsbrenk really excited about this!

**Comment by tychobrailleur** [comment]
For 4th point would reusing the Matches tab view be a possibility to select the man to mark?

**Comment by wsbrenk** [comment]
![manmarkingOrder](https://user-images.githubusercontent.com/11821502/89227524-221cf300-d5de-11ea-94a9-4fad0a7993ca.png)


Currently teamanalyzers team view is my favorite. a 4th button in SubstitutionOverview could start the team analyzer and some drag+drop action could create the man marking match order. But i don't have any idea how to implement that - up to now.

**Comment by tychobrailleur** [comment]
Sorry that's exactly the view i had in mind

**Comment by wsbrenk** [comment]
@tychobrailleur great - do you have a good idea how to do it, would you like to take over this part? this is completely new territory for me.

**Comment by tychobrailleur** [comment]
> @tychobrailleur great - do you have a good idea how to do it, would you like to take over this part? this is completely new territory for me.

I can give it a try.  Do you have a branch for this specific piece of work?

**Comment by wsbrenk** [comment]
@tychobrailleur this is the branch https://github.com/wsbrenk/HO/tree/%23632manmarking 
#632manmarking

since i merged a very old branch where i once started the man marking feature, there are a lot of commits which are no longer of interest and they will disappear (hopefully) when i will rebase this branch.

**Comment by wsbrenk** [comment]
@tychobrailleur another idea: since the bug part of this issue is done, i could create a pull request and we will handle the feature part in an extra ticket. what do you think?

**Comment by tychobrailleur** [comment]
> @tychobrailleur another idea: since the bug part of this issue is done, i could create a pull request and we will handle the feature part in an extra ticket. what do you think?

ok, works for me.  I can work on my own branch once this is merged then.

**Comment by akasolace** [comment]
@wsbrenk @tychobrailleur awesome ... this is a fantastic addition !
