### ISSUE TITLE
[BUG] error uploading substitution

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#633]
**Describe the bug**
After downloading a formation from HT the same can't be uploaded due to an error in a substitution.

**To Reproduce**
1. Go to 'Lineup'.
2. Open "Upload/Download".
3. Select match and click on "Download lineup".
4. Click on "Upload lineup".

**Screenshots**
![2020-07-13_1548](https://user-images.githubusercontent.com/67824966/87319169-2f841780-c521-11ea-939b-689890d61c95.png)
![2020-07-13_1549](https://user-images.githubusercontent.com/67824966/87319265-4d517c80-c521-11ea-8741-19d4bd411ee6.png)
![2020-07-13_1548_001](https://user-images.githubusercontent.com/67824966/87319283-52163080-c521-11ea-849e-500395ab1a18.png)

**Platform information:**
 - OS: Windows
 - Version 3.000

**Comment by akasolace** [comment]
@wsbrenk maybe you can look at it afer #632 as they may be related ...

**Comment by wsbrenk** [comment]
@akasolace OK

**Comment by wsbrenk** [comment]
@akasolace @tychobrailleur cherry picking the commit above could easily repair this bug in release 3 patch branch.
