### ISSUE TITLE
[BUG] Lineups folder not found in installed version of 4.0

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#635]
@wsbrenk  @tychobrailleur @yaute74 @DavidatorusF 

I will work on this one but I would need some of your inputs ....

**Windows**
   - installed:  %appdir%/HO   => db/, user.json, error.log, output.log   **no lineup folder** 
   - zip ?? 

**Linux**
   - installed:  ??
   - zip ?? 

**Mac**
   - installed:  ??
   - zip ?? 

Do you think we need this folder ?  Do we need this Actual.dat file ? Is it not something already present in the database ?

**Comment by wsbrenk** [comment]
Windows environment

- Application Data Folders: 
	Most applications store their settings in the Application Data folders at C:\Users\username\AppData\, by default. 
	Each Windows user account has its own Application Data folders, so each Windows user account can have its 
	own application data and settings if programs use this folder.
	There’s also the ProgramData folder. This folder has most in common with the Application Data folders, but—instead of having an individual folder for each user—the ProgramData folder is shared among all the user accounts on your PC.
	Data folders are hidden. for some users not easy to find.
	%APPDATA% will be copied to other computers if the user logs in on other computers of the local network (roaming)
	%LOCALAPPDATA% will not be copied, is not available on other systems of the network.
	%ProgramData%  if installer creates ho subdirs for each user, the user should be able to share these in the network


-    Documents Folders: 
	Some applications—especially PC games—choose to store their settings under the Documents folder at C:\Users\username\Documents. 
	This makes it even easier for people to find, back up, and edit these files.

**Comment by akasolace** [comment]
@wsbrenk  sorry my question was not clear, I just wanted to confirm which folder are created and where on the different platform ... I put the info for windows installed HO!,  I need help for macOS and Linux. Wanted to make sure this lineup folder is missing everywhere ...   Otherwise what about the second part of the question  `Do you think we need this folder ?  Do we need this Actual.dat file ? Is it not something already present in the database ?`

**Comment by tychobrailleur** [comment]
On Mac:

- installed:

```
~/Library/Application Support/HO 🔰‏ tree
.
├── db
│   ├── database.data
│   ├── database.lck
│   ├── database.log
│   ├── database.properties
│   ├── database.script
│   └── database.tmp
├── error.log
├── output.log
└── users.json

2 directories, 8 files
```

I cannot see the Lineups folder, not even under the `/Applications/HO` folder.

- zip (using unix zip): 

```
~/Library/Application Support/HO 🔰‏ tree
.
├── db
│   ├── database.data
│   ├── database.lck
│   ├── database.log
│   ├── database.properties
│   ├── database.script
│   └── database.tmp
├── error.log
├── output.log
└── users.json

2 directories, 8 files
```

and under the unzipped folder:

```
~/dev/HO/build/artefacts/HO-4.0.0.3013-unix-DEV (master *) 🔰‏ tree | grep -v jar
.
├── HO
├── HO.vmoptions
├── Lineups
│   └── tychobrailleur
│       └── Actual.dat
├── logs
│   └── HO-2020-07-15.log
├── prediction
│   ├── default
│   │   ├── centralattack.dat
│   │   ├── centraldefense.dat
│   │   ├── midfield.dat
│   │   ├── playerstrength.dat
│   │   ├── sideattack.dat
│   │   ├── sidedefense.dat
│   │   └── tactics.dat
│   ├── defaults.xml
│   ├── new
│   │   ├── centralattack.dat
│   │   ├── centraldefense.dat
│   │   ├── midfield.dat
│   │   ├── playerstrength.dat
│   │   ├── sideattack.dat
│   │   ├── sidedefense.dat
│   │   └── tactics.dat
│   ├── old\ Engine
│   │   ├── centralattack.dat
│   │   ├── centraldefense.dat
│   │   ├── midfield.dat
│   │   ├── playerstrength.dat
│   │   ├── sideattack.dat
│   │   ├── sidedefense.dat
│   │   └── tactics.dat
│   ├── predictionTypes.conf
│   └── skilldrops
│       ├── README.txt
│       ├── defending
│       ├── keeper
│       ├── passing
│       ├── playmaking
│       ├── scoring
│       ├── setpieces
│       └── winger
└── themes

9 directories, 59 files
```

**Comment by tychobrailleur** [comment]
If I understand this file correctly, it saves any potential lineup you may have come up with?

![Screenshot from 2020-07-15 21-21-33](https://user-images.githubusercontent.com/114285/87592118-3c4f6980-c6e1-11ea-83c5-4d7d88092250.png)

I don't believe we persist that in the DB, right?

**Comment by wsbrenk** [comment]
@tychobrailleur they are stored in the database (table aufstellung). actual and last lineup automatically each download and the user can store his edited lineup too, giving them any name.

**Comment by tychobrailleur** [comment]
But I don't believe this is what it is: here you can save your own lineups, even the ones you have not submitted, and give them names, like "4-4-2" or "CA". That wouldn't get stored in the db, right?

**Comment by akasolace** [comment]
in my case, what is strange is that I can't find the lineup folde anywhere but still the functionality seems to works

I also see that I have an actual and last lineup,maybe only those 2 are automatically updated during download and also sotred in the database while other are only stored in the text file (it is odd because it is the only exemple of information not stored in the database but in a separated text file ....)

![image](https://user-images.githubusercontent.com/1136496/87633120-1787e000-c73b-11ea-8576-5227b6b92431.png)

**Comment by tychobrailleur** [comment]
> in my case, what is strange is that I can't find the lineup folder anywhere on my system but the functionality is still working .... (I need to dig onthis one)

Weird indeed.  It should be created in the current working dir: https://github.com/akasolace/HO/blob/master/src/main/java/module/lineup/LineupPositionsPanel.java#L188

**Comment by wsbrenk** [comment]
@tychobrailleur @akasolace lineups are stored in database table AUFSTELLUNG

**Comment by wsbrenk** [comment]
i do not find any button to export lineups. are you sure this function is still called anywhere?

**Comment by akasolace** [comment]
> @tychobrailleur @akasolace lineups are stored in database table AUFSTELLUNG

Yes, I just check and I can confirm this, so I don't understand what this linuep folder is used for ....

**Comment by akasolace** [comment]
> i do not find any button to export lineups. are you sure this function is still called anywhere?

when you decide to save the lineup or load a linup the lineup folder is created

**Comment by akasolace** [comment]
@wsbrenk  @tychobrailleur  I might be wrong but it seems to me all those operations are useless. I will try to remove this on a branch and see what happens ...

**Comment by akasolace** [comment]
@wsbrenk @tychobrailleur I did it and made some test, I don't see any side effect for the moment
