### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder

### ISSUE THREAD

**Issue by piratenfuerimmer** [akasolace/HO#643]
This java error popped up after my brand new installation, running ho for the first time.
![ho-error](https://user-images.githubusercontent.com/68741966/88397418-3a835580-ce07-11ea-84bf-aebdd85a85e8.png)
Despite the error, ho seems to be running fine - I haven't been able to find anything that doesn't work.

**To Reproduce**
1. Start ho
2. Click on League details tab
3. See error

Screenshot attached

**Platform information:**
 - OS: [Linux Mint 20]
 - Version (including build number): ho 3.0 build 2728

**Additional context**
I did a clean upgrade of Linux Mint, but lost my ho 3.0 installation as it installed in usr.
I reinstalled it and the error appeared.
I do have at least two older versions of ho on this machine, but ho 3.0 managed to find the correct db in their folders.
Before this forced migration, I have been getting an error when running ho, which may have been the same one, but I cannot remember.

**Comment by tychobrailleur** [comment]
Hi @piratenfuerimmer, thanks for reporting; this seems to be a duplicate of https://github.com/akasolace/HO/issues/589 that will be fixed in the next release.
