### ISSUE TITLE
[BUG] Open CHPP url doesn't open any url

### ISSUE THREAD

**Issue by emi65** [akasolace/HO#656]
Hi
I'm just installed HO 3.0

It is a new installation
When I push "download" I need CHPP authorization
A windows with OPEN URL is openend but in the field there is not any url and the button doesn't open URL in order to
get CHPP auth

How can I get CHPP auth ?
thanks
Emilio

**Comment by tychobrailleur** [comment]
Hi @emi65 could you please share screenshots of what you're seeing with us, so we can get a sense of what is going on?
Thanks!

**Comment by emi65** [comment]
Hi Sebastien

Hi re-download the HO from github and reinstalled it

Now all work fine

thank and Regards

Emilio

**Comment by tychobrailleur** [comment]
Good to hear! I am going to close this one then, feel free to re-open if you're having a similar issue.
