### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crip1** [akasolace/HO#657]
**Describe the bug**
Under the lineup tab, the lineup tool, start assistant, since loading HO3.0, my top IM does not get selected for any position.    When I select the player pull-down for any of the IM positions, he is the first listed player, and I can manually add him to the lineup tool.

While I have my sequence set to MID-DE-FOR, the only other filter box selected is Consider form.     I have tried selecting options, re-running lineup tool, deselecting rerunning lineup tool, but the player continues to avoid being chosen by the lineup tool.    

But this morning, I noticed that my Top Winger was not being selected for a Wing position either, rather he was being inserted as a Wingback, rather than a winger.   This has not happened before.    I was able to swap the WB/Winger manually, but it seems that this should be a straightforward algorithm to select these players. 

**To Reproduce**
1. Go to 'Lineup'
2. Click on 2nd 'Lineup Tab'
3. Click on "Clear Lineup"
4. Click on "Start Assistant"
5.  Discrepancies as described above.

**Platform information:**
 - OS: Windows
 - Version (including build number):   HO 3.000

**Additional information:
 Reported this on the HO Forum in Hattrick about a week ago (or maybe longer ago), but no response received.   Not sure what the .db file is that should be enclosed.   I tried attaching my db_today's.zip file, but github didn't like that because it is over 10MB in size.

**Comment by wsbrenk** [comment]
@Crip1 it is not easy to reproduce this issue. uploading your db would be one option. 
in your decription you mentioned that only the form filter option was selected and the order the position should be set. Could it be, that above the order selection an group (a,b,c,d,f) is selected or deselected, which does not match with your missed players?

**Comment by Crip1** [comment]
The Listbox Group filter and “Not” boxes above are not selected.   In fact, the player in question is listed as part of Group A, and the other players in Group A all get selected for the lineup.   (I use Group A to identify who I normally intend for League match, 100% PM Training, Group B is League Match 50% PM Training, Group C is Friendly/Cup 100% PM, Group D is Friendly/Cup 50% PM)

 

Once I put the player in the lineup, I notice an Asterix (*) before the groupbox letter for all Group A players, and 4/6 of the no-group players.    None of the group B players have an Asterix.   

 

Where do I get the .db from?   In my directory structure, …/HO/HattrickOrganizer/db2 seems to point to my files.    However, database.data is 294,912 kB, so too big to upload to github.    There are compressed files, for my last 3 uses, db_Crip-2020-8-9.zip is the most recent but this is also 136,722 kB, and also too big to upload to github.     Is there another way besides just drag/drop within github to upload the file?

**Comment by Crip1** [comment]
Never mind, I just figured out the problem.      In the list of players below the onfield lineup in the lineup up tool, there is a column between the Age and Best Position fields.   This was deselected for the player in question.      Putting a checkmark into this field solved the problem.

 

Case Closed!

 

Thanks for the response.
