### ISSUE TITLE
[BUG] JRELoadError on MacOS

### ISSUE THREAD

**Issue by dlfigueira** [akasolace/HO#663]
When the application is executed, it immediatly returns the error 'JRELoadError'. No more information is given.

I have OpenJDK 11 installed on my machine.

java -version
> openjdk version "11.0.8" 2020-07-14
> OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
> OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)

echo $JAVA_HOME
> /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home

**Screenshots**
<img width="425" alt="imagem" src="https://user-images.githubusercontent.com/1057223/90170449-f812c000-dd97-11ea-8aa9-afa65402b869.png">

I have tried installing OpenJDK 8, thinking this could be an incompatibility with v11, but I had exactly the same error.
Any help would be much appreciated.

**Comment by akasolace** [comment]
@dlfigueira can you share the content of the log file ?

**Comment by dlfigueira** [comment]
Sure @akasolace. Can you tell me where the log file is located?

**Comment by akasolace** [comment]
@dlfigueira sorry for later answer, I was busy on something else ...
Which version are you trying to launch ? the latest stable or the latest dev ?

**Comment by dlfigueira** [comment]
No problem @akasolace. I'm trying to launch latest stable (3.0).

**Comment by akasolace** [comment]
This is strange but it is difficult for me to reproduce. If you can, I would suggest installing oracle jdk for Java 8. This is known to work for many users. Otherwise you can try the DEV version, it is requiring Java 14 but you can select one with JRE packaged. Be aware thought that the DEV version is still very unstable and has many known bugs.

**Comment by dlfigueira** [comment]
I do believe that to download oracle JDK you now need an oracle account, which I do not have.

In the meantime, I have created a linux VM and I have been using it there successfully. 
I'll wait for the next release with a bundled JRE :)

**Comment by akasolace** [comment]
ok I close the issue for now as it seems very specific to your install. Don't hesitate to reopen it in the future if needed
