### ISSUE TITLE
[BUG] No Download of Team Information After Training

### ISSUE THREAD

**Issue by RobertRescue** [akasolace/HO#664]
After Update to JAVA 8 - Update 261 there is an error when downloading team information.
![screenshot HO](https://user-images.githubusercontent.com/69968327/90765408-24739280-e2ea-11ea-9679-91acacf743f0.jpg)

MacOS 10.15.6
HO 3.0.2.2728

**Comment by akasolace** [comment]
@RobertRescue are you still experiencing this issue ?

**Comment by RobertRescue** [comment]
Yes, it´s still the problem on MacOS. Now i check the team with a Win-Laptop, but without update on JAVA Update 261 and that´s work.

**Comment by akasolace** [comment]
@dlfigueira could this be related to your issue (#663)? Could you try with a version of java 8 prior to u261 ? 
@tychobrailleur Can you reproduce on macOS?

**Comment by dlfigueira** [comment]
I don't believe so @akasolace. In my case the application would not load at all.

**Comment by tychobrailleur** [comment]
> @dlfigueira could this be related to your issue (#663)? Could you try with a version of java 8 prior to u261 ?
> @tychobrailleur Can you reproduce on macOS?

I can't, but I would need to set up the same version of the JDK.  Is it the oracle version, or the openjdk one? 

What is the full stacktrace for this error?

**Comment by akasolace** [comment]
without additonal info, I close this issue.  Especially that v4 is close.
