### ISSUE TITLE
[FEATURE] Create SVG icons compatible with new theming feature

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#674]
**Describe the solution you'd like**
Create new SVG icons replacing the existing ones so that they can match the different themes currently available in HO 4.0

**Additional context**
This completes the ticket #85

**Comment by wsbrenk** [comment]
> Everytime you encounter a png file still in use in HO, do not hesitate to list it in #674, this ticket will be a tracker for svg icon request.

line 625 following of java/module/lineup/substitution/SubstitutionOverview.java uses png icons

a man marking icon is here: resources/img/icons/official/HTwebsite/svg/manmark.svg
