### ISSUE TITLE
refactor HTCalendar.java and HTCalendarFactory.java

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#678]
_Originally posted by @akasolace in https://github.com/akasolace/HO/issues/671#issuecomment-684611311_
  
This is a prerequisite for #671 

 - [ ] #679 
 - [ ] a function that return HTWeek and HTSeason GregorianToHT (Globally and localy for the league)
 - [ ]  nb of training events between 2 dates (@wsbrenk would that be sufficient for training manager ?
 - [ ] nb of economic events between 2 dates (not even sure if we need that, tbc ?? )
 - [ ] anything else ?

Then we could get rid of the Economic and Training calendar that are not meaningful

**Comment by akasolace** [comment]
Officialy, HTWeek start on Monday midnight, HTSeason depends of leagueOffset.
Then I guess we need the following:
     - a function that return HTWeek and HTSeason GregorianToHT (Globally and localy for the league)
     - nb of training events between 2 dates (@wsbrenk would that be sufficient for training manager ? 
     - nb of economic events between 2 dates (not even sure if we need that, tbc ?? )
      - anything else ? 

Then we could get rid of the Economic and Training calendar that are not meaningful. @wsbrenk how does it sounds to you ?

**Comment by wsbrenk** [comment]
> * nb of training events between 2 dates (@wsbrenk would that be sufficient for training manager ?

training manager examines the list of matches between training dates, which are given in the different hrf records. HTCalendar is only used to map the date to the HT week.

**Comment by akasolace** [comment]
>training manager examines the list of matches between training dates, which are given in the different hrf records. HTCalendar is only used to map the date to the HT week.

ok and how does training manager knows the training dates? it relies on worlddetails ? If that is the case what happenes if a user forget to download some data?  Won't it be more robust to have the training dates calculated by HO! ? We would not even need the training recalculation functionality ....

**Comment by akasolace** [comment]
To summarize:

    - worldetails.xml always gives dates in Swedish time
   - Training tab implies local HT week and local HTSeason 

    - matchdetails alreday display time in local time, using time lag preference set per user (ideally it could be done automatically using computer local but not too bad as it is now)
     - training tab relies on HT week and HT Season to do some display:  at the moment HO only know global HTWeek and HTSeason, this would lead to incorrect display. For exampl in Brazil first league match is on Monday, hence it is already Global Week 2 but it is still Brazil week 1, possible fix:
            1) ignore season info from worlddetails and  introduce in HTCalendar localHTWeek and localHTSeason, this would need to be done base on the league level, not on the location where the user leaves (case of a German user having his second team in  Brazil: he needs to see match time in German time but HTWeek and HTSeason according to Brazilian Calendar. This one can be tricky, because for country like 
            2) relies on leaguefixtures, to determine to which season/round a given match belong ....

**Comment by wsbrenk** [comment]
classes are removed

functions are replaced by HTDatetime
