### ISSUE TITLE
[FEATURE]  leagueOffset need to be store in database

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#679]
- [ ] leagueOffset need to be store in database (XTRADATA) It needs to be retrieved only once from worlddetails.xml
might be part of misc.basics information, it will be accessed from HTCalendar

 - [ ] similarly at that time an offset for economy, match and training data need to be calculated

Training Date is used for Training Manager, @wsbrenk is matchdate also used or do you get that info somewhere else?
Similarly I am not sure that at the moment economydate is used but it would be useful when #530 is implemented (would trigger I imagine delta in finance .....)
 
		columns[4]= new ColumnDescriptor( "SeriesMatchDate",	Types.TIMESTAMP,false );
		columns[5]= new ColumnDescriptor( "TrainingDate",		Types.TIMESTAMP,false );
		columns[6]= new ColumnDescriptor( "EconomyDate",		Types.TIMESTAMP,false );

**Comment by wsbrenk** [comment]
download of SeasonOffset from worldetails is done: same procedure as for Season (Saison). this info is in the BASICS part now:

[basics]
application=HO
appversion=0.0
date=2020-09-13 14:51:48
season=75
seasonOffset=0
matchround=16
teamID=520472
teamName=Juventus Brenk
activationDate=2004-09-25 02:57:00
owner=wsbrenk
ownerHomepage=
countryID=3
leagueID=3
regionID=238
hasSupporter=True

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/93018702-e8bea680-f5d1-11ea-8b4a-935e5042127c.png)

**Comment by wsbrenk** [comment]
`    /*
    alternative to getHTSeasonCorrection based on worlddetails info SeasonOffset
    (not used up to now)
     */
    private static int getSeasonOffset(){
    	return HOVerwaltung.instance().getModel().getBasics().getSeasonOffset();
	}
`

**Comment by akasolace** [comment]
@wsbrenk this is something you recently added ?

**Comment by wsbrenk** [comment]
@akasolace yes, with the first item of this issue i'm just ready and i will push it soon. with the second one i'm still struggling. i could easily produce a static method that would examine the time difference of those dates to monday 0 AM. but i don't see any use of it!?!

- if those dates would change in the future, any calculation of those dates will be wrong
- estimations of future economy or trainings date could easily be done by adding weeks to the current date from xtra_data
