### ISSUE TITLE
[BUG] edit group column of player overview 

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#681]
select a line in player overview with group colored.
the group box in player detail view is colored as the overview line

now select a line in player overview with NO colored group
the group box in player detail view is still colored like the last selection. That is a bug!

you are not able to select the same color for the selected line. That is a bug, too!

Another point: i'm not really happy, that there are no longer the group names (A..F). These names indicated a order of those groups, i'm not fit in ordering these groups only by their color.

**Comment by akasolace** [comment]
> Another point: i'm not really happy, that there are no longer the group names (A..F). These names indicated a order of those groups, i'm not fit in ordering these groups only by their color.

I also liked the team name

**Comment by tychobrailleur** [comment]
I'll look into these when I get some time!

**Comment by tychobrailleur** [comment]
I can't reproduce what you are describing:
![2020-09-05 11-29](https://user-images.githubusercontent.com/114285/92303287-5849eb80-ef6b-11ea-9ef4-0d08e86529e4.gif)

But maybe I misunderstood: are you saying that in the "Squad" dropdown, the colour of the group doesn't reflect the one of the player that is selected?  Or is it something else?

As far as I am aware only the icons were changed, not the logic, so I am intrigued.

**Comment by wsbrenk** [comment]
@tychobrailleur i can reproduce your film only with one of my players, who has NO group selected. Could it be that this player is the only one, which i select for no group. the others with whom it does not work, the selection stays with the group of the previous selected player, could be those who were never selected for any group.

**Comment by wsbrenk** [comment]
@tychobrailleur players showing the decribed problem have the "smilie" F-Team,png, which is no longer found in JComboBox.setSelectedItem.

**Comment by tychobrailleur** [comment]
> here you see my spielernotiz table. could it be, that the .png infos are causing the problem?

Ah, very likely, thanks for that, I'll investigate that!

I have finally settled on an approach for those icons, and it seems to work ok so far (still need to work on better contrast):

![Screenshot from 2020-09-12 13-14-33](https://user-images.githubusercontent.com/114285/92995263-f30d7180-f4f9-11ea-871b-18705db66fdf.png)

Still some cleanup to be done there, but at least I have a path forward.

**Comment by tychobrailleur** [comment]
Can the issue be closed, @wsbrenk ?

**Comment by wsbrenk** [comment]
yes, i close it.
