### ISSUE TITLE
 follow up work on man marking support

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#682]
@wsbrenk I see you submitted your PR already so maybe the follow could be an open ticket for discussion for 5.0

> the position is the last played position? can you get this one directly from players.xml or do you have to parse a lot of files ?
you put age and experience, I don't think it impacts really the man marking effectiveness. I think what could be more useful, is indication of the specialty (green (Tech) and red (Unpred) similar color than for weather penalties/bonus) and maybe either a hoover message or a text somewhere giving info (-10% all skills, boost of 8% because technical, ......)

_Originally posted by @akasolace in https://github.com/akasolace/HO/issues/660#issuecomment-684802787_

**Comment by wsbrenk** [comment]
this is the line in combo box for opponent man marked players:

    @Override
    public String toString() {
        String buffer = getPosition(lastMatchPosition) +
                " " + name +
                ", age=" + age +
                ", experience=" + experience +
                ", form=" + form +
                ", rating=" + rating +
                ", status=" + status +
                ", motherClubBonus=" + motherClubBonus +
                ", loyalty=" + loyalty;
        return buffer;
    }

i have no (good) idea what of this and how that should be displayed in such short combo box line
there are further information available that could be of interest
- date of the last match
- rating at the end of that match
- minutes that were played in that match

**Comment by akasolace** [comment]
@wsbrenk is there still something you want to do with this ticket ?

**Comment by wsbrenk** [comment]
@akasolace not in this release i think. prio is lower than youth ticket.

and I still have the ambition to realize the graphical Drag&Drop feature, if i could get support on that  - in ui programming i'm still a bloody beginner.

**Comment by wsbrenk** [comment]
on this ticket and on my very first project concerning special event prediction, there is zero feedback from the community. this is a pity;-)

**Comment by akasolace** [comment]
I am wondering how many users are using the man marking orders. Since I play HT, I never used it and I only saw once one of my opponent use it against me ....

**Comment by akasolace** [comment]
>  this is a pity;-)

generally I think it is fun to develop HO! this is why I am doing it .... if it was for recognition I would have stopped a while ago :-)

**Comment by wsbrenk** [comment]
I agree with you in principle, and I have to say that the feedback from the HO community is much more euphoric and enthusiastic than that in the real profession, where i invest a lot more effort. i agree with you, it is all about the fun, but the difference is always remarkable.

concerning non feedback to special events - it was a joke.

**Comment by wsbrenk** [comment]
rules of man marking: https://www86.hattrick.org/Forum/Read.aspx?t=17345145&n=83&v=4&mr=0

**Comment by wsbrenk** [comment]
effect on own ratings could be displayed in lineup panel (ratings)
in simulator panel the user could toggle the options if man marked opponent player
* is in opposite/optimal section 50% loss
* is not in opposite/optimal section 65 % loss
* is not in lineup 10% loss

effect on opponents ratings could be displayed in team analyzer.
difficulties:
* estimate man marked top skill value

**Comment by akasolace** [comment]
I think it is too random event to worth modelizting it ....

**Comment by wsbrenk** [comment]
this is remaining:

effect on opponents ratings could be displayed in team analyzer panel,
difficulties:

estimate man marked player's top skill value
