### ISSUE TITLE
[BUG] empty lineup

### ISSUE THREAD

**Issue by aristodemos2008** [akasolace/HO#689]
**Describe the bug**
When I clear lineup it results in an java nullpointerexception

**To Reproduce**
1. Go to Lineup
2. Click on clear lineup

**Screenshots**
[https://www.screencast.com/t/LWo4mz7TMV](https://www.screencast.com/t/LWo4mz7TMV)

**Platform information:**
 - OS: Windows
 - Version 3.0

**Comment by wsbrenk** [comment]
same as #573

**Comment by akasolace** [comment]
@aristodemos2008 can you please check wheter or not you are still experiencing this bug with 4.0 development release ?

**Comment by aristodemos2008** [comment]
> 
> 
> @aristodemos2008 can you please check wheter or not you are still experiencing this bug with 4.0 development release ?

Loaded my DB in HO-4.0.0.3122. Bug seems to be solved.
