### ISSUE TITLE
HO icon missing on Mac

### ISSUE THREAD

**Issue by orgogliobauscia** [akasolace/HO#69]
After updating to 1.436.0.363 the HO icon disappeared.
<img width="124" alt="screenshot 2019-01-07 23 32 49" src="https://user-images.githubusercontent.com/45899362/50832211-cd57be80-134d-11e9-8350-d41a283df408.png">

**Comment by akasolace** [comment]
can someone confirm if the problem also exist for Linux and or Windows ?
