### ISSUE TITLE
[BUG] stopped working

### ISSUE THREAD

**Issue by jesuswasahovercraft** [akasolace/HO#690]
**Describe the bug**
 java.lang.NullPointerException

and then some lengthy gibberish

**To Reproduce**
Download HO!, latest 3.0 for Mac, unzip, start it, there you go

**Screenshots**
not available

**Platform information:**
 - OS: macOS
 - Version 10.15.6

**Additional context**
Anything about the Java version? Should I downgrade?

**Comment by tychobrailleur** [comment]
Hi @jesuswasahovercraft would you be able to send the lengthy gibberish, along with the Java version you use? (HO 3.x works on 1.8 only)

**Comment by akasolace** [comment]
@tychobrailleur I think this issue can be closed, it was a duplicate and @jesuswasahovercraft confirmed he fixed it on his side
