### ISSUE TITLE
[BUG] java.lang.NullPointerException

### ISSUE THREAD

**Issue by jesuswasahovercraft** [akasolace/HO#691]
**Describe the bug**
 java.lang.NullPointerException

and then some lengthy gibberish

**To Reproduce**
Download HO!, latest 3.0 for Mac, unzip, start it, there you go

**Screenshots**
not available

**Platform information:**
 - OS: macOS
 - Version 10.15.6

**Additional context**
Anything about the Java version? Should I downgrade?

**Comment by akasolace** [comment]
is HO 3.0 lauching at all? can you put a screenshot ? 
was it working before? which version were sou using? Have you modified your java install ?

**Comment by jesuswasahovercraft** [comment]
The error appears immediately after launching, at least there is the icon. It had been working before, just quit the job.

**Comment by jesuswasahovercraft** [comment]
Mate, I am sorry, I just removed all fragments on my Mac manually, it resumed working. Thank you and sorry for wasting your time.

**Comment by akasolace** [comment]
@jesuswasahovercraft  ok glad you manage to fix it. I close the issue then ...
