### ISSUE TITLE
[DOC] controle/complete release notes for 4.0 release

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#698]
If all of us can spend 5 minutes in reading/completing the release notes, I will then publish the first beta version.

**Comment by DavidatorusF** [comment]
https://ho.readthedocs.io/en/latest/installing_ho.html#latest-stable-version

replace last stable version link by latest release link, no ?
https://github.com/akasolace/HO/releases/tag/tag_stable

https://github.com/akasolace/HO/releases/latest

**Comment by DavidatorusF** [comment]
don't forget to write this https://ho.readthedocs.io/en/latest/installing_ho.html#latest-stable-version in the first step on the forum thread

**Comment by akasolace** [comment]
> https://ho.readthedocs.io/en/latest/installing_ho.html#latest-stable-version
> 
> replace last stable version link by latest release link, no ?
> https://github.com/akasolace/HO/releases/tag/tag_stable
> 
> https://github.com/akasolace/HO/releases/latest

good catch ... .just did it ...

**Comment by wsbrenk** [comment]
in chapter Rating is a [BUG], all other bugs are marked as [FIX]

**Comment by tychobrailleur** [comment]
Other than the snag @wsbrenk it looks good to me.
The new icons for jerseys and groups, is it worth calling out separately?

**Comment by akasolace** [comment]
@wsbrenk @tychobrailleur ok thank you !
