### ISSUE TITLE
Regarding Numbers & Tshirts rows looks bad

### ISSUE THREAD

**Issue by adrimorales1** [akasolace/HO#7]
I joined a photo with te bug

![image](https://user-images.githubusercontent.com/44621053/47746349-36ec8a00-dc86-11e8-985b-0b40e99bbba0.png)

**Comment by mistermax80** [comment]
I'm tring to resolve, I work on mac, and I retrieve the same beavihur.

**Comment by akasolace** [comment]
ok cool, so I remove the invalid tag.

**Comment by mistermax80** [comment]
I think a java bug... antialiasing doesn't work on macos.
The code point is row 462, file ImageUtilities.java
`g2d.setFont(new java.awt.Font("sansserif", java.awt.Font.BOLD, 10));`

**Comment by akasolace** [comment]
is it only in that tab that the police renders badly?  if yes, is it not possible to use a different font?

**Comment by akasolace** [comment]
closed by #30
