### ISSUE TITLE
[Error Obtaining URL]

### ISSUE THREAD

**Issue by Lebron519** [akasolace/HO#701]
Opening the Hattrick Organizer, there is a window that say "error obtaining URL". Error 503. How i can resolve?

**Comment by miloszatko** [comment]
HTTP Error 503 - Service unavailable.
Probably on Hattrick's side

**Comment by tychobrailleur** [comment]
It is possible, it looks like CHPP is experiencing issues:

![Screenshot from 2020-09-27 10-28-04](https://user-images.githubusercontent.com/114285/94361439-39430300-00ac-11eb-8938-f52f0f50a589.png)

**Comment by Lebron519** [comment]
Thank you guys!
