### ISSUE TITLE
Can not authorize CPHH

### ISSUE THREAD

**Issue by marcelomit** [akasolace/HO#703]
Hi,  I installed HO! from scratch on new hard disk.
When I open the program the URL box is empty.
What URL I have to fill there?  In the sample that appear in docs there are a URL with part covered by a black line (I suppose that is unique for user).  How I can know which URL I have to fill?  Or how can it be filled automictically?

Thanks

**Comment by lauko1** [comment]
> Hi, I installed HO! from scratch on new hard disk.
> When I open the program the URL box is empty.
> What URL I have to fill there? In the sample that appear in docs there are a URL with part covered by a black line (I suppose that is unique for user). How I can know which URL I have to fill? Or how can it be filled automictically?
> 
> Thanks

You're not alone, I've got the same issue :-/
I've already installed HO v3 and on my first installation, URL field was automatically filled.
It's not filled automatically anymore.

I've tried on HO v1.4 edition and I've got the same issue.

LauKo

**Comment by akasolace** [comment]
@marcelomit you are on windows?

**Comment by marcelomit** [comment]
Hi.  today it give me the URL and start works. I receive 2-3 errors during download but most of the program works.  I am in windows 10.

**Comment by akasolace** [comment]
@marcelomit fyi, since Friday, there has been a lot of CHPP errors reported on hattrick website .... tht could be the cause.
If you have other issues, please open ticket on github ...
cheers
