### ISSUE TITLE
[BUG] Release Channel not stored in userconfig table

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#705]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by akasolace** [comment]
it is actually not fixed

![bug705](https://user-images.githubusercontent.com/1136496/94850954-fd030000-0427-11eb-9660-dfd457d37122.gif)

**Comment by wsbrenk** [comment]
OK, i thought it would be an update issue
