### ISSUE TITLE
[BUG] database administration dialog can not change team name and DB name

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#706]
i'm trying to install the beta:

- open database admin
- select edit or add entry
- change team name or db name
- save
- the old/standard values are displayed:

![image](https://user-images.githubusercontent.com/11821502/94720343-a5479480-0354-11eb-8f9e-7c39e0ddd0be.png)

**Comment by akasolace** [comment]
@wsbrenk Should we keep only one column out of the 2 Team Name / DB name ?  They are quite redundant .... what do you think ?

**Comment by wsbrenk** [comment]
@akasolace if the restrictions to team and database names are identical (encodings, spaces) on all platforms, it would be a good idea to put them together.

**Comment by akasolace** [comment]
yes in doubt I wont touch that ...
