### ISSUE TITLE
[BUG] cannot start multiple instances of HO4 exe

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#707]
i used to start 3 instances of HO concurrently, one for each team i have. HO4 can only start single.

i start it by windows start menu.

**Comment by wsbrenk** [comment]
i think this is a feature of install4j, i don't want to have:

Configure Executable
[x]Allow only a single instance running

should be unmarked

**Comment by akasolace** [comment]
@wsbrenk I upgraded to r3260 and I can now start 2 instances at the same time.

**Comment by wsbrenk** [comment]
👍
