### ISSUE TITLE
[FEATURE] add new leagues:  Myanmar, Zambia, San Marino, Puerto Rico and Haiti 

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#713]
#710 fixes a npe, if a HT country is not in HO table HT_WORLDDETAILS. this can happen, when Hattrick introduces new countries.

with the fix HO starts and does not show the flag of those countries.

- we should add the new HT countries
- eventually we should add a feature, that users could add new country information by their own. It could happen again, that hattrick adds new countries.

**Comment by akasolace** [comment]
> we should add the new HT countries
+1

> eventually we should add a feature, that users could add new country information by their own. It could happen again, that hattrick adds new countries.

not sure if it worth the efforts now as I think this time HT has added almost every single country
