### ISSUE TITLE
[BUG] HO4 does not show/calculate skillups in set pieces when training is shooting

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#714]
HO4 shows this
![image](https://user-images.githubusercontent.com/11821502/95012678-ce10a800-063a-11eb-9f93-42d89c58d304.png)

HO3
![image](https://user-images.githubusercontent.com/11821502/95012690-f3051b00-063a-11eb-93fd-656bc1110a88.png)

**Comment by akasolace** [comment]
@wsbrenk you have any idea what caused this ?
