### ISSUE TITLE
[BUG] Data new competition not available

### ISSUE THREAD

**Issue by terwaan** [akasolace/HO#715]
As of this season, I only get the data for my cup-games.
As you can see, my competition is blank. So
![HO_20201004](https://user-images.githubusercontent.com/5090206/95017114-9c5a0a00-0657-11eb-8ec1-7ad488176f3e.png)
 these data seem not to have been downloaded

**Comment by akasolace** [comment]
@terwaan which version of HO are you using ?

**Comment by terwaan** [comment]
H.O. 3.000. How can I make a zio
[strandvoetbal_20201005.zip](https://github.com/akasolace/HO/files/5325717/strandvoetbal_20201005.zip)

**Comment by akasolace** [comment]
@terwaan I am not sure of what you shared. I am expecting your db/ folder as a whole compressed as a .zip as well as your file user.xml.  
Cheers

**Comment by wsbrenk** [comment]
@terwaan did you change your league this season. @akasolace maybe it is linked to #391

**Comment by wsbrenk** [comment]
Info per Hattrick-Mail:
Hello Wsbrenk,

Thanks for asking.
It turned out that both the previous and the current season. When I deleted the league of last season and reloaded the current season, the problem was fixed.

Greetz

Terwaan

**Comment by wsbrenk** [comment]
i will have a look, why both leagues were saved again.

**Comment by wsbrenk** [comment]
@akasolace i think we can close this ticket. the user was able to fix his problem. 
and i don't have any idea why a wrong league was stored in his database.

**Comment by akasolace** [comment]
ok perfect
thank you

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/97080824-91631b80-15fe-11eb-8d5a-3d3ab3b9c1fd.png)

sql join shows that the LeagueLevelUnitID can change in week 16 of a season. No fixtures should be loaded in such situations.
