### ISSUE TITLE
[BUG] Registration of HO installation in  windows "Apps&features"

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#724]
I ran the HO installation multiple times and updated the last one once. The result in Apps&Feature is this:

![image](https://user-images.githubusercontent.com/11821502/96165492-fb076980-0f1c-11eb-8392-cd2cfdd08a9f.png)

I would have expected a single entry.

maybe we have to remove the version information?!

**Comment by akasolace** [comment]
normally it should detect previous installation .... me I can't reproduce ... I only have one entry and I did execute the installer maybe hundred time when I was debugging it ...

**Comment by wsbrenk** [comment]
@akasolace update to 3260 overrides the last entry. So is the issue a relict of former versions.

**Comment by akasolace** [comment]
ok perfect
