### ISSUE TITLE
[BUG] No DB creation for HO 4.0

### ISSUE THREAD

**Issue by KlausAH-Hattrick** [akasolace/HO#727]
I have downloaded and installed "HOSetup-4.0.1.3260-BETA-JRE.exe".
When opening, I do get an error **"Could not create database folder"**
Installation went through for me, I have as well latest Java (on Win8.1Pro).
When searching the folder %appdata%HO it says Windows cannot find it.
HO is installed undr Program Files, has 3 directories which are:
.install4j        jre       prediction
(I'm logged on as Administrator, installed HO as Administrator, and tried to run HO shortcut as Administrator too)

Whatdo I have to do in order to create the database folders, and how do I get my database from previous installation into this new version ?
TQ
KlausAH-Hattrick
klaus.pj@gmail.com

**Comment by wsbrenk** [comment]
@akasolace isn't [this](https://www87.hattrick.org/Forum/Read.aspx?t=17366506&v=0&a=1&n=23) a workaround of this issue?

**Comment by KlausAH-Hattrick** [comment]
[HO-2020-10-18.log](https://github.com/akasolace/HO/files/5397682/HO-2020-10-18.log)
Error messages when downloading ...

**Comment by akasolace** [comment]
@wsbrenk I think this is only for Windows user, using adminstrator accounts.
I guess in that case HO! has no writting rights to %appdata%. If it is the case maybe I can force elevtion rights from installer. Otherwise, we need to put that additional information in the documentation.

**Comment by wsbrenk** [comment]
@akasolace i do not have an idea concerning this. but i wonder that administrator should not be able to create a folder in roaming.
interactivly there was no problem to create it.

**Comment by akasolace** [comment]
@KlausAH-Hattrick I tried to reproduce but I can't. 
You are using an account with admin rights. HO can't create the HO in appdata but you can create it manually and after that HO is working fine, is that correct? To create the HO directory, where you prompted for some password or could you simply do it via the explorer ?

**Comment by akasolace** [comment]
@wsbrenk could you reproduce this bug? I mean if you delete HO folder is it recr

> [HO-2020-10-18.log](https://github.com/akasolace/HO/files/5397682/HO-2020-10-18.log)
> Error messages when downloading ...

@KlausAH-Hattrick  If you still experience that issue, can you create a separated ticket for this one. And please include a copy of your db in the github ticket. Thank you

**Comment by wsbrenk** [comment]
1. renamed %APPDATA%/HO to HO4
2. run installation HOSetup-4.0.1.3260-BETA.exe
3. started HO from start menu

=>

![image](https://user-images.githubusercontent.com/11821502/96488664-9f035480-123e-11eb-81ee-bf8c2324f1e6.png)

no new folder %APPDATA%/HO is created

**Comment by wsbrenk** [comment]
i have no idea concerning the connection errors in @KlausAH-Hattrick  logs

**Comment by Caner26** [comment]
> 
> 
> @KlausAH-Hattrick I tried to reproduce but I can't.
> You are using an account with admin rights. HO can't create the HO in appdata but you can create it manually and after that HO is working fine, is that correct? To create the HO directory, where you prompted for some password or could you simply do it via the explorer ?

This is correct. I had the same error ad the original poster. But after manually creating the HO dir in %Appdata% All went well

**Comment by akasolace** [comment]
@KlausAH-Hattrick @Caner26 I think I fixed the issue please check with new BETA version 4.0.1.3261   Thank you for reporting the bug and providing information

**Comment by KlausAH-Hattrick** [comment]
The database was ok with manual adding folder in %appdata%.
Now two more problems cropped up (after changing to Beta r3266).
While attempting download for main team:
![HO-P1](https://user-images.githubusercontent.com/73033385/96500976-fa8a0e00-124f-11eb-83ed-4ac0c12d2203.jpg)
While attempting download for 2nd team:
![HO-P2](https://user-images.githubusercontent.com/73033385/96500997-007fef00-1250-11eb-8bed-d3036e933c7b.jpg)
