### ISSUE TITLE
fix update routine and update message

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#73]
- For a user on stable channel ... update only check for new stable .. message should be new stable version available   => this case should be properly managed

- For a user on betachannel ... I think it is currently broken
    it should look for latest beta and latest stable
   if beta is newer => message should be new beta version available 
   else => msg shoud be something like "Latest available version is a stable version:... "

- For a user on dev channel ... I think it is currently broken
    it should look for latest DEV, latest beta and latest stable
   if dev is newer => message should be new dev version available 
   if beta is newer => message should be "Latest available version is a BETA version:... "
   else =>  msg shoud be something like "Latest available version is a stable version:... "

Looking forward to hearing your feedback

**Comment by brokenelevator** [comment]
@akasolace I agree

**Comment by akasolace** [comment]
@brokenelevator  ok thank you for the feedback I will do this this weekend

**Comment by mistermax80** [comment]
@akasolace, Yes I think this is the correct update version management.

**Comment by yaute74** [comment]
@akasolace ok for me

**Comment by yaute74** [comment]
@akasolace I say ok but I have a stupid question.

>For a user on betachannel ... I think it is currently broken
>it should look for latest beta and latest stable
>if beta is newer => message should be new beta version available
>else => msg shoud be something like "Latest available version is a stable version:... "
>
>For a user on dev channel ... I think it is currently broken
>it should look for latest DEV, latest beta and latest stable
>if dev is newer => message should be new dev version available
>if beta is newer => message should be "Latest available version is a BETA version:... "
>else => msg shoud be something like "Latest available version is a stable version:... "

Dev version will be always greater than Beta version and Beta version will be always greater than Stable version.
So why check other channels ?

**Comment by akasolace** [comment]
> Dev version will be always greater than Beta version and Beta version will be always greater than Stable version. So why check other channels ?

@yaute74    Not necessarly, for example when 1.436 will be out, stable will have the highest build until we build a new development version.

**Comment by mistermax80** [comment]
Hi guys, I'm thinking on this.
Possibile situation:
There will be a stable version with an bug that we have to resolve before of the release the next release.
How we will do? We will do a branch from stable version and release without passing in dev and beta?

**Comment by brokenelevator** [comment]
@mistermax80 It is not like we have to follow that to the letter. If the bug will not require much testing we can just release new stable. Maybe even should because people will move to most recent stable and if it has a bug it may not be wise to leave it there. We would have to scrape this stable.
Otherwise we could just release new beta, skipping dev. We are the devs, it is our call. We can and should do what (we think) is best for the user.

**Comment by yaute74** [comment]
I do the modification.
I don't add message because the channel is already display in the version.

Potentially there is there may be a problem:
- user is on beta channel
- stable version is greater than beta version
=> user switch to stable version
=> if beta version become greater than stable, user will stay on table

**Comment by akasolace** [comment]
> I do the modification.
> I don't add message because the channel is already display in the version.

You mean no message in release note ?  If that yess thre is no need

> Potentially there is there may be a problem:
> 
> * user is on beta channel
> * stable version is greater than beta version
>   => user switch to stable version
>   => if beta version become greater than stable, user will stay on table

No there will be no problem. The release channel of the user remains the same.
So if he got DEV selected as release channel.  When stable got release, the check version inform him that latest version is a stable vesion and offer him to upgrade.
After that if a dev is published, the check update will offer him to update to DEV.

Now for someone in STABLE channel,
if he is in 1.435 when 1.436 get released he will be offered to upgrade, and next time this will happen it is only when next stable version is released.

@yaute74   Doest it make sense or do you want to discuss this further before you code ?

**Comment by mistermax80** [comment]
Hi if we release an new stable version for fix a important bug without passing by beta or Dev, what can it the number version?
I think if the stable is more greater Dev, the Dev user will receive the stable update... And lost the new Dev functionality...
I don't know if I am clear...

**Comment by akasolace** [comment]
> Hi if we release an new stable version for fix a important bug without passing by beta or Dev, what can it the number version?

Next versions will be 2.0 3.0 ....
In case a bug in 2.0 need to be patched we will release 2.1  (we might have dev or beta in between depending o how easy is the bug to fix)

> I think if the stable is more greater Dev, the Dev user will receive the stable update... And lost the new Dev functionality...

In case we are working on 3.0 DEV but a serious bug force us to relase 2.1,  we create a branch out of 2.0, we fix the bug, we port it to master and we release, so bug will be fixed in both DEV and 2.1 stable

users how is in Stable channel  will go 2.0 -> 2.1  ->3.0
users in DEV channel will go  2.0 -> DEV -> DEV  -> DEV(hotix) -> 3.0

> I don't know if I am clear...

Hope it is clearer now

**Comment by mistermax80** [comment]
Now It is clear... Sorry but I thought there was something that lose... But It's not...
Thanks for explaining.

**Comment by akasolace** [comment]
The alternative would be that when we build DEV we release DEV only
When we build BETA we release DEV and BETA
When we build stable we release all of them
DEV channel only look for DEV build and same goes for beta and stable channel

pro: no error possible
cons; a beta user or a dev user, might use a stable build at some point without knowing it

I am fine with both approach. So maybe we can vote on this one except if @yaute74 already coded a lot

**Comment by yaute74** [comment]
>I am fine with both approach. So maybe we can vote on this one except if @yaute74 already coded a lot

@akasolace I already do the modification but I can go back. Personally I prefer the second approach because it's more easier and clearer for the user. He choose beta, he stay in beta version.

>you mean not include is a BETA because the release name already says that? 

@brokenelevator yes. I can add a message if we keep the modification

**Comment by akasolace** [comment]
ok so let's vote:

Approach 1: brokenelevator
Approach 2: yaute74

I am personally neutral maybe with just a small preference to Approach 2 after thinking again about it. With approach 1 we have risk of breaking things if not careful (i.e user from DEV going back to stable) , this cant happen with approach 2.

@mistermax80 ,  @DavidatorusF   what do you think ?

**Comment by yaute74** [comment]
> hummm it is possible to use icon according to the version used ?

It's nice idea. 

Could we also think about modernizing the logo?

**Comment by akasolace** [comment]
looks like vast majority prefer option 2, I am also for logo per version.
It could actually be logo + splashscreen + headerbar
We could have a more modern logo but I have absolutely no designer skill.... either one of you is up for it or we can maybe ask on HT forum ...

**Comment by DavidatorusF** [comment]
I'm not designer, I just play a little with gimp

**Comment by akasolace** [comment]
playing around 2 minutes on the web:
![image](https://user-images.githubusercontent.com/1136496/51183910-03a7b780-18d3-11e9-94f2-bcfed0626ee0.png)

**Comment by yaute74** [comment]
I am familiar with graphic tools (inkscape, gimp), but the the difficult thing is to have a good idea!

**Comment by akasolace** [comment]
@yaute74 actually, this was for the spashscreen

**Comment by akasolace** [comment]
thank you @yaute74 !
shoud be closed by 9b0fb68fe2e60c7ac912bc2d02f5f88842c9bf00
in case we face error when we launch beta we will reopen the deal ticket

**Comment by akasolace** [comment]
@yaute74   btw, can you confirm you implemented 2nd approach, I did not check actually.

**Comment by akasolace** [comment]
> if it ain’t broken, don’t fix it

@brokenelevator I also like the moto but I am not sure it applies here. When will a logo got broken? Also for the record it is not my idea to have logo that differs for stable/beta/dev  but I really like it

**Comment by yaute74** [comment]
> @yaute74 btw, can you confirm you implemented 2nd approach, I did not check actually.

No actually it's the first  a5926bf

**Comment by akasolace** [comment]
@yaute74 @brokenelevator 
ok so in what you did we assume that a user on DEV channel will go DEV -> BETA -> STABLE -> DEV ...
whereas a user on BETA channel will go BETA -> STABLE -> BETA ...
and a user on STABLE channel will go STABLE -> STABLE -> STABLE ...
I am fine with that ... you can leave as it is,  lets releae 1.426 and we will see in the future if we have issue with that rolling process

**Comment by yaute74** [comment]
@akasolace 
ok but this the first Approach, no ?

**Comment by akasolace** [comment]
@yaute74 
yes but I am personally fine with both and I can tell the team is split on that topic as both approach have pro and cons. Si i suggest we leave it as it is now, and if needed we will reassess in the future.

**Comment by yaute74** [comment]
ok
