### ISSUE TITLE
[BUG] flickering box in the table header

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#733]
[HO! - Hattrick Organizer 0.0 - Juventus Brenk - 14.0.1 2020-09-12 19-19-26 (2).zip](https://github.com/akasolace/HO/files/5397921/HO.-.Hattrick.Organizer.0.0.-.Juventus.Brenk.-.14.0.1.2020-09-12.19-19-26.2.zip)

in the meantime i dispair at that problem. 

what i found out:

- it looks like a mouse enter and mouse leave handler. the affected components are the header of the Tabbed panel.
- it only happens if the player overview table is viewable in Player overview panel or lineup panel (other panels are not affected).
- it disappears if the size of the HO main window is reduced
- PlayerOverviewTable and SpielerUebersichtNamenTable (part of lineup panel) have the TableSorter object in common.

**Comment by akasolace** [comment]
@wsbrenk I think this only happen with Nimbus, right ?

**Comment by akasolace** [comment]
Should we not focus on Darklag them going forward. Honestly I am not sure we have the ressources to support 2 differents L&F ...

**Comment by wsbrenk** [comment]
you are right, i'm on nimbus!

but i tried dark theme too and i think the issue is there too, but a lot more faster (the delay of box disappear is a lot shorter).

to be honest: i'm not a friend of dark themes - it is not so friendly for my old eyes.

**Comment by wsbrenk** [comment]
again tried to verify it with darcula. Same issue as above, but not on mouse enter and leave, but mouse click in the header of HOTabbedPane

**Comment by akasolace** [comment]
I am also no fan of dark theme but darklaf solarized is "fairly" close to nimbus look and feel, don't you think ?
My point is that it will be really simpler if we could support only darklaf going forward. If the bug exist on darklf we could ask the creator of darklf he has been very reponsive and helpful in the past.

**Comment by wsbrenk** [comment]
a OK - i will test solarized, thought that darklaf is same as darcula.

since i observe that kind of flickering in both themes (with little variations), i think that it is not caused by the theme, but on something that is common in player overview tables in the first two panes.

**Comment by wsbrenk** [comment]
solarized-light could be an alternative. Concerning this
- why are the decimals of the skills in the player overview below the number - looks strange

- if i resize a table header of those skill columns the flickering of menu and Name header happens

**Comment by Synthespian** [comment]
I think it's a java issue.
I've got a similar "duplication of layers" with a mouseover with this and another application, so not something specific to HO.
Have dual screen setup.

Will grab a screenshot next time.

**Comment by akasolace** [comment]
ah ok good to know, thank you @Synthespian

**Comment by wsbrenk** [comment]
checked with openjdk15 and adopt-openjdk15. every time the same issue. i would be surprised if this is due to java.

**Comment by wsbrenk** [comment]
some citations from web, i found:

"... I accidently put the Display.update() call in my game loop instead of the render loop so it was called too often."

**Comment by Synthespian** [comment]
![image](https://user-images.githubusercontent.com/48737160/99807492-7faa6080-2b37-11eb-90f1-2ae37e9c0c2c.png)
visualisation of my dual-screen java overlap

**Comment by wsbrenk** [comment]
@akasolace in HO V5.0 i don't observe this anymore. Your gui refactoring seems to repair it.
