### ISSUE TITLE
[BUG] Player Info Icon in Squad column not visible

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#736]
Player info Icons in Squad column are completly white in skins

When I use skins
Nimbus
Darcula 
Solarized
Solarized white

The Player info Icons are just white blocks in column "Squad" and in the Player Information Pull Down Menu.

**Screenshots**
https://ibb.co/bvB0bzb
HO40r3266 skin solarized 2020-10-19 2138.jpg

Old Version to compare:
https://ibb.co/NW0d3f5
HO30 skin nimbus 2020-10-19 2159.jpg

**Platform information:**
 - OS: Windows 10 Pro 64-bit Version 2004 Build 19041.572
 - Version HO! 4.0 r3266 
**Additional context**
Is it possible for users to change colors in skins? I like to change background colour of Squad letters as well, "F" is way to bright!

**Comment by akasolace** [comment]
@tychobrailleur is it something you could look at?

**Comment by tychobrailleur** [comment]
> @tychobrailleur is it something you could look at?

It'll probably be tail end of the week before I can, but no problem!

**Comment by akasolace** [comment]
@tychobrailleur actually I did it. If you could just look at the PR ....

**Comment by tychobrailleur** [comment]
> @tychobrailleur actually I did it. If you could just look at the PR ....

Sure, let me do that before *not listening* to the Rennes match. ;-)
