### ISSUE TITLE
[BUG] HO 3.0 Missing next Cup opponent in the Lookup of TeamAnalyzer tab

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#738]
**Describe the bug**
My next CUP match is visible within the "Matches" tab but it isn´t visible in the lookup within the "TeamAnalyzer" tab.

**To Reproduce**
1. Go to tab 'Matches'
2. See my todays Cup Match at "1:FC Colonia"
3. Go to tab "TeamAnalyzer"
4. Open Lookup of teams
5. see error: team "1:FC Colonia" is not available

**Screenshots**

![HO_30_matches](https://user-images.githubusercontent.com/67096604/96564582-a1f45880-12c3-11eb-99ba-d66273c4b185.jpg)

![HO_30_TeamAnalyzer](https://user-images.githubusercontent.com/67096604/96564586-a28cef00-12c3-11eb-9f7f-596fc1b9fd7a.jpg)

**Platform information:**
 - OS: [Windows 10 pro (10.0.19041 Build 19041)]
 - Version HO_3.0.2.2728

**Comment by akasolace** [comment]
@johari75 this was fixed in 4.0 so I close this issue
