### ISSUE TITLE
[BUG] Loading a saved lineup does not synchronize with TeamAnalyzer

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#739]
**Describe the bug**
I installed HO-4.0.1.3266-portable-win-BETA-JRE and followed your instruction to copy the db-files from HO 3.0 to HO 4.0.
Today I have a CUP match. Therefore I wanted to use the TeamAnalyzer to get the best lineup. But no changes in the LineUp are usable in TeamAnalyzer. I can only test the Actual LineUp which is saved on hattrick.org.

**To Reproduce**
1. Go to "LineUp" 
2. change any player
3. go to "TeamAnalyzer"
4. choose the Cup opponent
5. mark flag for Cup Games
6. press button "Update"
7. press button "Analyze"
8. see error: own LineUp didn´t change

**Screenshots**
![HO_40_Actual LineUp](https://user-images.githubusercontent.com/67096604/96568901-c272e180-12c8-11eb-9bcd-cf907c65667a.JPG)

![HO_40_Changed_LineUp](https://user-images.githubusercontent.com/67096604/96568337-2052f980-12c8-11eb-9d08-fa289183bc70.JPG)

![HO_40_TeamAnalyzer](https://user-images.githubusercontent.com/67096604/96568343-20eb9000-12c8-11eb-8bd4-1a0274c9cefd.JPG)

**Platform information:**
 - OS: [Windows 10 pro (10.0.19041 Build 19041)]
 - Version HO-4.0.1.3266-portable-win-BETA-JRE

**Additional context**
My assumption is a problem with the doble dot in the team name of my opponent.

**Comment by akasolace** [comment]
@johari75 to make the update you need to click on Analyze

**Comment by johari75** [comment]
@akasolace yes, I know and I did. But nothing changed.

**Comment by akasolace** [comment]
then do you have this bug only with that specific team ?

**Comment by johari75** [comment]
no, i tried it a few seconds ago with my next League opponent (which isn´t marked in a different colour as in the past).
Same result.

**Comment by johari75** [comment]
@akasolace there is a strange behaviour
after a restart of HO 4.0 I changed 1 player in the lineup and turned to teamanalyzer. button analyze worked for that change.
afterwords I went back to LineUp and opened a saved lineup. Again to teamanalyzer, button analyze --> lineup not synchronized

**Comment by akasolace** [comment]
ah ok 
@johari75 if lineup changed manually (by changing a player) it works fine but if lineup changed by loading saved lineup, this is not detected by teamAnalyser, right ?

**Comment by akasolace** [comment]
I can confirm the bug

**Comment by johari75** [comment]
@akasolace in addition if you loaded a lineup manual lineup changes are ignored too

**Comment by wsbrenk** [comment]
found the error
