### ISSUE TITLE
[BUG] Unable to update beta version

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#742]
**Describe the bug**
Unable to use the in-application update from Help > Check for Updates

**To Reproduce**
1. Go to Help > Check for Updates
2. See result

**Screenshots**
![image](https://user-images.githubusercontent.com/48737160/96622026-4fd22800-1301-11eb-9134-c59ea22024db.png)

**Platform information:**
 - OS: Windows 10
 - Version 4.0 (3257 JRE - Portable NOT installed)

**Comment by akasolace** [comment]
With JRE, right ?

**Comment by akasolace** [comment]
@Synthespian I can't reproduce this. You still have the error ?

**Comment by akasolace** [comment]
@Synthespian can you share your db please ... I would like to see what is going on ...

**Comment by wsbrenk** [comment]
@akasolace until 3266 it worked for me - now i'm not able to update to 3276

changed to dev-channel

![image](https://user-images.githubusercontent.com/11821502/96929074-d893c400-14b9-11eb-80b6-e43902798368.png)

![image](https://user-images.githubusercontent.com/11821502/96929099-e5181c80-14b9-11eb-862d-8ef0874b4b59.png)

**Comment by akasolace** [comment]
you tried 3266 -> 3276 by changing release channel to "DEV"? 

you have an installed version, right ?

**Comment by wsbrenk** [comment]
yes - i started with HOSetup-4.0.1.3242-BETA.exe

two times the update of beta channel worked perfectly
updating the beta says, that latest version is installed
so i changed to the dev-channel and got the message shown above

**Comment by akasolace** [comment]
this is strange, I have to experience the issue myself to see what is going on and try to debug....

**Comment by Synthespian** [comment]
Sorry, wasn't getting notifications.
Yes, still getting error, 3257 with JRE (portable not installed)

Can share folder, but it's 550mb and three databases (want it all??)

**Comment by akasolace** [comment]
@Synthespian we will see if the error reproduce, but at the moment still quite a lot of tickets opened ...

**Comment by Synthespian** [comment]
No worries.
g-drive link sent privately.

**Comment by Synthespian** [comment]
Happy to stay on this version for now, otherwise can always create new portable version in another folder / over the top of this one.
Not sure of the easiest way. :)

**Comment by Synthespian** [comment]
No worries in switching to #777. 
Happy to test when ready (still shows as latest version today)
