### ISSUE TITLE
[BUG] misleading visual with darklaf

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#746]
With nimbus:
Editable and non-editable checkboxes are clearly distinguished

![image](https://user-images.githubusercontent.com/1136496/96965584-b11a1700-150c-11eb-9fad-602496cdb6d7.png)

![image](https://user-images.githubusercontent.com/1136496/96965609-baa37f00-150c-11eb-8d59-0fbcf7989116.png)

this is not the case with darklaf and this can be misleading:

editable => ok
![image](https://user-images.githubusercontent.com/1136496/96965720-e7579680-150c-11eb-9c53-33ea43ad8cf4.png)

non-editable => not ok
![image](https://user-images.githubusercontent.com/1136496/96965754-f9393980-150c-11eb-872d-8747b67db310.png)

**Comment by akasolace** [comment]
@weisJ do you also think the visual is confusing? Should I open a feature request for darklaf?

**Comment by weisJ** [comment]
No need for a feature request. I’m already working on it ;)

**Comment by weisJ** [comment]
Version 2.5.0 of darklaf should resolve this issue.

**Comment by akasolace** [comment]
awesome

**Comment by akasolace** [comment]
fixed by https://github.com/weisJ/darklaf/commit/1431f0e53a8f91439e9d2c1daf16042fabed7bf4

**Comment by akasolace** [comment]
@weisJ  just tested and with 2.5.0 nothing is displayed

![image](https://user-images.githubusercontent.com/1136496/97368607-97c9ef80-18ab-11eb-9f29-953ac8602a0d.png)

whereas nimbus

![image](https://user-images.githubusercontent.com/1136496/97368667-b4febe00-18ab-11eb-8b4a-9f831ff1a355.png)

**Comment by weisJ** [comment]
The icon is displayed but the wrong icon is used (If you look closely you'll see the icon in white). Fixed in darklaf 2.5.1 (could take a bit until it is available on maven central).

**Comment by akasolace** [comment]
@weisJ just check and 2.5.1 is already available on maven central, I will check tonight if this fix the issue. Thanks one more time for your reactivity! . Also, maybe you want to add HO! in the list of the project using darklaf  on your github page ?

**Comment by weisJ** [comment]
> [...] Also, maybe you want to add HO! in the list of the project using darklaf on your github page ?

Added!
