### ISSUE TITLE
[BUG] No Numbers for Skills in TeamAnalyzer

### ISSUE THREAD

**Issue by karlinonegool** [akasolace/HO#762]
**Describe the bug**
In the preferences you can chose if you want to have the numbers next to the skills (eg. passable (6), solid (7) etc.). Even if this option is active, it is not shown in the module "TeamAnalyzer".  

**To Reproduce**
1. Go to 'Preferences.'
2. Make sure 'Show numbers for skills : passable (6)' is active
3. Open 'TeamAnalyzer'
4. Click on "Update" and "Analyze"

**Platform information:**
 - OS: Windows
 - Version (including build number): 4.000 Beta (r3266)

**Comment by akasolace** [comment]
@karlinonegool actually, I just realized there are specific settings for this module. You need to go to 
Preference => Modules => Team Analyser (Options) => Select Numeric Ratings
