### ISSUE TITLE
[BUG] clicking on Matches TAB should never throws a connexion error

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#767]
One might want to launch HO even without internet connexion. In that case he would expect everything to work except downloading data.
Clicking on match tab breaks that behaviour and enter into never-ending broken loop:

Proposal: 
   - [ ] when clicking on match tab; if download error fails, it should exit loop silently,
   - [ ] match download should not be silent (information should be put in information tab)

@wsbrenk do you agree with that?

**Comment by wsbrenk** [comment]
Absolutely
