### ISSUE TITLE
Bad rendering of PlayersCB after upgrade of Darklaf 2.4 -> 2.5

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#771]
**Darklaf 2.4:**

![image](https://user-images.githubusercontent.com/1136496/97918709-d4d42d00-1d56-11eb-9980-73a7b60b71c9.png)

**Darklaf 2.5:**  -The bottom line is truncated 
![image](https://user-images.githubusercontent.com/1136496/97918784-f503ec00-1d56-11eb-89b3-21fabae6f73b.png)

**Comment by akasolace** [comment]
@weisJ any inputs would be very helpful...

**Comment by weisJ** [comment]
Could you guide me to the renderer used for the combobox?

**Comment by akasolace** [comment]
I guess it has something to https://github.com/weisJ/darklaf/commit/e1d0c3d9df95bafd374088209c69f0dfe9b4102f

**Comment by akasolace** [comment]
>Could you guide me to the renderer used for the combobox?

(https://github.com/akasolace/HO/blob/23d8b3299ba3a773550bc01963cacd54c0c6ff01/src/main/java/module/lineup/PlayerPositionPanel.java#L57)

 m_clEntry = new SpielerLabelEntry(null, null, 0f, true, true, true, " ", true);

then it calls the following with m_bMultiLine = true
https://github.com/akasolace/HO/blob/373bc26ee9692f714b9aa79cd36a9f85d3003370/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L147

**Comment by weisJ** [comment]
Could you please try to use the `latest.integration` version of darklaf? I wasn't able to reproduce the issue 100% but made some changes that may fix it.

**Comment by akasolace** [comment]
@weisJ just tried it .. still resolves to 2.5.1

**Comment by weisJ** [comment]
Have you added the snapshot repository?
````

repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}
````

**Comment by akasolace** [comment]
just realized that sorry ....

**Comment by akasolace** [comment]
@weisJ  It is better (the last line is now cropped just a bit) 

![image](https://user-images.githubusercontent.com/1136496/97997058-da7a5300-1de8-11eb-8e97-1d99fd67e0b6.png)

**Comment by weisJ** [comment]
https://github.com/akasolace/HO/blob/373bc26ee9692f714b9aa79cd36a9f85d3003370/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L254

Are you sure this reserves enough space for the cell renderer? Why is the value even hardcoded?

**Comment by akasolace** [comment]
strangely enough commenting this out does not change anything ....

**Comment by weisJ** [comment]
The line exists at multiple places e.g. here too
https://github.com/akasolace/HO/blob/373bc26ee9692f714b9aa79cd36a9f85d3003370/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L321

**Comment by akasolace** [comment]
Yes I think I remove them all but does not change anything so far ...
what seems different is that before (top image) the dropbox was steping on the border (clearly visible on element with blue border) but now it seems this has been fixed so it leaves less place to the rendering

**Comment by weisJ** [comment]
The problem is https://github.com/akasolace/HO/blob/373bc26ee9692f714b9aa79cd36a9f85d3003370/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L88
Making the font bold results in a larger component. The preferred size is calculated while the font isn't bold resulting in the smaller size. This wasn't visible with darklaf <=2.4.* because the insets use insets were barely large enough to cover the missing space.

Some other things I noticed while running HO locally.
- `releaseArtefacts` is set to `true` by default making it impossible to change the LaF.
- `preparingBuild` depends on `clean` making build slow. If a clean build is required each time something is changed then there is an underlying issue that needs to be solved. clean builds should be explicit.
- The HO frame isn't centered on the screen when launching (With the taskbar on the top the frame can't be moved).
- There are a lot of renderers which use a pattern similar to this:
   ````java
   comp.setBackground(HODefaultTableCellRenderer.SELECTION_BG)
   ````
   But those colours merely replicate the colour of the Laf. Why not make the component opaque instead.
- The new icons use `Label.foreground` as their colour. For darklaf based themes I would suggest to use `menuIconEnabled` instead. This colour
  - is guaranteed to be available with all themes (The same effectively applies for `Label.foreground` but it's still a rather internal value).
  -  was explicitly defined for the purpose for such icons.

**Comment by akasolace** [comment]
@weisJ   I will have a careful read ... thank you !

**Comment by akasolace** [comment]
> Making the font bold results in a larger component. The preferred size is calculated while the font isn't bold resulting in the smaller size. This wasn't visible with darklaf <=2.4.* because the used insets were barely large enough to cover the missing space.

I think this line does not apply to the comboBox but to the entries in the table below:

![image](https://user-images.githubusercontent.com/1136496/98083887-4ad1b480-1e7b-11eb-92af-982993779d1e.png)

**Comment by weisJ** [comment]
The font in fact doesn't affect the displayed value in the combobox. But it **does** apply to the values displayed in the popup, which makes for a weird rollover behaviour.
To be honest I wasn't able to reproduce the behaviour locally. But I didn't quite manage to replicate the exact icon setup, so there is that.

On a different note regarding
>  -  There are a lot of renderers which use a pattern similar to this:
    ````java
     comp.setBackground(HODefaultTableCellRenderer.SELECTION_BG)
    ````
> But those colours merely replicate the colour of the Laf. Why not make the component opaque instead.

If there are custom colours (background or foreground) used for renderers it is important that they aren't of type `ColorUIResource` (which is the case for all colours obtained from the `UIManager`) because otherwise they will be overwritten by the LaF or won't have the desired effect (i.e. not the whole combobox value area has the background of the renderer.

**Comment by akasolace** [comment]
> If there are custom colours (background or foreground) used for renderers it is important that they aren't of type ColorUIResource (which is the case for all colours obtained from the UIManager) because otherwise they will be overwritten by the LaF or won't have the desired effect (i.e. not the whole combobox value area has the background of the renderer.

Ok I will check that. Otherwise, I did not manage to have the checkbox properly rendered using darklaf. I played with all the parameters I could think of but nothing work. Everything work as expecting using Nimbus theme or darklaf < 2.5.0 .

> To be honest I wasn't able to reproduce the behaviour locally.

If you launched HO! I guess you did not had anything displayed. If you are interested to reproduce locally to debug darklaf I can provide you with a test db.

Otherwise regarding all your comments on the gradle file. I know it is highly unoptimized as I discovered gradle for this project but it does the job thought. Also I am runnning the script only when I want to create artefacts (when I do new release which is couple of times per year not more). The rest of the time I just run directly HO.main() via intelliJ without using gradle so I am not that impacted by the bad quality of the gradle script ....

**Comment by weisJ** [comment]
> > [...]
> Ok I will check that. Otherwise, I did not manage to have the checkbox properly rendered using darklaf. I played with all the parameters I could think of but nothing work. Everything work as expecting using Nimbus theme or darklaf < 2.5.0 .
> 

Could you please elaborate what you mean with that?

> > To be honest I wasn't able to reproduce the behaviour locally.
> 
> If you launched HO! I guess you did not had anything displayed. If you are interested to reproduce locally to debug darklaf I can provide you with a test db.
> 

That would be very helpful 👍🏻

**Comment by akasolace** [comment]
> Could you please elaborate what you mean with that?

with Nimbus:
![image](https://user-images.githubusercontent.com/1136496/98161147-8dc57380-1edf-11eb-9287-74a0bdfdaa14.png)

> That would be very helpful

you can download the db here:
https://wetransfer.com/downloads/505448aeaeacd6c0c1bb6223d4d0c2fb20201104195641/38ba6b8ceb10df6f962fada9b29222d320201104195641/09204d

**Comment by weisJ** [comment]
> > Could you please elaborate what you mean with that?
> 
> with Nimbus:
> [...]

Sorry I wasn't clear enough. I was referring to the following part:

>  Otherwise, I did not manage to have the checkbox properly rendered using darklaf.

> 
> > That would be very helpful
> 
> you can download the db here:
> https://wetransfer.com/downloads/505448aeaeacd6c0c1bb6223d4d0c2fb20201104195641/38ba6b8ceb10df6f962fada9b29222d320201104195641/09204d

Thank you I'll have another look.

**Comment by akasolace** [comment]
> Sorry I wasn't clear enough. I was referring to the following part:

I meant that with either Nimbus **or with a version of darklaf in the 2.4.x serie those combobox are properly displayed** (not truncated)

> Thank you I'll have another look.

Thank you ... let me know if I can help you in any ways !

**Comment by weisJ** [comment]
I just checked with the db and I encounter no issues with the `latest.integration` darklaf version. Could you please verify it also works for you?

**Comment by akasolace** [comment]
You made some changes since this morning, when I tried I had an improvement but was still slightly cropped.

https://github.com/akasolace/HO/issues/771#issuecomment-721147915

**Comment by akasolace** [comment]
@weisJ I think the db I sent you is using nimbus by default .... have you tried with a darklaf theme ?  File -> Preference - > Misc -> Skin

**Comment by weisJ** [comment]
I did use darklaf :D.  But the text isn't cropped for me... Have you checked that the actual latest snapshot is used. Either add
````kotlin
configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}
````
or run `gradlew --refresh-dependencies`

**Comment by akasolace** [comment]
I guess the snapshot changed in between. If I used the snapshot downloaded the 03/11 3.18 pm I got the screenshot I posted at the time (line still crop but much less) and no other visual changes.

I just refresh dependencies. A new snapshot of 2.5.2 was donwloded (different hash sum than the one on 03/11). This time:
   - no more cropping (problem solved) 
   - brownish background (not sure if this is a new bug in darklaf snapshot, or correction of a bug that highlight a bad coding in HO!  - nimbus looks ok)


**with latest.integration**
![image](https://user-images.githubusercontent.com/1136496/98218504-1e399d80-1f4c-11eb-997d-a189d649cb1b.png)


**with 2.5.1**
![image](https://user-images.githubusercontent.com/1136496/98219009-c2234900-1f4c-11eb-9e8c-751fc0c51c6d.png)

**Comment by weisJ** [comment]
Great!
The brownish background comes from a change in darklaf where the background of the combobox adapts to the background of the current cell renderer. So I guess the brown background comes from HO.

**Comment by akasolace** [comment]
> The brownish background comes from a change in darklaf where the background of the combobox adapts to the background of the current cell renderer. So I guess the brown background comes from HO.

![image](https://user-images.githubusercontent.com/1136496/98223254-27c60400-1f52-11eb-9c6e-61cc12969ea8.png)



Ok I see, indeed the background is set by HO! depending if the player is aligned or not. Until 2.5.2, this was only applied to the items in the list (but the selected item still had the theme background.  It might not have been very consistent but visually it is much nicer (by the way this is also the behaviour of Nimbus. )

![image](https://user-images.githubusercontent.com/1136496/98239847-e55bf180-1f68-11eb-87bc-0e4014de5021.png)

Do you think it would be possible to let the user choose the behaviour ?

**Comment by weisJ** [comment]
The renderer for the value in the combobox is requested using `#getListCellRendererComponent(..., value, -1, false, false)` i.e. `index` will be `-1`. Based on this the you could apply the colour or not.

**Comment by akasolace** [comment]
@weisJ  last question, when do you think 2.5.2 will be released ?

**Comment by weisJ** [comment]
Probably tomorrow or saturday.
