### ISSUE TITLE
[BUG]own team was removed from team analyzer's team combo box

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#774]
wettnetzer wrote per ht-mail:

 Is it intentional that the team analyzer has removed the possibility to analyze your own team? I've been using the HO for more than 10 years now and I've been using this option to see what the opponent sees when he analyzes my team. So I'd like if this would be possible again,..

**Comment by wsbrenk** [comment]
@yaute74 i found you was working at last on the mentioned combo box. Could you have a look if that could easily be resetted?

**Comment by akasolace** [comment]
@wsbrenk maybe you can have a quick look to confirm this is fixed by 2ee1a5f

**Comment by wsbrenk** [comment]
@akasolace It works. Minor change: Could you put the own team to the end of the list, since the most likely selection would be the next opponent team which is now no longer preselected.

**Comment by akasolace** [comment]
Arf I made in purpose to have it first as it was previously implemented. But if you think it is best to have it last I can do that.

**Comment by wsbrenk** [comment]
@akasolace i would really prefer it on last position - hopefully the (most) other users will see it the same way

**Comment by akasolace** [comment]
ok I will do that tomorrow
