### ISSUE TITLE
Feedback Plugin not working

### ISSUE THREAD

**Issue by emar9** [akasolace/HO#775]
I get an error message that says "The lineup in HO does not meet the requirements..." when I click on refresh.
I've checked all the points they are OK.

**To Reproduce**
1. Go to 'Lineup'
2. Click on 'Help to improve rating prediction' button on the right side where you see the rating prediction
3. Copy the ratings from the hattrick lineup page by clicking on the 'copy ratings to clipboard' button
4. Paste the clipboard content into the text field 2. Paste the prediction...  in HO
5. Click on 'Refresh' button
6. See the error

**Screenshots**
![image](https://user-images.githubusercontent.com/51410121/98461666-6526cd80-21ae-11eb-85e2-ba84af28cde9.png)

![image](https://user-images.githubusercontent.com/51410121/98461598-c39f7c00-21ad-11eb-9ca3-c87a24fa9898.png)

**Platform information:**
 - OS: Windows
 - Version: 1909, 18363.1082

**Additional context**

**Comment by emar9** [comment]
Sorry I was checking the manual and now I think know how to do it.
I recommend to improve the instruction on point 1.

**Comment by emar9** [comment]
Well, now I did it according the manual and I get following error:

![image](https://user-images.githubusercontent.com/51410121/98462201-a325f080-21b2-11eb-986f-67566a73590a.png)

**Comment by akasolace** [comment]
@emar9 yes feedback plugin is broken for the time being....

**Comment by akasolace** [comment]
linked to #583
