### ISSUE TITLE
[BUG] (Short) Passing not recognised in training update

### ISSUE THREAD

**Issue by Synthespian** [akasolace/HO#781]
**Describe the bug**
Have just had a week of "short passing" or "passing" in the new training regime.
On loading the team, there has been no update to the subskills, nor the training estimation.

**To Reproduce**
Train "passing"
Complete the week.
download data

**Screenshots**
![image](https://user-images.githubusercontent.com/48737160/99129240-e645f080-2604-11eb-9b4b-c617b5293f73.png)

**Platform information:**
 - OS: Windows 10
 - Version: 4 (3257) - waiting for update steps I can use on #777 / #742

**Additional context**
Probably impacts the other training regimes that have changed name

**Comment by akasolace** [comment]
@wsbrenk can you look at this one ?

> Version: 4 (3257) - waiting for update steps I can use on #777 / #742

@Synthespian those issue should be close from now on but as the version you were using has this bug, you will need to do a manual download this time again:-(

**Comment by wsbrenk** [comment]
if @Synthespian could make available his database i could try to reproduce this issue.

**Comment by wsbrenk** [comment]
Concerning context: at the morning of Nov 13th there was a devision battle match in which the opponent did not make a line-up. maybe this could cause the described problem!?

**Comment by Synthespian** [comment]
Logs sent.
And I did make the lineup for the division battle.  Won it 3-0. You made me check! 😛 
Happy to upgrade and close #742/#777 but stuck on JRE non-install version so just need to know which files to overwrite or which files/folders to keep. 😄

**Comment by akasolace** [comment]
@wsbrenk do we have an issue here? I waiting for your feedback before releasing 4.0 ...

**Comment by wsbrenk** [comment]
@akasolace this were the logs from Nov. 13th:

22:54:28 [Info]    core.gui.HOMainFrame: This is HO! version 4.0 r3257, have fun!
22:54:28 [Info]    core.gui.HOMainFrame: Operating system found: Windows 10 on amd64 (10.0)
22:54:28 [Info]    core.gui.HOMainFrame: Using java: 14.0.1 (AdoptOpenJDK)
22:55:02 [Info]    core.model.match.Matchdetails: Reload Matchdetails id: -1 type:League match events:0
22:55:02 [Info]    core.model.match.Matchdetails: Reload Matchdetails id: -1 type:International friendly (cup rules) events:0

the devision battle match is not mentioned. No errors were logged. the only dubious messages are the event counts of 0.

**Comment by akasolace** [comment]
@wsbrenk so I guess I can ignore this one for the time being and release 4.0, ok for you?

**Comment by Synthespian** [comment]
Have just gone to v 3308, HO-4.0.3308.2-portable-win-JRE
Still have short passes as the training type, but will re-test the training on Friday as well.

**Comment by wsbrenk** [comment]
@akasolace i think it is a good idea to wait until friday. if the bug will happen again, we should ask @Synthespian to make his database available, to help us debugging this error. 
if it will not happen again on friday, we should delay the work on this ticket until we again see such a constellation again and hopefully we will get a chance to debug it then.

**Comment by wsbrenk** [comment]
if @Synthespian still has a backup of the database from November 13th, we could also try to reproduce the error if he provides us this database.

**Comment by Synthespian** [comment]
Can give you the db as it is now.
Don't have a backup specifically after 13th.

**Comment by akasolace** [comment]
@wsbrenk sorry but I did release 4.0 before I saw your message. If there is really a bug here we will release a 4.1 shortly.

**Comment by wsbrenk** [comment]
not a problem - i think and hope

**Comment by Synthespian** [comment]
WELL ... specifically to Short Passing ... I got a good update today and it worked as expected.
Curiously none of the PM trainees in my 1st team got a training update (and I missed out a week of my hrf file downloads)
and the defenders who played in the friendly of my 2nd team didn't get training.

From a short passing specific perspective, this can be closed.
Happy to throw my 3x database (do you need everything or just the backup zip files?) if that can help?

**Comment by akasolace** [comment]
@Synthespian I am not sure I follow. You are saying that you still have issue with training and skill update but nothing specific to Short Passing, is it correct?

**Comment by Synthespian** [comment]
Correct.  It seemed to have two different issues from before but nothing specific to short passing.

**Comment by akasolace** [comment]
@wsbrenk I looked at my last training and I also observed some very abnormal change in decimals

**Comment by wsbrenk** [comment]
@akasolace me too - one new idea i had concerning that, is that the observed chpp-error would leave some corrupt objects in our database which we do not handle correctly.

**Comment by Synthespian** [comment]
I'm definitely not seeing some training updates unless I recalculate again.

**Comment by Synthespian** [comment]
[link=https://drive.google.com/file/d/1qwKkuHzSC6UUCIdoXX03kWo98F2q9KTa/view?usp=sharing]

Database from two teams updated today.
Vernon (2) was the first one I noticed.

You've got day before and today databases, and two files downloaded today. :)

**Comment by akasolace** [comment]
@Synthespian thank you, this is something we will look at but might take some time as we are busy with other part of the project at the moment.

**Comment by Synthespian** [comment]
Absolutely.
The most important thing if someone asks a question is that it's instantly resolved by re-calculating the training, which instantly reduces the severity/priority of the issue.

**Comment by wsbrenk** [comment]
thanks to the DB of @Synthespian I am now pretty sure why it happens.

if the user downloads only once per week, the download fetches training info and matches in one single run. Unfortunately the training effect calculation is then done before the matches were downloaded. without matches no training progress.

if the matches were downloaded before, then the download after training would find the matches info and the training progress can be calculated.

i will check if i could move the training calculation behind the match downloads. Then the first situation should be handled correctly.

**Comment by akasolace** [comment]
should be closed by #809

**Comment by akasolace** [comment]
#809 will need to be backported to 4.x branch

**Comment by Synthespian** [comment]
> thanks to the DB of @Synthespian I am now pretty sure why it happens.
> 
> if the user downloads only once per week, the download fetches training info and matches in one single run. Unfortunately the training effect calculation is then done before the matches were downloaded. without matches no training progress.
> 
> if the matches were downloaded before, then the download after training would find the matches info and the training progress can be calculated.
> 
> i will check if i could move the training calculation behind the match downloads. Then the first situation should be handled correctly.

Nice spot.  I have to say I generally have only ever done 1 download a week, each training update to get everything.  I think the idea to move the training calc post match download is sensible.

**Comment by wsbrenk** [comment]
@akasolace i think this ticket is closed with Milestone 5.0. So why don't relink it to 5.0? Only the backport wasn't carried out.

**Comment by akasolace** [comment]
so I just close it .. and we will tell users to upgrade
