### ISSUE TITLE
[ENHANCEMENT] League Tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#783]
What I would like is to have at each data download, those additional information downloaded:
      - team ranking of all teams in the league
      - Hatstats of all matches of the league

This might require a new table, like currently extra that would be reset at the end of each seasons. Then we would add:
   - in the league table, additional information like power ranking, max HatStats, (league ranking ?)  
   - 3 best games (based on hatstats)
   - 3 most surprising games (also based on HatStats)
   - .....

@wsbrenk @tychobrailleur  what do you think ?

**Comment by tychobrailleur** [comment]
I love the idea!  We could also maintain "historic data" regarding best games and most surprising games since beginning (this may require to fetch a lot of games, so this would need to be considered)

If we want to display more details, we probably need to look into "compacting" the current lower panel that displays all games?

**Comment by akasolace** [comment]
> I love the idea! We could also maintain "historic data" regarding best games and most surprising games since beginning (this may require to fetch a lot of games, so this would need to be considered)

for this we could do what was implemented by @wsbrenk for the match tab,  silent download of 10 historical games per HO launch in order to rebuild the historic. It allows to slowly recover data without being too painful for the user.  At some point we might let the user select via preference if he want to opt-in our out that functionality.  Also we might decide to make it part of the download functionality (with current design a user thinks there is a lag on the GUI when in reality some data download is taking place)

> we probably need to look into "compacting" the current lower panel that displays all games?

either we don't touch it and user will just have to scroll more or we replace it with a cross table (we remove the download button and we just download all league info by default in that new table)

**Comment by akasolace** [comment]
closed with e63f98edeafcc4f9aa79055b2ec04040721226d5
