### ISSUE TITLE
[BUG] allow to upgrade to stable from dev/beta channel

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#791]
**Describe the bug**
At the moment new version detection is managed by HO, it looks available upgrade as follow:
  stable -> stable
  beta -> newest between beta / stable
  dev -> newest between dev/beta/stable

however download is managed by install4J which only look for same channel:
   stable -> stable
   beta -> beta 
   dev -> dev

which should allow upgrade to more stable channel.

**Comment by wsbrenk** [comment]
should be fixed in HO5
