### ISSUE TITLE
Feedback Plugin[BUG]

### ISSUE THREAD

**Issue by paulreds** [akasolace/HO#792]
Windows 10
![Cattura](https://user-images.githubusercontent.com/74708272/99647479-23214580-2a52-11eb-887f-56484204e788.JPG)

**Comment by akasolace** [comment]
@paulreds there is already an open ticket for this, I will close this one.
Thank you

**Comment by paulreds** [comment]
May I have the reference please?


Inviato da iPhone

**Comment by akasolace** [comment]
https://github.com/akasolace/HO/issues/583
