### ISSUE TITLE
[BUG] error training updates

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#795]
For two weeks (= two training updates), my players Rudolf Saarow (443528008) and Per Olsson (437782720) playing friendlies in training positions did not get correct skill increase and XP in HO!, instead my goalie  Stefan Bilder (447501191) got the full playmaking skill plus, despite playing only in goal keeper position (-> should be osmosis training)

I am training playmaking and have not changed training settings recently.
The mentioned players get all other changes (age, form change, etc)
All other players seem to be fine, but I am not sure.
The matches are shown correctly in Matches Tap with all players in correct training  positions/ match settings like in Hattrick.

In an attempt to fix this **I did a subskill recalculation (7 weeks)**, after that the player Rudolf Saarow showed about 50% trained skill increase from what it should be and only + 0.01 XP increase after two friendlies. Before there was zero skill increase.
The skill increase for my Goal Keeper was lower than before, but still to high ImO.

**Timeline of Related games and affected  players, Hattrick Training Updates**
[matchid=668617518] Friendly Nov11th 2020 19:20
Rudolf Saarow (443528008) 0'-89' Position Right Inner Midfield towards wing, Position swap with Per Olsson to 90'-92' Right wing
Per Olsson (437782720) 0'-89' Position Right wing, Position swap with Rudolf Saarow to 90'-92'  Right Inner Midfield towards wing
Stefan Bilder (447501191) 0'-79' Goal keeper

Hattrick Training Update Nov13th 00:30

[matchid=668698347] Friendly Nov18th 15:25
Rudolf Saarow (443528008) 0'-89' Position Left Inner Midfield towards wing, Position swap with Per Olsson to 90'-92' Left wing
Per Olsson (437782720) 0'-89' Position Left wing, Position swap with Rudolf Saarow to 90'-92'  Left Inner Midfield towards wing
Stefan Bilder (447501191) 0'-79' Goal keeper

Hattrick Training Update Nov20th 00:30

**Screenshots**
HO! Squad Tab View https://ibb.co/9vvhMGd
HO! Training Tab View https://ibb.co/LS9hBG5
My latest db_user zip [db_user-2020-11-20.zip](https://github.com/akasolace/HO/files/5573117/db_user-2020-11-20.zip)

**Platform information:**
 - OS: Win 10 64bit Version 2004 build 19041.630
 - Version HO! 4.0 r3308

**Additional context**
Let me know if you need more details. Thanks for your time

**Comment by datatramp** [comment]
What kind of additional info do you need? I can zip the complete HO4.1 appdata, put it on google drive and give you a link ...

However I started my old HO!3.0 and after Hattrick download it showed ok skill increase for all relevant players. So the error in my HO!4.1 squad must be related to a recent corrupt download from Hattrick, right? And maybe it vanishes, if I delete recent download files and calculate subskills again? I do not want to waste your time ;)
Or did you change some calculation from HO3.0 to 4.1?

For reference I add two screenshots from HO!3.0 and HO!4.1, both showing changes in my squad from download Oct28th to download Nov21th. You can see the differences in the trained playmaking skill of Rudolf Saarow (13,59 / 13,91), Per Olsson (7,89 / 7,65), Stefan Bilder (2,42 / 2,53). Other minor differences may be rounding errors ...
![Screenshot 2020-11-21 161355HO30](https://user-images.githubusercontent.com/64270318/99880807-f3229f80-2c15-11eb-9005-0ae75c6cb3f7.JPG)
![Screenshot 2020-11-21 161617HO41](https://user-images.githubusercontent.com/64270318/99880820-0a618d00-2c16-11eb-85dc-1320eb902031.JPG)

**Comment by akasolace** [comment]
might be closed by training refactoring (see 7f91540834a18c8be13e4d53df640ae6f2be95f3)

**Comment by datatramp** [comment]
With todays training update, the errors in HO! 5DEV are still there.
I run stable HO! 3.0 with no issues, everything as expected
and parallel HO! 5.0 DEV r3407 in seperate directory and its own db on Win10 pro 64bit latest build.

After downloading training update with HO!5.0DEV,
some players with substitution in games did not receive (correct) training improvement,
a during game injured Player did not receive his part of training improvement
some players playing normal in their position did not receive training improvement at all.

I download this week´s matches again and did a subskill recalculation, but nothing changed.

While it seems that the league game was processed normal, the cup game did not.
This is my assumption, not sure!
Training this week was shooting, that should give improvements in scoring and set pieces for all playing team members.

I made screenshots of my squad table (sorted by player age) HO!3 and HO!5 to see the different output.
I underlined in red the players with differences.

I will try to add the HO!5DEV db, too.
[db_rsf-2021-02-05.zip](https://github.com/akasolace/HO/files/5932701/db_rsf-2021-02-05.zip)

![Screenshot 2021-02-05 142625 HO5](https://user-images.githubusercontent.com/64270318/107039696-85225900-67be-11eb-9267-035299686e31.JPG)
![Screenshot 2021-02-05 142753HO3](https://user-images.githubusercontent.com/64270318/107039740-923f4800-67be-11eb-8dfe-73181e542ed8.JPG)

**Comment by akasolace** [comment]
@datatramp are you using the latest DEV r3410 ?

**Comment by wsbrenk** [comment]
i will debug this

**Comment by datatramp** [comment]
No this report is for r3407, did not check for yesterdays new r4310 version.
How do I proceed?
Just update with HO! update feature with current issues in r3407, or should I delete and have a fresh r4310 and go from there /draw fresh update from hattrick?

**Comment by wsbrenk** [comment]
i'm debugging

**Comment by wsbrenk** [comment]
poor man cup matches are the problem, they are not loaded for training calculation

**Comment by wsbrenk** [comment]
@datatramp thanks a lot for providing your database.
