### ISSUE TITLE
Preferences Check tab

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#80]
**Describe the bug**
The check tab in preferences shows a lot of incorrect entry

 - First 2 entries should be removed
 - Entry number 3,  should be fixed because at the moment it does nothing and maybe placed on release channels tab for more consistency

- Entry 5 should be place on tab Downloads for consistency

  - we might be left only with Entry 4 
 which need to be investigated, I have no idea what it does (if it does something)  Maybe we can remove that entry and the code associated (if any) and get rid of that tab,

What do you think ?

![image](https://user-images.githubusercontent.com/1136496/51062414-19795c00-15f7-11e9-9c83-a776d1163e2f.png)

**Comment by brokenelevator** [comment]
`First two` **agree**
`third` **agree?** I mean, isn't that an awkward time to check for updates? Does anyone actually use that? If so **agree**, if not **dispose of it**
`fourth` **agree** I also have no idea what its purpose is
`fifth` **agree**

So removing that tab may make a lot of sense.

**Comment by mistermax80** [comment]
What was the original intent for the 1' 2'? Do you know?
I agree to remove tab, after check on 4'

**Comment by akasolace** [comment]
For 2) I don’t know maybe looking at the code will allow us to guess or maybe davidatorus knows 
For 1) a long time ago, HO developers were informing users about development news. News were stored in a server and fetched by the app. We will not support this. Anyway if someone care about development news he can just look github activity.

**Comment by akasolace** [comment]
@brokenelevator I think it is not a bad idea to check for new update automatically. But at the moment it is broken and it is not a really urgent functionality. Hence maybe we can simply delete the tab and why not in the future reintroduce automatized check for new updates.

**Comment by akasolace** [comment]
@brokenelevator can you by any chance take the lead on this one? 
If yes I can assign myself other bugs.

**Comment by brokenelevator** [comment]
@akasolace Automatic check makes sense but the timing. Wouldn't it be better to check before HRF download?
So what would be there to do? I may be not very high on time in near future. 
Remove the first 3-4? and move the 5th? possibly removing entire tab?

**Comment by brokenelevator** [comment]
@akasolace I guess I could do that. It should be easy enough. If something comes up I'll update here and maybe hand it to someone else.

**Comment by brokenelevator** [comment]
@akasolace One could (out of curiosity) check older version at SF but 1-4 seem to be dead code. Remnant of some old functionality. Do you still want to move 3rd to release channel tab?

**Comment by akasolace** [comment]
@brokenelevator 

> (2) HO had number of users on a website and parsed it into HO.

Do you mean it was used for statistics about number of HO users ?


> I guess I'll move the third one after all. It may be useful in the future, with a changed language string.
I may disable it though.

Exactly what I thought. Lets put the checkbox there in disabled mode. For 2.0 release we will decide either to remove it or to reactivate it with appropriate behaviour

**Comment by brokenelevator** [comment]
@akasolace It appears so. It downloads something from HO page. From name (names) it would look like it. Didn't try to open that page, in web or webarchive. Maybe will try :)

Rest is done. I'll prepare PR in a moment.

**Comment by akasolace** [comment]
@brokenelevator great thank you !

**Comment by akasolace** [comment]
closed by 635832f59fff6982d6f718a928d91aef75c41ad6

**Comment by brokenelevator** [comment]
@akasolace even webarchive seems to support it.[https://web.archive.org/web/20070925041025/http://www.hattrickorganizer.net/downloads/users.html](url)

**Comment by akasolace** [comment]
wow 162 491 HO users at that time, impressive !
