### ISSUE TITLE
[BUG] Error loading themes Darcula and Solarized 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#806]
**Describe the bug**

Error loading themes Darcula and Solarized  with Darklaf 2.5.3  from generated artefacts  (Solarized Light does not have the error)

It works well from the IDE for all themes.

@weisJ Any idea what could cause this?

**Comment by akasolace** [comment]
@weisJ I investigated and I noticed the following:
when upgrading my app it keeps previous version of libraries, hence in my installation folder I had couple of darklaf jars (this is the same for other librairies HO uses). Until 2.5.2 this never caused trouble. For 2.5.3 it cause dark themes not to load. The problem is solved by manually deleting the old jars. I don't know if this can help you find out what is going on ...

**Comment by weisJ** [comment]
> [...] it cause dark themes not to load. [...]

What do you mean exactly by this. If there is an exception could you provide a stacktrace?

**Comment by akasolace** [comment]
@weisJ stack trace is just a null pointer exception when calling this function https://github.com/akasolace/HO/blob/b82a37e347533401a73e46ece7387f7138cf8f95/src/main/java/core/gui/theme/dark/DarculaDarkTheme.java#L26

.  Tomorrow I will try to see which of the following line throws it:
`afManager.setTheme(new DarculaTheme());
            UIManager.setLookAndFeel(DarkLaf.class.getCanonicalName());
            UIDefaults defaults = UIManager.getLookAndFeelDefaults();`

I made some test and the NPE happens if 2.5.2 are alongside 2.5.3 jars (it does not happen otherwise for example before 2.5.3 I had something like 6 different versions of darklaf librairies).
Also as I mentioned previously only happen for dark themes.

However as a fix I will have my updater remove previous version of librairies.
