### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Vigneshr22** [akasolace/HO#808]
**Describe the bug**
Hi,

I am already using HO 3.0 and it is working fine. I tried to download and install HO 4.0.. But When I tried to Install HO.. I am getting a error message.

"The version of this file is not compatible with the version of windows you're running. Check your computer's system information to see whether you need an x86 or x64 version of the program."

I have tried to install both with JRE and without and am getting the same error message.
I have a 32 bit Windows 7 ultimate service pack 1..

Thank you for your help.

**To Reproduce**
I tried to install the HOSetup-4.0.3308.2 application as administrator, still getting the same error message.

HOSetup-4.0.3308.2-JRE , Tried this too with administrator privileges, still the same error message.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/75181261/100524350-74ad9b00-31dd-11eb-9651-d613f3ab4cb4.JPG)

**Platform information:**
 - OS: Windows 7 Ultimate service pack 1, System type : 32 bit operating system.

**Additional context**
Thank you very much for your help.

**Comment by Vigneshr22** [comment]
Hi,

Will I be able to use H.O 4.1 in my computer.. or should I wait for 5.0 to release..Please advise. Thank you.

**Comment by akasolace** [comment]
@Vigneshr22 building 32bits executable for all platform both with bundled and unbundled jre would be a big amount of work. Considering that 32bits OS would be generally gone from the market shortly, it is not ressources I want to invest into. 
I suggest you to build HO for your architecture ....
