### ISSUE TITLE
[eBUG] HO_1.436.0.680_OSX doesn't start

### ISSUE THREAD

**Issue by mistermax80** [akasolace/HO#81]
**Describe the bug**
Using HO_1.436.0.680_OSX.zip, this version doesn't start.

**To Reproduce**
1. Intall HO_1.436.0.680_OSX.zip
2. Click on 'HO.app'
3. during the startup, it's showed screenshot 1
4. close exception screen, screen startup hangup
5. close app, it's shower screenshot 2

**Screenshots**
1:
![schermata 2019-01-12 alle 05 03 39](https://user-images.githubusercontent.com/15519907/51069057-ef8c5d80-1627-11e9-92c5-d00f5fbf3529.png)
2:
![schermata 2019-01-12 alle 05 04 31](https://user-images.githubusercontent.com/15519907/51069058-f74c0200-1627-11e9-890e-368d47afdb9c.png)
logs:
[HO-2019-01-11.log](https://github.com/akasolace/HO/files/2751707/HO-2019-01-11.log)

**Platform information:**
 - OS: [macOS]
 - Version (1.436.0.680))

**Additional context**
I tried both ways: substitution install and fresh install, same behaviour.

**Comment by akasolace** [comment]
I changed jar task to not include sprache and theme folder within the jar.  This is working well for windows and Linux. However for mac os, the packaging is different and the HO.jar should contain those 2 folders.
However, I am running into an issue.  I don't know how to run twice the jar configuration, once for windows and Linux and once with different parameters for os x.  I am really new to graddle so maybe @brokenelevator you can help. Meanwhile I will ask the question on SO.

**Comment by akasolace** [comment]
the question on  [SO](https://stackoverflow.com/questions/54159312/gradle-run-twice-installdist-task-with-different-jar-configuration)
At the moment there is still no answers

**Comment by mistermax80** [comment]
@akasolace
Ok thanks!
I think we should remove the osx setup dev version...

**Comment by akasolace** [comment]
> @akasolace
> Ok thanks!
> I think we should remove the osx setup dev version...

I tried something. My osX VM is broken, can you please let me know if it fixed the bug. Thank you

**Comment by mistermax80** [comment]
@akasolace
I will try later (1 or 2 hours).

**Comment by akasolace** [comment]
@mistermax80  I did post the solution on SO

closed by ba0477c72422ac285629968780cc1fde5456e8c3

**Comment by brokenelevator** [comment]
> I changed jar task to not include sprache and theme folder within the jar.

@akasolace didn't you do it the other way around? remove them from folder but leave in jar?
