### ISSUE TITLE
[BUG] OAuth Access token not preserved on macos

### ISSUE THREAD

**Issue by tychobrailleur** [akasolace/HO#811]
**Describe the bug**
When restarting HO on Macos, some users are prompted with the OAuth challenge, which indicates that the OAuth access token doesn't seem to be stored in the `USERCONFIGURATION` table.

**To Reproduce**
1. Start HO
2. Download details from Hattrick, connect using OAuth
3. Shut down HO
4. Start HO again
5. Try downloading details again from Hattrick: OAuth challenge is prompted again.

**Screenshots**
N/A

**Platform information:**
 - OS: macOS
- Version: 4.1.3310

**Additional context**
N/A

**Comment by tychobrailleur** [comment]
<img width="440" alt="Screenshot 2020-11-29 at 14 27 52" src="https://user-images.githubusercontent.com/114285/100544641-1faa6d00-324f-11eb-9689-4c8ccef40eb7.png">

**Comment by tychobrailleur** [comment]
That is quite a strange one – I thought that using the closing button in the titlebar was solving the problem, but it seems to be happening randomly, as if there was some sort of race condition between `windowClosed` and `windowClosing`?

**Comment by dtslvr** [comment]
I don't know if it's related, but besides adding the access token every time I also have to set the path of my `.hrf` files.

**Comment by akasolace** [comment]
@tychobrailleur have you had time to look at this one ?

**Comment by tychobrailleur** [comment]
> I don't know if it's related, but besides adding the access token every time I also have to set the path of my `.hrf` files.

Thanks @dtslvr, it *is* related: user preferences (incl. OAuth access token) don't get saved when HO exits.  Arguably we could save it right after we have retrieved from HT.

> @tychobrailleur have you had time to look at this one ?

I haven't, but I am looking at it right now, hopefully I should have a fix soon.
As an aside, I am experiencing an NPE with `master` due Youth changes:

```
java.lang.NullPointerException
	at core.file.xml.ConvertXml2Hrf.createHrf(ConvertXml2Hrf.java:148)
	at core.net.OnlineWorker.getHrf(OnlineWorker.java:80)
	at core.net.DownloadDialog.startDownload(DownloadDialog.java:271)
	at core.net.DownloadDialog.actionPerformed(DownloadDialog.java:92)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
```
and line 148 in `ConvertXml2Hrf`:

```
		int youthteamId = HOVerwaltung.instance().getModel().getBasics().getYouthTeamId();
```

**Comment by tychobrailleur** [comment]
> That is quite a strange one – I thought that using the closing button in the titlebar was solving the problem, but it seems to be happening randomly, as if there was some sort of race condition between `windowClosed` and `windowClosing`?

I am convinced there is a race condition here, as this takes the form of a “heisenbug”: when adding logging statements to debug (or simply debugging), the problem disappears...  What is unclear to me is whether something changed in HO or the JDK to cause this issue to emerge.  Or if the problem was always there but somehow now appears due some changes.

**Comment by tychobrailleur** [comment]
I have created a PR with a fix that seems to work locally.  Having not been able to track down the cause of this, I am not fully convinced this fixes the issue for good, it would be great to have other people try out this fix (this may be challenging due to some NPEs on `master`).

**Comment by wsbrenk** [comment]
@tychobrailleur great to see you back. Concerning youth NPE. Thanks for that. Will fix this immediately. I guess you don't have an academy, which is a big mistake;-) 

More concerning this, in my "youth-ticket" #367

**Comment by cmeury** [comment]
I still have this problem; version 4.1.3310.2 on MacOS 11.5. Also, preferences do not seem to get saved either. Should I open a new issue for this?
