### ISSUE TITLE
[BUG] team analyzer shows incomplete lineups and no more info about played formation

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#814]
Feedback from wettnetzer  (HO 4.1):

In the team analyzer, the played formations are missing in the last column.

Blocked, transferred and injured players are not listed in the lineup of past matches. There are then only 9 or 10 players left on the lineup. In previous versions these players were marked in color, so you knew they weren't going to play in the next game. With the current variant, however, you can work badly, because then you have to look again at HT, where a player stood now.
...

**Comment by akasolace** [comment]
@tychobrailleur I think it is related to what you commit recently, right ?

**Comment by wsbrenk** [comment]
there were some bugs in team analyzers config settings. isShowUnavailable was set randomly i think. now it  again can be set in module config settings.

still missing is the colored marking of unavailable players.
if the formation is displayed correctly, i could not test yet.

**Comment by wsbrenk** [comment]
@tychobrailleur commit e96d911f8edeabfb6b4cf9b18db1541281ae769b removed the player status colors. Could we reset this?

**Comment by akasolace** [comment]
@wsbrenk the idea was to remove the color with clearer icons... not sure we want to step back on this one .... 
don't you think?

**Comment by wsbrenk** [comment]
@akasolace i agree - but i think we need some kind of displaying the information that a player will NOT occure in the lineup. This i understand is what wettnetzer is missing.

**Comment by akasolace** [comment]
@wsbrenk but the injury icon should be sufficient, no? Personally, I preferer this than changing the font color ....

**Comment by wsbrenk** [comment]
@akasolace i do not see those icons (injury, sold, red card) in team analyzers opponent team lineups.

**Comment by wsbrenk** [comment]
în UserTeamPlayerPanel i found some icon magics. this is not used for opponent team lineups, isn't it.

**Comment by akasolace** [comment]
@wsbrenk not sure, I would need to have a look

**Comment by akasolace** [comment]
@wsbrenk  I fixed it

before:

![image](https://user-images.githubusercontent.com/1136496/119102084-f1496580-ba19-11eb-8215-a0e5d2558a07.png)


now:
![image](https://user-images.githubusercontent.com/1136496/119102159-01614500-ba1a-11eb-8ab1-8f6656f06076.png)

**Comment by akasolace** [comment]
should be fixed by #1043
@wsbrenk  as you opened this ticket, I let you close it if solution is fine for you ...

**Comment by wsbrenk** [comment]
@akasolace looks promissing - i will test it tomorrow

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/119199530-8769a400-ba8b-11eb-949b-4577fcdae3a6.png)

goalkeeper tagged injured - well done!

**Comment by akasolace** [comment]
Still something wrong on your screenshot. Names of your player correctly displayed but the ones of your opponent still have old format ...
