### ISSUE TITLE
[BUG]Add teams to team analyzers team combo box

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#815]
Feedback from wettnetzer
...
Then perhaps a suggestion. I think it would be very handy if you could insert a team by hand that you would like to analyse. This is not absolutely necessary, but it would be a nice to have.

**Comment by wsbrenk** [comment]
this is an ancient feature not working anymore

modules->team analyzer->favorites->add shows a little dialog box where you can enter a team id. if you save the team name ist shown in the dialog box but not visible elsewhere, even not in the team combo box.

**Comment by akasolace** [comment]
should be closed by #873
