### ISSUE TITLE
[Feature] SkillInfoColumn showing colored bar for youth academy

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#825]
![SkillInfoColumn](https://user-images.githubusercontent.com/11821502/104838535-cd371580-58bb-11eb-81c2-faf8ce4e746f.png)

my next project could be some kind of SkillInfoColumn which displays a colored bar, presenting all the info about youth skill as shown above.

_Originally posted by @wsbrenk in https://github.com/akasolace/HO/issues/367#issuecomment-739489197_

@akasolace @tychobrailleur Will one of you get that in half a day? If not, will I deal with it in the next few weeks.

**Comment by wsbrenk** [comment]
that sounds promising: https://ernienotes.wordpress.com/2010/12/27/creating-a-java-swing-range-slider/

**Comment by wsbrenk** [comment]
the implementation with slider offers the following options:

* readonly for only displaying the values (text shows decimals for at least the current value, if possible the start value too)
* readonly==false, to edit the start value (may not be in the table cell itself, but in a separate dialog)
  edit the current value could adjust the training speed, if there is some training available

**Comment by akasolace** [comment]
@wsbrenk At the moment I am on the lineup tab. I want to reorganize it and make it more usefull. The code behind is quite a mess so I end up doing a lot of refactoring. When I am done with this I will be happy to help you. I might need another 2 weeks.

**Comment by wsbrenk** [comment]
Additional feature request:
- double click on skill column cell should start a skill edit dialog
- dialog should show bar with width increased by factor of 10
- the slider thumbs should be enabled to edit current value and start value
- additionally the dialog box shows edit fields for start and current values (constraints are startLevel and currentLevel if given)

**Comment by wsbrenk** [comment]
TODOs: 
* set column width
* sorting
* double click->open skill editor to change start skills

**Comment by wsbrenk** [comment]
sorting is done

**Comment by akasolace** [comment]
@wsbrenk should this one be considered done?

**Comment by wsbrenk** [comment]
Skill editor is one leftover TODO. could be a candidate for an extra ticket

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/113565874-073acc80-960c-11eb-97df-eef626429030.png)

for weeks I have been tormenting myself with layouts and other ui aspects. I am not satisfied yet, but that is the situation at the moment.

**Comment by akasolace** [comment]
it looks really nice ...

**Comment by wsbrenk** [comment]
![image](https://user-images.githubusercontent.com/11821502/116627538-99a16800-a94d-11eb-8852-7908d99828a5.png)

now I am reasonably satisfied with the ui. It was a hard piece of work and I learned a lot about java's layout manager

**Comment by wsbrenk** [comment]
dark look and feel version of youth module:

![image](https://user-images.githubusercontent.com/11821502/117208306-43bd3c00-adf5-11eb-8fc9-c220d287c1b4.png)

label color of skill values are to light

**Comment by wsbrenk** [comment]
@akasolace skill editors are in place - this ticket could be closed
