### ISSUE TITLE
[BUG] Download/Upload matches in Lineuptab doesn't work with one of three teams

### ISSUE THREAD

**Issue by cr0ssw1nd** [akasolace/HO#827]
[HO-2020-12-11.log](https://github.com/akasolace/HO/files/5676378/HO-2020-12-11.log)

**Describe the bug**
At Lineup tab, subtab Upload/Download, I hit the "Refresh list" button.
It takes about 10 secs, and the slider on the bottom slides multiple time from left to right.
Looking to the log file attached it seems that each time there is an error, the slider restarts.
In the end, after finishing, I've been left with an empty list in Upload/Download tab.

This function works seemless with my two other teams.

**To Reproduce**
1. Go to Tab "Lineup", SubTab "Upload / Download"
2. Click on button "Refresh list"
3. Watch the slider going wild
4. List of upcoming matches is empty 

**Screenshots**
NIL

**Platform information:**
 - OS: [Linux]
 - Version: HO: VERSION: 4.1   versionType:  RELEASE   RevisionNumber: 3310

**Additional context**
NIL

**Comment by akasolace** [comment]
I guess this has been fixed in master. However, I will wait for confirmation before closing this one.

**Comment by DavidatorusF** [comment]
@cr0ssw1nd 
do you still have this problem ?
I haven't... it's working for my 3 teams...
