### ISSUE TITLE
[BUG] No subskill increase for friendlies

### ISSUE THREAD

**Issue by leschmuh** [akasolace/HO#828]
Training for those players who played the friendly does not seem to be taken into account for subskill calvulations. For those having played in the league match everything is fine and subskill is ccorrectly calculated for full training, osmosis training and so on.

I am using 4.1 stable version with the JRE package provided on Windows 10 (Version 2004, Build 19041.630). Having this same problem on two independent PCs.

**Comment by wsbrenk** [comment]
maybe same as #781

**Comment by leschmuh** [comment]
Yes, most probably the very same issue.
