### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#829]
@weisJ   hello maybe, you can help me with the following issue I am struggling with.
I can't adjust the background of one column in a Jtable.

![image](https://user-images.githubusercontent.com/1136496/101984389-7bc6b580-3c81-11eb-9250-e9f75d506b60.png)

In case you wish to help and to save you time navigating the code. 
The JTable is define here: 

https://github.com/akasolace/HO/blob/8cd13ac282494adb770b7f54423fb647c6ac8148/src/main/java/module/lineup/LineupPlayersTable.java#L45

and the renderer of this specific column is defined here: 		https://github.com/akasolace/HO/blob/8cd13ac282494adb770b7f54423fb647c6ac8148/src/main/java/core/gui/comp/renderer/BooleanTableCellRenderer.java#L24

As you can see I put some debugging, if you run the code, you will see it says the component background is red but this is not how it is displayed. 

I am not sure what is going on here .... Any help would be welcome

**Comment by akasolace** [comment]
@weisJ actually I just tested with Nimbus, and it is working so it is a Darklaf bug .... arf spent so much time on this I should have tested Nimbus right away. 


![image](https://user-images.githubusercontent.com/1136496/101984562-8766ac00-3c82-11eb-8f3e-fe0592747cdf.png)

**Comment by akasolace** [comment]
@weisJ also would you be interested joigning our channel on Slack (not very active those days but still helpful to communicate)

**Comment by weisJ** [comment]
Sure :) just send me the link and I'll join.

**Comment by akasolace** [comment]
@weisJ     [HO channel](https://join.slack.com/t/ho-tle6272/shared_invite/zt-kcobqfz4-9pxK_GhpN3LL6h7rFQjRww)

**Comment by akasolace** [comment]
@weisJ it seems this will be closed with 2.5.4 release, correct ?

**Comment by weisJ** [comment]
Correct. But to be sure my fix actually solves your problem you might want to try out the snapshot version.

**Comment by akasolace** [comment]
ok I will do that ...

**Comment by akasolace** [comment]
@weisJ sorry for the very late feedback but I can confirm 2.5.4 fixed the issue for me!
Thank you one more time for your amazing reactivity !
