### ISSUE TITLE
CHPP Download Error

### ISSUE THREAD

**Issue by johari75** [akasolace/HO#831]
**Describe the bug**
CHPP download doesn´t work correctly. See error messages in attachment.

**Screenshots**
![CHPP_Download](https://user-images.githubusercontent.com/67096604/102053666-64560c80-3de8-11eb-9a73-2674a0fe70c5.JPG)

![CHPP_Download_2](https://user-images.githubusercontent.com/67096604/102053831-ac752f00-3de8-11eb-8658-c382ce54db9e.JPG)

**Platform information:**

- OS: [Windows 10 pro (10.0.19041 Build 19041)]
- Version (HO-4.0.3299.1-portable-win-BETA-JRE)

**Additional context**
e.g. in LineUps tab you can´t ignore last LineUp

**Comment by akasolace** [comment]
@johari75 could you please share your db (for example using wetransfer)

**Comment by johari75** [comment]
@akasolace I don´t know what´s going on. A few minutes ago I tried the download again and it worked. So sorry for the inconvenience. I´ll have an eye on that issue.
