### ISSUE TITLE
[BUG] Can't download current matches and league data

### ISSUE THREAD

**Issue by Raidri** [akasolace/HO#835]
**Describe the bug**
If I go to "Download" and select "current matches" or "league data" and want to download it I get many errors.
The squad data download works as expected.

**Screenshots**
![part_1](https://user-images.githubusercontent.com/148783/102876160-1fb01e00-4445-11eb-98ad-4930ed358a3e.PNG)
![part_2](https://user-images.githubusercontent.com/148783/102876174-23dc3b80-4445-11eb-9b9e-4912e2d85bbf.PNG)
![part_3](https://user-images.githubusercontent.com/148783/102876185-263e9580-4445-11eb-9aaa-8e7931e3d060.PNG)
![part_4](https://user-images.githubusercontent.com/148783/102876191-28a0ef80-4445-11eb-8161-d2d5b2133910.PNG)

**Platform information:**
 - OS: Windows 10 pro
 - Version	10.0.19042 Build 19042

**Additional context**
Here the log File
[HO-2020-12-22.log](https://github.com/akasolace/HO/files/5729177/HO-2020-12-22.log)

**Comment by akasolace** [comment]
@Raidri do you still experience that bug ?  Could you please test if this bug still exist in latest development version?

**Comment by Raidri** [comment]
@akasolace seems to be fixed in the new version.

**Comment by akasolace** [comment]
awesome
