### ISSUE TITLE
[FEAT] use icon / splashscreen / headerbar  according to the version used

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#84]
![image](https://user-images.githubusercontent.com/45043004/51177599-55931200-18c0-11e9-8a52-da448addd17b.png)

_Originally posted by @DavidatorusF in https://github.com/akasolace/HO/issues/73#issuecomment-454359423_

**Comment by yaute74** [comment]
I can work on it.
Do we change the current logo? Because it's old-fashioned.
You can create logos and do a survey on the hattrick forum.

**Comment by akasolace** [comment]
@yaute74   ok great!
Yes new logo would be very nice. 
Do you fell like asking it on HT forum? Otherwise we go for  it ourselves, plenty of free logo generators those days. We can also do both: ask for contribution and meanwhile give a try ourself.

**Comment by akasolace** [comment]
@yaute74 I had a look on the dedicated forum and indeed it might worth to seek for contributions.
On a side note the HT user guvidex who made some very nice logo already accepted to help. You might also reach out to him if you want

**Comment by yaute74** [comment]
Where is the dedicated forum ? [post=17237456.567] ?
You already contact him ?
I think we can ask and try ourself and after do a survey if necessary

When we talked about it, I made two of them:
![logo1b](https://user-images.githubusercontent.com/34601782/56987805-bce28280-6b8e-11e9-8109-f1ebd695df8f.png)  ![logo2b](https://user-images.githubusercontent.com/34601782/56987811-bfdd7300-6b8e-11e9-9936-beae1d252f3d.png)

**Comment by akasolace** [comment]
@yaute74 
> Where is the dedicated forum ? [post=17237456.567] ?
yes

> You already contact him ?
yes

> I think we can ask and try ourself and after do a survey if necessary
Agreed

> When we talked about it, I made two of them
I will also git it a try but I am very bad at it...

**Comment by yaute74** [comment]
I do the request on hattrick forum: [post=17237456.582]

**Comment by akasolace** [comment]
> I do the request on hattrick forum: [post=17237456.582]

I just saw it ... perfect now lets hope we will have some nice contribution

**Comment by yaute74** [comment]
>should you not ask for splashscreen contribution at the same time ?

@akasolace I wanted to do it after, but maybe it's a bad idea. I wanted it to match the logo we would have chosen.
I create 4 more logos and I receive 3 from contributor :)
I wait your logo :p

**Comment by akasolace** [comment]
> I create 4 more logos and I receive 3 from contributor :)
cool !

> I wait your logo
not sure where to start but I will give it a try

**Comment by akasolace** [comment]
@yaute74  the logos are not yet on your orange website ?
maybe you can also request some participation directly on HO forum ....

**Comment by mistermax80** [comment]
I can also on Italian HT forum... In logos section... Let me know...

**Comment by yaute74** [comment]
@akasolace no I will add them when I do the survey. Actually we have 17 logos.
@mistermax80 as you want :-)  (we have already an Italian logo!) 
I think I will do the survey before weekend

**Comment by akasolace** [comment]
Ok great, maybe you could put an update on forum to give those info and tell people few days left to participate!!


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaute74** [comment]
@akasolace done

**Comment by akasolace** [comment]
@hello Yaute
I had to do a small change in build.graddle to make it work. I am not sure how it was working for you before, hence I will wait that you confirm me that it is all good also on Linux and then you can close the issue. Thank you for the nice PR !!

**Comment by yaute74** [comment]
@akasolace hello, ok but I cannot test this week.

**Comment by akasolace** [comment]
@yaute74 @mistermax80 @brokenelevator @DavidatorusF  Can you please test and let me know if we can close that ticket?

**Comment by brokenelevator** [comment]
@akasolace splash screens work just fine.
icons do not show in the taskbar. https://imgur.com/1uxJpfM.png
and one more thing. was that on purpose? https://imgur.com/AmfQRCD.png (meaning colored tab bar)

Manjaro XFCE, run from jar

**Comment by akasolace** [comment]
> icons do not show in the taskbar  https://imgur.com/1uxJpfM.png
same issue in Windows

> and one more thing. was that on purpose? https://imgur.com/AmfQRCD.png (meaning colored tab bar)
yes this one was intended

**Comment by akasolace** [comment]
[ ] fix icons do not show in the taskbar  https://imgur.com/1uxJpfM.png

**Comment by brokenelevator** [comment]
@akasolace ok, fine. I get why color the tab bar in non-stable versions, but the stable? I don't think the change is necessary.
Also, why version is '2.000'? not '2'.

**Comment by akasolace** [comment]
>get why color the tab bar in non-stable versions, but the stable? I don't think the change is necessary. 
agree

**Comment by akasolace** [comment]
> Also, why version is '2.000'? not '2'.

Version is 2.00 but we might decide display only 1 digit in the header bar considering the last digit only indicate if it is a stable, beta or dev version.

**Comment by akasolace** [comment]
@yaute74  here below a summary of the open point before closing the issue.

 - [ ] 1. fix icons do not show in the taskbar  https://imgur.com/1uxJpfM.png
 - [ ] 2. for stable version let's remove the green headed bar
 - [ ] 3. In the header bar, display version with only one digit

**Comment by brokenelevator** [comment]
> In the header bar

@akasolace and maybe also splash screen. I think we should stick to significant digits only.

**Comment by yaute74** [comment]
@akasolace For point 3 it's only for stable version ?

**Comment by akasolace** [comment]
>@akasolace For point 3 it's only for stable version ?  ...

@yaute74 I would say for all versions. The second digit only indicate if it stable, beta or dev version. This is parsed by HO but not very helpful for the user. What do you think ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by yaute74** [comment]
@akasolace, @brokenelevator 
If I am right the version is decomposed like this: 
**major.minor.(stable|beta|dev).buildNumber**

So you speak about the third digit ?
I think we can remove this digit.

For the buildNumber:
- I think it could be interesting to keep it for beta and dev version because it's the only digit who change during development and for sustaining it could be interessing.
- for stable version, it's depend how you want to manage the version number. When the 2.0 will be in release, for each new release of this version you will increase the minor digit ? (if yes I think we can remove it)

So to resume:
dev, beta we have something like this: 2.0 r1234
stable, something like this: 2.0

What do you think ?

@akasolace do you stat about dowload of beta and dev ? some users use them ?
I was wondering if we should keep the beta version

**Comment by akasolace** [comment]
> dev, beta we have something like this: 2.0 r1234
> stable, something like this: 2.0
> What do you think ?

@yaute74 yes exactly what I had in mind

I think we should keep the beta. This is the channel used by default by the translators.

**Comment by akasolace** [comment]
@yaute74 can I close this one ?

**Comment by akasolace** [comment]
closed by ce1c75e
