### ISSUE TITLE
[eFEAT] simplify themes – keep normal and introduce dark theme

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#85]
maybe using this theme https://github.com/weisJ/darklaf/

**Comment by weisJ** [comment]
Hi, I just wanted to say that I appreciate you considering darklaf for the project. If you run into any complications I am always open to suggestions. I see that your are using JGoodies and I don’t know how well it works with darklaf but I’d be willing to support components from it if needed.

**Comment by tychobrailleur** [comment]
I have started looking into improving theming, and darklaf is definitely quite cool – I have done initial tests, and I am really excited by this!

![Screenshot 2020-04-11 at 14 58 45](https://user-images.githubusercontent.com/114285/79045812-05127d80-7c05-11ea-9fb5-1a077e906f67.png)


@weisJ Is there a mailing list or something for darklaf?  I am getting [an issue](https://gist.github.com/tychobrailleur/5fcba2c545cc09539b3f28e7a2a7e48e) on MacOS which someone already probably hit: a tabbed pane overlaps with the titlebar.

![Screenshot 2020-04-11 at 14 51 58](https://user-images.githubusercontent.com/114285/79045732-81f12780-7c04-11ea-8b27-9216a51dd5b6.png)

I see there is a macos library, but I haven't figured out if how this can be used.

**Comment by weisJ** [comment]
>I have started looking into improving theming, and darklaf is definitely quite cool – I have done initial tests, and I am really excited by this!

Happy to hear you like the laf. 

>@weisJ Is there a mailing list or something for darklaf?

There is no mailing list but you can simply create an issue if you encounter any problem. 

>I am getting an issue on MacOS which someone already probably hit: a tabbed pane overlaps with the titlebar.

This seems to be related to [this issue](https://github.com/weisJ/darklaf/issues/129) which will be resolved with the next release. The fix for now is to ensure that laf is installed before any frames are created.

>I see there is a macos library, but I haven't figured out if how this can be used.

The macos library isn't supposed to be used at all as its an internal implementation detail. The relevant api would be `LafManager#setDecorationsEnabled`.

**Comment by tychobrailleur** [comment]
> This seems to be related to [this issue](https://github.com/weisJ/darklaf/issues/129) which will be resolved with the next release. The fix for now is to ensure that laf is installed before any frames are created.

Thanks a mil @weisJ – I'll keep an eye out for the next release, and if the issue persists, I'll file a bug.

**Comment by akasolace** [comment]
@tychobrailleur  that looks promising ... not too much work to port the code?

**Comment by tychobrailleur** [comment]
> @tychobrailleur that looks promising ... not too much work to port the code?

It was a small enough to get the Squad tab to look ok in that snapshot, but generally speaking, there are a few components that define their own LAF (e.g. `SpielerLabelEntry` defines its own back [background color](https://github.com/akasolace/HO/blob/master/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L86) or its own [border](https://github.com/akasolace/HO/blob/master/src/main/java/core/gui/comp/entry/SpielerLabelEntry.java#L162) ) that need to be modified to “ask” the theme manager what colours to use.

The theme manager itself needs to be refactored:
- It needs to be able to support darklaf (possibly the different themes darklaf propose, like Darkula, Dark Solarized, etc.) alongside JGoodies (if we wish to keep them?),
- It needs to be loaded early to be able to inform the components that load colours [statically](https://github.com/akasolace/HO/blob/master/src/main/java/core/gui/comp/entry/ColorLabelEntry.java#L26)

It also looks like the theme manager at some point was supporting themes loaded from a zip file, it might be worth “resurrecting” that feature.

**Comment by akasolace** [comment]
@tychobrailleur  let me know if I can help on this one ... for the icons I have done in the past some python script to change the background of icons ... if it helps I can do that part

**Comment by akasolace** [comment]
>  alongside JGoodies (if we wish to keep them?)

if it is simpler to ditch support of this one we can just ditch it ...

**Comment by akasolace** [comment]
>  It also looks like the theme manager at some point was supporting themes loaded from a zip file

true very old version of HO had 2 sets of icons (one was called FatCow) it was held supported and was ugly :-)

**Comment by weisJ** [comment]
I see that some icons are in `.svg` format. Do you actually use those or are they converted to image icons? Darklaf has the option to load and display `.svg` icons and can also load icons with a light/dark variant (the correct version is used automatically). e.g. in the screenshot above the black icons should probably be some sort of light tone in a dark theme.

**Comment by tychobrailleur** [comment]
Ok, I think @weisJ's [commit](https://github.com/weisJ/darklaf/commit/cd4351ea0b3bea1999a6f176a22019b50fc40cfb) helped me figure out the problem – calling `LafManager.install` before the frame constructor seems to solve the problem.

This works:

```
public class DarkFrame extends JFrame {

    public DarkFrame() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Lorem Ipsum");

        try {
            setSize(new Dimension(400, 300));

            final JTabbedPane tabbedPane = new JTabbedPane();
            Arrays.stream("dolor sit amet consectetur adipiscing elit".split("\\W")).forEach(
                s -> tabbedPane.add(s, new JPanel())
            );

            getContentPane().setLayout(new BorderLayout());
            getContentPane().add(tabbedPane, BorderLayout.CENTER);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LafManager.install(new DarculaTheme());
            final DarkFrame frame = new DarkFrame();
            frame.setVisible(true);
        });
    }
}
```

This doesn't (i.e. calling the `LafManager` in `JFrame` constructor, which makes sense):

```
public class DarkFrame extends JFrame {

    public DarkFrame() {
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("Lorem Ipsum");

        try {
            setSize(new Dimension(400, 300));
            LafManager.install(new DarculaTheme());
            UIManager.setLookAndFeel(DarkLaf.class.getCanonicalName());

            final JTabbedPane tabbedPane = new JTabbedPane();
            Arrays.stream("dolor sit amet consectetur adipiscing elit".split("\\W")).forEach(
                s -> tabbedPane.add(s, new JPanel())
            );

            getContentPane().setLayout(new BorderLayout());
            getContentPane().add(tabbedPane, BorderLayout.CENTER);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {

        final DarkFrame frame = new DarkFrame();
        SwingUtilities.invokeLater(() -> {
            frame.setVisible(true);
        });
    }
}
```

From HO perspective, this does confirm we do need to move things around, as the `ThemeManager` is called too late for various reasons, including this one.

I am still of the mind to ditch JGoodies – @akasolace would it be worth asking in the HT forum is anyone actually uses them?

(@weisJ congrats on the new major release, awesome stuff there!)

**Comment by akasolace** [comment]
> I am still of the mind to ditch JGoodies – @akasolace would it be worth asking in the HT forum is anyone actually uses them?

JGoodies is only used in match analyzer right?

**Comment by tychobrailleur** [comment]
> JGoodies is only used in match analyzer right?

I don't believe they are used there specifically (but I could be wrong) – they are meant to change the overall appearance of HO, but the changes are so minor that I don't see the point: they seem to affect scrollbar, button, combo boxes appearance.

**Comment by akasolace** [comment]
Ok ... I recall there is something specific with the GUI of the tab match analyser. I thought it was JGoodies but it might be something else. I remember that when I ported the project to gradle I missed a dependency and only match analyser was broken. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tychobrailleur** [comment]
A bit of an update here as well: good progress, it is starting to look great.  I have done a bit of refactoring on the `ThemeManager` which handles all the theming aspect now (before some of it was spread out in other places), and removed JGoodies (for now – still nothing definitive)

![Screenshot 2020-04-25 at 15 10 46](https://user-images.githubusercontent.com/114285/80282622-5a24b800-870a-11ea-824a-fb3719145ba5.png)

![Screenshot 2020-04-25 at 15 32 42](https://user-images.githubusercontent.com/114285/80282609-4da05f80-870a-11ea-8a21-d1345c7a71e2.png)

![Screenshot 2020-04-25 at 15 39 25](https://user-images.githubusercontent.com/114285/80282711-f949af80-870a-11ea-8fca-17f25eae59f6.png)

Work is still carrying on to modifying places where UI logic hardcodes colours, and add colours to themes themselves.

Two weird issues that are now occurring with the dark theme that will need to be solved:
- Table headers get out of sync with column contents when scrolling across

![scroll](https://user-images.githubusercontent.com/114285/80282682-d1f2e280-870a-11ea-9d4e-7f6b8335bef2.gif)

- Some weird refresh issue with images when tabbing out and back:

![switch](https://user-images.githubusercontent.com/114285/80282848-986ea700-870b-11ea-82b0-1fc65fd05c96.gif)

**Comment by akasolace** [comment]
@tychobrailleur  it is such a change after having known HO! for so many years !

the out of sync column when scrolling across is only affecting player overview or all tables?

**Comment by tychobrailleur** [comment]
> the out of sync column when scrolling across is only affecting player overview or all tables?

All tables.

**Comment by tychobrailleur** [comment]
A few more screens (training not quite finished):

![Screenshot 2020-04-26 at 10 21 12](https://user-images.githubusercontent.com/114285/80303382-e6d18380-87a7-11ea-9425-852cbc7aaefc.png)

![Screenshot 2020-04-26 at 10 21 20](https://user-images.githubusercontent.com/114285/80303384-eb963780-87a7-11ea-9c72-82604874ed8a.png)

![Screenshot 2020-04-26 at 10 21 31](https://user-images.githubusercontent.com/114285/80303386-ee912800-87a7-11ea-9acc-15e5e01cbe29.png)

![Screenshot 2020-04-26 at 10 21 38](https://user-images.githubusercontent.com/114285/80303389-f224af00-87a7-11ea-8042-57ab36805040.png)

**Comment by akasolace** [comment]
> Modify old existing icons to have a better appearance on dark LAF (newer ones are perfect)

let me know which one are problematics ....

> Theme optional modules (Best/Worst team, Evil Card, Matches Analyzer, etc.)

@tychobrailleur  @wsbrenk  do we want to keep all those modules or should we get rid of some of them ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur @wsbrenk do we want to keep all those modules or should we get rid of some of them ?

I think we should keep them as much as possible, unless some of them are too much of a maintenance headache.

**Comment by tychobrailleur** [comment]
@akasolace Here are the major ones, these should cover roughly 90–95% of what we need:

- The jerseys on Squad (and other tabs):
![Screenshot 2020-04-26 at 11 39 09](https://user-images.githubusercontent.com/114285/80305112-c3f89c80-87b2-11ea-9989-f7b7bdfe44e6.png)

- The buttons in `SpielerDetailPanel`:
![Screenshot 2020-04-26 at 11 39 13](https://user-images.githubusercontent.com/114285/80305402-4cc40800-87b4-11ea-9be1-aa3ef8b09fa4.png)

- The print (Drucken), drehen icons (still in Squad):
![Screenshot 2020-04-26 at 11 39 34](https://user-images.githubusercontent.com/114285/80305447-a0365600-87b4-11ea-8301-df4bce2fc081.png)

- On Training:

![Screenshot 2020-04-26 at 11 55 06](https://user-images.githubusercontent.com/114285/80305466-cc51d700-87b4-11ea-808a-9fe26723632f.png)
 
![Screenshot 2020-04-26 at 11 54 59](https://user-images.githubusercontent.com/114285/80305470-d542a880-87b4-11ea-9c00-3b584c9c11a4.png)
![Screenshot 2020-04-26 at 11 54 52](https://user-images.githubusercontent.com/114285/80305473-d7a50280-87b4-11ea-812a-36926c7f8844.png)
![Screenshot 2020-04-26 at 11 54 45](https://user-images.githubusercontent.com/114285/80305474-da075c80-87b4-11ea-8ff7-cbaa7ddd6f1a.png)
![Screenshot 2020-04-26 at 11 54 41](https://user-images.githubusercontent.com/114285/80305487-f1464a00-87b4-11ea-980b-5cdb5a0dd2e5.png)

(on the clock one, only the red one seems to be fuzzy on the edges)

- On league details:
![Screenshot 2020-04-26 at 11 39 43](https://user-images.githubusercontent.com/114285/80305512-1935ad80-87b5-11ea-9a3f-0c52c0788c0a.png)
![Screenshot 2020-04-26 at 11 39 52](https://user-images.githubusercontent.com/114285/80305509-176bea00-87b5-11ea-92d9-8d6a0d00550d.png)
![Screenshot 2020-04-26 at 11 39 48](https://user-images.githubusercontent.com/114285/80305525-22267f00-87b5-11ea-89cd-60ee65032e09.png)
![Screenshot 2020-04-26 at 11 57 48](https://user-images.githubusercontent.com/114285/80305532-2b175080-87b5-11ea-8e95-64cad22bc683.png)

- On Transfers:

![Screenshot 2020-04-26 at 11 40 11](https://user-images.githubusercontent.com/114285/80305550-3ff3e400-87b5-11ea-8209-084e4f813091.png)

**Comment by weisJ** [comment]
As for the icons there are some mechanisms in Darklaf that ensure icons best match the current theme.
You can either use a set of dark/light icons or even use colours of the theme for some parts of the icon (`svg` only).
Everything relevant is handled by the `IconLoader` class.

List of properties that are ensured to exist in any theme:

https://github.com/weisJ/darklaf/blob/master/theme/src/main/resources/com/github/weisj/darklaf/theme/icon_presets/dark_icons.properties
https://github.com/weisJ/darklaf/blob/master/theme/src/main/resources/com/github/weisj/darklaf/theme/darcula/darcula_defaults.properties

e.g. the black icons in the squad tab (names table) could be `menuIconEnabled` (Its the default “grey” icon colour in darklaf).

The wiki article:

https://github.com/weisJ/darklaf/wiki/Icons

**Comment by tychobrailleur** [comment]
Thanks @weisJ . Most of the icons are png / gif, but this would definitely be handy (@akasolace would converting them to svg be an option, do you think?). In any case I think the icons could do with a bit of cleanup. ;-)

**Comment by tychobrailleur** [comment]
For sh*ts and giggles, here is what it looks like with Solarized Light:

![Screenshot 2020-04-26 at 12 35 20](https://user-images.githubusercontent.com/114285/80306310-7b44e180-87ba-11ea-8d85-b4358346344c.png)

Truly great stuff, @weisJ

**Comment by akasolace** [comment]
@tychobrailleur  we need to decide what we want to do with other themes? Nimbus, system, classic ...
Nimbus we can keep but I think the others two are really broken. Also we need to see how many themes we can reallistically support.
The way I see it, tell me if you agree, is the following: we are supporting one main theme (the one for which @yaute74  id doing some icons, not sure which one it is to be honest.  We are asking the commuity to contribute for the dark themes by providing svg icons variation.  But this won't be applicable to Nimbus, right ?

**Comment by tychobrailleur** [comment]
> @tychobrailleur we need to decide what we want to do with other themes? Nimbus, system, classic ...

That's my plan: keep Nimbus, and remove system & classic. 
I still see NImbus as the main theme, and the dark icons, as you mentioned, won't apply to that theme.

**Comment by akasolace** [comment]
ok perfect ... I did not know nimbus could also use the svg icons I thought it was darklaf specific ....

**Comment by yaute74** [comment]
@akasolace  I use Solarized Light on my side and test also with Dracula, I don't use other themes.

**Comment by akasolace** [comment]
same here I use Solarized Light  and sometime test Solarized and Darcula

**Comment by akasolace** [comment]
@tychobrailleur I think we can close this one, what do you think ?

**Comment by tychobrailleur** [comment]
Only outstanding thing on this are the icons, really.  We could track that with a separate ticket?

**Comment by akasolace** [comment]
> We could track that with a separate ticket?
Yes I would suggest a separate ticket listing the icons that still need to be created as svg, when this ticket is created I would ask help on the forum (dont know how many icons we are still mising really ...). @tychobrailleur Could you open that ticket and close this one when done?
