### ISSUE TITLE
[BUG] I can't install the software...

### ISSUE THREAD

**Issue by Coachalex1983** [akasolace/HO#852]
Hello,

after downloads some parts of the news HO 4.1...
Without and with Java integrated,

with this version :
-> HOSetup-4.0.3308.2.exe
-> HOSetup-4.0.3308.2-JRE.exe

I have the same mistake during installation try ->
"This software can't be execute on this computer"

Do you recognize this problem ? What sort of his this ?

Thanks !

**Comment by akasolace** [comment]
never saw such error.  The software is not signed so maybe you have to authorise installation of unsigned software.

**Comment by akasolace** [comment]
@Coachalex1983 have you find a solution to your problem?

**Comment by Coachalex1983** [comment]
No ii haven't find any solution :-/
It's so bad...
I've a windows 10 in 32 bits and 2004 version.
I don't find any options on authorization of unsigned software.
I''ve looking on the net but i don't find any issues....

**Comment by akasolace** [comment]
You need to select the 32bits version
