### ISSUE TITLE
Training Calculation not working[BUG] 

### ISSUE THREAD

**Issue by NaTakk3422** [akasolace/HO#853]
**Describe the bug**
Players played on cup game on Wednesday and this is listed also in the last match colum. But in the skill table no green +0.10 or somethin like that is displayed. On Players playing in the friendly on saturday it counts.

**To Reproduce**
Sync new data

**Screenshots**
![grafik](https://user-images.githubusercontent.com/77483301/104700482-82c76480-5714-11eb-8786-7531112e200e.png)

**Platform information:**
Windows 10

**Additional context**
Upgraded couples of days ago from an older version

**Comment by akasolace** [comment]
@wsbrenk not sure if this is still relevant in master ?

**Comment by wsbrenk** [comment]
same as #781 i think.

**Comment by NaTakk3422** [comment]
maybe the same. but what is the solution?

**Comment by wsbrenk** [comment]
#813 and #803 are the solutions. the first is on the master branch, the 2nd on release/4.x. both not yet released.

**Comment by NaTakk3422** [comment]
So, when is the solution available? Can I get a beta to test?

**Comment by akasolace** [comment]
yes you can test a dev version

**Comment by NaTakk3422** [comment]
ok, tested with the 5.0 DEV. There it is working! Can I update from DEV to a later stable version?

**Comment by akasolace** [comment]
@NaTakk3422 yes this will be possible. However, I advise you to be very careful if you use a dev version. We are doing some heavy changes at the moment and I can't guarantee that a dev version will not break everthing. You should always keep backup of your data when using dev version.
