### ISSUE TITLE
[BUG] Lineup Panel: incorrect display of match time when in different time zone

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#868]
as reported by @poteus

**Describe the bug**
I also noticed that the date and time of the game was wrong. I play on Wednesday at 19:30 (Central US). It says Thursday at 02:30. Maybe time in GMT instead of Local?

@poteus would you mind sharing your database here that I could do some testing ? 

Thank you

**Comment by akasolace** [comment]
@poteus could you please share your database here that I could do some testing ?

**Comment by poteus** [comment]
https://drive.google.com/file/d/1ZoWDXnOms3QA2Qxs-x2Q-kkmCy7WCAFE/view?usp=sharing

**Comment by akasolace** [comment]
thank you

**Comment by akasolace** [comment]
@poteus actually can I ask you to share with me your db folder ... I would like to check couple of things and the hrf won't be sufficient ... You can also send me the link via HTmail if you want to keep it confidential.

Thank you

**Comment by poteus** [comment]
So the folder with all the hrf?

Alexis Rivera
Math - STEM - Robotics

**Comment by akasolace** [comment]
no the folder with the database, normally called /db if you haven't renamed it.

**Comment by poteus** [comment]
Check the folder I shared with you. I added the folder "db2".
Let me know if I can do anything else.

Bon courage!

Alexis Rivera
Math - STEM - Robotics

**Comment by akasolace** [comment]
Merci

**Comment by akasolace** [comment]
@poteus actually a very last thing before I can start looking at it, can you share a screenshot from HT of your upcoming game ? 
Thank you

**Comment by poteus** [comment]
[image: Screen Shot 2021-02-04 at 7.48.52 AM.png]

Alexis Rivera
Math - STEM - Robotics

**Comment by akasolace** [comment]
@poteus I see the name of the attachment but not the attachment itself. Maybe it does not work to add attachement to GitHub ticket via mail ....

**Comment by poteus** [comment]
![Screen Shot 2021-02-04 at 7 48 52 AM](https://user-images.githubusercontent.com/20169360/106906350-af8eec00-66c2-11eb-8832-cba48a8e5955.png)

My mistake... :)

**Comment by akasolace** [comment]
The db you sent me is for the team Golden Bots and the screenshot for team Starlite ...

**Comment by poteus** [comment]
![Screen Shot 2021-02-04 at 8 58 41 AM](https://user-images.githubusercontent.com/20169360/106910815-3776f500-66c7-11eb-9c4c-96a5e0f19eb9.png)

OMG!! What a mess! Sorry bud.

**Comment by akasolace** [comment]
hi @poteus if I understood correctly your HT-mail, you have been tested the latest dev version 5.0.3410 and: 
     - you still have incorrect display of match time ?  Both in match tab and lineup tab? I made some check on match tab, it seemed fixed so I assumed it will be fixed also on Lineup tab ...
     - You are able to send Lineup correctly? tbh, I am a bit confused here I thought I still had to fix it (#872) ....
     
I will need to do futher test this weekend. If I am correct:
    - the team's db you shared with me is located in Mexico  
    - you local TZ is America/Chicago
    - HT displays your match time in your local TZ America/Chicago
    - The PC you are running HO displays time in your local TZ America/Chicago.
    - HO! continues to display time in an incorrect TZ even on latest DEV
        - both for match modules and lineup 
        - any change compare to the previous HO version ? 
     - with latest DEV you are able to download data and send lineup
       - HO! still requires you to have recent data but it detects correctly data download
       - If you download data and restart HO!  does HO! still allow you to setup lineup ?

**Comment by akasolace** [comment]
@poteus  I changed the timezone on my PC to test it and it works for me:


![image](https://user-images.githubusercontent.com/1136496/107094568-862ba880-6807-11eb-9ece-d5304fa77cbb.png)


![image](https://user-images.githubusercontent.com/1136496/107094577-8af05c80-6807-11eb-9834-be8dd5f189d2.png)

**Comment by akasolace** [comment]
@poteus as a follow up to this ticket, I know allow user to set timeZone in preference in case not correctly detected by the System. 
If you could try new DEV artefacts (to be released later this week) to ensure that all works correctly for you, thank you
