### ISSUE TITLE
[BUG] function DBManager.areDataTooOld() returns incorrect value for non CET timezone

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#872]
**Describe the bug**
The function DBManager.areDataTooOld() returns incorrect value if user is in a different time zone than HT default

```
When pressing the button "Help improve rating prediction" in Lineup, the message is showed "Your data is not recent, last update is 31 груд. 2020 р. 12:11:59, please start by downloading new data from Hattrick". But I just downloaded the data. It is 31.12.2020 13:12 UTC+2 now.

The problem is in the time zone difference: Hattrick time is 12:12, but my local time is 13:12. When I change time zone to Stockholm, the button works normally.
```

@wsbrenk  thinks he might have close it with #870 

to be checked...

**Comment by wsbrenk** [comment]
@akasolace this is again an example, that the way of downloading Hattrick's data is not handled very intuitively. It tooks a quiet long time to find out:

* ConvertXml2Hrf.java.CreateBasics appends the hattrick FetchedDate string to hrfstring
* HRFStringParser.java.createModel converts this first to a properties list
* which is given to HRFStringParser.createHOModel to create the new HOModel instance
* there the Basics constructor is called which uses getTimestamp->parseHattrickDate to parse the Hatrick time string to timestamp using the correct Hattrick time zone CEST

i hope this could help a little to verify if the date used by areDataTooOld (this comes from FetchedDate) is correct.
