### ISSUE TITLE
[BUG] training

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#875]
@wsbrenk I create this ticket from a post on HT forum ....

**Describe the bug**

![image](https://user-images.githubusercontent.com/1136496/106387362-b45d5280-63d9-11eb-8427-e5adb451e1ed.png)

**Comment by wsbrenk** [comment]
@akasolace my french is a lot more poor than my english is. You have to translate this. i fear the reporter is not happy with training prediction!?

**Comment by DavidatorusF** [comment]
@wsbrenk 

training -> prediction

![image](https://user-images.githubusercontent.com/45043004/106390293-f8575400-63e7-11eb-9095-09a4dcf7f5db.png)

before we only saw the prediction according to the forecast of future training

displaying everything is nice but being able to select the ones you really want to see would be cool

**Comment by DavidatorusF** [comment]
@wsbrenk  I'm so confused... I become old...

Preferences->Training->Display skill downs did the trick

**Comment by wsbrenk** [comment]
@DavidatorusF this is what I wish to you: to become very old - I am old;-)
