### ISSUE TITLE
[eBUG]

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#88]
**Describe the bug**

In order to have the release notes properly displayed in GitHub, the markdown page need specific header. However this header should not be displayed to the users.

![image](https://user-images.githubusercontent.com/1136496/51414988-87340380-1b74-11e9-9711-1d5e40d3f7ce.png)

**Comment by brokenelevator** [comment]
@akasolace Maybe I'm a little out of loop or something different but it looks fine to me.
![przechwycenie obrazu ekranu_2019-01-19_13-39-58](https://user-images.githubusercontent.com/2612128/51426797-00bd0780-1bf0-11e9-8e95-6adddcc0a16b.png)

**Comment by akasolace** [comment]
That’s weird that it does not behave the same. I will need to have another look ...

**Comment by DavidatorusF** [comment]
my .zip is will updated to r**974** 
seem you haven't add the last translation from poeditor, isn't it ?

**Comment by akasolace** [comment]
@DavidatorusF so you confirm you had the same screen as brokenelevator , no weird text ?
I released yesterday around midnight, normally all translation that were done at that time should be included ...

**Comment by DavidatorusF** [comment]
same screen as brokenelevator
oups... made last translations around midnight too
![image](https://user-images.githubusercontent.com/45043004/51429329-fc074c00-1c0d-11e9-956a-df4083e861c5.png)
![image](https://user-images.githubusercontent.com/45043004/51429335-0d505880-1c0e-11e9-9c58-df48aee02cf9.png)

**Comment by akasolace** [comment]
@DavidatorusF  i don't understant yuo shared 2 screenshots, one with the bug and the other not. What is the diference between the 2?  Also according to you screenshot you are updating from 1.435? I would not have expected this one to work ....

**Comment by akasolace** [comment]
@mistermax80 @yaute74  how is it for you ?

**Comment by mistermax80** [comment]
I will do in night...

**Comment by DavidatorusF** [comment]
> @DavidatorusF i don't understant yuo shared 2 screenshots, one with the bug and the other not. What is the diference between the 2? Also according to you screenshot you are updating from 1.435? I would not have expected this one to work ....

oh... title is the bug ? the second screenshot is the same,  just a scroll on the popup windows

don't take care at 1435 who was open too, was the 1436.0.723...

**Comment by akasolace** [comment]
@DavidatorusF  ah ok so you have the issue same as me.  Release notes start with unwanted text. On @brokenelevator example it is different (the text is also formated)

**Comment by yaute74** [comment]
@akasolace 
It"s ok for me but I do a manipulation.
As I install the last release (r974) with an archlinux package the "Update" was respond that I am also in the laste version. So I modify the version inside the manifest to see the message and it's good:  

![image](https://user-images.githubusercontent.com/34601782/51432324-f1f94380-1c35-11e9-96a6-f539256d92f1.png)

I think the problem depend from which release you check the update because in the previous release the source code was not good.

On the other hand in the help menu I have an error if I try to open the "changelog"

**Comment by akasolace** [comment]
> I think the problem depend from which release you check the update because in the previous release the source code was not good. 

ok maybe but I thought I was also on the latest version , I will try again to confirm

> On the other hand in the help menu I have an error if I try to open the "changelog"

thats ennoying, your version was not working for me when launched from the zip. So I had to change the code into 
`File jarFile = new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());
URI logFile = jarFile.getParentFile().toPath().resolve("changelog.html").toUri();
Desktop.getDesktop().browse(logFile);`
which assume that `changelog.html` is in the same directory as HO.jar, which I think should always be the case.

That fix is  working well in all use case under Windows

**Comment by akasolace** [comment]
I confirm the bug does not exist with more recent DEV versions

**Comment by mistermax80** [comment]
I cannot try, because, the previous version that works in macos was X.723... and this wasn't the funcionality.
I will try in next version.

**Comment by brokenelevator** [comment]
I did the same (maybe not exactly) as @yaute74 and had the same result. Including the changelog bug (I'll write there). 

@akasolace as for version. I use 'master' version. So one can say that I already upgraded.

**Comment by akasolace** [comment]
@brokenelevator so just to clarify, you confirmed you do not experience the bug so will leave it closed ?

**Comment by brokenelevator** [comment]
@akasolace as you can see at the top. I never did.
