### ISSUE TITLE
[BUG]  remove Time shift in preferences

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#884]
Remove current time offset functionality in preference (quite broken). Introduce time zone or system default selection. 
Change code accordingly e.g.  Basics.parseHattrickDate  should have something like 

```
               if userTimePreference == "systemDefault" :
                    userLocalDateTime = htLocalDateTime.withZoneSameInstant(ZoneId.systemDefault());
               else:
                       userLocalDateTime = htLocalDateTime.withZoneSameInstant(ZoneId.of(userTimePreference););
```

code example for the listing of all zonesID:  
https://mkyong.com/java8/java-display-all-zoneid-and-its-utc-offset/

**Comment by wsbrenk** [comment]
@akasolace Internal time representation should be a unique, not changeable one. for now it is the hattrick time zone (CEST). Only the displays should be configurable for the users. we should spent a basics.formatDateTime method to handle this uniquely for all usages.

**Comment by akasolace** [comment]
@wsbrenk  yes I was talking about the display using the function `parseHattrickDate ()`

**Comment by wsbrenk** [comment]
@akasolace i'm not sure if parseHattrickDate is used only for displaying purpose.

**Comment by akasolace** [comment]
ah ok so I will introduce a `parseHattrickDate(Boolean localDatetime)`

**Comment by akasolace** [comment]
@wsbrenk actually, what I would like to do is:
   - keep timestamp only for db storage and hrf
   - in all other case use ZonedDateTime 

I think we could even have a class witch hold the 3 informations:
    - timestamp, ht and localdatetime  hence there will be no confusion, we know what we get ....

**Comment by akasolace** [comment]
@wsbrenk I started work on this ....  https://github.com/akasolace/HO/tree/feature/884

**Comment by wsbrenk** [comment]
@akasolace in my opinion the only case, where we should use other timezone than CEST is the display purpose. if we calc durations or compare DateTimes, we have to use one defined internal time zone. in germany we say: otherwise you'll come into devil's kitchen.

**Comment by akasolace** [comment]
@wsbrenk we need for display and for #872 ...

**Comment by akasolace** [comment]
@poteus if you could try this one when new artefacts are release (later this week) ... thank you !
