### ISSUE TITLE
Start HO 4.1 without using HO.exe

### ISSUE THREAD

**Issue by lv913** [akasolace/HO#888]
Hi, I need to use the portable version without starting it through HO.exe, as my laptop has a protection enabled against untrusted exe files.
In the older versions it was possible to launch manually JRE and start HO.jar.
Can you suggest a way to do the same in HO 4.1?

**Comment by akasolace** [comment]
@lv913 can't you bypass the restriction i.e authorizing Windows to open this .exe? Otherwise I don't know but I can look into this ...

**Comment by lv913** [comment]
No unfortunately I don't have control over the security suite...
What does exactly the exe file? Is it a wrapper for launching the HO.jar with some parameters?

**Comment by akasolace** [comment]
>  What does exactly the exe file? Is it a wrapper for launching the HO.jar with some parameters?

yes

**Comment by akasolace** [comment]
if you want to give it a try I suggest you to look at the script in the Unix portable release....

**Comment by lv913** [comment]
Ok it worked launching the following command:

`E:\Documenti\HO-4.1-win>E:\Documenti\HO-4.1-win\jre\bin\java.exe -classpath "E:\Documenti\HO-4.1-win\.install4j\i4jruntime.jar;E:\Documenti\HO-4.1-win\.install4j\launcher9f1a8bf3.jar;E:\Documenti\HO-4.1-win\*;E:\Documenti\HO-4.1-win\prediction" install4j.core.HOLauncher`

The only issue appears to be with .install4j\launcher9f1a8bf3.jar, which exists in the Unix portable package but not in the Windows package. I have copied it from the Unix package and HO started correctly.
Do you know if .install4j\launcher9f1a8bf3.jar has been intentionally excluded from Windows version or if it still exists with another name?
Thanks in any case!

**Comment by akasolace** [comment]
I never really looked into this. Glad you achieved what you wanted.
