### ISSUE TITLE
[eFEAT] Add a section translating HO in the wiki

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#89]
just few lines and maybe 1 or 2 screenshots explaing briefly how to register and that both term fuzzy and untranslated need to be translated (I will add a link to that on the forum post at release time)

**Comment by DavidatorusF** [comment]
@akasolace 

must be added in Contributing-to-HO, no ?

https://github.com/akasolace/HO/wiki/Contributing-to-HO


## Translations
You can simply do so via PoEditor https://poeditor.com/join/project/jCaWGL1JCl

You need to fix both 'Fuzzy translation' (priority) and remaining untranslated terms.
In case the language in which you would like to contribute is not listed in the project page please contact [capitaineFro](https://www.hattrick.org/goto.ashx?path=%2FClub%2FManager%2F%3FuserId%3D13441219%26browseIds%3D)

**Comment by akasolace** [comment]
Ok perfect. 
Thank you !

**Comment by DavidatorusF** [comment]
here is the link you can add in forum

https://github.com/akasolace/HO/wiki/Contributing-to-HO#translations

**Comment by akasolace** [comment]
Cheers !

**Comment by Sune23** [comment]
I can't add my confirmation code. I use macbook with catalina.

**Comment by akasolace** [comment]
> I can't add my confirmation code. I use macbook with catalina.

@Sune23 sorry but I doubt your comment/question has anything to do with this ticket (i.e wiki and translations).

**Comment by DavidatorusF** [comment]
@Sune23 not the nice thread...

whatever... selct the code then : 
on windows, CTRL+C for copy and CTRL+V for paste
on mac , use Cmd in place of CTRL : ⌘+C and ⌘+V

**Comment by Sune23** [comment]
> @Sune23 not the nice thread...
> 
> whatever... select the code then :
> on windows, CTRL+C for copy and CTRL+V for paste
> on mac , use Cmd in place of CTRL : ⌘+C and ⌘+V

@DavidatorusF 
When I do that on mac and press "enter", nothing happens.
<img width="1440" alt="Skærmbillede 2019-10-23 kl  12 27 57" src="https://user-images.githubusercontent.com/56848212/67384026-a7c03c80-f590-11e9-8dc2-f01a3fbd9531.png">

**Comment by akasolace** [comment]
@Sune23 @DavidatorusF can you move that discussion to the newly created thread #261
Thank you
