### ISSUE TITLE
[BUG] Last match column can not be sorted by match date

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#895]
in player overview table i was used to order by match date. with the new merged information the order is given by the rating value. I would like to have two different columns, one showing the rating of last match and another one showing the match date.

**Comment by tychobrailleur** [comment]
I have started work on this to separate rating and last match date in the Squad table.
https://github.com/tychobrailleur/HO-t/commit/78e48f8dc646848ef6b6cf76cdf8591f05a13aed

Some more work is needed to fix sorting, and restore last match date in player overview.

**Comment by akasolace** [comment]
@tychobrailleur ok cool
