### ISSUE TITLE
[eBUG] help menu error when trying to open the "changelog"

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#90]
Bug reported by @yaute74 (I think under Linux)

Personnaly I do not experience the bug in Windows either from installed version or zip.
So we need confirmation of who is affected by it.
@mistermax80  @brokenelevator @DavidatorusF

**Comment by DavidatorusF** [comment]
from my .zip, my changelog is well open on my firefox

**Comment by yaute74** [comment]
@akasolace   I update to revision 989 and now it"s ok
I d'on't understand why because because you change nothing

**Comment by mistermax80** [comment]
I see the error.
![schermata 2019-01-20 alle 09 31 59](https://user-images.githubusercontent.com/15519907/51436927-4f24e180-1c96-11e9-9e04-441426058b50.png)
I reopened the bug.

**Comment by akasolace** [comment]
Indeed, I should have expected issues with MacOS. I guess there is no changelog file next to the  jar.
I hope  this can be easily fixed via the build script but I am not 100% sure .. I will try tonight

**Comment by brokenelevator** [comment]
I don't have that problem but why does local html file open in browser? I mean, I get that it made some sense to open the web one in browser but the local one?

**Comment by brokenelevator** [comment]
@akasolace Linux/Manjaro

**Comment by akasolace** [comment]
@mistermax80  as I explained last time, I do not have anymore a MacOS VM, hence you will have to help me on this one. Could you please tell me what is the current folder structure of the osX zip archive ?
I can't even open it under windows.  If I recall correctly in OSX all the files are included within the JAR even prediction for example, is that correct?  If it is the case we will need a method for opening changelog dedicated to OSX.

**Comment by mistermax80** [comment]
@akasolace 
ZIP:
![schermata 2019-01-21 alle 17 05 08](https://user-images.githubusercontent.com/15519907/51485706-060c8480-1d9f-11e9-9690-18fda74ec282.png)
HO.jar
![schermata 2019-01-21 alle 17 06 58](https://user-images.githubusercontent.com/15519907/51485714-0efd5600-1d9f-11e9-811e-23c2c1985523.png)

**Comment by akasolace** [comment]
@mistermax80 ok thank you and where is HO.jar ? whithin HO.app ? anything next to it ?

**Comment by mistermax80** [comment]
@akasolace  HO.jar is whithin HO.app

**Comment by akasolace** [comment]
@mistermax80 ok and nothing along with it ?

**Comment by mistermax80** [comment]
@akasolace 
This is contained in HO.app:
![schermata 2019-01-21 alle 17 19 54](https://user-images.githubusercontent.com/15519907/51486419-ed9d6980-1da0-11e9-90d7-3ac1aa3628a1.png)

**Comment by akasolace** [comment]
ok so I guess the way to go is to replace:

~~~
if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE))
{
...
File jarFile = new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());
URI logFile = jarFile.getParentFile().toPath().resolve("changelog.html").toUri()
}
~~~

with something like
~~~
if (Desktop.isDesktopSupported() && Desktop.getDesktop().isSupported(Desktop.Action.BROWSE))
{ 
File jarFile = new File(this.getClass().getProtectionDomain().getCodeSource().getLocation().toURI());
if not isMac()
{
URI logFile = jarFile.getParentFile().toPath().resolve("changelog.html").toUri()
}
else
{
URI logFile = jarFile.getParentFile().getParentFile().toPath().resolve("changelog.html").toUri()
}
~~~

@mistermax80 can you give a try and let me know if it works ?

Thank you

**Comment by mistermax80** [comment]
@akasolace I will try.
I have to try in only by intellij?

**Comment by akasolace** [comment]
No ... maybe what you can do is a PR and I build it if that helps.
Meanwhile I will try to recreate an macOS VM

**Comment by akasolace** [comment]
@mistermax80  ok no worry I'll do it now.

**Comment by akasolace** [comment]
ok can you try now the latest DEV ?

**Comment by mistermax80** [comment]
@akasolace 
Ok in r1013 it's works.

But I saw the setup zip name file is changed "_OSX.zip" to "macOs.zip". which is the correct name?

**Comment by mistermax80** [comment]
@akasolace I saw you had udpate the code in coerence with new mscos name (91a2003), perfect!!!
