### ISSUE TITLE
[BUG] trainweekmanager 

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#903]
private static final Instant m_NextTrainingDate = HOVerwaltung.instance().getModel().getXtraDaten().getTrainingDate().toInstant()

in trainweekmanager will crash for freshinstall

**Comment by wsbrenk** [comment]
FutureTrainingTable is broken. it uses TraininPerWeek, especially deleted methods

**Comment by wsbrenk** [comment]
FutureTrainingTable changed (same structure as TRAINING). 
DBUpdater data migration needs to be done.

Statistics need refactoring of TrainingPerWeek usage.

**Comment by wsbrenk** [comment]
statistic could get the week list with 
select min(hrf_id) from hrf group by  100*YEAR(datum)+WEEK(datum)

**Comment by wsbrenk** [comment]
HTSkillID versus PlayerSkill should be refactored too
