### ISSUE TITLE
[eFEAT] Create message box after update complete

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#91]
currently when user decide to update HO 
 1. after download is finished, ho closes
 2. next click on ho, the update takes place (the user sees nothing he might think nothing is done)
 3. next launch, the new HO version is launched

It might be cleaner to have a pop up message at the end of step 2 saying the update is finished.
The alternate would be to launch HO just after the update is finished but the code is not at all structured this way so I would rather go with the former.

**Comment by brokenelevator** [comment]
@akasolace actually it is not how it works for me.

When I check for update there is the update/release notes window.
When I click yes, there is a progress bar. It sort of blinks(?) but it did for as long as I remember and I don't really care.
Then message shows up. 'to apply changes you need to restart ho' or something like that.
Then I restart and new HO shows.

I think it is fine.

I used beta zip from releases.

**Comment by akasolace** [comment]
> Then I restart and new HO shows.
but normally you have to restart twice to make it work, correct ?

**Comment by brokenelevator** [comment]
no. only once.
start -> seek updates and yes -> progress bar -> message -> manual (not auto) close -> manual start (updated)

**Comment by akasolace** [comment]
ok then maybe it is a Windows only issue.
btw I just realized that out of 5 devs I am the only one on Windows.
@mistermax80  I think you have a Windows VM, could you check how it behaves for you?

Thank you

**Comment by brokenelevator** [comment]
I guess I can somewhat confirm the issue. For Windows it goes like this:

start -> seek updates and yes -> progress bar -> message -> auto close -> nothing when I start manually (background update) -> manual start (updated)

I moved to Linux but that does not mean I have no longer access to Windows. I had dual-boot for a long time, it's the order that has changed.


> I just realized that out of 5 devs I am the only one on Windows

Somehow I'm not surprised :)

**Comment by mistermax80** [comment]
Yes @akasolace, that behaviour is for Windows, I can confirm, I use Mac and Ubuntu for developing, but I use Windows for use HO, and also I use HO fron years, to each update... I think... It don't matter nothing...

**Comment by akasolace** [comment]
@mistermax80  ok so it confirms it is a Windows only. Not a big deal though really
