### ISSUE TITLE
[BUG] TeamAnalyzer/Manual: subsequent analysis only after result has been emptied

### ISSUE THREAD

**Issue by thwkmst** [akasolace/HO#913]
**Describe the bug**
In the TeamAnalyzer/Manual: You have to empty the result before you can analyze a new game selection.

**To Reproduce**
1. Go to 'TeamAnalyzer'
2. Select 'Manual'
2. Select one or more games
3. Click 'Analyze' -> all is fine
4. Now select an additional game
5. Click 'Analyze' -> doesn't work
6. (You have to unselect all games, then click 'Analyze' to empty the result, then you can start again.)

**Platform information:**
 - 4.1 (3310) and 5.0 (3412)

**Comment by akasolace** [comment]
@thwkmst thank you for reporting the issue, I could reproduce it, I will have a look at is shortly
