### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ericm78** [akasolace/HO#919]
**Describe the bug**
On 10 February I played my first match in the Sapphire Cup. Although the match is shown in the matches tab, no training is calculated. The competition player did get an update.
I double checked the formation, but it is a normal 3-5-2, so nothing special.

**To Reproduce**
Play a match in the Sapphire Cup and see if training gets updates

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux] Windows 10
 - Version (including build number) HO 3.1

**Additional context**
Training: winger
Team name: FC Eisern Utrecht TeamID=211813
The match that didn't get training (according to HO)
https://stage.hattrick.org/Club/Matches/Match.aspx?matchID=673715659&SourceSystem=Hattrick&TeamId=211813&UpdateViewedReport=False

**Comment by akasolace** [comment]
hello @ericm78 this is know bug, that has been fixed for the upcoming 5.0 release.

**Comment by ericm78** [comment]
Hi @akasolace 
Ah ok, next time I will spend more time going through the log...
Thanks for the quick answer
