### ISSUE TITLE
[eBUG] Skills format in Squad screen

### ISSUE THREAD

**Issue by brunoviananascimento** [akasolace/HO#92]
**Describe the bug**
The skill number is wrongly formatted in the Squad screen, appearing like _130$00_, instead of _13.00_ or _13,00_, as it would be expected.

**To Reproduce**
1. Use Windows locale and money formats related to Portuguese (Either Brazil or Portugal)
2. Go to 'Squad' tab, with Language set to **PortuguesBrasil** - Portuguese (Brazil)
3. See error in all decimal 

**Screenshots**
![image](https://user-images.githubusercontent.com/6499670/51746968-ed061b00-209f-11e9-9609-8b37c242aa95.png)

**Platform information:**
 - OS: Windows
 - Version 10.1803

**Additional context**
The same error appears in screens like:

Lineup
![image](https://user-images.githubusercontent.com/6499670/51747101-5f76fb00-20a0-11e9-921d-d058ebdd714c.png)

Player Analysis
![image](https://user-images.githubusercontent.com/6499670/51747209-b2e94900-20a0-11e9-8db1-df13b7061d7c.png)

Transfer Scout
![image](https://user-images.githubusercontent.com/6499670/51747287-f0e66d00-20a0-11e9-9796-892b2e57043a.png)

**Comment by brokenelevator** [comment]
The problem does not appear on Windows 7.
@akasolace what Windows version are you on?
Can anyone confirm this?

**Comment by akasolace** [comment]
@brokenelevator  @brunoviananascimento 
I made the test on Windows 10 and I do not have the problem.
@brunoviananascimento  are you sure you do not have some special settings. in region option, select Additional Settings and then reset, after that launch again HO and see i it fix the problem.
Also can you try with another languae settings like UK or US ?

**Comment by brunoviananascimento** [comment]
Reset to original settings in Additional Settings as stated, did not work.
Changed HO internal language to English and no change at all. The bug still happens as the screenshots show.

But, when I set the format equal to the language settings (Portuguese (Brazil), I was using Portuguese, but original, as the keyboard format needed it), it worked perfectly. Not only formatted correctly, but used the full Windows definitions set.
This may be an important observation to be done: your Windows number format setting MUST BE the same as your internal Language setting, otherwise formatting won't work correctly.

**Comment by brunoviananascimento** [comment]
These tests were done on Windows 10, build 1803.

**Comment by akasolace** [comment]
Does anyone else can reproduce this bug?

**Comment by mistermax80** [comment]
For me It is resolved (it was reference to #93), can I close the bug?

**Comment by akasolace** [comment]
@mistermax80 yes good catch, I close this one
