### ISSUE TITLE
[FEATURE] new version of chpp file players available

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#923]
CHPP - Changelog
2021-01-19
players - 2.5
Added Output: TransferListed
Removed Output: TransferListed

TransferListed is changed fom Integer to Boolean

**Comment by wsbrenk** [comment]
Removed class XMLPlayerParser. It is not used anymore. 
Years ago the function was replaced by constructor of Player(Properties).

**Comment by akasolace** [comment]
closed by #924
