### ISSUE TITLE
[eBUG] Money simbol taken from Windows configuration instead of Hattrick configuration

### ISSUE THREAD

**Issue by brunoviananascimento** [akasolace/HO#93]
**Describe the bug**
Salary wages/week are appearing with the money symbol configured in Windows instead to the one related to the Language associated to Hattrick.

**To Reproduce**
1. Go to Windows > Settings > Region and Language > Language adinistrative definitions > Formats > Advanced definitions > Money
2. Set Symbol to €. 
3. Press OK.
4. Start HO with Language **PortuguesBrasil**.
5. Monetary simbol for the country - Brazil - is R$ and the coin is reais (plural form), instead Salary (Salário) column appears with €.

**Screenshots**

![image](https://user-images.githubusercontent.com/6499670/51747786-6b63bc80-20a2-11e9-9208-f64e42f393b2.png)

**Platform information:**
 - OS: Windows
 - Version 10.1803

**Additional context**
Same problem appear in other points, like:

Player Analysis
![image](https://user-images.githubusercontent.com/6499670/51747876-9c43f180-20a2-11e9-9bcf-be4522269fce.png)

**Comment by brokenelevator** [comment]
For now...I can confirm the bug exists on Windows 7.

**Comment by akasolace** [comment]
@brokenelevator  @brunoviananascimento 
I can also confirm this behavior, but for me it is not a bug.
It is standard to have language settings to be applied accross application. 
For example, you can install Office application in one language but still the local are taken from system.
Maybe we can thing of having an option to take priority over system local but it is kind of unseen and I am not sure this is something we want to do. 
I am waiting for your feedback before closing the issue.

**Comment by brunoviananascimento** [comment]
After changing settings for issue #92 , the money symbol also changed to the correct one.
So, I would say that whichever solution is applied to issue #92 should tackle this one too.

Recommendation: close this issue and answer all problems related to different language and money settings on issue #92 .

**Comment by brokenelevator** [comment]
@akasolace while I don't disagree with taking system locales in other programs... here we have a different problem. The values are in the teams local currency and calculated as such. Taking system locale we reach a situation where a wage of 12k of national currency of the team is once shown as USD, once EUR, or GBP while the wage is in R$. Note that only the symbols change, not values.
I'm not sure if anyone actually pays attention to this, but it is plain wrong.

I proposed a change (#94). Anyone on board?

**Comment by akasolace** [comment]
@brokenelevator  .... I thought it was a problem of formatting (local) i.e like '.' instead of ','.  
After reading what you described here there is effectively a bug.
