### ISSUE TITLE
[BUG] Future trainings might be lost during upgrade (to be checked)

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#954]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Platform information:**
 - OS: [Windows / macOS / Linux]
 - Version (including build number)

**Additional context**

**Comment by datatramp** [comment]
Not sure if bug is related, therefore I post here in comments first before opening seperate report:

I upgraded my HO!5.0 Dev to latest 3551 Built.
I downloaded from Hattrick after training went through and Training was not processed in HO!5 built 3551 at all, week 8 still shows at "future trainings"
In "Squad" table, no improvements were shown though weeks matches were downloaded.

I run parallel HO!3 stable and everything was downloaded and training calculated in that version, no problems.

**Comment by akasolace** [comment]
yes that has been fixed in latest dev ... I will release artefacts shortly ....
