### ISSUE TITLE
database size increase during upgrade 4.0 -> 5.0

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#958]
There is one thing however which is suprising and that I dont like is the size increase of your db during the upgrade 
which almost quadrupled (database example available here: https://we.tl/t-YvnbFY5JsL): 

![image](https://user-images.githubusercontent.com/1136496/109843320-3647d200-7c4b-11eb-855d-41cdf2d0eb7f.png)

_Originally posted by @akasolace in https://github.com/akasolace/HO/issues/941#issuecomment-789894775_

**Comment by Cold-Burn** [comment]
Hello.

Reporting that on updating from 2.1 to HO-4.1.3310.2-portable-win-JRE database has increased 6.2 times.

**Comment by wsbrenk** [comment]
from hsqldb docs: 
* The size of the .data file grows in operation although the total row count for CACHED tables has not gone up. Why?
In version 2.6.0 you can enable SET FILES SPACE TRUE and empty spaces are tracked much better than old versions. HSQLDB tracks and reuses empty spaces left after DELETE or during UPDATE operations. If the .data file is still too fragmented, both CHECKPOINT DEFRAG and SHUTDOWN COMPACT commands will remove the empty spaces.

**Comment by wsbrenk** [comment]
the command checkpoint defrag reduces the file size to a fraction

**Comment by wsbrenk** [comment]
SET TABLE <table> NEW SPACE  is called for the 2 greatest HO tables:
* MATCHHIGHLIGHTS
* MATCHLINEUPPLAYER

**Comment by akasolace** [comment]
closed by #1346
