### ISSUE TITLE
[BUG] Cannot send the feedback

### ISSUE THREAD

**Issue by pivsxii** [akasolace/HO#959]
**Describe the bug**
When i try to send the feedback an error appearing

**To Reproduce**
1. Place the same orders both on HO and Hattrick website
2. Click on "Ricaricare" (italian for Reload)
3. Click on "Invia" (italian for Send)

**Screenshots**
![immagine](https://user-images.githubusercontent.com/2829627/110173198-8c10ab80-7dfe-11eb-9345-2463d759fa44.png)
![immagine](https://user-images.githubusercontent.com/2829627/110173216-916df600-7dfe-11eb-9cb6-cb62d42901dd.png)

**Platform information:**
 - OS: Windows 10
 - Version 19042.804

**Additional context**
If i try to place all my orders (with all players) it says me that my lineups/languages are different/

**Comment by akasolace** [comment]
@pivsxii this feature is currently not supported ...
