### ISSUE TITLE
[BUG]download does not update training lists

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#960]
consequence: training effect is not calculated after download.

reproduce:

* press f11
* verify if past training and future training lists in training panel are updated correctly
* verify if training progress is displayed on player overview

**Comment by akasolace** [comment]
I made a commit for this last week but then you also made a commit for the same thing so I told you I will let you decide how to deal with it. I noticed the function I created in training manager is never called ... happy to help if you want me to ...

**Comment by akasolace** [comment]
@wsbrenk to clarify, I expect this should work as follow: 
your function calculate subskill should look whether or not trainingmanager.recentTrainings has entries. 
if no -> pass,  if yes -> subskill are updated then at the end of your function you should call updateHistoricalTrainings()

**Comment by akasolace** [comment]
lookimng at the function recalcSubskills()  (https://github.com/akasolace/HO/blob/1fd0aa76ecd05e1801cf2c9f37049e76e53d1b91/src/main/java/core/model/HOVerwaltung.java#L116)

I am confused because it seems you are not even using trainingManager.recentTrainings .....

**Comment by akasolace** [comment]
Applying the above, I get this:

- before download:

![image](https://user-images.githubusercontent.com/1136496/110207630-100d7680-7e85-11eb-9723-430e547d0eaa.png)

![image](https://user-images.githubusercontent.com/1136496/110207642-23b8dd00-7e85-11eb-9508-87d22164c558.png)


We can see that training 05.03 is nowhere .... is it what we want ? 

- after download:


![image](https://user-images.githubusercontent.com/1136496/110209314-118e6d00-7e8c-11eb-8e3a-613734fee5ae.png)

 
![image](https://user-images.githubusercontent.com/1136496/110209319-1e12c580-7e8c-11eb-84aa-cbfa08f1db05.png)


but 12.03 is not in future training
