### ISSUE TITLE
[BUG] Past Training cannot be edited

### ISSUE THREAD

**Issue by datatramp** [akasolace/HO#963]
**Describe the bug**
After upgrading HO!5 Dev to latest build 3552
Past Training week 8 shows/calculates  wrong Training Type (short passes, should be scoring) and cannot be edited.

Previous edited training weeks from earlier HO!5 Dev builds are still marked blue and show with mouseover info.

I downloaded a new update from hattrick and did a subskill recalculation in Training tab, but it changed nothing.

I turned HO!5 DEV off and on ;) but it changed nothing.

**To Reproduce**
I updated from build 3551 when training week 8 was not processed at all.

**Screenshots**
I put HO!5 DEv and stable HO!3 on same screen to show the difference. I underlined Training week 8 in red
![HOScreenshot 2021-03-07 112219](https://user-images.githubusercontent.com/64270318/110236813-37714b80-7f38-11eb-9d10-3513738294d3.JPG)

**Platform information:**
 - OS: Win10 Pro 20H2 build 19042.804

**Comment by datatramp** [comment]
P.S. Thanks for your ongoing work on this project!
5.0 will be really useful and nice Look&Feel from User perspective when the glitches are sorted out! Great improvements!

**Comment by datatramp** [comment]
Does closed issue mean it was dealt with?
Because I updated to Build 3555 and editing Training still not possible.

**Comment by akasolace** [comment]
yes it was dealt with ... it will be available in next builds ... later this week I guess
