### ISSUE TITLE
Fresh install of DEV artefacts throws DB error on second launch

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#968]
I installed JRE and after that installed HO!, I opened it and started to use it, I got the CHPP code and download my team info, after that I closed it and when I opened it again it show me the next message:
![imagen_2021-03-04_110158](https://user-images.githubusercontent.com/79470364/110000545-09da9700-7cd9-11eb-9daf-4fa7e359d758.png)

I uninstalled and reinstalled, but the message stills shows. Thank you.

_Originally posted by @gescobita in https://github.com/akasolace/HO/issues/928#issuecomment-790773596_

**Comment by akasolace** [comment]
@gescobita if I understand correctly, you made a fresh install of HO!. Then you managed to do your first download. However after closing HO! and reopening it (2nd time) you got the error message above, right ?

**Comment by wsbrenk** [comment]
it is the DBConfigVersion which is not saved in new created database. restart load a value DBConfigVersion=0 which is too old.

**Comment by gescobita** [comment]
> it is the DBConfigVersion which is not saved in new created database. restart load a value DBConfigVersion=0 which is too old.

Thanks. How may I do that???

Thank you in advance.

**Comment by wsbrenk** [comment]
Sorry - i wanted to address it to @akasolace. We need to fix this and provide a new dev version. Pull request is in preparation.
