### ISSUE TITLE
[BUG] training panels are cpu intensive

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#975]
changing several times between training panel and prediction panel costs a lot of  cpu time:

![image](https://user-images.githubusercontent.com/11821502/110856930-8b718c80-82b8-11eb-9bd5-9b8c3df80bcf.png)

**Comment by akasolace** [comment]
I flagged this as regression as I imagined it is the case. 
I haven't done any test myself....

**Comment by wsbrenk** [comment]
to many FutureTrainingManagers were created
