### ISSUE TITLE
[BUG] Extra-time messes up training

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#976]
After a cup match with extra-time, some players won't get full training. They will either get osmosis training (if they played the 120 minutes) or no training at all (if they are subbed off).

Here's the cup match from this week: https://www.hattrick.org/Club/Matches/Match.aspx?matchID=674042640
[9059-2021-03-12.hrf.txt](https://github.com/akasolace/HO/files/6128295/9059-2021-03-12.hrf.txt)
[db_user-2021-03-12.zip](https://github.com/akasolace/HO/files/6128284/db_user-2021-03-12.zip)

**To Reproduce**
On Squad, hit, Subskill recalculation and look at player progress between 03/05 and 03/12. In particular, look for Helleren (winger), Gökdemir, Bourne and Balland all receiving less than a full construction training, if any at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/1204726/110907760-23e62c00-830e-11eb-8a82-b86b678e084b.png)
![image](https://user-images.githubusercontent.com/1204726/110907641-fd27f580-830d-11eb-8688-8cbfdb012008.png)

**Platform information:**
 - OS: Windows
 - Version HO 4.1 (3310)

**Additional context**
This may be a follow up to https://github.com/akasolace/HO/issues/431.

**Comment by akasolace** [comment]
@dominiquelee any chances to check if this still happen with 5.0 dev version ?

**Comment by dominiquelee** [comment]
@akasolace 5.0 r3555 is even stranger:
- it had the same subskills the first time I started it (coming from the db)
- I downloaded a new .hrf with 4 months of matches
- I hit Subskill recalculation, there's literally not a single subskill value now, all values are 11,00, 12,00, 13,00 and so on.

**Comment by akasolace** [comment]
actually that is normal (the version you just tried had an issue with subskill recal). I will release new artefacts really shortly and I will ask you to test again.

**Comment by wsbrenk** [comment]
@akasolace current pr includes a fix for that
