### ISSUE TITLE
Issue  in HO Import

### ISSUE THREAD

**Issue by HTSirEbi** [akasolace/HO#978]
Hi,  

When download in HO I receice error message all the time. I reeive data in the end, but download is interrupted several times by error popup

adding my db here. Also attached errors I received during last load. 

Guess its temporary on HT side, as errors seems to vary.

CHeers
Sir_ebi
[ho-issue.docx](https://github.com/akasolace/HO/files/6134846/ho-issue.docx)
[database.log](https://github.com/akasolace/HO/files/6134853/database.log)
[db_user-2021-03-13.zip](https://github.com/akasolace/HO/files/6134856/db_user-2021-03-13.zip)

**Comment by wsbrenk** [comment]
@HTSirEbi download itself worked fine with new dev version
@akasolace a lot of npe in new TrainingManager on fresh database instance (upgraded from HO V4)

**Comment by wsbrenk** [comment]
today i restored HO V4.1 and started with the provided database. Downloading worked fine. the result shows that @HTSirEbi could only download one single match. my start reloaded all the other matches (see fetch date):

![image](https://user-images.githubusercontent.com/11821502/111062952-66de0600-84ac-11eb-96bf-669daa9a8c9a.png)
