### ISSUE TITLE
[eBUG] No Authentification Code

### ISSUE THREAD

**Issue by MagKekse** [akasolace/HO#98]
**Describe the bug**
If i would download my team data i need the authentification of HO, but the Button doesn´t work and there is no link for this code

**To Reproduce**
1. Open HO
2. push F11 on the keyboard to load the team data
3. now there comes the pop up window with the warning you need the authentification code.
4. But there is no link and the button doesn´t work

**Screenshots**
[https://www.directupload.net/file/d/5362/xerb4fuc_png.htm](https://www.directupload.net/file/d/5362/xerb4fuc_png.htm)
[https://www.directupload.net/file/d/5362/vs9m95li_png.htm](https://www.directupload.net/file/d/5362/vs9m95li_png.htm)
[https://www.directupload.net/file/d/5362/po7o38i8_png.htm](https://www.directupload.net/file/d/5362/po7o38i8_png.htm)
[https://www.directupload.net/file/d/5362/alu64af6_png.htm](https://www.directupload.net/file/d/5362/alu64af6_png.htm)

**Platform information:**
 - OS: Windows 10 Home
 - Version 1803
- Systemtyp 64bit

**Additional context**
I had install the old version of HO 1.434 and this one works great. A few days ago there was a download problem for the team data and after this problem HO doesn´t work.

**Comment by yaute74** [comment]
So you do a test after rename the 'db' folder ? What is your java version ?
I cannot do test on windows, @akasolace  do you reproduce ?

**Comment by akasolace** [comment]
@yaute74 @MagKekse  I cannot reproduce.
@MagKekse  can you please do the following:
   1. Backup your db  
   2. Update your java and download latest HO stable
   3. Launch HO and download your data
   4. restore your previous db 

If step 3 is failing, can you please confirm  whether or not you are behind a firewall ? 
Does HO crash or just hanging ? Can you also  share your log file ?

I can't see your screenchots btw

**Comment by MagKekse** [comment]
Yes i make the test with the renamed db folder. The same thing.

My Java version - i hope i found the right - is Java 8 Update 201 / 8.0.2010.9

**Comment by akasolace** [comment]
@MagKekse 
1. Today if you install fresh 1.434, do you also have the issue ?
2. Can you upload again the screenshot ( I can't see them)
3. Does your computer behind a firewall know to refuse non https connexion ? As a test, can you try on another network ?

**Comment by brokenelevator** [comment]
@akasolace bad links. try now.

**Comment by yaute74** [comment]
@akasolace  a screenshot is on the hattrick forum.
The URL filed is empty and I don't know how it's possible without exception (he has no error in the logs).

**Comment by akasolace** [comment]
@MagKekse 

On the screenshot on HT you are using an old version of HO.
Can you please try with latest version and confirm the bug.

**Comment by MagKekse** [comment]
@akasolace 
I used the new version of HO.
I tried it with HO 1.434, HO 1.435 and HO 1.436 - in all this versions the same, i got no code or the button doesn´t work.

i deleted my old version of HO with all his components and install the new version.
every time i install a new version i don´t get the link and the button doesn´t work.

**Comment by MagKekse** [comment]
[https://www.bilder-upload.eu/bild-0ee657-1550128001.png.html](url)
[https://www.bilder-upload.eu/bild-01a732-1550128030.png.html](url)
[https://www.bilder-upload.eu/bild-53faed-1550128049.png.html](url)
[https://www.bilder-upload.eu/bild-257320-1550128069.png.html](url)

**Comment by MagKekse** [comment]
today i stop my anti virus to try it again.
i delet HO and install the new version HO 1.436 again. I tried to download my team data files but i get no authentification code and no link and the button doesn´t work.

i don´t understand this, a few days ago HO works perfekt. and after the crash nothing works.

**Comment by akasolace** [comment]
@MagKekse it is really strange behavior.
I suggest you try again with the dev version (there are more logs for debugging) and check if relevant debug messages are dumped into the log file. If not we will produce a new dev with more logging activity around the authentification step to try to catch what is broken on your machine.

**Comment by MagKekse** [comment]
where can i find the dev version?

**Comment by MagKekse** [comment]
So, next try.
I delet java from my pc.
Next i download the new version of java from there homepage and install java.
After that, i install HO 1.437 DEV and start it.
i push F11 and it works !!!
i got the link and the button works - now i can download my team data from HT.

I have no idea what´s going wrong with my system but now it´s work!

Thanks for your help and your time to helping me!

**Comment by yaute74** [comment]
Good news, I close
