### ISSUE TITLE
[BUG] NPE on fresh install first launch

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#982]
**Describe the bug**
NPE on fresh install first launch

@wsbrenk this is cause by #977 changes on TrainingWeekManager.getNextTrainingDate()

![image](https://user-images.githubusercontent.com/1136496/111281815-a25c0a00-863d-11eb-93ba-64cc499e8171.png)

**Comment by wsbrenk** [comment]
I wonder what I might have broken. I think the situation hasn't changed from the previous solution because getNextTrainingDate executes exactly the same commands as the constructor before. I'll investigate it.
