### ISSUE TITLE
[BUG] skill drop

### ISSUE THREAD

**Issue by akasolace** [akasolace/HO#984]
hello @wsbrenk , 

I just downloaded some data and looking at the subskill evolution since the preivous data (between 7th and 18th of March). The upside looks good but I am surprised by the downside of my older player. 

![image](https://user-images.githubusercontent.com/1136496/111637448-b9dff200-87f9-11eb-8625-7006e823fceb.png)

![image](https://user-images.githubusercontent.com/1136496/111637476-c19f9680-87f9-11eb-8695-a13ab83ee94c.png)

I would expect him to be just below 6 but he is reported to 5.31, which seem surprising to me.

**Comment by wsbrenk** [comment]
@akasolace could you check if there is a message in the log file concerning this player?

**Comment by wsbrenk** [comment]
the HO calculation does not take into account, that skill drops only happens on monday. i guess that the training calculation for last friday assumes that target skill of skill drop is inadequate and not passable. Later would be the case if you downloaded on friday yielding to skill 6.0. then a next download on monday would give what you expected: 5.99

**Comment by akasolace** [comment]
Here is the log file ....
[HO-2021-03-19.log](https://github.com/akasolace/HO/files/6171444/HO-2021-03-19.log)

**Comment by akasolace** [comment]
it seems skilled dropped is calculated multiple times ...
![image](https://user-images.githubusercontent.com/1136496/111789364-59b48300-88c1-11eb-913d-182dbb74bb60.png)

**Comment by wsbrenk** [comment]
>it seems skilled dropped is calculated multiple times ...

looks strange: Playmaking before calculation is 5.31, decrement is approx 0.1, so new value should be around 5.21.
i have no idea, why HO has the info, that playmaking value is 5.31.

(the Log output is not well formatted - i will change that!)

**Comment by wsbrenk** [comment]
ah yes - before d2f1772ea171acc66e69358a753ddf5a338b9c08 the skill was simply reduced by one without adjusting the sub. 
so now i would say the week before 7th your player had reached playmaking value 6.31
you downloaded after skill drop on monday HO reduced to 5.31 (nowaday he won't do that anymore)
next download calculates with that wrong start value.

One question is left for me - why does HO display the "old" value 5.31 and not the new one 5.21?

**Comment by wsbrenk** [comment]
Since skill gains in training, but their losses will be published on Monday, we could take that into account by treating the time from training to Monday differently than the days after.

the current solution works best, if the user downloads after monday only, since than both effects in hattrick are over (training and skill down).

**Comment by wsbrenk** [comment]
in https://github.com/wsbrenk/HO/commit/6c64c6d470dc74501141b9ed3496abedc91f8f6f i proposed an idea (TODOs), how we could handle this.

**Comment by akasolace** [comment]
closed by #985
