### ISSUE TITLE
[BUG] "Past trainings" imported from .hrf tend to be shifted by one week

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#987]
On a fresh update, the past trainings are filled from existing .hrf but are wrong by one week
![image](https://user-images.githubusercontent.com/1204726/112152235-5f240d00-8be2-11eb-99f5-acb18ced050e.png)
Here, I did a defending training on the 1/1 but it was reported as done on the 1/8.

I believe that's because for someone that only downloads one .hrf by week (on the training day), the only .hrf "downloaded on the same week as the training" is the one that was downloaded 7 days before the training, thus, with the previous training.

**To Reproduce**
Update from 4.1 to 5.0 dev
Training / Past Trainings
Check for last training change
Compare with your lineups that week, it most likely doesn't match
After a subskill recalculation, it's also visible through Statistics/Players for trained players as the curves won't be smooth at all.

**Platform information:**
 - OS: Windows
 - Version 5.0 dev, r3557

**Comment by wsbrenk** [comment]
I'm afraid the software has no real chance to decide for sure which training is the right one if before the training date training A was set and then training B. It could be both A correct, as well as B or even C, depending on what happened in the meantime in hattrick. At the moment, the algorithm chooses A. If this is incorrect, the user must correct it manually. A more complex investigation due to player developments is difficult to perform in the context.

**Comment by dominiquelee** [comment]
It's clear that there's no perfect solution, but I'd argue that choosing the training of the following week might be correct more often for most people. I believe most people do their weekly sync immediately after the training rather than immediately before the training (though obviously, that's a big baseless hypothesis).

**Comment by wsbrenk** [comment]
@dominiquelee i agree, and i think that could be changed easily. Let us wait on @akasolace who should decide which way we should go.

**Comment by wsbrenk** [comment]
changed method is not only called on db upgrading, but also each time when HO downloads hattrick's data.

current solution gives errors on sequence:   Change training type - Training Date - HO download => download selects previously selected training type

proposed solution gives errors on sequence Training Date - Change training type - HO download => download selects future training type

which one is less likely?
