### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by koef6** [akasolace/HO#989]
**Describe the bug**
HRF file lists incorrect player on Leftwinger position in [lineup]. It is listed in substInsideMid

**To Reproduce**
1. Download team data
2. open HRF file
3. Scroll down to [Lineup]'
4. Check for LeftWinger position; it appears to be the Leftwinger for the [Lastlineup]

**Platform information:**
 - OS: Windows
 - Version 4.1 (just upgraded from old version)

**Additional context**
I am using the HCF file as import to Excel. HO is the only reliable tool that provides player download files in a readable format
This week. I've started analysing the data in the Lineup and came accross that bug

**Comment by wsbrenk** [comment]
i cannot reproduce this.

**Comment by koef6** [comment]
Sorry, neither could I; must be mistaken
Just slight side note: The LeftWinger in [lastlineup ]has a capital more  then in Leftwinger in [lineup].
But hardly would call that a bug more like suggestion
