### ISSUE TITLE
[BUG]training calculation: missing set pieces skill sub

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#994]
HO5.0-3557:
![stdsub](https://user-images.githubusercontent.com/11821502/114265569-c9fe8200-99f1-11eb-8c4e-8a019df0dc0b.jpg)

only full skill ups are displayed - trained subskills should be displayed too

**Comment by wsbrenk** [comment]
situation abbove is the first start of HO after upgrading to version 5.0.
even running recalc 7 weeks does not change the displayed standard skills.

but after restarting HO and running recalc again everything is fine:
![stdsub2](https://user-images.githubusercontent.com/11821502/114266351-29f72780-99f6-11eb-8a70-068b88c3fb27.jpg)

**Comment by wsbrenk** [comment]
i have no idea what leads to this error in the upgrade process

**Comment by akasolace** [comment]
@wsbrenk should we also close this one if the bug get fixed on restart / data download ?

**Comment by wsbrenk** [comment]
@akasolace yes - i confirm
