### ISSUE TITLE
[BUG] In Matches, own goals are given to the wrong team

### ISSUE THREAD

**Issue by dominiquelee** [akasolace/HO#998]
**Describe the bug**
In Matches, own goals are not properly reported in the main table
![image](https://user-images.githubusercontent.com/1204726/115200189-3b29ed80-a0f4-11eb-831a-08166d0893c3.png)

Here's the match in Hattrick: https://www.hattrick.org/goto.ashx?path=/Club/Matches/Match.aspx?matchID=671245002

**To Reproduce**
In Matches, open a match with an own goal. The score will be correct in the lower side details, but not in the main table.

**Platform information:**
 - OS: Windows
 - Version 5.0 DEV r3557

**Additional context**
In the Chance Distribution, Hattrick themselves give the SE to the team that has the unpredictable player that scores the own goal, so it's already quite bizarre there.

**Comment by wsbrenk** [comment]
this is the info from hattrick: "there is indeed a bug here but not related to chpp, it's also on the website.
they will look deeper in it, seems not easy :)"

**Comment by wsbrenk** [comment]
i'm implementing a verfication which checks if matchdetails values of the end result are equal to the counting of the goals in match events. if not all goals are moved to the last match part (second half, extra time or penalty contest).

**Comment by wsbrenk** [comment]
info from hattrick: the event 125 has been fixed and old matches too

**Comment by wsbrenk** [comment]
@akasolace yes - and even if the hattricks will reintroduce this error, it should be handled by the commits.
