### ISSUE TITLE
[BUG]NPE loading ImageIcon of team 1159698 (0 byte jpg file)

### ISSUE THREAD

**Issue by wsbrenk** [akasolace/HO#999]
22:39:38 [Error]   core.util.ExceptionHandler: java.lang.NullPointerException: Cannot invoke "java.awt.Image.getProperty(String, java.awt.image.ImageObserver)" because "image" is null
22:39:38 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:240)
22:39:38 [Error]   core.util.ExceptionHandler: core.gui.theme.ThemeManager.getClubLogo(ThemeManager.java:187)
22:39:38 [Error]   core.util.ExceptionHandler: core.gui.theme.ThemeManager.getClubLogo(ThemeManager.java:170)
22:39:38 [Error]   core.util.ExceptionHandler: module.lineup.lineup.MatchBanner.refresh(MatchBanner.java:187)
22:39:38 [Error]   core.util.ExceptionHandler: module.lineup.lineup.LineupPositionsPanel.refresh(LineupPositionsPanel.java:209)
22:39:38 [Error]   core.util.ExceptionHandler: module.lineup.LineupPanel.update(LineupPanel.java:80)
22:39:38 [Error]   core.util.ExceptionHandler: module.lineup.assistant.LineupAssistantPanel.actionPerformed(LineupAssistantPanel.java:136)
22:39:38 [Error]   core.util.ExceptionHandler: java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)

**Comment by wsbrenk** [comment]
don't know why download didn't work. this is the correct logo:
![1159698](https://user-images.githubusercontent.com/11821502/116313560-36c59a80-a7ae-11eb-9bd6-125b9cf2227b.jpg)

**Comment by akasolace** [comment]
closed with #1000
